### ISSUE TITLE
Double Player Arrow

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#10]
I sometimes get 2 player arrows on the minimap. It seems it happens after I use portals (Lock order hall portal to Dalaran, Mage portal to Dalaran, Hunter order hall portal etc). A reload fixes it. 
![wowscrnshot_061617_024613](https://user-images.githubusercontent.com/22230769/27215241-4e092d84-523e-11e7-8dec-df8da0da2ca0.jpg)
![wowscrnshot_061617_024415](https://user-images.githubusercontent.com/22230769/27215245-4f9821b4-523e-11e7-8e4a-2e57a1a41eb9.jpg)

**Comment by IrcDirk** [comment]
I will check this.

**Comment by Palonblade** [comment]
Still happened, Hunter OH portal to Dalaran.
![wowscrnshot_061617_115917](https://user-images.githubusercontent.com/22230769/27234569-704f3972-528b-11e7-84f2-1ddf7c77a26a.jpg)

**Comment by IrcDirk** [comment]
Ok. Please try again and report back.

**Comment by Palonblade** [comment]
Seems ok on hunter and mage so far, will report back if any more issues. You rock and thank you!

**Comment by IrcDirk** [comment]
Im trying my best. Closing, if this occurs again please report.
