### ISSUE TITLE
Map.MiniMapBlks need update

### ISSUE THREAD

**Issue by IrcDirk** [mikepauer/Carbonite#100]
Map.MiniMapBlks need update. Zooming map shows wrong zone position. Dont know yet how to fix this issue, maybe @mikepauer when he returns from vacation will help with this.

**Comment by Thrumbar** [comment]
Twilight Highlands does not show in Carbonite map when moused over...

**Comment by IrcDirk** [comment]
@Thrumbar Twilight Highlands should be ok now.

**Comment by Palonblade** [comment]
Is this why the player arrow sometimes does not show on the minimap?
