### ISSUE TITLE
NxMap.lua:6538: attempt to call global 'GetMapOverlayInfo' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#102]
Git this while mousing over the zones in Carb map.  

315x Carbonite\NxMap.lua:6538: attempt to call global 'GetMapOverlayInfo' (a nil value)
Carbonite\NxMap.lua:6538: in function `UpdateOverlay'
Carbonite\NxMap.lua:6343: in function `UpdateZones'
Carbonite\NxMap.lua:4609: in function `Update'
Carbonite\NxMap.lua:3841: in function <Carbonite\NxMap.lua:3725>

Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 PlyrRZY = 14.859181642532
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 202.20127900136
 Scrolling = false
 Menu = <table> {
 }
 ScrollingX = 531.00005383045
 EffScale = 0.63999998569489
 Zone = 504
 WorldAlpha = 1
 StartupShown = true
 ScaleDraw = 0.11463761031821
 ClickFrmY = 466.00023091584
 BackgndAlphaFade = 0.4
 MoveLastX = 6127.7530109956
 PlyrDir = 202.20127900136
 PlyrSpeedCalcTime = 565507.396
 MapPosYDraw = 4017.4578845978
 PlyrSpeed = 0
 MapScale = 0.011440879273274
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 1522.0002441406
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 934.00012207031
 MMScales = <table> {
 }
 MapPosX = 1358.4818010678
 BackgndAlphaTarget = 1
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.28
 H = 141
 Tick = 630
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 1433.5903715552
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 6127.7530109956
 QuestAlpha = 0.3
 CurWorldUpdateOverlayNum = 0
 Scale = 0.11463761031821
 Targets = <table> {
 }
 BackgndAlpha = 1
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 504
 MMOwn = false
 Size1 = 1.1718750261934
 ShowUnexplored = false
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 MapIndex = 1
 StepTime = 0
 PlyrSpeedX = 6127.7530109956
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.1
 ScaleDrawW = 8.7231406623377
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 ScrollingY = 732.00008121133
 RealScale = 1.5803720656416
 Data = <table> {
 }
 PlyrY = 1433.5903715552
 TrackDir = false
 CurOverlaysTexFolder = "zuldazar"
 BGIconMenu = <table> {
 }
 CurOverlays = <table> {
 }
 WorldHotspotTipStr = "Pandaria, |cffffff00Isle of Thunder (80-90)
"
 MouseIsOver = 925.0001090616
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TrackETA = false
 TextFrm = <unnamed> {
 }
 TextScFrm = <unnamed> {
 }
 ClickFrmX = 230.00001723319
 GIconMenuIFindNote = <table> {
 }
 MapPosY = 4017.4578845978
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 TargetNextUniqueId = 1
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Tracking = <table> {
 }
 Cont = 6
 Level = 9
 MenuIInstanceMaps = <table> {
 }
 W = 150
 GIconMenu = <table> {
 }
 DotRaidScale = 1
 MapsDrawnFade = <table> {
 }
 CurWorldUpdateMapId = 862
 ContFrms = <table> {
 }
 IconWQFrms = <table> {
 }
 TileFrms = <table> {
 }
 ScaleW = 8.7231406623377
 BackgndAlphaFull = 1
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 IconFrms = <table> {
 }
 ArchAlpha = 0.3
 MMOwnedFrms = <table> {
 }
 MenuIMonitorZone = <table> {
 }
 PlyrSpeedY = 1433.5903715552
 MenuIShowTimber = <table> {
 }
 PlyrRZX = 54.197508096695
 KillShow = false
 MMChkDelay = 16
 NeedWorldUpdate = false
 MapPosXDraw = 1358.4818010678
 MoveDir = 180
 Frm = <unnamed> {
 }
 TransMenu = <table> {
 }
 DotZoneScale = 1
 UpdateTargetDelay = 0
 DotPalScale = 1
}
mapId = 504
bright = 1
noUnexplored = nil
wzone = <table> {
 Overlay = "isleofthethunderking"
 Zone = 504
 Scale = 8.27083203125
 Explored = true
 Y = -1629.583203125
 X = -1530.833203125
 Cont = 6
 5 = 2870.416796875
 4 = 969.166796875
 Name = "Isle of Thunder"
}
txFolder = "isleofthethunderking"
overlays = <table> {
 isleofthethunderking = "0,0,1024,768"
 dynamic = "0,0,0,0"
}
unex = nil
bW = 4
bH = 3
txIndex = 13
txPixelW = 256
txFileW = 256
txPixelH = 256
txFileH = 256
path = "Worldmap\isleofthethunderking\"
alpha = 1
unExAl = 0.35
zscale = 0.827083203125
exploredWHXY = <table> {
}
explored = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
layerIndex = 1
layers = <table> {
 1 = <table> {
 }
}
layerInfo = <table> {
 layerHeight = 668
 layerWidth = 1002
 additionalZoomSteps = 2
 minScale = 1
 ma

**Comment by IrcDirk** [comment]
Should be fixed.
