### ISSUE TITLE
Large map opens to wrong zone

### ISSUE THREAD

**Issue by Greyswandir1973** [mikepauer/Carbonite#102]
When I press the M key to bring up the large main carbonite map, it defaults to the wrong zone for instance I'm up near the top of Tirisfal Glades 43.7 38.9  and when I bring up the map it defaults to having Silverpine Forest centered on the map.  When I was in Felwood depending on my location the map would either default to Mount Hyjal or Ashenvale.  Minor issue I know but it does prevent quick glances and require you to scroll to the proper zone.

**Comment by samyonair** [comment]
by latest Version it is in too but can only reproduce it in old world, about 5-20 secs until Mapdata is updated, guides for mailboxes are right but graphical mapupdate is delayed
