### ISSUE TITLE
going nuts flying over stormwind. 

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite#104]
ok I just went to stormwind to do the new content and Carbonite went totally nuts on me the errors rolling off constantly, I was able to stop it, and start it with no other addons other than bugsack and grabber. even with that, in the time it took me to disable Carbonite it racked up 1415 errors. here is my bugsack cut and past, I hope it helps.

1415x Carbonite\NxCom.lua:1710: attempt to call global 'GetMapNameByID' (a nil value)
Carbonite\NxCom.lua:1710: in function `UpdatePlyrIcons'
Carbonite\NxCom.lua:1641: in function `UpdateIcons'
Carbonite\NxMap.lua:4856: in function `Update'
Carbonite\NxMap.lua:3841: in function <Carbonite\NxMap.lua:3725>

Locals:
self = <table> {
 SendChatMessageFixed = <function> defined @Carbonite\NxCom.lua:1185
 ZMonitor = <table> {
 }
 PalNames = <table> {
 }
 OnTestTimer = <function> defined @Carbonite\NxCom.lua:153
 RestoreChars = <function> defined @Carbonite\NxCom.lua:1220
 IsZoneMonitored = <function> defined @Carbonite\NxCom.lua:1270
 SendTime = 322855.346
 ChanALetter = "B"
 LeaveChan = <function> defined @Carbonite\NxCom.lua:851
 UpdateChannels = <function> defined @Carbonite\NxCom.lua:675
 PalsInfo = <table> {
 }
 PlyrY = 0.43450224399567
 SendQNames = <table> {
 }
 ZPInfo = <table> {
 }
 OnChat_msg_channel = <function> defined @Carbonite\NxCom.lua:426
 Chksum = <function> defined @Carbonite\NxCom.lua:1117
 PalsSendQ = <table> {
 }
 ParseLGP = <function> defined @Carbonite\NxCom.lua:634
 SendSecW = <function> defined @Carbonite\NxCom.lua:1020
 RegisterMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 OnLeaveATimer = <function> defined @Carbonite\NxCom.lua:291
 OnBytesSecTimer = <function> defined @Carbonite\NxCom.lua:169
 OnPlayer_level_up = <function> defined @Carbonite\NxCom.lua:300
 RegisterEvent = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UpdatePlyrIcons = <function> defined @Carbonite\NxCom.lua:1664
 SendRate = 1
 OnJoinChanATimer = <function> defined @Carbonite\NxCom.lua:785
 OnFriendguild_update = <function> defined @Carbonite\NxCom.lua:311
 TryA = 1
 OnJoinChanZTimer = <function> defined @Carbonite\NxCom.lua:804
 Punks = <table> {
 }
 MemberNames = <table> {
 }
 Encode = <function> defined @Carbonite\NxCom.lua:1154
 UnregisterAllEvents = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Data = <table> {
 }
 InChan = <function> defined @Carbonite\NxCom.lua:963
 ScanChans = <function> defined @Carbonite\NxCom.lua:906
 SendChanQ = <table> {
 }
 PlyrChange = 322855.811
 OnUpdate = <function> defined @Carbonite\NxCom.lua:1279
 Initialized = true
 SendQ = <table> {
 }
 SendChan = <function> defined @Carbonite\NxCom.lua:1092
 SendPMask = 7
 PlyrName = "Reflexwolf-Gnomeregan"
 SendPosTime = 322854.999
 PlyrClassI = 3
 UpdateIcons = <function> defined @Carbonite\NxCom.lua:1586
 Name = "Crb"
 SendZSkip = 4
 PlyrMapId = 84
 IsChksumOK = <function> defined @Carbonite\NxCom.lua:1129
 GetPlyrQStr = <function> defined @Carbonite\NxCom.lua:1794
 SendChanTime = 322847.392
 SentBytesTime = 322768.359
 SentBytes = 1260
 SentBytesSec = 0
 TypeColors = <table> {
 }
 UpdateChannelsTimer = <function> defined @Carbonite\NxCom.lua:679
 MonitorZone = <function> defined @Carbonite\NxCom.lua:1235
 Send = <function> defined @Carbonite\NxCom.lua:1034
 ClassNames = <table> {
 }
 LeaveChans = <function> defined @Carbonite\NxCom.lua:868
 JoinChan = <function> defined @Carbonite\NxCom.lua:757
 ParsePlyrStatus = <function> defined @Carbonite\NxCom.lua:513
 Friends = <table> {
 }
 SendSecG = <function> defined @Carbonite\NxCom.lua:997
 List = <table> {
 }
 OnChatEvent = <function> defined @Carbonite\NxCom.lua:355
 SendMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 Decode = <function> defined @Carbonite\NxCom.lua:1172
 ZStatus = <table> {
 }
 Created = true
 OnLoginTimer = <function> defined @Carbonite\NxCom.lua:234
 SendQMode = 1
 SetSendPa

**Comment by reflexwolf** [comment]
what version should I pull to test to see if its working now?

**Comment by IrcDirk** [comment]
Latest form master branch or wait for Alpha update on Curse/Twitch client.

**Comment by reflexwolf** [comment]
danka :)

**Comment by reflexwolf** [comment]
confirmed its gone away now :) thank you!
