### ISSUE TITLE
something is wrong with the flight points and tracking to waypoints

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite#107]
hi, this one isn't critical but is annoying, when I have a quest targeted the mini map is showing me right on top of the location I need to go but is telling me to fly way far away, then hop a flight point, and go back to the flight point I was just at and then come here again. I enclosed a screen shot of the screen. 

![world of warcraft](https://user-images.githubusercontent.com/15761117/43319356-432a3998-9159-11e8-810d-3eb86cde8b2b.jpg)

**Comment by IrcDirk** [comment]
This is know issue. Will work on this later.

**Comment by reflexwolf** [comment]
sounds good to me I wasn't sure if it was a new problem or not and as I love this addon I thought I would let you know :)

**Comment by IrcDirk** [comment]
Leave it open ;)

**Comment by reflexwolf** [comment]
oops ok :) sorry!
