### ISSUE TITLE
Quests not showing up in minimap for Broken Shore

### ISSUE THREAD

**Issue by Morindra** [mikepauer/Carbonite#11]
Minimap does not show quests.  Alt+M map shows quests and other details.  I am on build 7.2.5 4af7239.

**Comment by Thrumbar** [comment]
This should be in the Quest issues.

**Comment by fdellwing** [comment]
Yep, it should be. But one question: Is it on an instance map? If so, its a duplicate of #8

**Comment by Thrumbar** [comment]
Also what quest (World or Normal) also is he talking about quest blobs...???

**Comment by Morindra** [comment]
I do not see world or normal quests, nor do I see quest blobs in my Carbonite maps.  I can see them in the alt+m map.

**Comment by Morindra** [comment]
I'm an effin noob and did not realize that this was split into separate repositories.  I added the carbonite.quest and all is well.  Closing this issue.
