### ISSUE TITLE
several minor things

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite#112]
hi, me again, I have a few more little niggling problems that have been cropping up a lot of late.

first off, when I log into a character, or when I just sit and do things like crafting the map goes full screen on me without prompting. just takes over the screen and will even kill work jobs I'm doing. as I was typing this and idle in wow it did it again. 

second is the map arrow, it keeps going away, some times I can see no reason I look up and its gone, other times its after I hop a griffin or the like, it happens in and out of dungeons.  Below is a screen shot of it. 

![world of warcraft no flight arrow](https://user-images.githubusercontent.com/15761117/43616382-1ead379c-9671-11e8-8efe-3d29657acc1d.jpg)

third is a strange thing that just popped when going from the main map to the smaller one it left a map of Dalaran hanging there, the only way I could get it to go away was to do a /relaod 

![world of warcraft strange map](https://user-images.githubusercontent.com/15761117/43616444-604cdfe0-9671-11e8-88be-3ef1c9a72872.jpg)

and the forth thing, the flight points don't show up when the map is scrolled out, after a point the just go away, this also includes things like dungeon locations and the like, the next 2 shots are of before and after where they show up when zooming in and out. 

![world of warcraft 1](https://user-images.githubusercontent.com/15761117/43616506-a8dd94d4-9671-11e8-8be5-6210a271e790.jpg)

And 

![world of warcraft 2](https://user-images.githubusercontent.com/15761117/43616510-ae07027e-9671-11e8-8076-2673886e94d3.jpg)

once again thank you all for all the hard work you do and I hope I'm not being a pest with all the little things I keep bringing up.

**Comment by IrcDirk** [comment]
First of all. One problem one opened issue.

Next disable all other addons except Carbonite and then check if this accours. All problems except Player Arrow seems problems or incompatibility with other addon.

**Comment by IrcDirk** [comment]
Missing arrow and flight masters should be ok now.

**Comment by reflexwolf** [comment]
ok I just got the updates and loaded them with no other things other than maps and quests loaded, and right now in dal I'm flying and the arrow isn't moving to point where I'm going but sorta just moves over the map randomly, right now I just did a circle around the statue in front of the bank and the circle of dots moved from point a to the enclave, I'm not sure if its just my settings, is there a way to reset them to default?
