### ISSUE TITLE
v8.0.1 performance issue.

### ISSUE THREAD

**Issue by woranhun** [mikepauer/Carbonite#115]
I have fps drops (screen freezes for 1-2sec) when accepting quests or completing quests. Also, I have the drop when killing mobs related to the quest.

After disabling Carbonite addon there was no performance problem.

**Comment by IrcDirk** [comment]
This i known issue. Im working on it. Closing since this is duplikate of https://github.com/mikepauer/Carbonite.Quests/issues/47
