### ISSUE TITLE
Recurring Map Issues

### ISSUE THREAD

**Issue by PhiraNova** [mikepauer/Carbonite#117]
Mini Map is once again not keeping its set scale and frequently resets to blue screen till you zoom out. Also once again gathering nodes are not being saved.

**Comment by PhiraNova** [comment]
Adding onto this hoping to get a reply. A new map issue has occurred, if you have the mini map up and the world quest map it causes the world quest map to flicker.

**Comment by IrcDirk** [comment]
All those issues are all ready on fix list.
