### ISSUE TITLE
Very strange map effect

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#118]
See screenshot:

![wowscrnshot_082318_190525](https://user-images.githubusercontent.com/22813377/44540632-ba7a7f80-a707-11e8-8f8e-2c26159d2b8e.jpg)

/reload ui fixxes this problem btw

**Comment by IrcDirk** [comment]
you didnt get any errors?

**Comment by fdellwing** [comment]
No, not a single one. I also did not had this problem for over a week now. So maybe it was a strange side effect of something already fixxed?

**Comment by IrcDirk** [comment]
Yep, maybe. Closing, if it occours again please open.
