### ISSUE TITLE
NxTravel.lua:391: attempt to index local 'dstInfo' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#12]
Was traveling from Azurewing Repose, Azsuna to Nesingwary, Highmoutain when I get this error.  Do not know if it is an interaction error or carbonite specific as this error is erratic in appearance. 

2839x Carbonite\NxTravel.lua:391: attempt to index local 'dstInfo' (a nil value)
Carbonite\NxTravel.lua:391: in function `MakePath'
Carbonite\NxMap.lua:5756: in function `CalcTracking'
Carbonite\NxMap.lua:5709: in function `?'
Carbonite\NxMap.lua:4909: in function `Update'
Carbonite\NxMap.lua:3812: in function <Carbonite\NxMap.lua:3696>

Locals:
self = <table> {
 LegionFlyName = "Broken Isles Pathfinder"
 CaptureTaxi = <function> defined @Carbonite\NxTravel.lua:104
 MakePath = <function> defined @Carbonite\NxTravel.lua:376
 OnTaximap_opened = <function> defined @Carbonite\NxTravel.lua:91
 TaxiNameStart = "Gloaming Reef, Val'sharah"
 TaxiTimer = <function> defined @Carbonite\NxTravel.lua:321
 TaxiSaveTime = <function> defined @Carbonite\NxTravel.lua:336
 OrigTakeTaxiNode = <function> defined =[C]:-1
 FindConnection = <function> defined @Carbonite\NxTravel.lua:749
 TaxiFindNodeFromRouteXY = <function> defined @Carbonite\NxTravel.lua:241
 PandariaFlyName = "Wisdom of the Four Winds"
 Init = <function> defined @Carbonite\NxTravel.lua:30
 AzerothFlyName = "Flight Master's License"
 DebugCaptureTaxi = <function> defined @Carbonite\NxTravel.lua:850
 Travel = <table> {
 }
 TaxiCalcTime = <function> defined @Carbonite\NxTravel.lua:169
 WrathFlyName = "Cold Weather Flying"
 FindFlight = <function> defined @Carbonite\NxTravel.lua:611
 DraenorFlyName = "Draenor Pathfinder"
 FindClosest = <function> defined @Carbonite\NxTravel.lua:696
 TakeTaxiNode = <function> defined @Carbonite\NxTravel.lua:136
 GetRidingSkill = <function> defined @Carbonite\NxTravel.lua:902
 TaxiFindConnectionTime = <function> defined @Carbonite\NxTravel.lua:262
 Add = <function> defined @Carbonite\NxTravel.lua:55
}
tracking = <table> {
}
srcMapId = 1015
srcX = 1608.3653943641
srcY = -1012.0061695492
dstMapId = "7334"
dstX = 0
dstY = 0
targetType = "Goto"
Map = <table> {
 Menu_OnTrackPlyr = <function> defined @Carbonite\NxMap.lua:2785
 GetInstanceID = <function> defined @Carbonite\NxMap.lua:8970
 ZoneOverlays = <table> {
 }
 HideExtraFrames = <function> defined @Carbonite.Info\NxInfo.lua:1261
 GetZoneAchievement = <function> defined @Carbonite\NxMap.lua:10585
 MinimapOwnInit = <function> defined @Carbonite\NxMap.lua:1814
 RestoreBlizzBountyMap = <function> defined @Carbonite\NxMap.lua:3124
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Carbonite\NxMap.lua:2427
 OnButToggleGuide = <function> defined @Carbonite\NxMap.lua:1588
 GetWinName = <function> defined @Carbonite\NxMap.lua:1173
 SetToCurrentZone = <function> defined @Carbonite\NxMap.lua:9052
 GetIconStatic = <function> defined @Carbonite\NxMap.lua:8093
 UpdateToolBar = <function> defined @Carbonite\NxMap.lua:1210
 Menu_OnBackgndAlphaFade = <function> defined @Carbonite\NxMap.lua:2690
 BlizzToggleWorldMap = <function> defined @Carbonite\NxMap.lua:3151
 Menu_OnMapDebugFullCoords = <function> defined @Carbonite\NxMap.lua:2736
 GotoPlayer = <function> defined @Carbonite\NxMap.lua:9177
 ResetIcons = <function> defined @Carbonite\NxMap.lua:7841
 Minimap_OnEvent = <function> defined @Carbonite\NxMap.lua:1905
 UnpackObjective = <function> defined @Carbonite\NxMap.lua:10833
 GetWorldContinentInfo = <function> defined @Carbonite\NxMap.lua:9345
 ReverseTargets = <function> defined @Carbonite\NxMap.lua:9655
 GetWorldZoneScale = <function> defined @Carbonite\NxMap.lua:9404
 GMenu_OnPasteLink = <function> defined @Carbonite\NxMap.lua:2914
 ContCnt = 8
 CreateToolBar = <function> defined @Carbonite\NxMap.lua:1180
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Carbonite\NxMap.lua:11113
 RestoreWorldMap = <function> defined @Carbonite\NxMap.lua:10871
 DetachWorldMap = <function> defined @Carbonite\NxMap.lua:1423

**Comment by Thrumbar** [comment]
Got this today when finishing "A Call to Action" and acquiring The Threat Rises..\

9266x Carbonite\NxTravel.lua:391: attempt to index local 'dstInfo' (a nil value)
Carbonite\NxTravel.lua:391: in function `MakePath'
Carbonite\NxMap.lua:5778: in function `CalcTracking'
Carbonite\NxMap.lua:5731: in function `?'
Carbonite\NxMap.lua:4918: in function `Update'
Carbonite\NxMap.lua:3821: in function <Carbonite\NxMap.lua:3705>

Locals:
self = <table> {
 LegionFlyName = "Broken Isles Pathfinder"
 CaptureTaxi = <function> defined @Carbonite\NxTravel.lua:104
 MakePath = <function> defined @Carbonite\NxTravel.lua:376
 OnTaximap_opened = <function> defined @Carbonite\NxTravel.lua:91
 TaxiSaveName = false
 TaxiNameStart = "Valdisdall, Stormheim"
 TaxiTimer = <function> defined @Carbonite\NxTravel.lua:321
 TaxiTimeEnd = 86606.236
 TaxiSaveTime = <function> defined @Carbonite\NxTravel.lua:336
 OrigTakeTaxiNode = <function> defined =[C]:-1
 FindConnection = <function> defined @Carbonite\NxTravel.lua:749
 TaxiFindNodeFromRouteXY = <function> defined @Carbonite\NxTravel.lua:241
 PandariaFlyName = "Wisdom of the Four Winds"
 Init = <function> defined @Carbonite\NxTravel.lua:30
 AzerothFlyName = "Flight Master's License"
 DebugCaptureTaxi = <function> defined @Carbonite\NxTravel.lua:850
 Travel = <table> {
 }
 TaxiCalcTime = <function> defined @Carbonite\NxTravel.lua:169
 WrathFlyName = "Cold Weather Flying"
 FindFlight = <function> defined @Carbonite\NxTravel.lua:611
 DraenorFlyName = "Draenor Pathfinder"
 FindClosest = <function> defined @Carbonite\NxTravel.lua:696
 TakeTaxiNode = <function> defined @Carbonite\NxTravel.lua:136
 GetRidingSkill = <function> defined @Carbonite\NxTravel.lua:902
 TaxiFindConnectionTime = <function> defined @Carbonite\NxTravel.lua:262
 Add = <function> defined @Carbonite\NxTravel.lua:55
}
tracking = <table> {
}
srcMapId = 1024
srcX = 2233.5592141735
srcY = -1499.6437433939
dstMapId = "7334"
dstX = 0
dstY = 0
targetType = "Goto"
Map = <table> {
 Menu_OnTrackPlyr = <function> defined @Carbonite\NxMap.lua:2794
 GetInstanceID = <function> defined @Carbonite\NxMap.lua:9057
 ZoneOverlays = <table> {
 }
 HideExtraFrames = <function> defined @Carbonite.Info\NxInfo.lua:1261
 GetZoneAchievement = <function> defined @Carbonite\NxMap.lua:10680
 MinimapOwnInit = <function> defined @Carbonite\NxMap.lua:1816
 RestoreBlizzBountyMap = <function> defined @Carbonite\NxMap.lua:3133
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Carbonite\NxMap.lua:2436
 OnButToggleGuide = <function> defined @Carbonite\NxMap.lua:1590
 GetWinName = <function> defined @Carbonite\NxMap.lua:1175
 SetToCurrentZone = <function> defined @Carbonite\NxMap.lua:9139
 GetIconStatic = <function> defined @Carbonite\NxMap.lua:8176
 UpdateToolBar = <function> defined @Carbonite\NxMap.lua:1212
 Menu_OnBackgndAlphaFade = <function> defined @Carbonite\NxMap.lua:2699
 BlizzToggleWorldMap = <function> defined @Carbonite\NxMap.lua:3160
 Menu_OnMapDebugFullCoords = <function> defined @Carbonite\NxMap.lua:2745
 ClipFrameByMapType = <function> defined @Carbonite\NxMap.lua:6851
 ResetIcons = <function> defined @Carbonite\NxMap.lua:7924
 Minimap_OnEvent = <function> defined @Carbonite\NxMap.lua:1907
 UnpackObjective = <function> defined @Carbonite\NxMap.lua:10928
 GetWorldContinentInfo = <function> defined @Carbonite\NxMap.lua:9432
 ReverseTargets = <function> defined @Carbonite\NxMap.lua:9744
 GetWorldZoneScale = <function> defined @Carbonite\NxMap.lua:9491
 GMenu_OnPasteLink = <function> defined @Carbonite\NxMap.lua:2923
 ContCnt = 8
 CreateToolBar = <function> defined @Carbonite\NxMap.lua:1182
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Carbonite\NxMap.lua:11208
 RestoreWorldMap = <function> defined @Carbonite\NxMap.lua:10966
 DetachWorldMap = <function> d

**Comment by IrcDirk** [comment]
Thats weird... never got this error... Is this still happening?

**Comment by Thrumbar** [comment]
Have not seen this error so will close.  May have been fix with other patches..
