### ISSUE TITLE
Map location is inaccurate at the minimap detail level.

### ISSUE THREAD

**Issue by Wolfane** [mikepauer/Carbonite#120]
Hi, my map location (at the minmap detail level) appears to be inaccurate for all of the new zones in Battle for Azeroth, except for Tiragarde Sound.  Most of the other zones shows me as in the ocean when I'm on land.  Please see the screenshots below.  The first shows my location using blizzards map just fine, but then when I zoom in to get the minimap detail, it shows me as in the ocean northeast of the Nazmir zone.  When I am near Atal'Gral in Zuldazar.

![capture](https://user-images.githubusercontent.com/21977017/44632487-d0668b00-a927-11e8-88a5-78bbaeef0bd6.PNG)

![capture2](https://user-images.githubusercontent.com/21977017/44632490-d9eff300-a927-11e8-9880-96bb44d96bb4.PNG)

**Comment by IrcDirk** [comment]
This is known issue. Will be fixes soon.

niedz., 26 sie 2018, 22:03 użytkownik Wolfane <notifications@github.com>
napisał:

**Comment by Wolfane** [comment]
Ah ok.  Thank you so much for your hard work on this addon.  It is by far my favorite addon.  My guild leader makes fun of me for recommending it people so much, I don't care though.  It's worth it.  Keep up the hard work, your efforts are appreciated!
