### ISSUE TITLE
NxMap.lua:7364: TexCoord out of range

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#122]
`23x Carbonite\NxMap.lua:7364: TexCoord out of range
[C]: in function `SetTexCoord'
Carbonite\NxMap.lua:7364: in function `ClipFrameTL'
Carbonite\NxMap.lua:5549: in function `?'
Carbonite\NxMap.lua:4967: in function `Update'
Carbonite\NxMap.lua:3878: in function <Carbonite\NxMap.lua:3762>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = -nan(ind)
(*temporary) = 0
(*temporary) = 1
`

**Comment by IrcDirk** [comment]
It would be great to know when this happened.

**Comment by Thrumbar** [comment]
Got this again while grouped in Boralus..  The group leader logged off and right before I logged off this error poped..  Had to log back in to check error..  Was on my paladin.

**Comment by Thrumbar** [comment]
Still getting this error. Happens when in group and leader logs off without leaving group. Error is on the other player.. It is much worse now.... I was dual boxing at the time...

Message: Interface\AddOns\Carbonite\NxMap.lua:7364: TexCoord out of range
Time: Fri Sep 14 18:48:47 2018
Count: 199
Stack: Interface\AddOns\Carbonite\NxMap.lua:7364: TexCoord out of range
[C]: in function SetTexCoord' Interface\AddOns\Carbonite\NxMap.lua:7364: in functionClipFrameTL'
Interface\AddOns\Carbonite\NxMap.lua:5549: in function ?' Interface\AddOns\Carbonite\NxMap.lua:4967: in functionUpdate'
Interface\AddOns\Carbonite\NxMap.lua:3878: in function <Interface\AddOns\Carbonite\NxMap.lua:3762>

Locals: (*temporary) = {
0 =
}
(*temporary) = 0
(*temporary) = -nan(ind)
(*temporary) = 0
(*temporary) = 1

**Comment by IrcDirk** [comment]
U didnt update thats not posdible after my fix.

**Comment by Thrumbar** [comment]
I figured out what was wrong.  You pull bf5173fb5764aa0f03d6bd8b4019d1e09ef571b9  was never accepted on curseforge..  When you did a fix with pull 9e02296213958cb03c348e30bce96f4acb038ef6 that was accepted..  The change you did to NxUI was never accepted by Curseforge and is missing from that version and the cause of the error I have gotten...  Need to refresh or re push it to curseforge

**Comment by Thrumbar** [comment]
Well I thought I did.  Downloaded from git and now trying deleting saved var...

**Comment by Thrumbar** [comment]
Deleting the saved variables seemed to solve the issue closing...  May want to check if all the patches made it to Curseforge..
