### ISSUE TITLE
issue not bug

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite#126]
Hi, I'm having an issue, when trying to mouse over the map to click on a world quest or some other poi it goes bank in the whole zone I'm trying to click on to create a way point or just check out the tool tip on it. its a bit frustrating, if there is a setting I'm not seeing to stop this I would love to know and am sorry to have bothered you all :) also could we get a option to turn off the floating world quest icon? I Never use it and its annoying to me at this point :) 
Thanks and let me know if I posted this to the wrong place.

**Comment by IrcDirk** [comment]
I dont get it, what king of "floating icon"? Can u give me an example, screenshot?

**Comment by reflexwolf** [comment]
when you finish a world quest carbonite pulls a world quest icon from
elsewhere and place it over where I'm at, I am guessing its a sort of doing
a bread crumb so you can just click on it and go to the next world quest.
the only way I have found to get rid of it is to zoom way out past zone
level. I'm not sure how to do a screen shot of it that would show what its
doing. its just adding a world quest icon to your location that if you
click on it will jump to where its from with a path. I just tried to
recreate it, and now its not doing it so I'm a bit confused perhaps it was
removed and I didn't notice... oh well its early I need more coffee :)

**Comment by IrcDirk** [comment]
Ok, i think i fixed it.

**Comment by reflexwolf** [comment]
Thank you :)

**Comment by reflexwolf** [comment]
what release is it in?

**Comment by IrcDirk** [comment]
Alpha

**Comment by reflexwolf** [comment]
ok so far looks like the floating WQ marker is gone :) yay! now if I could just not have to play hide and seek with POI on maps, where I can see them then move my mouse over to click on them to get a tool tip or set waypoints to them they go away.

**Comment by IrcDirk** [comment]
As for the other issue, i made fix and now u can hold ALT key not to display overlay map of city (or not to hide it) to be able to click WQ icons.

**Comment by reflexwolf** [comment]
Thank you Radek! that makes me happy and why I love this addon as you
people work hard for us and make changes to help make it a better thing!
