### ISSUE TITLE
NxMap.lua:7390: TexCoord out of range Time: Sat Sep 29 16:24:52 2018

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#127]
Get this when dual playing on a single box.  When grouped I log off one character the error pops on the remaining character still logged on until the other logs back on...

https://youtu.be/84ansZvVg4o

`Message: Interface\AddOns\Carbonite\NxMap.lua:7390: TexCoord out of range
Time: Sat Sep 29 16:24:52 2018
Count: 570
Stack: Interface\AddOns\Carbonite\NxMap.lua:7390: TexCoord out of range
[C]: in function `SetTexCoord'
Interface\AddOns\Carbonite\NxMap.lua:7390: in function `ClipFrameTL'
Interface\AddOns\Carbonite\NxMap.lua:5565: in function `?'
Interface\AddOns\Carbonite\NxMap.lua:4983: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3878: in function <Interface\AddOns\Carbonite\NxMap.lua:3762>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = -nan(ind)
(*temporary) = 0
(*temporary) = 1
`

**Comment by IrcDirk** [comment]
Should be fixed. Please report back when u check this.

**Comment by Thrumbar** [comment]
Originally when I downloaded the last push I got an overflow error. Did not save the error because after I changed the dungeon and raid level from mythic to normal the error vanished..  Now it does not happen regardless of said settings..  Closing...
