### ISSUE TITLE
 integer overflow attempting to store -nan(ind)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#128]
Message: integer overflow attempting to store -nan(ind)
Time: Tue Oct  2 06:29:12 2018
Count: 269
Stack: integer overflow attempting to store -nan(ind)
[C]: in function `format'
Interface\AddOns\Carbonite\NxMap.lua:5655: in function `?'
Interface\AddOns\Carbonite\NxMap.lua:4983: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3878: in function <Interface\AddOns\Carbonite\NxMap.lua:3762>

Locals: (*temporary) = "%s %d %s %d%%
(%d,%d) %s %s%s"
(*temporary) = "Steeloak"
(*temporary) = 0
(*temporary) = "Druid"
(*temporary) = -nan(ind)
(*temporary) = 74.505504505495
(*temporary) = 15.115995115995
(*temporary) = ""
(*temporary) = ""
(*temporary) = ""

**Comment by IrcDirk** [comment]
When?

**Comment by Thrumbar** [comment]
When I log off while dual playing.  Does not happen everytime but was in a city at the time.  had all but Maps disabled..

**Comment by IrcDirk** [comment]
This should do it.

**Comment by Thrumbar** [comment]
Fixed
