### ISSUE TITLE
Carbonite Notes issue

### ISSUE THREAD

**Issue by greenjw8734** [mikepauer/Carbonite#129]
9x Carbonite\NxUI.lua:3418: attempt to index field '?' (a nil value)
Carbonite\NxUI.lua:3418: in function `SetType'
Carbonite\NxUI.lua:5568: in function`Update'
Carbonite.Notes\NxFav.lua:717: in function `Update'
Carbonite.Notes\NxFav.lua:585: in function`ToggleShow'
Carbonite.Notes\NxFav.lua:1424: in function `func'
Carbonite\NxUI.lua:6917: in function`UserFunc'
Carbonite\NxUI.lua:3587: in function <Carbonite\NxUI.lua:3571>

Locals:
self = <table> {
 SelFrm = <unnamed> {
 }
 LineHPad = 4
 MinW = 2
 Vis = 30
 Save = <table> {
 }
 Data = <table> {
 }
 BaseLineH = 16
 UserFunc = <function> defined @Carbonite.Notes\NxFav.lua:602
 Strs = <table> {
 }
 ButData = <table> {
 }
 HdrFrm = <unnamed> {
 }
 SSH = 505.99993896484
 Num = 4
 Columns = <table> {
 }
 User = <table> {
 }
 SSW = 306.84001464844
Sorted = false
 Buts = <table> {
 }
 UsedFrms = <table> {
 }
 Top = 1
 Font = "Font.Medium"
 MinH = 1
 Frm = <unnamed> {
 }
 FontObj = NxFontM {
 }
 HdrH = 12
 Selected = 0
 Slider = <table> {
}
}
showLast = nil
lineH = 16
hdrH = 12
last = 4
strNum = 61
cNum = 3
padW = 1
padH = 0
butNum = 2
f = <unnamed> {
 0 = <userdata>
 NxInst = <table> {
 }
 texture = <unnamed> {
 }
}
offX = 0
offY = 0
adjY = 20.5
(for index) = 2
(for limit) = 30
(for step) = 1
n = 2
line = 2
but = <table> {
 Frm = <unnamed> {
 }
 UserFunc = <function> defined @Carbonite\NxUI.lua:6271
 User = <table> {
 }
}
butType = "QuestHdr"

**Comment by atk** [comment]
Can anybody reproduce that bug?

**Comment by gOOvER** [comment]
I will try to reproduce this,  when i'm back home

**Comment by gOOvER** [comment]
When this Error happen??? i only get

```
2x Carbonite\NxUI.lua:363: bad argument #1 to 'ipairs' (table expected, got nil)
[C]: in function `ipairs'
Carbonite\NxUI.lua:363: in function `Util_TMoveItem'
Carbonite.Notes\NxFav.lua:306: in function `MoveCur'
Carbonite.Notes\NxFav.lua:290: in function `UserFunc'
Carbonite\NxUI.lua:3713: in function <Carbonite\NxUI.lua:3697>

Locals:
t = nil
item = "addons"
low = true
```

When i try up or down

**Comment by atk** [comment]
The problem lies on line 370:

```local parent = self:GetParent (item)```

yields nil, but should actually return the view the item is bound to. Maybe someone else with more knowledge of the UI system should have a look into that.

**Comment by IrcDirk** [comment]
This is old and i cant reproduce. So closing for now.
