### ISSUE TITLE
NxQuest.lua:4810: assertion failed!

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#133]
Got this error in Blight Lands doing the find Jaina story quest "Scenario: Thros, The Blighted lands"

15x Carbonite.Quests\NxQuest.lua:4810: assertion failed!
[C]: in function `assert'
Carbonite.Quests\NxQuest.lua:4810: in function `FindCur'
Carbonite.Quests\NxQuest.lua:9844: in function `UserFunc'
Carbonite\NxUI.lua:6529: in function `UserFunc'
Carbonite\NxUI.lua:3695: in function <Carbonite\NxUI.lua:3677>

Locals:
(*temporary) = false

**Comment by IrcDirk** [comment]
Same as https://github.com/mikepauer/Carbonite.Quests/issues/53 closing.
