### ISSUE TITLE
Carbonite and Candy Bucket's addon

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite#134]
Hi.

Is it by any chance possible for Candy Bucket and Carbonite Map to work together like Candy Bucket does on the Blizzard Map?

If this is possible is it then for the Carbonite Team or the Developer of Candy Bucket?

Thank you
//Jag

**Comment by IrcDirk** [comment]
Cabonite works quite well with HandyNotes use https://www.curseforge.com/wow/addons/handynotes_hallowsend
