### ISSUE TITLE
Herbalism nodes and more

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#135]
I saw commit with BFA herbalism and mining nodes but it look like it's not working. No nodes are saved on BFA maps neither old maps. I've got "enable saving gathered nodes" on but still not saving nodes. Because i was using gathermate 2 for a while since there was no BFA fix for carbonite, i've tried to import data from it but it's only importing old continent and also it's still not saving newly discovered nodes (even on old continent). I've tried to remove, clear and then reinstall carbonite from github, uninstall gathermate 2, but no matter what configuration of addons im using (with or without gathermate2) it's still not saving any nodes. Show herb location is on, i've tried to use different scale settings, no luck.
And 2nd problem:
I don't know if that's only me but when i hoover over Drustvar map, around half way (right after Arom's stand line) map is changing for tirgarde sound map witch is quite annoying because all PoI icons dissapear aswell as world quest icons so i can't click and track the route for that quests.

**Comment by IrcDirk** [comment]
Please! Dont mix two issues in one thread.

1) https://github.com/mikepauer/Carbonite.Gathermate2_Data/issues/1
2) hold ALT, this will leave map in state that u want (hovered overlay will not hide)

**Comment by IrcDirk** [comment]
As to nodes saving, this is right it doesnt save nodes becouse of API change. Ill fix this today.

**Comment by IrcDirk** [comment]
Saving nodes fixed.

**Comment by qlesz** [comment]
ok nodes are working now and thx for the tip for map :)
