### ISSUE TITLE
world quest icons do not show up on the map after patch

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#136]
i've got this error message every time i log in to the game and no world quest icons on the map appear.

Date: 2018-12-12 11:33:50
ID: 1
Error occured in: Global

Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 8112:
   attempt to call global 'WorldMap_SetupWorldQuestButton' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:8112: UpdateIcons()
   Carbonite\NxMap.lua:4949: Update()
   Carbonite\NxMap.lua:3887:
      Carbonite\NxMap.lua:3771
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10488
 DailyTypes = <table> {
 }
 AcceptPool = <table> {
 }
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3268
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3322
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11124
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5254
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11378
 GOpts = <table> {
 }
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11522
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3206
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5068
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 0
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10768
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3508
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4305
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4125
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4040
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4792
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5339
 FindNewQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4404
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10479
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5866
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10539
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11371
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4017
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11220
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8229
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4266
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4168
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3456
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8174
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10149
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4899
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4297
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5934
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4451
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3386
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2172
 RealQEntries = 27
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3302
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4218
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4714
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10073
 ScanBlizzQuestDataTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3972
 CheckShow = <function> defined @Interface\AddOns\Carbo
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AskMrRobot, v68
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  AutoLootPlus, v1.2.3
  BadBoy, vv8.0.16
  BadBoyCCleaner, vv8.0.0
  Bartender4, v4.8.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BuyEmAll, v3.5.0
  Carbonite, v@project-version@
  CarboniteNotes, v8.0.0
  CarboniteQuests, vv8.0.1.4
  CarboniteSocial, vv8.0.1-2-g1049149
  CarboniteWarehouse, v8.0.0
  DBMCore, v8.1.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTargetCaller, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  ExRT, v4000
  GottaGoFast, v30200
  GottaGoFastHistory, v30200
  HandyNotes, vv1.5.3
  HandyNotesArgus, v0.20.0
  HandyNotesBrokenShore, vv1.29
  HandyNotesDraenorTreasures, v1.21
  MoveAnything, v17.0.2
  OmniCC, v8.0.9
  Overachiever, v1.0.4
  OverachieverCache, v1.0.4
  Pawn, v2.2.31
  PersonalLootHelper, v2.17
  Postal, vv3.6.0
  Prat30, vr1193      
  Prat30Libraries, v
  RaiderIO, v8.0.1 (v201812120600)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  ReputationBars, v8.0.0
  SavedInstances, v8.0.6
  SimpleTauntAnnounce, v1.0.38
  Skillet, v4.06
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TellMeWhen, v8.5.6
  TellMeWhenOptions, v
  TidyPlatesContinued, v6.18.12
  TidyPlatesContinuedAlvara, v5a
  TidyPlatesContinuedBlizzardPlates, v1.5
  TidyPlatesContinuedClassicPlates, v
  TidyPlatesContinuedGraphite, v
  TidyPlatesContinuedGrey, v
  TidyPlatesContinuedNeon, v
  TidyPlatesContinuedQuatre, v
  TidyPlatesContinuedRenaitre, vv7.0.3
  TidyPlatesContinuedRoth, v
  TidyPlatesContinuedSimple, v7.3.0
  TidyPlatesContinuedSlimHorizontal, v2.2
  TidyPlatesContinuedSlimVertical, v2.2
  TidyPlatesContinuedHub, v
  TidyPlatesContinuedWidgets, v
  WeakAuras, v2.10.5
  WorldQuestTracker, v
  WoWProgressLink, v1.26
  BlizRuntimeLib_enUS v8.1.0.80000 <none>
  (ck=96b)

**Comment by IrcDirk** [comment]
Always check for latest Alpha. This is already resolved and was reported as an issue before ;)

**Comment by qlesz** [comment]
y i've just noticed it was in quest module sry for that

**Comment by IrcDirk** [comment]
No problem.
