### ISSUE TITLE
FPS Drop with latest patch using either DX11 or DX12

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#137]
After the MT patch, and the DX12 full support enabled, the fps in game dropped around 10-15 fps in town, and about 30 in other areas of Kul-Tiras and Zandalar.

**Comment by IrcDirk** [comment]
What do u mean by MT patch? I dont see any drops on the contrary in 8.1 FPS is much higher, but i only use DX11.

**Comment by SteveEbey73742** [comment]
Blizzard enabled Multi-Thread with DX12, and the client tries to use DX12 on systems that are compatible.  With carbonite enabled my FPS drops off about 15 to 20 frames per second. When I disable carbonite, I jump back up where it belongs, based on my hardware and settings.There is no particular setting in options or on the map, that seem to affect it, so I have no idea where to look to see what is different with this patch and carbonite.

**Comment by IrcDirk** [comment]
Thats not our fault. DX11 works fine and with even higher FPS than 8.0.x.

**Comment by SteveEbey73742** [comment]
Did not imply it was your fault.  Just wondering what is different with carbonite and DX12.  More people will be using it eventually, and I just thought it was worth exploring.

**Comment by IrcDirk** [comment]
Maybe this is related to this: https://wow.curseforge.com/projects/carbonite?comment=73 and CPU Profiling.

**Comment by SteveEbey73742** [comment]
I have a GTX 970, so that does not apply to me.  I will continue testing, to see what I can find.  It is definitely tied to the DX12 and 8.1 patch.  It goes back to near normal, if I run DX11, so I may revert to that, and just not worry about using the multi-thread features.

**Comment by IrcDirk** [comment]
More FPS fixes were added. For now im closing this.
