### ISSUE TITLE
Player arrow stuttering on Carbonite Map since WoW Patch 8.1

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite#140]
Hi.
On my end, it appears that the player arrow on the Carbonite Map when the player is in motion, stutters or slightly trembles from side to side, making the Map look like the culprit. At first I though it was until it dawned on me that the Map doesn't do it, when the player doesn't move, and therefor the arrow doesn't move. Also, mousing over the Carbonite Map stops the Map moving with the arrow, though the arrow still stutters. 
So to be sure, I right-clicked the map and deselected the "Follow You" tickbox, which made the map stop moving with the character, but the arrow indicating the player - that still stuttered when in motion. Turning the "Follow You" tickbox back on and when it motion, it then again looked as if the map was stuttering.
So to clarify: The Map isn't the culprit. The player arrow is.

This doesn't happen on the Blizzard Map, with or without Carbonite enabled.

As text can only explain so much and given that this is only visible when the player is in motion, I have taken 2 ten-seconds movies with my phone filming the part of my computer screen when my Carbonite Map is located when it's "docked" as in not fullscreen. (before any confusion arise, it is the world carb map that is docked and not carb minimap and carb minimap my end has always- and still is disabled)

On both videoes you'll see a slight tremor of the entire video.. those are my hands holding my phone without anything supporting my hands, hence the slight tremor, but please just notice the arrow.

One video shows my toon being complete still (not moving) in MoP at a Pet Master Tamer, though it's worth mentioning that the stuttering player arrow isn't specific to MoP maps. It's everywhere: MoP, WoD, Vanilla, BfA, Broken Shore ect.
https://imgur.com/Nx8GaDA

The other video shows my character in motion flying from one location in Townlong Steppes to another location within the same area.
https://imgur.com/DTkcwSz

**Comment by Swirrel** [comment]
Ohh I forgot to mention that I have the newest Alpha of the Carbonite Map from the Twitch Client

Thank you.

**Comment by IrcDirk** [comment]
People are always complaining about FPS so i made changes to make FPS better and in many of them there is one with player arrow. This is minor disadvantage but it makes Carbonite run smoother and this was made after 8.0 release not in 8.1 ;)

**Comment by Swirrel** [comment]
How can it be an FPS issue, when I don't have an issue with my FPS.

I still had the issue with the player arrow on the Carb Map a few days ago. (I haven't been online in like 3 days)... 
As I've said in my top post, This only started happening after 8.1 was released, not before. So if change to player arrow issue was corrected in 8.0 and I didn't have the issue in 8.0, then why would I have the issue in 8.1 ?

I'm confused.

**Comment by IrcDirk** [comment]
U didnt get what i wrote. I made at start of 8.0 fixes to make Carbonite run smoother becouse people was complainign about FPS issues. One of this fixes was to make player icon refresh less often.

But after my testing i dont see player arrow shuttering in 8.1... Maybe i have other options set. But my player arrow runs smooth in all zones. 

**Can anyone else confirm this?** @Swirrel your videos was recorder with only Carbonite + Modules enabled?

**Comment by Swirrel** [comment]
No. All addons was on.
I suppose that the next step would be to disable all addons and try again. Then if the stutter isn't there, then turn on each used addon at a time to see which makes the conflict. Gotcha.
If the stutter is still there with only Carbonite + Modules, then what would you like me to do/try?

Cheers.

**Comment by IrcDirk** [comment]
Please try with only Carb + Modules if it stays ill need your Carbonite
configs from wtf folder.

pon., 7 sty 2019, 15:44: Swirrel <notifications@github.com> napisał(a):

**Comment by Swirrel** [comment]
So I disabled all addons except Carbonite + Carbonite Quest
I still have the stuttering https://imgur.com/mmfZeg6 Apologies on the quality, I took the video with my phone and uploaded it from that to imgur, instead of through the computer first.

[4 Carbonite files from the WTF folder.zip](https://github.com/mikepauer/Carbonite/files/2733213/4.Carbonite.files.from.the.WTF.folder.zip)

The files are packed using Winrar.

Thank you.

**Comment by Swirrel** [comment]
I completely forgot... like 40 minutes ago I checked for addon updates through the Twitch client. There was an update to Carbonite which I ofcourse installed before entering the game.

**Comment by IrcDirk** [comment]
I think thats map shattering, not Player Arrow as other icons seems to shutter.

**Comment by Swirrel** [comment]
Edit: I am now in Legion re-testing my pet battle strategies for those fights. As we both know, there are world quests and flightmaster icons (Lightning Bolts my end) on the map and those icons do indeed stutter.

So what would I do about it?

**Comment by IrcDirk** [comment]
Im having this too, so ill try to check what changed in 8.1... It might be some optimization or change in Blizz API... dont know yet...

**Comment by Swirrel** [comment]
Well, thanks to you, what you do and your help I'm sure you'll figure it out :)
I'm just glad it's narrowed down some-what.
If you need any more data from me, let me know.

Big Thanks.

**Comment by IrcDirk** [comment]
Thats seems to be somekind Blizz optimization or Nvidia drivers... dont know yet... It seems to be compliated issue/bug. U need to get used to it since it can take a while.

**Comment by Swirrel** [comment]
I'll never get use to it. I'll just avert my attention from it while it's there and only notice when it "goes back to normal"...
But I'll also not, not use Carbonite :) hehe

And I do have Nvidia.. lovely... Just odd it "clashed" with the patch.. lol

**Comment by IrcDirk** [comment]
They are many changes in API in 8.1 and many FPS fixes that Blizz did, they changed something. Just tested on 8.0 and there is no stuttering... F*ck u Blizz...

**Comment by IrcDirk** [comment]
Ohhhh.... wait!!!! Shit ... thats DX12 bug... Blizz fucked something with DX12 support. Just changed to DX11 and i think its ok... Please check if this helps on your side.

**Comment by Swirrel** [comment]
Change that where? Cus I can't change it in-game.
![image](https://user-images.githubusercontent.com/31900265/50784640-823a9e80-12ae-11e9-9180-b5728028c77f.png)

**Comment by IrcDirk** [comment]
Sorry thats not it and u dont have it becouse u have old system or card that doesnt support it DX12

**Comment by Swirrel** [comment]
Nvidia GeForce GTX 1050 TI STRIX

**Comment by IrcDirk** [comment]
Win 10?

**Comment by Swirrel** [comment]
https://i.imgur.com/xlHpdL7.jpg

No.
Windows 7 64 bit Ultimate

**Comment by IrcDirk** [comment]
Thats why. But changing to DX11 didnt help... I dont have a clue what this can be...

**Comment by Swirrel** [comment]
Neither do I.

**Comment by Swirrel** [comment]
Everything was fine before 8.1. Now we have 8.1 and the issue is there.

**Comment by IrcDirk** [comment]
Thats not the first time that Blizz f*cked something.

**Comment by Swirrel** [comment]
No it certainly isn't

I have had the issue 1 time before, but that was way before Rythal's time.
I've no clue how it was sorted way back then. Back then though I had an entirely different pc.

**Comment by IrcDirk** [comment]
Made simple test in 8.1 and 8.0. Wrote simple addon to test frame moving. 

Here u can see the difference: https://imgur.com/a/vg4X4y1

No other addons, default settings...

**Comment by IrcDirk** [comment]
After talking to guys from wowinterface i think we found a sollution. Not all frames all fixed but overlays, player arrow and guide icons should not stutter now. Please check if this helps on your side.

**Comment by Swirrel** [comment]
I have just updated through the Twitch Client. 
I'll log in to wow asap and get back to you :)

**Comment by Swirrel** [comment]
Now the player arrow doesn't stutter anymore... but the icons for the world quests and flightmasters still do... It feels like the map moves like water... like in waves.. (watery)

**Comment by Swirrel** [comment]
https://i.imgur.com/5oiZ9dA.mp4

**Comment by IrcDirk** [comment]
Try now ;) I think its same as was in 8.0. Tested on 8.0 and 8.1 to see if they match so it should be good.

**Comment by Swirrel** [comment]
I've just update Carb map through the twitch client, so I'll log in asap and test it.
Thank you :)

**Comment by Swirrel** [comment]
Flying from Dalaran to Azsuna (it's still those pet battle strats I need to test, that keeps me in Legion^^).. however, Azsuna still has world quests, so it's a good a place as any.. That said, the player arrow doesn't stutter, the world map isn't acting watery, but the world quest icons and the flightmaster icons still stutter a little. It's nearly impossible to see unless you know what to look for and I'm in doubt because I don't know if I notice it because I have now seen it alot or because they're still not stationary.
You have done a great "job" so far. I thank you for that :)

**Comment by IrcDirk** [comment]
That minimal WQs and other icons stutter was also in 8.0 (did tests on private server to see differences between 8.0 and 8.1). Dont know how to make this dissapear.

**Comment by Swirrel** [comment]
It is very minor. You've fixed the map and the player arrow. I'm more than happy with that. Now my eyes doesn't go haywire when I have to look at the map. Now I can look at it again, and not get a headache or having to stop/mouse over map to see where I'm going.

Thank you for all the work you've put in to fixing this for me and everyone else who it might have happend too.

Cheers
//Jag

**Comment by Swirrel** [comment]
I still didn't have that odd stutter on any icons in 8.0 so which ever for you or others was there in 8.0.. as I said, it wasn't there for me, or I'd been here reporting it back then.

**Comment by IrcDirk** [comment]
I can send u videos 8.0 vs 8.1 ;)

**Comment by Swirrel** [comment]
Sure thing. I'd like to see if I can see the/any difference

**Comment by IrcDirk** [comment]
Will do when im back home.

**Comment by IrcDirk** [comment]
https://imgur.com/a/dryj3wC

**Comment by Swirrel** [comment]
The 8.1 looks like the icons are trying to move up/down/left/right all at the same time.
The 8.0 looks like it's icons are also trying to move up/down/left/right all at the same time, but their black backgrounds seem to be pulsating too, where that's way less in the 8.1.
What you're 8.1 looks like, looks nothing like what my icons in 8.1 did/does. (past tense)
And your 8.0 is no where near what mine used to be.
So I can a teeny tiny difference in your 8.1 and 8.0 but none of them comes even close to my 8.1 and 8.0

My icons in 8.0 was as unmoving as the countertop in your kitchen (unless you break it apart ofc).

I'll be online in wow later and get back to you, if the issue is "fixed".

Thank you.

**Comment by IrcDirk** [comment]
This is 8.1 with Carbonite after latest fixes and 8.0 with Carbonite last 8.0 release. They are almost the same, maybe little difference becouse the zoom might not be the same.

I consider this fixed.

**Comment by Swirrel** [comment]
I consider it fixed too.

Again, thank you for all the time and effort you've spend fixing this "thing" :D
