### ISSUE TITLE
Map overlay appears to be off

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#145]
Vid 1
https://youtu.be/wOpZ0rA47Lo

Vid 2
https://youtu.be/aAM2aHKVcFg

**Comment by fdellwing** [comment]
I do have this or a similar problem sometimes. `/reload` fixes this for some time.

**Comment by IrcDirk** [comment]
Will check that in spare time ;)

**Comment by Thrumbar** [comment]
Fixed thanks...
