### ISSUE TITLE
'Carbonite' tried to call the protected function 'NxQuestWatch:SetPoint()'

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#146]
2x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'NxQuestWatch:SetPoint()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetPoint'
Carbonite\NxUI.lua:2376: in function `?'
Carbonite.Quests\NxQuest.lua:9772: in function `UpdateList'
Carbonite.Quests\NxQuest.lua:9058: in function `func'
DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
InCombatSkipped

**Comment by IrcDirk** [comment]
When did this happened?

**Comment by Thrumbar** [comment]
War doing Tirgarde Sound starting with Defenfing the gate to Treason of ashvane.  The issue popped sometime along that time.  Will watch if it pops again.

**Comment by Thrumbar** [comment]
Got it again doing the following quest
https://www.wowhead.com/search?q=soup+stone
https://www.wowhead.com/quest=48196/following-eddies-trail
https://www.wowhead.com/quest=48195/troublesome-troglodytes

**Comment by Thrumbar** [comment]
Got it in killing the following mob
https://www.wowhead.com/npc=127290/mugg
Will try with only carbonite addon active..

**Comment by Thrumbar** [comment]
The error only pops when carbonite map / quest and GSE is active.  This shows in taint log. 

An action was blocked in combat because of taint from Carbonite - NxQuestWatch:SetPoint()
    Interface\AddOns\Carbonite\NxUI.lua:2376 ?()
    Interface\AddOns\Carbonite.Quests\NxQuest.lua:9772 UpdateList()
    Interface\AddOns\Carbonite.Quests\NxQuest.lua:9058 func()
    Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57
Interface\FrameXML\RestrictedFrames.lua:751
An action was blocked in combat because of taint from Carbonite - NxQuestWatch:SetPoint()
      Interface\AddOns\Carbonite\NxUI.lua:2376 ?()
      Interface\AddOns\Carbonite.Quests\NxQuest.lua:9772 UpdateList()
      Interface\AddOns\Carbonite.Quests\NxQuest.lua:9058 func()
      Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57
SetAction()

With only Carb map and Quest

An action was blocked in combat because of taint from Carbonite - NxQuestWatch:SetPoint()
      Interface\AddOns\Carbonite\NxUI.lua:2376 ?()
      Interface\AddOns\Carbonite.Quests\NxQuest.lua:9772 UpdateList()
      Interface\AddOns\Carbonite.Quests\NxQuest.lua:9058 func()
      Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57
Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:176 RemoveAllPinsByTemplate()

After updating to latest Ace release 1200

An action was blocked in combat because of taint from Carbonite - NxQuestWatch:SetPoint()
    Interface\AddOns\Carbonite\NxUI.lua:2376 ?()
    Interface\AddOns\Carbonite.Quests\NxQuest.lua:9772 UpdateList()
    Interface\AddOns\Carbonite.Quests\NxQuest.lua:9058 func()
    Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57
SetAction()
An action was blocked in combat because of taint from Carbonite - NxQuestWatch:SetPoint()
    Interface\AddOns\Carbonite\NxUI.lua:2376 ?()
    Interface\AddOns\Carbonite.Quests\NxQuest.lua:9772 UpdateList()
    Interface\AddOns\Carbonite.Quests\NxQuest.lua:9058 func()
    Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:57
SetAction()

**Comment by IrcDirk** [comment]
Cant reproduce...
