### ISSUE TITLE
PTR issue

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#153]
All zone outdoor maps go green screen when zooming in to minimap detail..

**Comment by IrcDirk** [comment]
Got no time for ajustments for 8.2 version :/

**Comment by IrcDirk** [comment]
https://wow.gamepedia.com/Patch_8.2.0/API_changes :

- No files outside of Interface\ can be addressed by file path anymore
- GetFileIDFromPath will no longer work for non-interface file paths.

Thats bad :/ Dumping minimap map blks will make our addon huge :/ Without we will have no minimap detail level when zooming in :/

**Comment by IrcDirk** [comment]
Ok, but we can load them by IDs. So i need to convert them from Path to IDs.

**Comment by IrcDirk** [comment]
I have converted those tables with filepaths to FileIDs and now minimap zoom works on PTR.
