### ISSUE TITLE
Local (error) - 3319

### ISSUE THREAD

**Issue by jerryjoh** [mikepauer/Carbonite#154]
The symptom that made me look is that the quest log and game map won't toggle with Carbonite enabled. The map and quest log displays when I press "L" but it doesn't toggle off when I press "L" again. In fact, no keyboard input is accepted except for ESC. I checked BugSack and the following error is being thrown:

34x Carbonite\Carbonite-v8.1.5.lua:3673: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: NXMiniMapBut:SetPoint.
[C]: in function `SetPoint'
Carbonite\Carbonite-v8.1.5.lua:3673: in function `Move'
Carbonite\Carbonite-v8.1.5.lua:3644: in function `NXOnUpdate'
[string "*:OnUpdate"]:2: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = NXMiniMapBut {
 0 = <userdata>
 NXDrag = true
}
(*temporary) = "TOPLEFT"
(*temporary) = Minimap {
 timer = 0
 0 = <userdata>
 SetZoom = <function> defined =[C]:-1
}
(*temporary) = "TOPLEFT"
(*temporary) = -8.919816
(*temporary) = -6.228704

**Comment by Thrumbar** [comment]
Not getting this error but am getting issues when using Blizzards map and quest frame (alt l,  alt m),
Map window opens but will not close unless esc pressed, same with quest windows.

**Comment by IrcDirk** [comment]
Will work on those problems with toggling map and quest frame.

**Comment by IrcDirk** [comment]
Fix pushed, but not for SetPoint error but for those issues with map toggling.

**Comment by jerryjoh** [comment]
I'm not getting this error any more but I'm getting a different one. I'm closing this one and will open a new issue. Thank you for all you do! This is an addon I use more than any other.
