### ISSUE TITLE
Issues after getting to Nazjatar

### ISSUE THREAD

**Issue by Avabehe** [mikepauer/Carbonite#155]
After I got to Nazjatar i got 4 Errors and cant use carbonite any more on this char, I also tried to delete the settings, without success.

If I use it on other chars (which weren't in Nazjatar yet) it works.

But this error is everywhere now ;)

- [x] > `1x Carbonite\NxMap.lua:3390: attempt to index local 'win' (a nil value)

> Carbonite\NxMap.lua:3390: in function `ToggleSize'
> Carbonite\NxMap.lua:3241: in function <Carbonite\NxMap.lua:3214>
> [C]: ?
> [C]: ?
> [C]: ?
> [C]: in function `Show'
> FrameXML\UIParent.lua:2652: in function `SetUIPanel'
> FrameXML\UIParent.lua:2497: in function `ShowUIPanel'
> FrameXML\UIParent.lua:2365: in function <FrameXML\UIParent.lua:2361>
> [C]: in function `SetAttribute'
> FrameXML\UIParent.lua:3212: in function `ShowUIPanel'
> FrameXML\QuestLogOwnerMixin.lua:103: in function `SetDisplayState'
> FrameXML\QuestLogOwnerMixin.lua:41: in function `HandleUserActionToggleSelf'
> ...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:413: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:412>
> [C]: in function `ToggleWorldMap'
> [string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>
> 
> Locals:
> self = <table> {
>  Menu_OnTrackPlyr = <function> defined @Carbonite\NxMap.lua:2926
>  GetInstanceID = <function> defined @Carbonite\NxMap.lua:9399
>  ZoneOverlays = <table> {
>  }
>  GetZoneAchievement = <function> defined @Carbonite\NxMap.lua:11041
>  MinimapOwnInit = <function> defined @Carbonite\NxMap.lua:1949
>  RestoreBlizzBountyMap = <function> defined @Carbonite\NxMap.lua:3298
>  MapLevels = <table> {
>  }
>  MinimapSetScale = <function> defined @Carbonite\NxMap.lua:2568
>  OnButToggleGuide = <function> defined @Carbonite\NxMap.lua:1656
>  GetWinName = <function> defined @Carbonite\NxMap.lua:1241
>  SetToCurrentZone = <function> defined @Carbonite\NxMap.lua:9481
>  GetIconStatic = <function> defined @Carbonite\NxMap.lua:8508
>  UpdateToolBar = <function> defined @Carbonite\NxMap.lua:1278
>  Menu_OnBackgndAlphaFade = <function> defined @Carbonite\NxMap.lua:2831
>  BlizzToggleWorldMap = <function> defined @Carbonite\NxMap.lua:3325
>  Menu_OnMapDebugFullCoords = <function> defined @Carbonite\NxMap.lua:2877
>  ClipFrameByMapType = <function> defined @Carbonite\NxMap.lua:7133
>  ZandalarMapBlks = <table> {
>  }
>  ResetIcons = <function> defined @Carbonite\NxMap.lua:8235
>  Minimap_OnEvent = <function> defined @Carbonite\NxMap.lua:2038
>  UnpackObjective = <function> defined @Carbonite\NxMap.lua:11289
>  GetWorldContinentInfo = <function> defined @Carbonite\NxMap.lua:9785
>  ReverseTargets = <function> defined @Carbonite\NxMap.lua:10102
>  GetWorldZoneScale = <function> defined @Carbonite\NxMap.lua:9849
>  GMenu_OnPasteLink = <function> defined @Carbonite\NxMap.lua:3055
>  ContCnt = 11
>  CreateToolBar = <function> defined @Carbonite\NxMap.lua:1248
>  PlyrNamesTipStr = ""
>  GetPlayerMapPosition = <function> defined @Carbonite\NxMap.lua:11597
>  RestoreWorldMap = <function> defined @Carbonite\NxMap.lua:11327
>  DetachWorldMap = <function> defined @Carbonite\NxMap.lua:1491
>  ClearTarget = <function> defined @Carbonite\NxMap.lua:10064
>  BGMenu_OnHelp = <function> defined @Carbonite\NxMap.lua:3091
>  UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
>  VerifySettings = <function> defined @Carbonite\NxMap.lua:300
>  HideMiniFrames = <function> defined @Carbonite\NxMap.lua:7020
>  HideExtraZoneTiles = <function> defined @Carbonite\NxMap.lua:6376
>  Menu_OnDetailAlpha = <function> defined @Carbonite\NxMap.lua:2827
>  IsInstanceMap = <function> defined @Carbonite\NxMap.lua:9726
>  EkMapBlks = <table> {
>  }
>  CheckWorldHotspotsType = <function> defined @Carbonite\NxMap.lua:6215
>  BuildPlyrLists = <function> defined @Carbonite\NxMap.lua:8647
>  SetMapByID = <function> defined @Carbonite\NxMap.lua:229
>  ScrollScale = <function> defined @Carbonite\NxMap.lua:3848
>  Menu_OnBackgndAlphaFull = <function> defined @Carbonite\NxMap.lua:2843
>  DraeneiXO = -3500
>  SetIconTypeAlpha = <function> defined @Carbonite\NxMap.lua:7876
>  MMMenuIFull = <table> {
>  }
>  CreateIconMenu = <function> defined @Carbonite\NxMap.lua:1288
>  ScanContinents = <function> defined @Carbonite\NxMap.lua:5315
>  MinimapUpdateMask = <function> defined @Carbonite\NxMap.lua:2579
>  OLMapBlks = <table> {
>  }
>  Menu_OnPlyrFollow = <function> defined @Carbonite\NxMap.lua:2807
>  Menu_OnGetQuests = <function> defined @Carbonite\NxMap.lua:2917
>  __index = <table> {
>  }
>  IconOnUpdateTooltip = <function> defined @Carbonite\NxMap.lua:8757
>  UpdateWorldMap = <f`

___________________________________________________________________________________________________________

- [x] > `3x Carbonite\Carbonite-v8.1.5.lua:1901: bad argument #2 to 'min' (number expected, got nil)

> [C]: in function `min'
> Carbonite\Carbonite-v8.1.5.lua:1901: in function `PackXY'
> Carbonite\Carbonite-v8.1.5.lua:2115: in function `AddEvent'
> Carbonite\Carbonite-v8.1.5.lua:2155: in function `AddInfoEvent'
> Carbonite\Carbonite-v8.1.5.lua:2489: in function `AddInfo'
> Carbonite\Carbonite-v8.1.5.lua:1149: in function `?'
> ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
> [C]: ?
> ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
> ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
> DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>`

___________________________________________________________________________________________________________

- [x] > `2x Carbonite\NxUI.lua:3276: attempt to concatenate field 'LayoutMode' (a boolean value)

> Carbonite\NxUI.lua:3276: in function `OpenMenu'
> Carbonite\NxUI.lua:2971: in function <Carbonite\NxUI.lua:2920>
> 
> Locals:
> self = <table> {
>  TitleFStr = <table> {
>  }
>  BorderW = 7
>  BorderH = 7
>  Border = true
>  BackgndAlphaDiff = 1
>  BackgndAlphaMin = 0
>  BackgndFadeOut = 0.150000
>  SaveData = <table> {
>  }
>  TitleH = 22
>  TitleLineH = 10
>  CursorIsSet = true
>  TitleLines = 2
>  Locked = false
>  LayoutMode = false
>  NoButs = true
>  MovSizing = false
>  BackgndFadeTarget = 1
>  TopH = 29
>  ChildFrms = <table> {
>  }
>  BackgndFadeIn = 1
>  Name = "NxHUD"
>  Frm = NxHUD {
>  }
>  BackgndFade = 1
>  FullLock = false
>  ButW = 0
>  Sizeable = false
> }
> noLock = true
> w = <table> {
>  ToggleSize = <function> defined @Carbonite\NxUI.lua:2831
>  SetSizeable = <function> defined @Carbonite\NxUI.lua:2313
>  Menu_OnTrans = <function> defined @Carbonite\NxUI.lua:1298
>  GetBorderSize = <function> defined @Carbonite\NxUI.lua:2385
>  SetTitleColors = <function> defined @Carbonite\NxUI.lua:2242
>  ResetLayout = <function> defined @Carbonite\NxUI.lua:2405
>  GetFade = <function> defined @Carbonite\NxUI.lua:2287
>  GetAttribute = <function> defined @Carbonite\NxUI.lua:1979
>  SetBGColor = <function> defined @Carbonite\NxUI.lua:2295
>  Create = <function> defined @Carbonite\NxUI.lua:1535
>  MenuWin = <table> {
>  }
>  Show = <function> defined @Carbonite\NxUI.lua:2015
>  IsLocked = <function> defined @Carbonite\NxUI.lua:2129
>  Menu = <table> {
>  }
>  GetLayoutMode = <function> defined @Carbonite\NxUI.lua:2457
>  SetTitle = <function> defined @Carbonite\NxUI.lua:2230
>  GetClientOffset = <function> defined @Carbonite\NxUI.lua:2305
>  Menu_OnHideInCombat = <function> defined @Carbonite\NxUI.lua:1248
>  IsSizeMax = <function> defined @Carbonite\NxUI.lua:2878
>  SwitchLayoutMode = <function> defined @Carbonite\NxUI.lua:2466
>  CreateButtons = <function> defined @Carbonite\NxUI.lua:1707
>  SetSize = <function> defined @Carbonite\NxUI.lua:2331
>  MenuIHideInCombat = <table> {
>  }
>  SetAttribute = <function> defined @Carbonite\NxUI.lua:1997
>  IsVisible = <function> defined @Carbonite\NxUI.lua:2067
>  SetTitleJustify = <function> defined @Carbonite\NxUI.lua:2255
>  SetMinimize = <function> defined @Carbonite\NxUI.lua:2861
>  Menu_OnLock = <function> defined @Carbonite\NxUI.lua:1252
>  SideNames = <table> {
>  }
>  __index = <table> {
>  }
>  SetCreateFade = <function> defined @Carbonite\NxUI.lua:1523
>  IsCombatHidden = <function> defined @Carbonite\NxUI.lua:2075
>  AdjustAll = <function> defined @Carbonite\NxUI.lua:1349
>  MenuITrans = <table> {
>  }
>  ConsoleShow = <function> defined @Carbonite\NxUI.lua:1410
>  MenuILayer = <table> {
>  }
>  MenuIFadeOut = <table> {
>  }
>  OnMinBut = <function> defined @Carbonite\NxUI.lua:2848
>  ResetLayouts = <function> defined @Carbonite\NxUI.lua:1312
>  SetLayoutData = <function> defined @Carbonite\NxUI.lua:2711
>  EnableMenu = <function> defined @Carbonite\NxUI.lua:2166
>  ConsoleSize = <function> defined @Carbonite\NxUI.lua:1433
>  GetBGAlpha = <function> defined @Carbonite\NxUI.lua:2265
>  MenuIFadeIn = <table> {
>  }
>  Menu_OnFadeOut = <function> defined @Carbonite\NxUI.lua:1265
>  MenuILock = <table> {
>  }
>  SetTotalSize = <function> defined @Carbonite\NxUI.lua:2345
>  StrataNames = <table> {
>  }
>  Borders = <table> {
>  }
>  SetUser = <function> defined @Carbonite\NxUI.lua:2796
>  BORDERW = 7
>  OnUpdate = <function> defined @Carbonite\NxUI.lua:3122
>  Menu_OnLayer = <function> defined @Carbonite\NxUI.lua:1274
>  BORDERH = 7
>  ClrSaveData = <function> defined @Carbonite\NxUI.lua:1339
>  Wins = <table> {
>  }
>  OpenMenu = <function> defined @Carbonite\NxUI.lua:3259
>  Attach = <function>`

___________________________________________________________________________________________________

- [x] > `5x ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:624: <unnamed>:SetScale(): Scale must be > 0
[C]: in function `SetScale'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:624: in function `InstantPanAndZoom'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:614: in function `ResetZoom'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:423: in function `OnCanvasSizeChanged'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:407: in function `SetMapID'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:33: in function `SetMapID'
Carbonite\NxMap.lua:255: in function `SetMapByID'
Carbonite\NxMap.lua:9482: in function `SetToCurrentZone'
Carbonite\NxMap.lua:9617: in function `GotoPlayer'
Carbonite\NxMap.lua:368: in function `?'
Carbonite\NxMap.lua:1204: in function `Create'
Carbonite\NxMap.lua:294: in function `Open'
Carbonite\Carbonite-v8.1.5.lua:821: in function `SetupEverything'
Carbonite\Carbonite-v8.1.5.lua:1253: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 TiledBackground = <unnamed> {
 }
}
(*temporary) = 0
`

**Comment by Thrumbar** [comment]
Please check your version of carbonite addon you have installed.... Carbonite main options screen.

Most current
8.0 Build fb8f8f1 

First 8.2 release
8.0 Build e32f699

**Comment by IrcDirk** [comment]
Use Alpha release from Twitch\Curse client.

**Comment by Avabehe** [comment]
Thx, it works with Alpha release :)
