### ISSUE TITLE
Carbonite\NxUI.lua:4031: Action[SetPoint] failed

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#160]
63x Carbonite\NxUI.lua:4031: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
[C]: in function `SetPoint'
Carbonite\NxUI.lua:4031: in function `Update'
Carbonite\NxUI.lua:3785: in function <Carbonite\NxUI.lua:3779>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 texture = <unnamed> {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = <unnamed> {
 0 = <userdata>
 NxTip = "Zoom In"
 texture = <unnamed> {
 }
 NxBut = <table> {
 }
}
(*temporary) = -1
(*temporary) = 1

**Comment by IrcDirk** [comment]
I think this was fixed?
