### ISSUE TITLE
Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)

### ISSUE THREAD

**Issue by bmtphoenix** [mikepauer/Carbonite#162]
**I'm using v8.2.0-8-gd0c16f5-alpha on WoW Retail English. This only happens in Orgrimmar when I hover over anything in the minimap. The count just keeps going until I leave Orgrimmar. This error will also happen when a quest turn-in points me back to Orgrimmar, without me hovering over the minimap.** 

_Message: Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)
Time: Wed Oct 23 17:49:04 2019
Count: 3426
Stack: Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)
[C]: ?
Interface\AddOns\Carbonite\NxTravel.lua:814: in function `FindConnection'
Interface\AddOns\Carbonite\NxTravel.lua:723: in function `FindClosest'
Interface\AddOns\Carbonite\NxTravel.lua:634: in function `FindFlight'
Interface\AddOns\Carbonite\NxTravel.lua:493: in function `MakePath'
Interface\AddOns\Carbonite\NxMap.lua:5991: in function `CalcTracking'
Interface\AddOns\Carbonite\NxMap.lua:5944: in function `?'
Interface\AddOns\Carbonite\NxMap.lua:5122: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3999: in function <Interface\AddOns\Carbonite\NxMap.lua:3883>

Locals:_

**Another error pops up at the same time:**

_Message: Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)
Time: Wed Oct 23 17:45:20 2019
Count: 1
Stack: Interface\AddOns\Carbonite\NxTravel.lua:814: attempt to index field 'Connections' (a nil value)
[C]: ?
Interface\AddOns\Carbonite\NxTravel.lua:814: in function `FindConnection'
Interface\AddOns\Carbonite\NxTravel.lua:723: in function `FindClosest'
Interface\AddOns\Carbonite\NxTravel.lua:634: in function `FindFlight'
Interface\AddOns\Carbonite\NxTravel.lua:493: in function `MakePath'
Interface\AddOns\Carbonite\NxMap.lua:5991: in function `CalcTracking'
Interface\AddOns\Carbonite\NxMap.lua:9636: in function `GotoPlayer'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:10499: in function `TrackOnMap'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:10035: in function `Set'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:9928: in function `UserFunc'
Interface\AddOns\Carbonite\NxUI.lua:6540: in function `UserFunc'
Interface\AddOns\Carbonite\NxUI.lua:3706: in function <Interface\AddOns\Carbonite\NxUI.lua:3688>

Locals:_

**Comment by IrcDirk** [comment]
Cannot reproduce, maybe ist already fixed?

**Comment by bmtphoenix** [comment]
Unfortunately, no. Anytime I have a waypoint set in Orgrimmar or hover over the minimap while in Org,

**Comment by IrcDirk** [comment]
Weird cant reproduce... try with only Carbonite + Modules enabled.

**Comment by Thrumbar** [comment]
Maybe this could,  would this help. will look into this after I get from work..

https://youtu.be/km8iCWjM4EA

**Comment by IrcDirk** [comment]
@Thrumbar thanks this helps, will check this ;)

**Comment by IrcDirk** [comment]
@Thrumbar your error should be fixed, dont know if this fixes @bmtphoenix problem. Cant reproduce his error.

**Comment by IrcDirk** [comment]
@bmtphoenix update your Carbonite to version from this repository and try again.

**Comment by Thrumbar** [comment]
Fixed for me waiting on OP.
