### ISSUE TITLE
AddOn 'Carbonite' tried to call the protected function 'UNKNOWN()'.

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#163]
I waded through the code and found a possible solution which appears to have fixed this:-

I changed line 1269:-
	local ok = pcall (SendChatMessage, msg, typ, nil, num)

to:-
	local ok = pcall (SendChatMessageFixed, msg, typ, nil, num)
	
This seems to have resolved the following:-
29x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'UNKNOWN()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `pcall'
Carbonite\NxCom.lua:1269: in function `SendChatMessageFixed'
Carbonite\NxCom.lua:1624: in function `OnUpdate'
Carbonite\Carbonite-@project-version@.lua:1329: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
InCombatSkipped

I tried to create a pull request but was being denied but can't figure out why...

Dave Johns

**Comment by IrcDirk** [comment]
Sorry your solution was bad, it fixed error but made msg never get send. Fixed.

**Comment by DaveJ61** [comment]
Hi,

Thanks for fixing this. I'm no LUA expert but it appeared to make the 
error go away. But as you said, the message was never sent.

Regards

Dave
