### ISSUE TITLE
Default install announces quest objectives many times, spamming chat

### ISSUE THREAD

**Issue by glowinghands** [mikepauer/Carbonite#168]
So, for some reason, the quest objectives get announced again, and again, and again, and again. Every few seconds. I've attached a screenshot of the behavior. 

It's been happening to my daughters since they installed last week, and it happens to my wife that I just installed tonight fresh from the Twitch managed addon repository. If you would like more information I'd be happy to give whatever is necessary. 

Luckily it's okay for now since it's just my family but I've turned it off for myself because I don't want to be "that guy" - Note I have the classic version as well and it does not exist in there, if that helps track it down.

![image](https://user-images.githubusercontent.com/15329212/79177008-fa034d00-7dbe-11ea-849a-c91b148bdee7.png)

![image](https://user-images.githubusercontent.com/15329212/79177256-a2191600-7dbf-11ea-8039-31ea0fa9b0d1.png)

**Comment by IrcDirk** [comment]
Yep i didnt moved fix from Classic to Retail. This needs to be done.

**Comment by IrcDirk** [comment]
Ok, fixed in Quest Module => https://github.com/mikepauer/Carbonite.Quests, please download version from github or Alpha release. Test and report back ;)

**Comment by glowinghands** [comment]
Sorry for the delay. I managed to fix one of my kids up with it and confirmed the fix worked. Thank you!
