### ISSUE TITLE
World map tooltips wrong place

### ISSUE THREAD

**Issue by IrcDirk** [mikepauer/Carbonite#17]
All tooltips (not only those quest once) are above main or minimap:

![obraz](https://user-images.githubusercontent.com/1030023/27781070-9dfe9270-5fcc-11e7-8522-2340fb05d833.png)

![obraz](https://user-images.githubusercontent.com/1030023/27781023-6b43dbf6-5fcc-11e7-8ddf-49ef74d69a7a.png)

**Comment by fdellwing** [comment]
This was not the case for me yesterday

**Comment by IrcDirk** [comment]
Closing. Didnt changed "Show tooltips above map" but it was checked. Unchecking this, all work fine. So this was no issue.
