### ISSUE TITLE
NxMapGuide.lua:1194: bad argument #1 to 'strlower'

### ISSUE THREAD

**Issue by DrBartschi** [mikepauer/Carbonite#171]
Retail Version and I tried it without addons / reinstallation

When I oppened the map and try to select a Instance Waypoint or something else 

```
Message: Interface\AddOns\Carbonite\NxMapGuide.lua:1194: bad argument #1 to 'strlower' (string expected, got nil)
Time: Mon May  4 09:12:16 2020
Count: 1
Stack: Interface\AddOns\Carbonite\NxMapGuide.lua:1194: bad argument #1 to 'strlower' (string expected, got nil)
[string "=[C]"]: in function `strlower'
[string "@Interface\AddOns\Carbonite\NxMapGuide.lua"]:1194: in function `UpdateList'
[string "@Interface\AddOns\Carbonite\NxMapGuide.lua"]:1144: in function `Update'
[string "@Interface\AddOns\Carbonite\NxMapGuide.lua"]:681: in function `OnListEventDo'
[string "@Interface\AddOns\Carbonite\NxMapGuide.lua"]:636: in function `UserFunc'
[string "@Interface\AddOns\Carbonite\NxUI.lua"]:6502: in function <Interface\AddOns\Carbonite\NxUI.lua:6481>

Locals: (*temporary) = nil
(*temporary) = "string expected, got nil"

```

**Comment by IrcDirk** [comment]
Not all Guides are updated. Common Place, Class, Trainers, Travel should be OK.

Dont have time for updating others :(

**Comment by IrcDirk** [comment]
Also update to latest version from this repo ;) My lines doesnt match yours.

**Comment by IrcDirk** [comment]
Instance Guides now (https://github.com/mikepauer/Carbonite/commit/b16aebbbc6fa827fc53a3fffd53795fa7525efbc) should not return an error.

So your issue sould be fixed. Update from Alpha version and report back.

**Comment by DrBartschi** [comment]
Thank you for your quick reply and your help.

It is true that no Lua error is now issued, but still no information is shown to me. Even in storm wind / older areas. No matter what I choose, including place, class, trainers, nothing is shown in the list :-(

https://www.bilder-upload.eu/bild-ad8925-1588580168.png.html

In addition, the world map (carbonite version) now opens when I want to open the quest log

**Comment by IrcDirk** [comment]
All other addons disabled? Only Carb + Modules?

Dont have DE client...

**Comment by IrcDirk** [comment]
As to opening map with L, wait till Quest Module is loaded, then it should be ok. 

Need to fix it make exemption for this.

**Comment by IrcDirk** [comment]
I have simulated deDE localization, problem was in wrong translation ;) Should be ok now (https://github.com/mikepauer/Carbonite/commit/93a6af4cf506177d850912fc4e17e0fb3a17142c).

**Comment by DrBartschi** [comment]
> 
> 
> I have simulated deDE localization, problem was in wrong translation ;) Should be ok now ([93a6af4](https://github.com/mikepauer/Carbonite/commit/93a6af4cf506177d850912fc4e17e0fb3a17142c)).

Now it works. Thank you so much!!! Now it's the good old Carbonite ;-)
