### ISSUE TITLE
NxMap.lua:7288: attempt to compare number with nil Time: 07/03/17 12:30:35

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#18]
Got this upon logging into my Druid in The Dreamgrove with only Carbonite addons loaded..
Edit 1: 
This error stopped after I left Dreamgrove...  
Carbonite 7.2.5 Build e2b81c5 was latest from Curse at the time...

Message: Interface\AddOns\Carbonite\NxMap.lua:7288: attempt to compare number with nil
Time: 07/03/17 12:30:35
Count: 843
Stack: Interface\AddOns\Carbonite\NxMap.lua:7288: attempt to compare number with nilInterface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
Interface\AddOns\Carbonite\NxMap.lua:7288: in function <Interface\AddOns\Carbonite\NxMap.lua:7233>
(tail call): ?
(tail call): ?
Interface\AddOns\Carbonite\NxMap.lua:4827: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3821: in function <Interface\AddOns\Carbonite\NxMap.lua:3705>

Locals: errorMessage = "Interface\AddOns\Carbonite\NxMap.lua:7288: attempt to compare number with nil"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by mikepauer** [comment]
should be fixed now.. i've been meaning to do it since i was getting the same error, the report just kicked me to finally fix it :P

**Comment by Thrumbar** [comment]
Now getting this after patching while in Dreamgrove.... 

627x Carbonite\NxMap.lua:7288: attempt to compare number with nil
Carbonite\NxMap.lua:7288: in function <Carbonite\NxMap.lua:7233>
(tail call): ?
(tail call): ?
Carbonite\NxMap.lua:4827: in function `Update'
Carbonite\NxMap.lua:3821: in function <Carbonite\NxMap.lua:3705>

Locals:
self = <table> {
 InstMapWX2 = 1082.6640625
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 117.60806107405
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.63999998569489
 Zone = 1077
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 163.25748502989
 BackgndAlphaFade = 0.4
 MoveLastX = 1081.2589384522
 PlyrDir = 117.60806107405
 PlyrSpeedCalcTime = 332636.947
 MapPosYDraw = -1892.0062887053
 PlyrSpeed = 0
 MapScale = 16.293162178637
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 501.79956054688
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 284
 MMScales = <table> {
 }
 MapPosX = 1081.2589384522
 BackgndAlphaTarget = 0.4
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0
 H = 141
 Tick = 145
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -1892.0062887053
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 1081.2589384522
 QuestAlpha = 0.3
 InstMapWX1 = 1078.75
 CurWorldUpdateOverlayNum = 1
 Scale = 163.25748502994
 Targets = <table> {
 }
 BackgndAlpha = 0.4
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 1077
 MMOwn = false
 Size1 = 1.1718750261934
 ShowUnexplored = false
 InstLevelSet = 0
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 InstMapWY1 = -1892.9166
 DotRaidScale = 1
 IconFrms = <table> {
 }
 StepTime = 0
 PlyrSpeedX = 1081.2589384522
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.1
 ScaleDrawW = 0.0061252934272318
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 163.25748502994
 Data = <table> {
 }
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 MMChkDelay = 20
 InstMapWY2 = -1890.307225
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TextFrm = <unnamed> {
 }
 DotPalScale = 1
 TextScFrm = <unnamed> {
 }
 InstMapInfo = <table> {
 }
 GIconMenuIFindNote = <table> {
 }
 MMOwnedFrms = <table> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 InstMapId = 1077
 PlyrY = -1892.0062887053
 Cont = "8"
 Tracking = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Level = 10
 PlyrRZY = 34.886181354523
 MenuIMonitorZone = <table> {
 }
 W = 150
 MapsDrawnFade = <table> {
 }
 CurWorldUpdateMapId = 1077
 ContFrms = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 TileFrms = <table> {
 }
 ScaleW = 0.00612529342723
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 PlyrSpeedY = -1892.0062887053
 MapPosY = -1892.0062887053
 IconWQFrms = <table> {
 }
 MapPosXDraw = 1081.2589384522
 ArchAlpha = 0.3
 MapIndex = 1
 PlyrRZX = 64.100623130798
 KillShow = false
 MenuIInstanceMaps = <table> {
 }
 NeedWorldUpdate = true
 BGIconMenu = <table> {
 }
 DotZoneScale = 1
 Frm = <unnamed> {
 }
 GIconMenu = <table> {
 }
 TransMenu = <table> {
 }
 MoveDir = 180
 BackgndAlphaFull = 1
}
frm = NxIcon1 {
 0 = <userdata>
 NxMap = <table> {
 }
 NxTip = "The Dreamgrove, Val'sharah (Druids Only)"
 texture = <unnamed> {
 }
}
bx = 1081.2463381188
by = -1892.0252822907
w = 16
h = 16
dir = 0
x = 63.778698444366
y = 34.158283472061
bw = 16
clipW = 501.79956054688
texX1 = 0
texX2 = 1
vx0 = 55.778698444366
vx1 = 55.778698444366
vx2 = 71.778698444366
bh = 16
clipH = 284
texY1 = 0
texY2 = 1
vy0 = 26.158283472061
vy1 = 26.158283472061
vy2 = 42.158283472061
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = 1
(*temporary) = 0
(*temporary) = 1
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Comment by mikepauer** [comment]
dumb mistake on my part... try now.

**Comment by Thrumbar** [comment]
Fixed
