### ISSUE TITLE
Beta - NxCom.lua:1451: Division by zero

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#184]
Getting this when porting or zoning in quest but this may be corrected with later patching by blizzard.

Message: Interface\AddOns\Carbonite\NxCom.lua:1451: Division by zero
Time: Mon Sep  7 20:36:46 2020
Count: 3
Stack: Interface\AddOns\Carbonite\NxCom.lua:1451: Division by zero
[string "@Interface\AddOns\Carbonite\NxCom.lua"]:1451: in function `OnUpdate'
[string "@Interface\AddOns\Carbonite\Carbonite.lua"]:1349: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = <table> {
 JoinChan = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:825
 ZMonitor = <table> {
 }
 PalNames = <table> {
 }
 OnLoginTimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:234
 RestoreChars = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1292
 IsZoneMonitored = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1342
 SendTime = 15626.847000
 ChanALetter = "B"
 LeaveChan = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:919
 SendPals = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1054
 PalsInfo = <table> {
 }
 PlyrY = 0.500157
 Friends = <table> {
 }
 ZPInfo = <table> {
 }
 OnChat_msg_channel = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:430
 Chksum = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1185
 PalsSendQ = <table> {
 }
 ParseLGP = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:703
 OnChat_msg_addon = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:525
 SendQMode = 1
 UnregisterMessage = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 PlyrChange = false
 OnBytesSecTimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:169
 PlyrName = "Steeloak-Oribos"
 RegisterEvent = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UpdatePlyrIcons = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1736
 SendRate = 1
 SentBytesSec = 0
 OnFriendguild_update = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:311
 OnJoinChanZTimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:872
 Punks = <table> {
 }
 MemberNames = <table> {
 }
 Encode = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1222
 UnregisterAllEvents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Data = <table> {
 }
 InChan = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1031
 ScanChans = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:974
 SendChanQ = <table> {
 }
 OnUpdate = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1351
 SendChatMessageFixed = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1253
 SendQ = <table> {
 }
 SendChan = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1160
 OnTestTimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:153
 SendPMask = 0
 UpdateChannels = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:744
 SendQNames = <table> {
 }
 SendSecW = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1088
 UpdateIcons = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1658
 RegisterMessage = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 SendZSkip = 1
 OnLeaveATimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:291
 IsChksumOK = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1197
 GetChanCount = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:901
 SendChanTime = 3753.284000
 OnPlayer_level_up = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:300
 SentBytes = 0
 OnJoinChanATimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:853
 PlyrMapId = 1699
 UpdateChannelsTimer = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:748
 MonitorZone = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1307
 Send = <function> defined @Interface\AddOns\Carbonite\NxCom.lua:1102
 ClassNames = <tabl

**Comment by IrcDirk** [comment]
Cant test this, no access to Beta.
