### ISSUE TITLE
Dungeon maps fixed at small size and quests only show on first level

### ISSUE THREAD

**Issue by Ghosthree3** [mikepauer/Carbonite#186]
After the fix for dungeon maps showing only the first level the maps have become force fixed at a really small size.

This is the size it should be forced to, http://i.imgur.com/AKcHwDd.png

This is the size it IS forced to, http://i.imgur.com/9rGeLuC.png

Shaded quest areas in dungeons also all appear on the first floor only, shown here, http://i.imgur.com/Yw9tGXi.png

Both the red and green areas on that map should have appeared on the second level where I and the party are.

**Comment by samyonair** [comment]
Size should be fixed by Rythals commit e5a32f31a30692a696e977441337a2772c348328

**Comment by IrcDirk** [comment]
Levels of dungeons should be fixed, quests blobs may be wrong.
