### ISSUE TITLE
PTR - NxMap.lua:4824: attempt to call global 'GetBattlefieldVehicleInfo' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#186]
Listing this in for reference when you get beta access or exp releases..

Message: Interface\AddOns\Carbonite\NxMap.lua:4824: attempt to call global 'GetBattlefieldVehicleInfo' (a nil value)
Time: Wed Sep  9 05:01:04 2020
Count: 532
Stack: Interface\AddOns\Carbonite\NxMap.lua:4824: attempt to call global 'GetBattlefieldVehicleInfo' (a nil value)
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:4824: in function `Update'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:4002: in function <Interface\AddOns\Carbonite\NxMap.lua:3886>

Locals: self = <table> {
 InstMapWX2 = -316.085938
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 23.355139
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.640000
 Zone = 0
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 4.113283
 BackgndAlphaFade = 0.400000
 MoveLastX = 0
 PlyrDir = 23.355139
 PlyrSpeedCalcTime = 38954.678000
 MapPosYDraw = 0
 PlyrSpeed = 0
 MapScale = 0.005000
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 502.800049
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 234.000107
 MMScales = <table> {
 }
 MapPosX = 0
 BackgndAlphaTarget = 0.400000
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.630000
 H = 141
 Tick = 6195
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 0
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 0
 QuestAlpha = 0.300000
 InstMapWX1 = -320
 CurWorldUpdateOverlayNum = 0
 Scale = 4.113283
 Targets = <table> {
 }
 BackgndAlpha = 0.400000
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 1671
 MMOwn = false
 Size1 = 1.171875
 ShowUnexplored = false
 InstLevelSet = 0
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 InstMapWY1 = 322.833325
 DotRaidScale = 1
 IconFrms = <table> {
 }
 StepTime = 0
 PlyrSpeedX = 0
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.100000
 ScaleDrawW = 0.243115
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 4.113283
 Data = <table> {
 }
 TrackDir = false
 TrackETA = false
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 MMChkDelay = 10
 InstMapWY2 = 322.833325
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TextFrm = <unnamed> {
 }
 DotPalScale = 1
 TextScFrm = <unnamed> {
 }
 InstMapInfo = <table> {
 }
 GIconMenuIFindNote = <table> {
 }
 MMOwnedFrms = <table> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 InstMapId = 1671
 PlyrY = 0
 Cont = 90
 Tracking = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Level = 12
 PlyrRZY = 52.758312
 MenuIInstanceMaps = <table> {
 }
 W = 150
 MapsDrawnFade = <table> {
 }
 CurWorldUpdateMapId = 1671
 ContFrms = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 TileFrms = <table> {
 }
 ScaleW = 0.243115
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 PlyrSpeedY = 0
 MapPosY = 0
 IconWQFrms = <table> {
 }
 MapPosXDraw = 0
 ArchAlpha = 0.300000
 MapIndex = 1
 PlyrRZX = 59.635085
 KillShow = false
 MenuIMonitorZone = <table> {
 }
 NeedWorldUpdate = false
 BGIconMenu = <table> {
 }
 DotZoneScale = 1
 Frm = <unnamed> {
 }
 GIconMenu = <table> {
 }
 TransMenu = <table> {
 }
 MoveDir = 180
 BackgndAlphaFull = 1
}
elapsed = 0.593000
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1896
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1126
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3029
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <functi

**Comment by IrcDirk** [comment]
I saw that once in PTR too.

@Thrumbar check issues 178 to 181 ;)
