### ISSUE TITLE
PTR  - NxMap.lua:4837: attempt to index local 'vtex' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#187]
Got this while in combat in Ardenweald ( Elder Srand ) while fighting a Ravenous Blightwing..  Caused a lit of lag that continued while in combat and ended when I dropped out of combat..

Message: Interface\AddOns\Carbonite\NxMap.lua:4837: attempt to index local 'vtex' (a nil value)
Time: Thu Sep 10 18:56:32 2020
Count: 28
Stack: Interface\AddOns\Carbonite\NxMap.lua:4837: attempt to index local 'vtex' (a nil value)
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:4837: in function `Update'
[string "@Interface\AddOns\Carbonite\NxMap.lua"]:4010: in function <Interface\AddOns\Carbonite\NxMap.lua:3894>

Locals: self = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 10.798710
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.640000
 Zone = 0
 WorldAlpha = 0
 StartupShown = false
 ScaleDraw = 4
 BackgndAlphaFade = 0.400000
 MoveLastX = 0
 PlyrDir = 10.798710
 PlyrSpeedCalcTime = 175488.009000
 MapPosYDraw = 0
 PlyrSpeed = 0
 MapScale = 0.005000
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 502.800049
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 234.000107
 MMScales = <table> {
 }
 MapPosX = 0
 BackgndAlphaTarget = 0.400000
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.190000
 H = 141
 Tick = 3447
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 0
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 0
 QuestAlpha = 0.300000
 CurWorldUpdateOverlayNum = 13
 Scale = 4
 Targets = <table> {
 }
 BackgndAlpha = 0.400000
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 1565
 MMOwn = false
 Size1 = 1.171875
 ShowUnexplored = false
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 DotRaidScale = 1
 IconFrms = <table> {
 }
 StepTime = 0
 PlyrSpeedX = 0
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.100000
 ScaleDrawW = 0.250000
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 4
 Data = <table> {
 }
 TrackDir = false
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TrackETA = false
 TextFrm = <unnamed> {
 }
 TextScFrm = <unnamed> {
 }
 PlyrY = 0
 GIconMenuIFindNote = <table> {
 }
 Cont = 90
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Level = 11
 Tracking = <table> {
 }
 PlyrRZY = 45.964283
 MenuIInstanceMaps = <table> {
 }
 W = 150
 CurWorldUpdateMapId = 1565
 MMOwnedFrms = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 MapsDrawnFade = <table> {
 }
 MMChkDelay = 38
 ContFrms = <table> {
 }
 PlyrSpeedY = 0
 TileFrms = <table> {
 }
 ScaleW = 0.250000
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 MapPosY = 0
 IconWQFrms = <table> {
 }
 MapPosXDraw = 0
 ArchAlpha = 0.300000
 MapIndex = 1
 MenuIMonitorZone = <table> {
 }
 PlyrRZX = 28.378069
 KillShow = false
 BGIconMenu = <table> {
 }
 NeedWorldUpdate = false
 DotZoneScale = 1
 GIconMenu = <table> {
 }
 Frm = <unnamed> {
 }
 TransMenu = <table> {
 }
 MoveDir = 180
 BackgndAlphaFull = 1
 DotPalScale = 1
}
elapsed = 0.375000
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1896
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1126
 IsGathering = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3029
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:133
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:204
 ScheduleTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbo

**Comment by IrcDirk** [comment]
I did tested it on Horde and Alliance ships in Icecrown. Now it doest throw this error but @Thrumbar please test on the same vehicle that u described.

**Comment by Thrumbar** [comment]
No vehicle was in druid form..  Bear and cat forms..  also travel form (stag).

**Comment by IrcDirk** [comment]
Maybe there is some kid of moving vehicle in this zone like in icecrown. Should be fixed.
