### ISSUE TITLE
Mogu'shan Vaults

### ISSUE THREAD

**Issue by Indubitabwy** [mikepauer/Carbonite#19]
The travel point to this instance is on the opposite side of the continent.  Didn't find out till I had to Wowhead it.  I believe this has happened with other instances like Throne Of Thunder, in that case it would be better to set the point at the portal or something.

Anyway thanks for all your hard work!

**Comment by fdellwing** [comment]
@IrcDirk Zones.lua says entrance is at 74.53/205.71/1025 but wowhead says its at 60/38/x. Can you check that?

**Comment by IrcDirk** [comment]
Yes Mogushan Valuts entrance is in wrong place, will fix this.

**Comment by fdellwing** [comment]
Should be fixxed now, please check :)
