### ISSUE TITLE
Beta and PTR - NxMapGuide.lua:1499: bad argument #4 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#191]
Beta and PTR
Getting this from Dalaran in Broken Isles

1x Carbonite\NxMapGuide.lua:1499: bad argument #4 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Carbonite\NxMapGuide.lua"]:1499: in function `UpdateMapGeneralIcons'
[string "@Carbonite\NxMapGuide.lua"]:1596: in function `?'
[string "@Carbonite\NxMap.lua"]:5077: in function `Update'
[string "@Carbonite\NxMap.lua"]:4010: in function <Carbonite\NxMap.lua:3894>

Locals:
(*temporary) = "%s
%s
%s %.1f %.1f"
(*temporary) = "Neutral Flight"
(*temporary) = "Krasus Landing, Dalaran (Legion)"
(*temporary) = nil
(*temporary) = 69.800000
(*temporary) = 51
(*temporary) = "string expected, got nil"

**Comment by Thrumbar** [comment]
Also getting this if it helps

3x ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:426: attempt to index local 'layers' (a nil value)
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:426: in function `CreateZoomLevels'
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:413: in function `OnCanvasSizeChanged'
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:404: in function `SetMapID'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:55: in function `SetMapID'
[string "@Carbonite\NxMap.lua"]:263: in function `SetMapByID'
[string "@Carbonite\NxMap.lua"]:9476: in function `SetCurrentMap'
[string "@Carbonite\NxMap.lua"]:6253: in function `CheckWorldHotspotsType'
[string "@Carbonite\NxMap.lua"]:6223: in function `CheckWorldHotspots'
[string "@Carbonite\NxMap.lua"]:4073: in function <Carbonite\NxMap.lua:3894>

Locals:
self = <unnamed> {
 0 = <userdata>
 MarkCanvasDirty = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:381
 GetMinZoomViewRect = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:550
 GetNormalizedHorizontalScroll = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:716
 SetPanTarget = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:583
 DenormalizeVerticalSize = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:741
 IsAtMaxZoom = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:652
 AccumulateMouseDeltas = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:245
 ScalingMode = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:290
 GetMap = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:664
 IsZoomingIn = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:644
 ZoomOut = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:604
 ShouldZoomInstantly = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:542
 SetScalingMode = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:286
 targetScale = 1.693114
 GetNormalizedCursorPosition = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:774
 TryPanOrZoomOnClick = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:84
 shouldPanOnClick = false
 SetZoomTarget = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:588
 normalizedPanXLerpAmount = 0.150000
 NormalizeUIPosition = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:761
 OnMouseUp = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:102
 MarkAreaTriggersDirty = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:373
 CalculateViewRect = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:554
 ResetZoom = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:616
 NormalizeHorizontalSize = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:729
 SetNormalizedHorizontalScroll = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:711
 OnLoad = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:7
 Child = <unnamed> {
 }
 zoomLevels = <table> {
 }
 SetShouldPanOnClick = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:530
 scrollYExtentsMin = 0.500000
 areaTriggersDirty = true
 scrollXExtentsMin = 0.500442
 SetCanvasSize = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:214
 normalizedZoomLerpAmount = 0.150000
 zoomAmountPerMouseWheelDelta = 0.075000
 GetScaleForMaxZoom = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:668
 CalculateLerpScaling = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:261
 GetCanvasScale = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:687
 FindBestLocationForClick = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:58
 OnMouseDown = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:26
 ShouldZoomInOnClick = <function> defined @Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:518
 shouldZoomInstantly = true
 GetScaleForMinZoom = <function> defined

**Comment by IrcDirk** [comment]
Should be ok now ;) There may be more of this kind errors when PrePatch comes live. More people playing more testing ;)
