### ISSUE TITLE
Major FPS Drop when Zooming out Carbonite Mini-Map (Worst in BfA Areas)

### ISSUE THREAD

**Issue by X3troc** [mikepauer/Carbonite#193]
The farther you zoom out the Carbonite Map, the lower the FPS goes.

In an area such as Stormwind for example, with map zoomed in, I get around 95fps.
If I zoom all the way out I drop to somewhere between 90-70fps.

However, when I do this while in Kul Tiras while questing, the FPS drops to around 15FPS.

While using the Quest addon, if the next quest is a little ways away, the farther the map zooms out the lower the FPS goes until it is around 15FPS.

I have tested this on multiple computers and multiple accounts (with all mods disabled except for Carbonite Maps) and it seems that the map performance in BfA areas is oddly worse than an area such as Stormwind.
![msedge_cmobRkAudy](https://user-images.githubusercontent.com/40405581/97117168-56cdb180-16d8-11eb-85fa-34b90fe052cb.png)
![msedge_ggJ8vvBcx9](https://user-images.githubusercontent.com/40405581/97117177-65b46400-16d8-11eb-8a31-8ddc4c230928.png)
![Wow_qtVu9cuWid](https://user-images.githubusercontent.com/40405581/97117195-6f3dcc00-16d8-11eb-9532-4ae25ab8b665.png)
![Wow_72O69JtbHq](https://user-images.githubusercontent.com/40405581/97117198-72d15300-16d8-11eb-8930-7be42ac4008b.png)

**Comment by IrcDirk** [comment]
Yes i know that. Thats becouse textures of maps after BFA are 10 times bigger then before :/ 

Before they where 3072px now they are 38400px and thats each map :( Dont know if i can do anything about it.

**Comment by IrcDirk** [comment]
I could convert them to smaller size... But then addons size will get bigger...

**Comment by X3troc** [comment]
Thanks for the insight!
Personally, I would be fine with a bit bigger download size, as the FPS hit is tremendous if the next quest is more than a short distance away (which causes the map to zoom out)

I have been using Carbonite since it first came out and I wouldn't know how to function without it. haha!

**Comment by IrcDirk** [comment]
I think so too... bigger addons size is better then lower FPS... need to test this solution.

**Comment by X3troc** [comment]
That would be great if you are able to do it and boost the performance.  I am assuming Blizzard will continue to use large (or larger) maps for Shadowlands as well.  Happy to help test if needed.  Thank you again!

**Comment by IrcDirk** [comment]
Ok, first testing Commit with new converted overlays of BFA maps pushed (ab7620ee441f12a3358c03c3bed3a6f31671f5f6, fbc4672d22a83b1679b2ec565c4708c92005f196)

Now addon is about ~50MB it depends on compression of zip. After decompresion its about 500MB :( THATS BIG!!!

**Comment by X3troc** [comment]
Downloading the Alpha version to test this out.

Thank you IrcDirk!

**Comment by IrcDirk** [comment]
Ok, now we are down to 288MB after decompresion. Not bad ;) But still those textures take much space.

**Comment by X3troc** [comment]
That is better!  I will give this version a try.

On the plus side, the previous version had SIGNIFICANT improvement.  I was not able to get the FPS to drop more than 10 or so no matter what I did with the map.

Excellent work!

**Comment by IrcDirk** [comment]
Yeah... i think it works. The bad news is that new zones in Shadowlands means more conversion needed... so again bigger addon :(

**Comment by IrcDirk** [comment]
@Thrumbar Can u check it? That it works on your side?

**Comment by Thrumbar** [comment]
Working for me on my side.

**Comment by IrcDirk** [comment]
Thanks ;) Closing...

**Comment by X3troc** [comment]
Thank you very much!
