### ISSUE TITLE
Nazmir map overlay

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#196]
Since last update Nazmir map look doubled. you can see 2 different maps on each other no matter of zoom in/out. It's the same in Kul Tiras map but in lower scale (less visible). It's best visible in Nazmir especialy when you mouse over map.

**Comment by IrcDirk** [comment]
Please provide screenshot. I dont see this problem on my version. Are u sure u are using latest alpha?

**Comment by qlesz** [comment]
Ok i've taken screenshots.Because there is no mouse cursor visible i'll just say i was taking one wihout and one with mouse over map and i uploaded it in that order. I've attached them just to show the difference but i've found out where is the problem. Look like problem exist in initial fade in/out transparency settings. After i've played aroud those i've sorted it and one map was correctly dissapearing and another appearing while zooming in out. And yes i'm using latest github version. Downloaded it and installed yesterday just in case.

![WoWScrnShot_110820_081353](https://user-images.githubusercontent.com/14138274/98459440-191e5d80-219b-11eb-8e1a-c6c5e0f31a3a.jpg)attac
![Uploading WoWScrnShot_110820_081356.jpg…]
![WoWScrnShot_110820_081406](https://user-images.githubusercontent.com/14138274/98459443-1d4a7b00-219b-11eb-95a8-cd4779260817.jpg)
![WoWScrnShot_110820_081408](https://user-images.githubusercontent.com/14138274/98459445-1de31180-219b-11eb-80c9-ad43ddabd303.jpg)
![WoWScrnShot_110820_081219](https://user-images.githubusercontent.com/14138274/98459430-099f1480-219b-11eb-8716-dbb85b33ab41.jpg)
![WoWScrnShot_110820_081226](https://user-images.githubusercontent.com/14138274/98459431-0c016e80-219b-11eb-9d5b-93a77e6ca002.jpg)
![WoWScrnShot_110820_081255](https://user-images.githubusercontent.com/14138274/98459434-0e63c880-219b-11eb-86f3-3c7b3e3ba069.jpg)
![WoWScrnShot_110820_081257](https://user-images.githubusercontent.com/14138274/98459438-13287c80-219b-11eb-9b6e-419cee7430cf.jpg)

**Comment by IrcDirk** [comment]
Hmmm... seems u have overlay transparency set... weird, cant reproduce on my side. Need to check on new profile.
