### ISSUE TITLE
Map coords and speed doesnt work

### ISSUE THREAD

**Issue by Henchman284** [mikepauer/Carbonite#197]
carb map doesn't show cords or speed, even with 2nd title and everything checked. i tried to reload UI, i have tries uninstall the game, i havbe tried to reinstal all the carbonite addons with no luck for it to work. it shows up only on some of my alt toons. but not the main one i play. please help.

**Comment by IrcDirk** [comment]
They are zone in which player position cant be tracked so this will not work. Like: Garrison, Dungs, some Instanced zones. No issue here.
