### ISSUE TITLE
integer overflow

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#198]
after leaving thorgast tower i got spammed with this and many other error messages:

Date: 2020-11-27 10:59:13
ID: 2
Error occured in: Global
Count: 1
Message: integer overflow attempting to store 21297401080.558
Debug:
   [string "=[C]"]: format()
   [string "@Carbonite\NxMap.lua"]:6047: DrawTracking()
   [string "@Carbonite\NxMap.lua"]:5990: ?()
   [string "@Carbonite\NxMap.lua"]:5148: Update()
   [string "@Carbonite\NxMap.lua"]:4021: OnUpdate()
   [string "@Carbonite\NxMap.lua"]:1423: MainOnUpdate()
   [string "@Carbonite\Carbonite.lua"]:1397: NXOnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
(*temporary) = "%s
%d yds"
(*temporary) = "Goto 58, 74"
(*temporary) = 21297401080.558075

and another:

Date: 2020-11-27 11:02:21
ID: 244
Error occured in: Global
Count: 1
Message: integer overflow attempting to store 21297401078.063
Debug:
   [string "=[C]"]: format()
   [string "@Carbonite\NxMap.lua"]:6047: DrawTracking()
   [string "@Carbonite\NxMap.lua"]:5990: ?()
   [string "@Carbonite\NxMap.lua"]:5148: Update()
   [string "@Carbonite\NxMap.lua"]:4021:
      Carbonite\NxMap.lua:3905
Locals:
(*temporary) = "%s
%d yds"
(*temporary) = "Goto 58, 74"
(*temporary) = 21297401078.062527

AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  Altoholic, v9.0.2-003
  AskMrRobot, v95
  AutoLootPlus, v2.0.0-80200
  BadBoy, vv9.0.3
  BadBoyCCleaner, vv9.0.1
  Bartender4, v4.10.6
  BuyEmAll, v3.5.9
  CanIMogIt, v9.0.2v1.30
  Carbonite, vv9.0.2.2-7-g8057366
  CarboniteNotes, vv9.0.2
  CarboniteQuests, vv9.0.2
  CarboniteSocial, vv9.0.2
  CarboniteWarehouse, vv9.0.2
  CTABroker, v1.07
  DataStore, v9.0.1-033
  DataStoreAchievements, v9.0.1-033
  DataStoreAgenda, v9.0.2-000
  DataStoreAuctions, v9.0.1-033
  DataStoreCharacters, v9.0.1-033
  DataStoreContainers, v9.0.1-033
  DataStoreCrafts, v9.0.2-000
  DataStoreCurrencies, v9.0.1-033
  DataStoreGarrisons, v9.0.1-033
  DataStoreInventory, v9.0.2-001
  DataStoreKeystones, v9.0.1-033
  DataStoreMails, v9.0.1-033
  DataStorePets, v9.0.1-033
  DataStoreQuests, v9.0.1-033
  DataStoreRares, v9.0.2-003
  DataStoreReputations, v9.0.2-003
  DataStoreSpells, v9.0.1-033
  DataStoreStats, v9.0.1-033
  DataStoreTalents, v9.0.1-033
  DBMCore, v9.0.6
  DBMDefaultSkin, v
  DBMPartyShadowlands, v
  DBMStatusBarTimers, v
  Details, v
  DetailsCastHistory, v
  DetailsChartViewer, v
  DetailsDeathGraphs, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsRaidPowerBars, v
  DetailsStreamer, v
  DetailsTargetCaller, v
  DetailsTimeLine, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ExRT, v4390
  GatherMate2, v1.46.2
  GottaGoFast, v31200
  GottaGoFastHistory, v31200
  HandyNotes, vv1.6.1
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzeroth, v3
  HandyNotesBrokenShore, vv1.39
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionTreasures, vv18
  MoveAnything, v18.0.4
  MythicDungeonTools, v3.3.1
  NeatPlates, v9.0.2.15
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v9.0.4
  Pawn, v2.4.6
  PersonalLootHelper, v2.25
  Postal, vr436
  Prat30, v3.9.1
  Prat30Libraries, v
  RaiderIO, v9.0.2 (v202011240323)
  RaiderIODBEUA, v
  RaiderIODBEUAR, v
  RaiderIODBEUH, v
  RaiderIODBEUHR, v
  ReputationBars, v8.0.0
  SavedInstances, v9.0.2
  SimpleTauntAnnounce, v1.0.44
  Skillet, v4.19
  SlideBar, v8.3.BETA-4-4 (NzothsFolly)
  Stubby, v8.3.BETA-4-4 (NzothsFolly)
  TellMeWhen, v9.0.2
  TellMeWhenOptions, v
  TransmogTokens, v1.4.9
  WeakAuras, v3.1.2
  WoWProgressLink, v1.27
  BlizRuntimeLib_enUS v9.0.2.90002 <none>
  (ck=a28)

**Comment by IrcDirk** [comment]
Should be fixed. Please report back ;)

**Comment by qlesz** [comment]
seem to be fine closing

**Comment by CaptJack2883** [comment]
I know this is marked closed, and I'm not 100% sure it is the same error as the previous, but I received this error last night after having updated to Carbonite v9.0.2.3 
I believe I had also just left torghast, and the addon kept spamming this error every few seconds until I reloaded the UI. 

```
60x integer overflow attempting to store 1459501387774.7
[string "=[C]:"]: in function 'format'
[string "@Carbonite\NxHUD.lua"]:237: in function '?'
[string "@Carbonite\NxMap.lua"]:5089: in function 'Update'
[string "@Carbonite\NxMap.lua"]:4021: in function <Carbonite\NxMap.lua:3905>
```

**Comment by IrcDirk** [comment]
Thats another place. I just posted a fix, let me know if it works.
