### ISSUE TITLE
Carbonite and TomTom - Social NXUI and AceDBOptions-3.0.lua:326: table index is nil

### ISSUE THREAD

**Issue by VOiDProXy** [mikepauer/Carbonite#199]
I've submitted a few bugs that are not because of Carbonite but because of other addons, I'm not sure how to tell unfortunately, and I'm not sure to tell if it's any critical or if I am pestering you busy masterminds with unnecessary things, but I received this error when I logged in on a character that had the latest TomTom running. I didn't mean to have them both running, but I figured I should share the report:

Message: ...Carbonite\Libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:326: table index is nil
Time: 12/30/14 21:51:13
Count: 1
Stack: (tail call): ?
[C]: ?
...Carbonite\Libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:326: in function <...Carbonite\Libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:315>
...Carbonite\Libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:429: in function `?'
Interface\AddOns\TomTom\TomTom_Config.lua:753: in function <Interface\AddOns\TomTom\TomTom_Config.lua:3>
Interface\AddOns\TomTom\TomTom_Config.lua:775: in function <Interface\AddOns\TomTom\TomTom_Config.lua:774>
Interface\AddOns\TomTom\TomTom_Config.lua:829: in function <Interface\AddOns\TomTom\TomTom_Config.lua:827>
[C]: in function `Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:204: in function `InterfaceOptionsFrame_Show'
Interface\FrameXML\InterfaceOptionsFrame.lua:482: in function `InterfaceOptionsFrame_OpenToCategory'
Interface\AddOns\Carbonite\NxOptions.lua:4135: in function `Open'
Interface\AddOns\Carbonite.Social\NxSocial.lua:1055: in function `Func'
Interface\AddOns\Carbonite\NxUI.lua:4904: in function <Interface\AddOns\Carbonite\NxUI.lua:4874>

Locals: (*temporary) = "LeftButton"
(*temporary) = <function> defined =[C]:-1

Love the work you've done on Carbonite so far getting it back up to speed, I've really missed the punk feature and the way Carbonite runs when there's a feasible chunk of people running it. Thanks for everything!

**Comment by nelegalno** [comment]
If you don't use TomTom I'd suggest disabling it, otherwise disable the Carbonite's TomTom emulation.
If you have time can you try if the problem is still present in the latest DEV version: https://github.com/Rythal/Carbonite/archive/DEV.zip

**Comment by IrcDirk** [comment]
We should test this in Live version.
