### ISSUE TITLE
Technical question about Herbalism nodes/icons

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#199]
Where is carbonite taking herbalism icons from? I've added all new herbs to my copy of carbonite but i couldn't make new icons to be properly displayed (it was displaying only red square instead of icon). I was taking icon name from wowhead.

**Comment by IrcDirk** [comment]
Push it as pull request ill check it. Need to see the code.

**Comment by qlesz** [comment]
im not familiar with github, cant find how to push it as pull request so i just attach files i've changed. and i've changed file extension to txt so i can attach it
[Carbonite.lua.txt](https://github.com/mikepauer/Carbonite/files/5631695/Carbonite.lua.txt)
[NxOptions.lua.txt](https://github.com/mikepauer/Carbonite/files/5631696/NxOptions.lua.txt)

**Comment by qlesz** [comment]
basically its working fine if i use any old icons instead

**Comment by IrcDirk** [comment]
Check those files here => https://wow.tools/files/#search=&page=1&sort=0&desc=asc

I think those are bad:

{ 700,  "inv_-misc_herb_deathblossom",L["Death Blossom"]},
{ 700,  "inv_-misc_herb_marrowroot",L["Marrowroot"]},
{ 700,  "inv_-misc_herb_ardenweald",L["Vigil's Torch"]},

Search them by entering e.g.: herb_deathblossom

**Comment by qlesz** [comment]
ty m8 now i know what mistake i've done. On wowhead is `inv_-misc_herb_deathblossom` while on page u gave me `inv_ misc_herb_deathblossom` so basically they used dash instead of space. Now it's working fine. I'm attaching file so you can push it to others. For some reason i can't push pull request.
[Carbonite.lua.txt](https://github.com/mikepauer/Carbonite/files/5636995/Carbonite.lua.txt)
[NxOptions.lua.txt](https://github.com/mikepauer/Carbonite/files/5636996/NxOptions.lua.txt)

 In near future i'll do the same for mine nodes (as soon as i start lvling my miner ;) )

**Comment by psyllock** [comment]
I kind of made the mining nodes work too, i guess next step is to fix the importer? 
[Carbonite.lua.txt](https://github.com/mikepauer/Carbonite/files/5701639/Carbonite.lua.txt)
[NxOptions.lua.txt](https://github.com/mikepauer/Carbonite/files/5701640/NxOptions.lua.txt)
