### ISSUE TITLE
Overlays for various BfA maps causing tracking issues

### ISSUE THREAD

**Issue by SiameKat** [mikepauer/Carbonite#205]
I can be standing in one spot, and pull up my map to see where the next BfA world quest is located, there are certain locations where I can't see or click on the nearby WQs. I've experienced this in Tirigarde Sound, Drustvar, Dazar'alor, and a few other places. Screenshots for clarity. 

Makes it difficult to get to the next WQ, since I don't have the Shadowlands xpac yet and WQs are the only way I can level my rep. The only way I can click on a WQ that falls under the area overlay (like in Dazar'alor) is to zoom way out on my map and then I can click on that WQ for a waypoint/go-to.

Any resolutions for this? I've tried reinstalling, uninstalling/fresh install, and do updates whenever they come out. 

![WoWScrnShot_052521_035858](https://user-images.githubusercontent.com/84740373/120081542-c8614a00-c083-11eb-9b59-9314b2a3bcb1.jpg)
![WoWScrnShot_052521_035852](https://user-images.githubusercontent.com/84740373/120081545-c9927700-c083-11eb-878a-00674276085a.jpg)
![WoWScrnShot_052421_145612](https://user-images.githubusercontent.com/84740373/120081564-e038ce00-c083-11eb-9cad-1d5db7fecf98.jpg)
![WoWScrnShot_052421_145615](https://user-images.githubusercontent.com/84740373/120081566-e169fb00-c083-11eb-9c00-0db256a0951a.jpg)

**Comment by IrcDirk** [comment]
Thats not a bug... Please see here => https://www.wowinterface.com/forums/showpost.php?p=331479&postcount=11
