### ISSUE TITLE
Overlays - Technical question

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#207]
I'm trying to add new korthia map. My question is how do you get map overlays in blp format? I was browsing wow tools web page but all overlays in there are strongly fragmented. What do you use to get ur overlays added to ...\Interface\Addons\Carbonite\Gfx\Map\Conv ?

**Comment by IrcDirk** [comment]
I got my own tool that joins and the optimize those fragments together.

**Comment by qlesz** [comment]
So basically there is no other way than pull all 140 pieces from wow tools and put all those puzzles togerher by hands :/

Is there any chance you could add Korthia map to carbonite then?

**Comment by IrcDirk** [comment]
I'm in middle of big project. It needs to wait :(

Im sure u can add it normal without using converted BLP, there is a fallback function. So u can do it as it was before i used converted map files.

**Comment by qlesz** [comment]
one more question. I've added my map to carbonite (i'll add it to github in spare time when i'll remind myself how ;) ) and it's working fine but i'm curious what is last two numbers (in this case 954, 1076) mean? I know first two is overlay resolution next two is x y axis of the main map but can't find what those last two does:
 ["_hopesascent, 2048, 2048"] = "130,0,954,1076",

**Comment by IrcDirk** [comment]
Those are taken from WorldMapOverlay (https://wow.tools/dbc/?dbc=worldmapoverlay) table and if i recall correctly its:

... = "OffsetX, OffsetY, TextureWidth, TextureHeight",
