### ISSUE TITLE
Korthia: Map overlay

### ISSUE THREAD

**Issue by codegain** [mikepauer/Carbonite#209]
Hi,

I tried adding the korthia map overlay to Carbonite because currently its just the "unexplored" map and does not appear next to the maw on the worldmap, but now I'm stuck.

I think I got the overlay config right, but can't figure out why no map texture is displayed:

NxMapData:
```
Map.MapWorldInfo = {
....
	[1543] = {
		Scale = 8.279166,
		X = -1733.3332,
		Y = -1146.6666,
		Name = L["The Maw"],
		Overlay = "themaw",
	},
	[1648] = {
		BaseMap = 1543
	},
	[1961] = { -- my korthia implementation, X/Y not adjusted currently
		Scale = 8.279166,
		X = -1733.3332,
		Y = -646.6666,
		Name = L["Korthia"],
		Overlay = "korthia",
	},
...
Map.ZoneOverlays = {
...
["korthia"] = {
        ["4074917,4074918,4074919,4074920,4074921,4074922,4074923,4074924,4074925"] = "958,997,766,637",
        ["4075007,4075011,4075012,4075013,4075014,4075015,4075016,4075017,4075018,4075008,4075009,4075010"] = "1500,0,834,696",
        ["4074961,4074969,4074970,4074971,4074972,4074973,4074974,4074975,4074976,4074962,4074963,4074964,4074965,4074966,4074967,4074968"] = "2113,0,844,875",
        ["4074977,4074988,4074999,4075001,4075002,4075003,4075004,4075005,4075006,4074978,4074979,4074980,4074981,4074982,4074983,4074984,4074985,4074986,4074987,4074989,4074990,4074991,4074992,4074993,4074994,4074995,4074996,4074997,4074998,4075000"] = "945,0,1362,1088",
        ["4075019,4075026,4075027,4075028,4075029,4075030,4075031,4075032,4075033,4075020,4075021,4075022,4075023,4075024,4075025"] = "1841,645,1264,715",
        ["4075034,4075045,4075051,4075052,4075053,4075054,4075055,4075056,4075057,4075035,4075036,4075037,4075038,4075039,4075040,4075041,4075042,4075043,4075044,4075046,4075047,4075048,4075049,4075050"] = "1474,891,1412,792",
        ["4075090,4075098,4075099,4075100,4075101,4075102,4075103,4075104,4075105,4075091,4075092,4075093,4075094,4075095,4075096,4075097"] = "597,1053,929,817",
        ["4075058,4075069,4075080,4075084,4075085,4075086,4075087,4075088,4075089,4075059,4075060,4075061,4075062,4075063,4075064,4075065,4075066,4075067,4075068,4075070,4075071,4075072,4075073,4075074,4075075,4075076,4075077,4075078,4075079,4075081,4075082,4075083"] = "1231,1429,1871,1010",
        ["4074926,4074937,4074948,4074955,4074956,4074957,4074958,4074959,4074960,4074927,4074928,4074929,4074930,4074931,4074932,4074933,4074934,4074935,4074936,4074938,4074939,4074940,4074941,4074942,4074943,4074944,4074945,4074946,4074947,4074949,4074950,4074951,4074952,4074953,4074954"] = "153,0,1612,1268",

        -- this did work, but the tiles are somewhat randomly placed and don't fit nice together
        --["sanctuaryofguidance"] = "1500,0,834,696",
        --["keepersrespite"] = "2113,0,844,875",
        --["maulersoutlook"] = "945,0,1362,1088",
        --["scholarsden"] = "1841,645,1264,715",
        --["seekersquorum"] = "1474,891,1412,792",
        --["windsweptaerie"] = "597,1053,929,817",
        --["vaultofsecrets"] = "1231,1429,1871,1010",
        --["estuaryofawakening"] = "958,997,766,637",
        --["hopesascent"] = "153,0,1612,1268",
},
...
```

Zones:
```
...
	[1543] = L["The Maw"] .. "|110|120|2|13||",
	[1648] = L["The Maw"] .. "|110|120|2|13||",
	[1961] = L["Korthia"] .. "|110|120|2|13||", -- my korthia implementation
	[1565] = L["Ardenweald"] .. "|110|120|2|13||",
...
```

NxMap:
```
Nx.Map.MapZones = {
...
		 [13] = {1525,1533,1536,1543,1565,1648,1670,1671,1672,1673,1961}, -- added 1961 for korthia map
		 [90] = {91,92,93,112,128,169,206,275,397,417,423,519,623},		 
		 [100] = {},
	}
...
```

Am I missing something? If I hover over some place on the map (where korthia should be) I can see the inner title on the top right saying "The Shadowlands, Korthia" but no overlays are drawn (with the fixed IDs - I got the idea from https://github.com/mikepauer/Carbonite/commit/ab7620ee441f12a3358c03c3bed3a6f31671f5f6).

**Comment by IrcDirk** [comment]
Please push pull request with it... This way i can check it on my side.

**Comment by codegain** [comment]
@IrcDirk I pushed the changes with #210.

**Comment by IrcDirk** [comment]
@codegain Thanks for PR.

I did comment the code which was making non converted overlays work thats why it didnt worked. Also u had wrong position and scale in NxMapData ;)

Ill convert overlays in spare time.. but the map should be working now. Please check on your side.

**Comment by IrcDirk** [comment]
I did convert the Korthia overlay to one BLP ;) Pushed release. Korthia map should be working fine.

**Comment by codegain** [comment]
@IrcDirk Can confirm, Korthia is now shown on the world map, positioning looks good!

I stated in the PR that the scale, X and Y was not adjusted (and just copied from the maw) because I couldn't get it to show on my map, making this rather difficult :)

I know that X/Y are just simply trial/error based, but how do normally calulcate the `scale` value? I'm currently also working on a PR for the map for "heart of the forest" on the world map (and possible the other covenant cities in the future), but I don't see any changes going over scale 1 (just that my X/Y positioning is wrong after that).

**Comment by codegain** [comment]
@IrcDirk I forgot to mention that Korthia is now on the world map, but I think the maw blp needs updating since Korthia was added later in the game:

Korthia:
![image](https://user-images.githubusercontent.com/11192306/135141527-c39709b5-e911-4d7d-873b-62cfde8db209.png)

The maw:
![image](https://user-images.githubusercontent.com/11192306/135141565-559d5adf-1416-49f1-98f7-5059e6627832.png)

Ingame world map:
![image](https://user-images.githubusercontent.com/11192306/135141631-9d514f63-1520-4146-a47c-e660045a4613.png)

The connection to korthia in the maw is missing on the map

**Comment by IrcDirk** [comment]
Yeah, the Maw need update.

As to X,Y and Scale they are taken from https://wow.tools/dbc/?dbc=uimapassignment but they need recalculation before use.

**Comment by IrcDirk** [comment]
Correction, i used Necrolords and did add **Seat of the Primus** in Zones.lua, other Covenant cites should work just by adding them to **Zones.lua**.

**Comment by IrcDirk** [comment]
Ok, **The Maw BLPs** updated ;)
