### ISSUE TITLE
Specify license in GitHub

### ISSUE THREAD

**Issue by codegain** [mikepauer/Carbonite#211]
Hi,

There is no license text linked with GitHub so I'm not sure which license the project has. I can see that there is a GPL license in the `Docs` folder, but also the `CarboniteLicenseAgreement.txt` (https://github.com/mikepauer/Carbonite/blob/master/Docs/CarboniteLicenseAgreement.txt). Could you clarify under which license the code currently is?

**Comment by IrcDirk** [comment]
Yes, its still GNU GPL.

**Comment by mikepauer** [comment]
Should be displayed within github now.
