### ISSUE TITLE
Incorrect package info for curseforge

### ISSUE THREAD

**Issue by MyTechnoHunter** [mikepauer/Carbonite#212]
the curseforge client shows the game version wrong, the toc included has the correct interface for retail

![image](https://user-images.githubusercontent.com/55214545/135916026-6cea10c9-4cb3-474a-bcda-9943683c24aa.png)

**Comment by IrcDirk** [comment]
Please report it to the Curse ;) Here everything is ok:

![obraz](https://user-images.githubusercontent.com/1030023/135962168-e3c5da2f-96ea-4eb8-9d77-71ab92b1b066.png)
