### ISSUE TITLE
Lag in Elwynn Forest

### ISSUE THREAD

**Issue by Morindra** [mikepauer/Carbonite#214]
Going to Elwynn from SW causes a framerate drop from 100 to 8-12.  I removed cache folder.  It persisted.  

I disabled all addons, added back one at a time.  I got to Carbonite Maps and it started.  I disabled all addons and only left Carbonite Maps and the lag persisted.  Now, I've enabled all addons, except Carbonite suite, and no lag.

**Comment by IrcDirk** [comment]
Disable mining/herb nodes. Zoom in the map.

**Comment by Morindra** [comment]
That did it.  Thank you!
