### ISSUE TITLE
Zereth Mortis support

### ISSUE THREAD

**Issue by codegain** [mikepauer/Carbonite#217]
Hi,

what needs to be done to implement the zereth mortis map to the world map? I could provide a PR for the zereth mortis BLK for the minimap-view but I don't know how to generate the BLP for the map view.

**Comment by IrcDirk** [comment]
U can do it without generating any files. See this commit for Korthia => https://github.com/mikepauer/Carbonite/commit/1af6e02c085ff7e13c4fe39eae0200946a757416

Just use IDs of BLP files. There is fallback for that.

**Comment by IrcDirk** [comment]
Those three commits are what needs to be done to add a map to Carbonite:

https://github.com/mikepauer/Carbonite/commit/1af6e02c085ff7e13c4fe39eae0200946a757416
https://github.com/mikepauer/Carbonite/commit/91c65a5d6f4c55c85a65b7a7567d0e573e032dd1
https://github.com/mikepauer/Carbonite/commit/54f371b614c4037f29f765be76e5787ae60f3b4a

**Comment by IrcDirk** [comment]
Shit ... why im explaining that to you :D those are your commits :D
