### ISSUE TITLE
dragon isles map

### ISSUE THREAD

**Issue by codegain** [mikepauer/Carbonite#230]
Hi,

I was working on the dragon isles map and got it somewhat working:

![image](https://user-images.githubusercontent.com/11192306/205742263-1a5915f6-8b4e-4783-a5ec-ecaa36ef2bb9.png)

I also got the file ids for all the zones, but there is a small problem: to get the zone blps to show, I would need data from `WorldMapOverlayTile` (for X,Y,W,H) and it seems wow.tools is no longer being updated - https://wow.tools/dbc/?dbc=worldmapoverlaytile still shows 9.2.0.

Is there another way to get this data? I already extracted the .db2 file from my local installation but can't find a parser online which works. Any ideas?

**Comment by IrcDirk** [comment]
All tools are listed here: https://wow.tools/2022.php

**Comment by IrcDirk** [comment]
Im buying Dragonflight soon :)

**Comment by codegain** [comment]
@IrcDirk I found https://github.com/wowdev/DBCD which is exacly what I needed, trying now :)

**Comment by IrcDirk** [comment]
https://github.com/Marlamin/DBC2CSV seems simpler to use and u dont have to compile it ;)

**Comment by codegain** [comment]
@IrcDirk I copied the wrong link, thats the tool I'm currently trying :)

**Comment by codegain** [comment]
@IrcDirk I will still need help calculating all the different `Scale` values for the new zones if you like to share how you calculate them :)

```
	[1978] = {
		Scale = 48.3125,
		X = -2513.75,
		Y = -1266.25,
	},
	
	[2022] = {
		Scale = 11.254166,
		X = -1883.3332,
		Y = 68.75,
		Name = L["The Waking Shores"],
		Overlay = "thewakingshores",
	},
	[2023] = {
		Scale = 13.3375,
		X = 284.1668,
		Y = 172.5,
		Name = L["Ohn'ahran Plains"],
		Overlay = "plainsofohnahra",
	},
	[2024] = {
		Scale = 12.6,
		X = -125.4168,
		Y = -963.3332,
		Name = L["The Azure Span"],
		Overlay = "theazurespan",
	},
	[2025] = {
		Scale = 8.279166,
		X = -733.3332,
		Y = -1146.6666,
		Name = L["Thaldraszus"],
		Overlay = "thaldraszus",
	},
```

**Comment by IrcDirk** [comment]
```
 let x = (parseFloat(data[8]) * -1) / 5; // X
 let y = (parseFloat(data[7]) * -1) / 5; // Y
 let s = (parseFloat(data[5]) * -1 + parseFloat(data[8])) / 500; // Scale
```

data[NUMBER] are columns from UiMapAssignment
