### ISSUE TITLE
NxQuest Lua Error

### ISSUE THREAD

**Issue by Agamemnon128** [mikepauer/Carbonite#233]
Message: Interface/AddOns/Carbonite.Quests/NxQuest.lua:9259: attempt to call global 'WorldMap_AddQuestTimeToTooltip' (a nil value)
Time: Tue Dec  6 20:17:35 2022
Count: 12
Stack: Interface/AddOns/Carbonite.Quests/NxQuest.lua:9259: attempt to call global 'WorldMap_AddQuestTimeToTooltip' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: in function `WorldMap_AddQuestTimeToTooltip'
[string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9259: in function `ScanTip'
[string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9308: in function `UpdateList'
[string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:9128: in function `func'
[string "@Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:57: in function <Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals

**Comment by IrcDirk** [comment]
Thanks but it should go to Carbonite Quest repository ;)

**Comment by IrcDirk** [comment]
Should be fixed.
