### ISSUE TITLE
Restore Map Scale

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#24]
This is not really an issue but a question as it seems the boards on WowInterface are not that active. Is there a command that can be used in macros to restore map scale?

**Comment by Thrumbar** [comment]
Right click on Carbonite map and select Restore Map Scale

**Comment by Palonblade** [comment]
Yes, I realize that, what I was looking for was code so I can force it to do so when I log in. I have issues with Alts like the Pally, DK and Rogue with the map constantly being zoomed in when I log in.

**Comment by mikepauer** [comment]
/script Nx.Map:GetMap(1).Scale = 1

I'm already doing that :) it would be nice if we didn't have to, but trying to support 2 different styles of map drawing at once is a little difficult, and the old style instance drawing going on in the background for order halls is drawing at a very tiny scale :( so when you logout and back in it's using that last scale.

**Comment by mikepauer** [comment]
or if you want to use the saved scale, /script Nx.Map:GetMap(1):Menu_OnScaleRestore()

**Comment by Palonblade** [comment]
Thank you, worked fine

**Comment by IrcDirk** [comment]
Carbonite uses one profile for all characters. So zoom persists between characters. U can setup different profile for every character then this problem will not ocour.

Closing since, there is nothing to fix here.
