### ISSUE TITLE
Carbonite Bug Crafting?

### ISSUE THREAD

**Issue by GeoRam2016** [mikepauer/Carbonite#240]
Hello
I have a Bug found.

1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' hat versucht die geschützte Funktion 'UNKNOWN()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CraftRecipe'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:785: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:784>
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:844: in function `craftingCallback'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:729: in function `ContinueCrafting'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:128: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:120>

**Comment by Thrumbar** [comment]
Does this still happen ??
