### ISSUE TITLE
When the new version will be on after update to 10.01.0

### ISSUE THREAD

**Issue by Damorka** [mikepauer/Carbonite#244]
Hello
when the new version of map and quests will be available after update to 10.01.0
I miss this addon very much and playing without it is much less fun :(
I realize you are working on it in your spare time and you are doing it for free, therefore thank you for all the efort you put in keeping this addon allive
Best Regards
Damorka

**Comment by IrcDirk** [comment]
Should work without problems, try loading out of date addons.

**Comment by Damorka** [comment]
Hello,
I did try load old addons.
Unfortunately it does not work properly
It causes lags to the game so I had to disable it
I'm hope you will find the time to make an update
I would truly appreciate it
Best regards
Olga

pt., 12 maj 2023 o 23:27 IrcDirk ***@***.***> napisał(a):

**Comment by IrcDirk** [comment]
Works fine on my side. No errors.
