### ISSUE TITLE
Retail Bug 10.1.5 Dungeon

### ISSUE THREAD

**Issue by GeoRam2016** [mikepauer/Carbonite#249]
Bug Nokhud

421x Carbonite/NxMap.lua:11670: attempt to call method 'AddUnitAtlas' (a nil value)
[string "@Carbonite/NxMap.lua"]:11670: in function `NXWorldMapUnitPositionFrame_UpdateFull'
[string "@Carbonite/NxMap.lua"]:11639: in function `NXWorldMapUnitPositionFrame_UpdatePlayerPins'
[string "@Carbonite/NxMap.lua"]:11555: in function `MoveWorldMap'
[string "@Carbonite/NxMap.lua"]:4526: in function `Update'
[string "@Carbonite/NxMap.lua"]:4026: in function `OnUpdate'
[string "@Carbonite/NxMap.lua"]:1423: in function `MainOnUpdate'
[string "@Carbonite/Carbonite.lua"]:1457: in function `NXOnUpdate'
[string "*Carbonite.xml:16_OnUpdate"]:1: in function <[string "*Carbonite.xml:16_OnUpdate"]:1>

Locals:
timeNow = 6860.081000
r = 1
g = 1
b = 1
isInRaid = false
memberCount = 4
unitBase = "party"
(for index) = 1
(for limit) = 4
(for step) = 1
i = 1
unit = "party1"
atlas = "WhiteCircle-RaidBlips"
class = "PALADIN"
r = 0.956863
g = 0.549020
b = 0.729412
(*temporary) = nil
(*temporary) = NXWorldMapUnitPositionFrame {
 0 = <userdata>
 GetCurrentMouseOverUnits = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:140
 SetMouseOverUnitExcluded = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:148
 SetPinSubLevel = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:128
 GetMemberCountAndUnitTokenPrefix = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:254
 SetupSecureData = <function> defined =[C]:-1
 currentMouseOverUnitCount = 0
 SetNeedsFullUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:303
 ResetCurrentMouseOverUnits = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:115
 SetUseClassColor = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:136
 OnShow = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:94
 NeedsPeriodicUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:315
 GetUnitColor = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:225
 UpdateFull = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:264
 excludedMouseOverUnits = <table> {
 }
 SetPinSize = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:120
 UpdateTooltips = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:219
 AddUnitInternal = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:240
 UpdateAppearanceData = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:110
 UpdatePlayerPins = <function> defined =[C]:-1
 SetAppearanceField = <function> defined =[C]:-1
 NeedsFullUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:307
 needsFullUpdate = true
 OnLoad = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:83
 OnHide = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:99
 SetShouldShowUnits = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:132
 needsPeriodicUpdate = true
 SetUnitAppearanceInternal = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:247
 currentMouseOverUnits = <table> {
 }
 UpdatePeriodic = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:286
 IsMouseOverUnitExcluded = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:144
 unitAppearanceData = <table> {
 }
 SetNeedsPeriodicUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:311
 OnEvent = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:104
 UpdateUnitTooltips = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:187
 SetPinTexture = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:124
}
(*temporary) = "party1"
(*temporary) = "WhiteCircle-RaidBlips"
(*temporary) = 24
(*temporary) = 24
(*temporary) = 0.956863
(*temporary) = 0.549020
(*temporary) = 0.729412
(*temporary) = 1
(*temporary) = "attempt to call method 'AddUnitAtlas' (a nil value)"

**Comment by GeoRam2016** [comment]
Bug Brckenfellhöhle

1279x Carbonite/NxMap.lua:11670: attempt to call method 'AddUnitAtlas' (a nil value)
[string "@Carbonite/NxMap.lua"]:11670: in function `NXWorldMapUnitPositionFrame_UpdateFull'
[string "@Carbonite/NxMap.lua"]:11639: in function `NXWorldMapUnitPositionFrame_UpdatePlayerPins'
[string "@Carbonite/NxMap.lua"]:11555: in function `MoveWorldMap'
[string "@Carbonite/NxMap.lua"]:4526: in function `Update'
[string "@Carbonite/NxMap.lua"]:4026: in function `OnUpdate'
[string "@Carbonite/NxMap.lua"]:1423: in function `MainOnUpdate'
[string "@Carbonite/Carbonite.lua"]:1457: in function `NXOnUpdate'
[string "*Carbonite.xml:16_OnUpdate"]:1: in function <[string "*Carbonite.xml:16_OnUpdate"]:1>

Locals:
timeNow = 147954.594000
r = 1
g = 1
b = 1
isInRaid = false
memberCount = 4
unitBase = "party"
(for index) = 1
(for limit) = 4
(for step) = 1
i = 1
unit = "party1"
atlas = "WhiteCircle-RaidBlips"
class = "MAGE"
r = 0.247059
g = 0.780392
b = 0.921569
(*temporary) = nil
(*temporary) = NXWorldMapUnitPositionFrame {
 0 = <userdata>
 GetCurrentMouseOverUnits = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:140
 SetMouseOverUnitExcluded = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:148
 SetPinSubLevel = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:128
 GetMemberCountAndUnitTokenPrefix = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:254
 SetupSecureData = <function> defined =[C]:-1
 currentMouseOverUnitCount = 0
 SetNeedsFullUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:303
 ResetCurrentMouseOverUnits = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:115
 SetUseClassColor = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:136
 OnShow = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:94
 NeedsPeriodicUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:315
 GetUnitColor = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:225
 UpdateFull = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:264
 excludedMouseOverUnits = <table> {
 }
 SetPinSize = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:120
 UpdateTooltips = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:219
 AddUnitInternal = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:240
 UpdateAppearanceData = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:110
 UpdatePlayerPins = <function> defined =[C]:-1
 SetAppearanceField = <function> defined =[C]:-1
 NeedsFullUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:307
 needsFullUpdate = true
 OnLoad = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:83
 OnHide = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:99
 SetShouldShowUnits = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:132
 needsPeriodicUpdate = true
 SetUnitAppearanceInternal = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:247
 currentMouseOverUnits = <table> {
 }
 UpdatePeriodic = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:286
 IsMouseOverUnitExcluded = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:144
 unitAppearanceData = <table> {
 }
 SetNeedsPeriodicUpdate = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:311
 OnEvent = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:104
 UpdateUnitTooltips = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:187
 SetPinTexture = <function> defined @FrameXML/UnitPositionFrameTemplates.lua:124
}
(*temporary) = "party1"
(*temporary) = "WhiteCircle-RaidBlips"
(*temporary) = 24
(*temporary) = 24
(*temporary) = 0.247059
(*temporary) = 0.780392
(*temporary) = 0.921569
(*temporary) = 1
(*temporary) = "attempt to call method 'AddUnitAtlas' (a nil value)"

**Comment by IrcDirk** [comment]
Try version from this repository or Alpha from Curse.

**Comment by Thrumbar** [comment]
The function UnitPositionFrameMixin:AddUnitInternal has been updated. Previously, it contained a conditional check that decided whether to call AddUnitAtlas or AddUnit. Now, it only calls AddUnit.  At least that is what I see.. 

Replace this
NXWorldMapUnitPositionFrame:AddUnitAtlas(unit, atlas, Nx.db.profile.Map.InstanceGroupSize, Nx.db.profile.Map.InstanceGroupSize, r, g, b, 1)

With this
NXWorldMapUnitPositionFrame:AddUnit(unit, atlas, Nx.db.profile.Map.InstanceGroupSize, Nx.db.profile.Map.InstanceGroupSize, r, g, b, 1, 7, true)

The arguments after b, 1 are based on the current changed in code, which used the AddUnit method. Ensure these values make sense in your context. Particularly, 7 and true are example values. Adjust these as necessary.

**Comment by IrcDirk** [comment]
Should be fixed. Thanks @Thrumbar
