### ISSUE TITLE
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7682

### ISSUE THREAD

**Issue by Basman1969** [mikepauer/Carbonite#25]
Date: 2017-07-11 11:44:12
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7682:
   attempt to index local 'quest' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:7682: UpdateIcons()
   Carbonite\NxMap.lua:4854: Update()
   Carbonite\NxMap.lua:3821: OnUpdate()
   Carbonite\NxMap.lua:1344: MainOnUpdate()
   Carbonite\Carbonite.lua:1314: NXOnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10214
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9980
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3185
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3238
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10850
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5149
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11087
 GOpts = <table> {
 }
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11231
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3123
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4963
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 971
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10494
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3423
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4197
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4019
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3947
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4686
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5234
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3291
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10205
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5767
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10265
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11080
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3925
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10946
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8086
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4160
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4062
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3371
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8031
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9875
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4793
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4189
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5835
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4345
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3301
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2113
 RealQEntries = 7
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3218
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4112
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4608
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9799
 ScanBlizzQuestDataTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3886
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  ArkInventory, v30731
  ArkInventoryRules, v10003
  ArkInventoryRulesExample, v10000
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  AutoGratzer, v2.0.2
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  Carbonite, v7.2.5
  CarboniteQuests, v7.2.5
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  idTip, v7.0.5
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  Outfitter, v5.19
  Postal, vv3.5.8
  Scrap, v13.5
  ScrapMerchant, v13.5
  ScrapSpotlight, v13.5
  SilverDragon, vv4.0.2
  SilverDragonBurningCrusade, vv4.0.2
  SilverDragonCataclysm, vv4.0.2
  SilverDragonLegion, vv4.0.2
  SilverDragonMists, vv4.0.2
  SilverDragonVanilla, vv4.0.2
  SilverDragonWarlords, vv4.0.2
  SilverDragonWrath, vv4.0.2
  SlideBar, v7.0.5 (<%codename%>)
  SpartanUI, v4.4.0
  SpartanUIArtwork, v3.3.0
  SpartanUIFilmEffects, v3.1.4
  SpartanUIPartyFrames, v3.3.0
  SpartanUIPlayerFrames, v3.3.0
  SpartanUIRaidFrames, v3.3.0
  SpartanUISpinCam, v3.1.4
  SpartanUIStyleFel, v1.0.0
  SpartanUIStyleMinimal, v3.3.0
  SpartanUIStyleTransparent, v3.3.0
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=abb)

**Comment by Thrumbar** [comment]
Do you have the latest release..

**Comment by fdellwing** [comment]
To check that, look at the Carbonite loaded string after logging into the world or look at the addon options page. Behind the version string there is a build string. The newest version is:  2f32277

**Comment by Thrumbar** [comment]
Appears to be the release version on curse...

7682		local qname = Nx.TXTBLUE .. L["Quest: "] .. (cur and cur.Title or Quest:UnpackName (quest["Quest"]))

**Comment by IrcDirk** [comment]
Use latest alpha release.

**Comment by qlesz** [comment]
when error ocurred i had latest alpha version (installed via curse client with alpha version installation setting on) i'm updating my addons daily because of numerous of errors poping up from different addons (this is first WoW expansion where i'm literally flooding with errors, never had this before and when i speak to the people look like i'm not the only one). This error seemed to be random when you get to the instance. Anyway i just updated carb so if that's gonna happen again i'll update this post
