### ISSUE TITLE
Retail 10.2.6 seems to have broken Carbonite

### ISSUE THREAD

**Issue by Panerdar** [mikepauer/Carbonite#252]
With nothing but carbonite and bug grabber enabled, just get error and it does not bring up map at all:

2x Carbonite/Carbonite.lua:2750: attempt to index local 'map' (a nil value)
[string "@Carbonite/Carbonite.lua"]:2750: in function `GetPlyrPos'
[string "@Carbonite/Carbonite.lua"]:2622: in function `AddInfo'
[string "@Carbonite/Carbonite.lua"]:1284: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 AddHerb = <function> defined @Carbonite/Carbonite.lua:2680
 UpdateAll = <function> defined @Carbonite/Carbonite.lua:2755
 AddDeath = <function> defined @Carbonite/Carbonite.lua:2634
 AddOpen = <function> defined @Carbonite/Carbonite.lua:2733
 GetPlyrPos = <function> defined @Carbonite/Carbonite.lua:2747
 AddHonor = <function> defined @Carbonite/Carbonite.lua:2667
 AddTimber = <function> defined @Carbonite/Carbonite.lua:2695
 AddMine = <function> defined @Carbonite/Carbonite.lua:2717
 SortCmp = <function> defined @Carbonite/Carbonite.lua:2765
 Sort = <function> defined @Carbonite/Carbonite.lua:2777
 AddKill = <function> defined @Carbonite/Carbonite.lua:2653
 UpdateMap = <function> defined @Carbonite/Carbonite.lua:2891
 Init = <function> defined @Carbonite/Carbonite.lua:2612
 AddInfo = <function> defined @Carbonite/Carbonite.lua:2620
 List = <table> {
 }
}
mapId = 84
map = nil
(*temporary) = 84
(*temporary) = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = 0
(*temporary) = "attempt to index local 'map' (a nil value)"

**Comment by qlesz** [comment]
i just issued fix pull request so hopefully it will be added soon. If you are impatient you can fix it by yourself by modifying NxUI.lua and replacing lines 28 to 51 with this code:

```
function Nx:UIInit()
    local qc = {}
    self.QualityColors = qc

    for n = 0, 10 do
        local r, g, b, hex = C_Item.GetItemQualityColor(n)
        qc[n] = hex
    end

    qc[1] = "|cffe7e7e7" -- Dim the white

    Nx.Font:Init()
    Nx.Skin:Init()

    Nx.Menu:Init()
    Nx.Window:Init()

    Nx.Button:Init()
    Nx.List:Init()
    Nx.DropDown:Init()
    Nx.ToolBar:Init()

    -- Nx.GList:Init()
end
```

Chat GPT is awesome :) helped me fixing this with my zero LUA programming knowledge :) and it work perfect :)
BTW your error is second for two carbonite errors showing up and its just because first one (the one i've pushed fix) blocking map from being displayed so carbonite couldn't count player position.

**Comment by Panerdar** [comment]
Seems good.
