### ISSUE TITLE
Map update rate setting is not accessible / not showing

### ISSUE THREAD

**Issue by Bowiee17** [mikepauer/Carbonite#255]
Map update rate setting is not accessible in this version therefore the zooming in and out is very laggy, therefore it is kind of bad to use (it exists in the classic version inside the map settings where it can be set so that the zooming is smooth as butter.)

**Comment by IrcDirk** [comment]
Ill look into it.

**Comment by IrcDirk** [comment]
Fixed => https://github.com/mikepauer/Carbonite/commit/55ea16f1786b8cc7143eeb9ea6d1174e8f91bf14
