### ISSUE TITLE
FPS drop from 120 to 4

### ISSUE THREAD

**Issue by Silv3rDragon** [mikepauer/Carbonite#258]
Disabling all other addons and only enabling carbonite drops framerate to 9 or 4, it bounces back and forth some times usually staying on 9.2, and i normally run at 120 fps (7900 cpu and 7900xtx gpu)  tried dropping "detail graphics visible area" from 40 to 10 and "maximum zones to draw at once" from 20 to 5 then /reload and no changes.  if i enable all other addons and leave carbonite disabled it goes back to my fps cap of 120.  this addon works amazingly with wowpro for questing so looking forward to a fix.

**Comment by Thrumbar** [comment]
Will look into this.  Getting about 50 fps but have a 14 year old computer and all graphics turned to low because of that..

**Comment by Silv3rDragon** [comment]
Willing to assist with troubleshooting if it will help any.  I had the same issue running on a different computer.

**Comment by IrcDirk** [comment]
Are those drops on all maps or only in some places? Do u have nodes mining/herbs enabled?

**Comment by IrcDirk** [comment]
Also try to change **Map update rate**.

**Comment by IrcDirk** [comment]
Just checked got steady 105 FPS.

Are u sure u are using latest version of Carbonite?

**Comment by Silv3rDragon** [comment]
Sorry just got home from work.  When I was using the version updated yesterday (10.2.0.8) it was running poorly and per the op i did have all other addons disabled to rule out any conflict with them and carbonite even reloading the game multiple times through /reload and exiting and restarting WoW.  I have curseforge set to auto update all addons and i noticed it was updating carbonite when i got on again to todays version (11.0.0.1) and it is running just like normal.  For future reference, the map update rate was at .05 and i dont remember messing with that setting at all.  Thanks for the great addon and constant updates.
