### ISSUE TITLE
Lua Error when mouse hovers over map

### ISSUE THREAD

**Issue by Caynn** [mikepauer/Carbonite#259]
998x Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua:64: attempt to index local 'tagInfo' (a boolean value)
[string "@Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua"]:64: in function <Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua:62>
[string "@Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua"]:109: in function `GetWorldQuestAtlasInfo'
[string "@Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua"]:326: in function `SetupWorldQuestButton'
[string "@Carbonite.Quests/NxQuest.lua"]:8218: in function `UpdateIcons'
[string "@Carbonite/NxMap.lua"]:5037: in function `Update'
[string "@Carbonite/NxMap.lua"]:4011: in function <Carbonite/NxMap.lua:3920>

Locals:
questID = 2
tagInfo = false
inProgress = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'tagInfo' (a boolean value)"

**Comment by Caynn** [comment]
Seems to only be in Valdrakken

**Comment by qlesz** [comment]
Got exacly the same but not only in valdrakken. It's even worse while i leave Valdrakken because i don't even have to mouse over but got that error msg instantly and it keep counting untill i disable carbonite

**Comment by IrcDirk** [comment]
Download Alpha **Carbonite.Quest module** and check if this fix works.

**Comment by Caynn** [comment]
Unfortunately the alpha of the Quest module did not fix the issue. 

137x Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua:64: attempt to index local 'tagInfo' (a boolean value)
[string "@Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua"]:64: in function <Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua:62>
[string "@Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua"]:109: in function `GetWorldQuestAtlasInfo'
[string "@Blizzard_FrameXMLUtil/Mainline/QuestUtils.lua"]:326: in function `SetupWorldQuestButton'
[string "@Carbonite.Quests/NxQuest.lua"]:8218: in function `UpdateIcons'
[string "@Carbonite/NxMap.lua"]:5037: in function `Update'
[string "@Carbonite/NxMap.lua"]:4011: in function <Carbonite/NxMap.lua:3920>

Locals:
questID = 2
tagInfo = false
inProgress = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'tagInfo' (a boolean value)"

**Comment by IrcDirk** [comment]
Another try, download Alpha **Carbonite** and **Carbonite.Quest module** and check if this fix works.

**Comment by qlesz** [comment]
Last fix working only partially. I do not get previous error messages but  when i click on world quest i get that error message:
Message: Interface/AddOns/Carbonite.Quests/NxQuest.lua:8210: attempt to call global 'BonusObjectiveTracker_TrackWorldQuest' (a nil value)
Time: Mon Jul 29 10:45:00 2024
Count: 2
Stack: Interface/AddOns/Carbonite.Quests/NxQuest.lua:8210: attempt to call global 'BonusObjectiveTracker_TrackWorldQuest' (a nil value)
[string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:8210: in function <Interface/AddOns/Carbonite.Quests/NxQuest.lua:8192>

Locals: self = NxIconWQ1 {
 Glow = NxIconWQ1Glow {
 }
 worldQuest = true
 SelectedGlow = NxIconWQ1SelectedGlow {
 }
 CriteriaMatchGlow = NxIconWQ1CriteriaMatchGlow {
 }
 texture = Texture {
 }
 questID = 70623
 Underlay = NxIconWQ1Underlay {
 }
 NxMap = <table> {
 }
 numObjectives = 1
 Texture = NxIconWQ1Texture {
 }
 TimeLowFrame = Frame {
 }
 SpellTargetGlow = NxIconWQ1SpellTargetGlow {
 }
 CriteriaMatchRing = NxIconWQ1CriteriaMatchRing {
 }
}
button = "LeftButton"
watchType = nil
(*temporary) = nil
(*temporary) = 70623
(*temporary) = 0
(*temporary) = "attempt to call global 'BonusObjectiveTracker_TrackWorldQuest' (a nil value)"
map = <table> {
 MiniBlks = 6
 IconScale = 10
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 3
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 268.772776
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.711111
 Zone = 2023
 MouseIsOver = 599.999904
 WorldAlpha = 1
 StartupShown = true
 ScaleDraw = 1.028865
 BackgndAlphaFade = 0.400000
 MoveLastX = 11849.960302
 PlyrDir = 268.772776
 PlyrSpeedCalcTime = 5630.242000
 MapPosYDraw = -1064.834020
 PlyrSpeed = 0
 MapScale = 0.102681
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 1522.000122
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 837.999817
 MMScales = <table> {
 }
 MapPosX = 11849.960302
 BackgndAlphaTarget = 1
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.260000
 H = 141
 Tick = 15926
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -1064.834020
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 11849.960302
 QuestAlpha = 0.300000
 CurWorldUpdateOverlayNum = 13
 Scale = 1.028865
 Targets = <table> {
 }
 BackgndAlpha = 1
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 2023
 MMOwn = false
 Size1 = 1.054687
 ShowUnexplored = false
 Arch = ArchaeologyDigSiteFrame {
 }
 PIconMenu = <table> {
 }
 DotRaidScale = 1
 IconFrms = <table> {
 }
 StepTime = 1
 PlyrSpeedX = 11849.960302
 PlyrFrm = Frame {
 }
 DebugAdjustScale = 0.100000
 ScaleDrawW = 0.971944
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 TrackName = "70, 38"
 TrackDistYd = 1035.408276
 Win = <table> {
 }
 InstanceId = false
 ScaleBeforeTarget = 1.028865
 RealScale = 1.028865
 Data = <table> {
 }
 TrackDir = 223.420731
 WorldHotspotTipStr = "Dragon Isles, Ohn'ahran Plains (110-120)
"
 MenuIShowTimber = <table> {
 }
 CurOverlays = <table> {
 }
 CurOverlaysTexFolder = "plainsofohnahra"
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TrackETA = false
 TextFrm = Frame {
 }
 TextScFrm = ScrollFrame {
 }
 PlyrY = -1064.834020
 GIconMenuIFindNote = <table> {
 }
 Cont = 14
 QuestWin = QuestPOIFrame {
 }
 WorldHotspotsCity = <table> {
 }
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Level = 36
 Tracking = <table> {
 }
 PlyrRZY = 21.751386
 MenuIInstanceMaps = <table> {
 }
 W = 150
 CurWorldUpdateMapId = 2023
 MMOwnedFrms = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 MapsDrawnFade = <table> {
 }
 MMChkDelay = 39
 ContFrms = <table> {
 }
 PlyrSpeedY = -1064.834020
 TileFrms = <table> {
 }
 ScaleW = 0.971944
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 MapPosY = -1064.834020
 IconWQFrms = <table> {
 }
 MapPosXDraw = 11849.960302
 ArchAlpha = 0.300000
 MapIndex = 1
 MenuIMonitorZone = <ta

**Comment by IrcDirk** [comment]
Ohhh... let me check that.

**Comment by IrcDirk** [comment]
Ok, its should be good now @qlesz. **Try with Alpha Carbonite.Quest module.**

**Comment by qlesz** [comment]
Look fine for me now.
