### ISSUE TITLE
error on wq autoaccept

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#261]
I got this error in Emerald Dream while i flew in watched quest area:
Message: Interface/AddOns/Carbonite.Quests/NxQuest.lua:8281: attempt to index local 'title' (a nil value)
Time: Mon Jul 29 12:11:56 2024
Count: 16
Stack: Interface/AddOns/Carbonite.Quests/NxQuest.lua:8281: attempt to index local 'title' (a nil value)
[string "@Interface/AddOns/Carbonite.Quests/NxQuest.lua"]:8281: in function `UpdateIcons'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:5037: in function `Update'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:4011: in function <Interface/AddOns/Carbonite/NxMap.lua:3920>

Locals: self = <table> {
 IconTracking = <table> {
 }
 DailyTypes = <table> {
 }
 Watch = <table> {
 }
 AcceptAId = 2200
 Custom = <table> {
 }
 TTChange = <table> {
 }
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 CapturePlyrData = <table> {
 }
 TrackedAchievements = <table> {
 }
 DailyIds = <table> {
 }
 QLocColors = <table> {
 }
 RealQEntries = 38
 Requirements = <table> {
 }
 Cols = <table> {
 }
 WorldUpdate = false
 Tick = 0
 CapFactionAbr = <table> {
 }
 RealQ = <table> {
 }
 QInit = false
 AcceptDLvl = 0
 AcceptQName = ""
 AcceptGiver = "?"
 FriendQuests = <table> {
 }
 IconHoverObjI = 0
 WQList = <table> {
 }
 QGivers = <table> {
 }
 QIdsNew = <table> {
 }
 Initialized = true
 IsOpen = false
 TTIgnore = <table> {
 }
 IconMenuIWatch = <table> {
 }
 IconMenu = <table> {
 }
 Map = <table> {
 }
 RcvTotal = 0
 Reputations = <table> {
 }
 TagNames = <table> {
 }
 AcceptX = 50.184023
 DailyDungeonIds = <table> {
 }
 HeaderHide = <table> {
 }
 RcvCnt = 0
 RcvPlyrLast = "None"
 HeaderExpanded = <table> {
 }
 PartyQ = <table> {
 }
 DailyPVPIds = <table> {
 }
 Enabled = true
 AcceptPool = <table> {
 }
 QIds = <table> {
 }
 GOpts = <table> {
 }
 Tracking = <table> {
 }
 CurCharacter = <table> {
 }
 OldMap = 0
 List = <table> {
 }
 AlchemistsApprenticeData = <table> {
 }
 AcceptY = 61.638677
 Sorted = <table> {
 }
 ScanBlizzMapId = 1
 CurQ = <table> {
 }
}
map = <table> {
 InstMapWX2 = 3.914063
 MiniBlks = 6
 IconScale = 10
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 PlyrRZY = 52.025473
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 115.773718
 Scrolling = false
 Menu = <table> {
 }
 ScrollingX = 807.999954
 EffScale = 0.711111
 Zone = 2200
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 1.028865
 ClickType = 3000
 ClickFrmY = 612.000065
 BackgndAlphaFade = 0.400000
 MoveLastX = 10784.023950
 PlyrDir = 115.773718
 PlyrSpeedCalcTime = 10845.836000
 MapPosYDraw = -761.581523
 Cont = 14
 ScrollingFrm = NxIconS11 {
 }
 MapScale = 0.102681
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 414.799652
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 404.000153
 MMScales = <table> {
 }
 MapPosX = 10784.023950
 BackgndAlphaTarget = 0.400000
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.830000
 H = 141
 Tick = 52462
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -760.082393
 MenuIShowHerb = <table> {
 }
 InstMapWY2 = 0
 DotZoneScale = 1
 QuestAlpha = 0.300000
 InstMapWX1 = 0
 CurWorldUpdateOverlayNum = 10
 Scale = 1.028865
 Targets = <table> {
 }
 BackgndAlpha = 0.400000
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 2200
 MMOwn = false
 CurOverlaysTexFolder = "dreamtree"
 Size1 = 1.054687
 ShowUnexplored = false
 InstLevelSet = 0
 Arch = ArchaeologyDigSiteFrame {
 }
 PIconMenu = <table> {
 }
 InstMapWY1 = 0
 DotRaidScale = 1
 MapIndex = 1
 StepTime = -5
 PlyrSpeedX = 10783.332803
 PlyrFrm = Frame {
 }
 DebugAdjustScale = 0.100000
 ScaleDrawW = 0.971944
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 45
 IconNavScale = 1
 MiniFrms = <table> {
 }
 MapPosY = -760.082393
 InCombat = false
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 Win = <table> {
 }
 InstanceId = false
 ScaleBeforeTarget = false
 RealScale = 1.028865
 Data = <table> {
 }
 ArchAlpha = 0.300000
 TrackDir = fals

I've checked if it's one time or repeatable error and i flew out and in the zone and error poped up again.

**Comment by IrcDirk** [comment]
Fixed in Quests Module.

**Comment by qlesz** [comment]
Look like it is ok now.
