### ISSUE TITLE
error after teleportation

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#262]
I got this error after using portal to sw and also after using tp scroll to silithius. After porting to silithius map got messed up.
Message: ...lizzard_MapCanvas/MapCanvas_ScrollContainerMixin.lua:465: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Wed Jul 31 18:54:40 2024
Count: 590
Stack: ...lizzard_MapCanvas/MapCanvas_ScrollContainerMixin.lua:465: bad argument #1 to 'ipairs' (table expected, got nil)
[string "@Interface/AddOns/Blizzard_MapCanvas/MapCanvas_ScrollContainerMixin.lua"]:465: in function `GetZoomLevelIndexForScale'
[string "@Interface/AddOns/Blizzard_MapCanvas/MapCanvas_ScrollContainerMixin.lua"]:477: in function `GetCurrentLayerIndex'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:6807: in function `UpdateOverlay'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:6633: in function `UpdateZones'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:4757: in function `Update'
[string "@Interface/AddOns/Carbonite/NxMap.lua"]:4011: in function <Interface/AddOns/Carbonite/NxMap.lua:3920>

Locals: self = ScrollFrame {
 shouldPanOnClick = false
 normalizedPanXLerpAmount = 0.150000
 Child = Frame {
 }
 normalizedZoomLerpAmount = 0.150000
 shouldZoomInstantly = true
 shouldZoomInOnClick = false
 normalizedPanYLerpAmount = 0.150000
 scalingMode = "SCALING_MODE_TRANSLATE_FASTER_THAN_SCALE"
 mouseWheelZoomMode = 2
 zoomAmountPerMouseWheelDelta = 0.075000
 targetScrollY = 0.500000
 mouseButtonInfo = <table> {
 }
 shouldNavigateOnClick = true
 targetScrollX = 0.500000
}
scale = 1
bestIndex = 1

**Comment by qlesz** [comment]
Another error after reload and accepting quest from quest giver in silithius:
Message: Interface/AddOns/Carbonite/NxMapGuide.lua:1919: attempt to index global 'GameTooltipTextLeft4' (a nil value)
Time: Wed Jul 31 18:58:36 2024
Count: 1
Stack: Interface/AddOns/Carbonite/NxMapGuide.lua:1919: attempt to index global 'GameTooltipTextLeft4' (a nil value)
[string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:1919: in function `SavePlayerNPCTarget'
[string "@Interface/AddOns/Carbonite/NxMapGuide.lua"]:1937: in function `?'
[string "@Interface/AddOns/Altoholic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Altoholic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Altoholic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 ItemTypeNames = <table> {
 }
 ItemStatRequiredSkill = <table> {
 }
 ItemCats = <table> {
 }
 ItemStatLen = <table> {
 }
 ItemSlotNames = <table> {
 }
 ItemStatNames = <table> {
 }
 __index = <table> {
 }
 ItemStatAllowableClass = <table> {
 }
 PlayerTargets = <table> {
 }
}
tag = "Level ?? (Boss)"
lvl = ""
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'GameTooltipTextLeft4' (a nil value)"
L = <table> {
 Mogu'shan Palace = "Mogu'shan Palace"
 Dragonblight = "Dragonblight"
 Bloodwatcher Point, Badlands = "Bloodwatcher Point, Badlands"
 Rich Elethium Ore = "Rich Elethium Ore"
 Westfall = "Westfall"
 Isle of Conquest = "Isle of Conquest"
 Empyrium Seam = "Empyrium Seam"
 Stormshield = "Stormshield"
 Options have been reset for the new version. = "Options have been reset for the new version."
 Archaeology Blob Transparency = "Archaeology Blob Transparency"
 Map Mouse Button Binds = "Map Mouse Button Binds"
 Shadowmoon Village, Shadowmoon Valley = "Shadowmoon Village, Shadowmoon Valley"
 Opening = "Opening"
 Darnassus = "Darnassus"
 Menus = "Menus"
 Gilneas = "Gilneas"
 Reset global options = "Reset global options"
 Left-Click to Toggle Map = "Left-Click to Toggle Map"
 Imported = "Imported"
 Un'Goro Crater = "Un'Goro Crater"
 Dustwind Dig, Badlands = "Dustwind Dig, Badlands"
 Show Map = "Show Map"
 Kirthaven, Twilight Highlands = "Kirthaven, Twilight Highlands"
 Western Plaguelands = "Western Plaguelands"
 The Jade Forest = "The Jade Forest"
 Middle-Click to Toggle Guide = "Middle-Click to Toggle Guide"
 Large Timber = "Large Timber"
 Shrine of Seven Stars = "Shrine of Seven Stars"
 Max Vendors To Record = "Max Vendors To Record"
 Crypt of Forgotten Kings = "Crypt of Forgotten Kings"
 Left click toggle Map = "Left click toggle Map"
 Laestrite Deposit = "Laestrite Deposit"
 Flamestar Post, Burning Steppes = "Flamestar Post, Burning Steppes"
 Sets the action performed when middle clicking holding CTRL = "Sets the action performed when middle clicking holding CTRL"
 Report Status = "Report Status"
 Winterspring = "Winterspring"
 Main Options = "Main Options"
 Flying = "Flying"
 Com %d Bytes sec %d = "Com %d Bytes sec %d"
 Darkshore = "Darkshore"
 Dark Heart of Pandaria = "Dark Heart of Pandaria"
 Paladin Trainer = "Paladin Trainer"
 The Shadowlands = "The Shadowlands"
 Lush Hochenblume = "Lush Hochenblume"
 Storm Silver Deposit = "Storm Silver Deposit"
 Small Font = "Small Font"
 Frostweed = "Frostweed"
 Show Received Levelups = "Show Received Levelups"
 Gold Vein = "Gold Vein"
 Onyxia's Lair = "Onyxia's Lair"
 Apexis Excavation, Spires of Arak = "Apexis Excavation, Spires of Arak"
 When enabled, the full size map will ignore all mouse clicks unless the ALT key is held down. = "When enabled, the full size map will ignore all

**Comment by IrcDirk** [comment]
One problem, one issue.

**Comment by Thrumbar** [comment]
Not seeing this error on my Druid.

**Comment by qlesz** [comment]
Well i had it couple of times. Every single one of them was after using some kind of teleport (portal, scroll of teleportation etc.) 2nd error was random aswell but every time after completing quests.

**Comment by qlesz** [comment]
After playing another 2 alts i didn't have any of those. It might have been because of some Blizz bugs (there was small patch after this happened) so i think you could close this topic.
