### ISSUE TITLE
Maps goes into perpetual LUA errors on toons with Draenor Garrisons

### ISSUE THREAD

**Issue by Fl1pp3d0ff** [mikepauer/Carbonite#263]
The title says it all.

If I login on a toon that has a Draenor Garrison, LUA errors are constantly generated - sometimes.
If I login on a toon that has never initiated the Garrison questline, no errors are kicked out - ever.

Can't copy the error text because it locks the interface up, necessitating killing the WOW client using task manager.

**Comment by Fl1pp3d0ff** [comment]
Update:

Separating the Blizz minimap from the Carbonite map seems to stop the errors, However, it makes for a less-satisfying experience.

**Comment by chris-arsenault** [comment]
until there's a fix for this, you can comment out NxMap.lua ln: 2525 by placing a `--` infront of it
`-- or C_Garrison.IsPlayerInGarrison(Enum.GarrisonType.Type_7_0) -- Order Halls `

and everything seems to work with the minimap integrated.

**Comment by chris-arsenault** [comment]
fix confirmed on my side
