### ISSUE TITLE
NxMap.lua 'UnitDebuff' Mass error

### ISSUE THREAD

**Issue by Mechrior** [mikepauer/Carbonite#265]
cant get much information as the error while stood in valdrakken and in a party with my partner is throwing about 10 errors a second!

![image](https://github.com/user-attachments/assets/2c67d110-1acb-491f-ab4b-1ef6e9289629)

**Comment by TheAussie** [comment]
Open the NxMap.lua, and replace UnitDebuff with C_UnitAuras.GetBuffDataByIndex it seems to fix the error and show the party members icon on the map again.

**Comment by Mechrior** [comment]
that stopped the error it seems, will update if anything changes.

Now to work out why its not actually displaying the map right in the area just the flight points

**Comment by IrcDirk** [comment]
Fixed by this commit => https://github.com/mikepauer/Carbonite/commit/f08a32aaa27a0b6b53266e631cada6b88d8179c7
