### ISSUE TITLE
The War Within

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#266]
Does anyone working on adding new maps?

**Comment by IrcDirk** [comment]
Not me ;) I dont even own this expansion ;)

**Comment by Thrumbar** [comment]
Lost my macro that i used to get this info..  Anybody can help with it..
The InBetween
Dump: value=C_Map.GetBestMapForUnit("player")
[1]=1550

Oribos
Dump: value=C_Map.GetBestMapForUnit("player")
[1]=1671

Bastion
Dump: value=C_Map.GetBestMapForUnit("player")
[1]=1533
Dump: value=C_MapExplorationInfo.GetExploredMapTextures(C_Map.GetBestMapForUnit("player"))
[1]={
[1]={
hitRect={
top=0,
right=0,
left=0,
bottom=0
},
offsetX=2004,
textureHeight=494,
textureWidth=826,
offsetY=1590,
fileDataIDs={
[1]=3192962,
[2]=3192963,
[3]=3192964,
[4]=3192965,
[5]=3192966,
[6]=3192967,
[7]=3192968,
[8]=3192969
},
isShownByMouseOver=false
},
[2]={
hitRect={
top=0,
right=0,
left=0,
bottom=0
},
offsetX=2110,
textureHeight=911,
textureWidth=881,
offsetY=588,
fileDataIDs={
[1]=3192970,
[2]=3192978,
[3]=3192979,
[4]=3192980,
[5]=3192981,
[6]=3192982,
[7]=3192983,
[8]=3192984,
[9]=3192985,
[10]=3192971,
[11]=3192972,
[12]=3192973,
[13]=3192974,
[14]=3192975,
[15]=3192976,
[16]=3192977
},
isShownByMouseOver=false
},

**Comment by Thrumbar** [comment]
Using this but no textures..
/run local m=C_Map.GetBestMapForUnit("player") local t=C_MapExplorationInfo.GetExploredMapTextures(m) if t then for _,v in ipairs(t) do print("Texture:",v.fileDataID,"Overlay:",v.overlay) end else print("No textures found for this zone.") end

**Comment by IrcDirk** [comment]
@Thrumbar If i now it right u can get this data from game it self or by queering https://wago.tools/ I have tool for this but it was written for https://wow.tools/ which is gone now.

**Comment by IrcDirk** [comment]
@Thrumbar Write to me by email ;)

**Comment by Thrumbar** [comment]
Got this using an self made addon..

Map ID: 2339
Layer 1:
 MinScale: 1
 Layer Height: 2560
 Texture 3: File ID: 5847477
 Texture 8: File ID: 5847544
 Texture 11: File ID: 5847402
 MaxScale: 4
 Texture 6: File ID: 5847517
 Texture 10: File ID: 5847207
 Texture 2: File ID: 5847462
 Texture 5: File ID: 5847504
 Layer Width: 3840
 Texture 4: File ID: 5847490
 Texture 12: File ID: 5847415
 Texture 1: File ID: 5847206
 Texture 13: File ID: 5847428
 Texture 7: File ID: 5847530
 Texture 9: File ID: 5847557
 Texture 29: File ID: 5847476
 Texture 18: File ID: 5847460
 Texture 21: File ID: 5847464
 Texture 14: File ID: 5847441
 Texture 19: File ID: 5847461
 Texture 24: File ID: 5847468
 Texture 15: File ID: 5847455
 Texture 16: File ID: 5847457
 Texture 17: File ID: 5847458
 Texture 26: File ID: 5847472
 Texture 20: File ID: 5847463
 Texture 33: File ID: 5847482
 Texture 31: File ID: 5847480
 Texture 27: File ID: 5847474
 Texture 30: File ID: 5847478
 Texture 23: File ID: 5847467
 Texture 35: File ID: 5847484
 Texture 34: File ID: 5847483
 Texture 25: File ID: 5847470
 Texture 22: File ID: 5847466
 Texture 36: File ID: 5847486
 Texture 32: File ID: 5847481
 Texture 40: File ID: 5847492
 Texture 48: File ID: 5847501
 Texture 45: File ID: 5847498
 Texture 46: File ID: 5847499
 Texture 38: File ID: 5847488
 Texture 55: File ID: 5847511
 Texture 41: File ID: 5847493
 Texture 39: File ID: 5847489
 Texture 43: File ID: 5847495
 Texture 37: File ID: 5847487
 Texture 28: File ID: 5847475
 Texture 44: File ID: 5847497
 Texture 42: File ID: 5847494
 Texture 47: File ID: 5847500
 Texture 51: File ID: 5847506
 Texture 52: File ID: 5847507
 Texture 53: File ID: 5847509
 Texture 56: File ID: 5847512
 Texture 49: File ID: 5847503
 Texture 58: File ID: 5847515
 Texture 63: File ID: 5847522
 Texture 61: File ID: 5847519
 Texture 50: File ID: 5847505
 Texture 57: File ID: 5847513
 Texture 54: File ID: 5847510
 Texture 60: File ID: 5847518
 Texture 62: File ID: 5847521
 Texture 65: File ID: 5847524
 Texture 66: File ID: 5847525
 Texture 59: File ID: 5847516
 Texture 64: File ID: 5847523
 Texture 67: File ID: 5847527
 Texture 71: File ID: 5847533
 Texture 80: File ID: 5847545
 Texture 72: File ID: 5847534
 Texture 77: File ID: 5847540
 Texture 74: File ID: 5847536
 Texture 75: File ID: 5847537
 Texture 73: File ID: 5847535
 Texture 76: File ID: 5847539
 Texture 70: File ID: 5847531
 Texture 69: File ID: 5847529
 Texture 68: File ID: 5847528
 Texture 79: File ID: 5847542
 Texture 87: File ID: 5847553
 Texture 83: File ID: 5847548
 Texture 85: File ID: 5847551
 Texture 86: File ID: 5847552
 Texture 78: File ID: 5847541
 Texture 89: File ID: 5847556
 Texture 81: File ID: 5847546
 Texture 88: File ID: 5847554
 Texture 82: File ID: 5847547
 Texture 84: File ID: 5847550
 Texture 93: File ID: 5847562
 Texture 94: File ID: 5847563
 Texture 90: File ID: 5847558
 Texture 91: File ID: 5847559
 Texture 92: File ID: 5847560

**Comment by Thrumbar** [comment]
using this..

-- ZoneInfoAddon.lua

local function GetZoneInfo()
  local mapID = C_Map.GetBestMapForUnit("player")
  print("Map ID:", mapID)

  -- Retrieve all map art layers
  local layers = C_Map.GetMapArtLayers(mapID)
  if not layers then
    print("No map art layers found.")
    return
  end

  -- Loop through each layer
  for layerIndex, layerInfo in ipairs(layers) do
    print("Layer " .. layerIndex .. ":")
    print(" Layer Width:", layerInfo.layerWidth)
    print(" Layer Height:", layerInfo.layerHeight)
    print(" MinScale:", layerInfo.minScale)
    print(" MaxScale:", layerInfo.maxScale)

    -- Get the textures for this layer
    local textures = C_Map.GetMapArtLayerTextures(mapID, layerIndex)
    for i, textureFile in ipairs(textures) do
      print(" Texture " .. i .. ": File ID:", textureFile)
    end
  end
end

SLASH_ZONEINFO1 = "/zoneinfo"
SLASH_ZONEINFO2 = "/zi"
SlashCmdList["ZONEINFO"] = GetZoneInfo

**Comment by Thrumbar** [comment]
`-- ZoneInfoAddon.lua

local function GetZoneInfo()
  local mapID = C_Map.GetBestMapForUnit("player")
  print("Map ID:", mapID)

  -- Retrieve all map art layers
  local layers = C_Map.GetMapArtLayers(mapID)
  if not layers then
    print("No map art layers found.")
    return
  end

  -- Loop through each layer
  for layerIndex, layerInfo in ipairs(layers) do
    print("Layer " .. layerIndex .. ":")
    print(" Layer Width:", layerInfo.layerWidth)
    print(" Layer Height:", layerInfo.layerHeight)
    print(" MinScale:", layerInfo.minScale)
    print(" MaxScale:", layerInfo.maxScale)

    -- Get the textures for this layer
    local textures = C_Map.GetMapArtLayerTextures(mapID, layerIndex)
    for i, textureFile in ipairs(textures) do
      print(" Texture " .. i .. ": File ID:", textureFile)
    end
  end
end

SLASH_ZONEINFO1 = "/zoneinfo"
SLASH_ZONEINFO2 = "/zi"
SlashCmdList["ZONEINFO"] = GetZoneInfo
`

**Comment by IrcDirk** [comment]
@Thrumbar Write to me i got all the data ;)

**Comment by Caynn** [comment]
I see the winky face, does that mean you are planning on updating (no rush, I just love this addon and want to know)?

**Comment by instant0** [comment]
Thanks for working on update. I had a look myself but it was difficult without a starting point, anyone want to write a short readme.md to describe the process of adding map updates that way more people can fix the map issues quicker?

**Comment by IrcDirk** [comment]
Its not an easy process to describe.

**Comment by instant0** [comment]
I see. Well, anything would help. Cheers for the work. 
Suppose I can just 'diff' the version I'm using now with the fixed one when it comes out to see what had to be done.

When I looked I primarily tried to fix the position of quest icons. The player arrow seemed to be identified correctly on the map for the first TWW Zone so I assumed it had something to do with the map zone having the incorrect 'scale' for quest markers. But that could've been the wrong starting point.

**Comment by qlesz** [comment]
@instant0 The biggest issue is to find where all new map blips are stored. As Ircdirk stated before you can use wago.tools for the start. Or dig a bit deeper and use [https://github.com/Ghostopheles/Datamine](url). I found that while searching different methods to extract maps. They got all data extracted and even script in python if you wish to do it by yourself.
I'll try to work on adding those maps on the weekend if i find some spare time.

**Comment by IrcDirk** [comment]
@qlesz Check your email ;)

**Comment by IrcDirk** [comment]
We are working on it. So be patient it will be
