### ISSUE TITLE
New Pet Battle Scenario - Deadmines

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#27]
All kinds of errors in chat and lua when entering new pet battle scenario - Deadmines
Date: 2017-07-17 23:54:19
ID: -1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 3854:
   attempt to index field '?' (a nil value)
Debug:
   Carbonite\NxMap.lua:3854:
      Carbonite\NxMap.lua:3706
Locals:
this = <unnamed> {
 0 = <userdata>
 NxMap = <table> {
 }
 texture = <unnamed> {
 }
}
elapsed = 0.12900000810623
Nx = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1722
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:145
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1089
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:102
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:173
 ScheduleTimer = <function> defined @Interface\AddOns\Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:92
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:813
 prtFrame = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:210
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 SetEnabledState = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Graph = <table> {
 }
 ShowEditBox = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1369
 GatherInit = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3110
 prtTable = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:158
 Font = <table> {
 }
 Util_TMoveI = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:355
 Combat = <table> {
 }
 NewModule = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 MenuI = <table> {
 }
 VERSIONList = 0.1
 OnPlayer_regen_enabled = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1085
 ModuleUpdateIcon = <table> {
 }
 Initialized = true
 Script = <table> {
 }
 UNIT_NAME_UPDATE = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:817
 VERSIONCAP = 0.8
 GetName = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GatherMine = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3183
 MapOverlayToMapId = <table> {
 }
 QInit = true
 Disable = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 GatherUnpack = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3241
 VERSIONHUDOPTS = 0.03
 GatherDeleteHerb = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3254
 TabBar = <table> {
 }
 Window = <table> {
 }
 Print = <function> defined @Interface\AddOns\Carbonite\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 Util_SnapToScreen = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:576
 GatherTimber = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3176
 Tick = 10531
 UnitDTip = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1004
 UnpackEvent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1998
 ToolBar = <table> {
 }
 FindCharacter = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1873
 RegisterComm = <function> defined @Interface\AddOns\Carbonite\Libs\AceComm-3.0\AceComm-3.0.lua:61
 MapWorldHotspots = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 ModQAction = ""
 AddEvent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1953
 EnableModule = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 IterateEmbeds = <function> defined @Interface\AddOns\Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 GetEventMapId = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1989
 Util_SecondsToDays = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:709
 Util_TMoveItem = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:375
 VERSIONTransferData = 0.1
 Util_TCopyRecurse = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:321
 VERSIONWin = 0.31
 strpos = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:54
 CalendarDate = 0
 NXMapKeyTogHerb = <function> defined @Interface\AddOns\Carbonite\NxMa

**Comment by Palonblade** [comment]
Do you need more information?

**Comment by mikepauer** [comment]
Need to be able to zone in to check what's going on, been slowly building up enough 25's so I can beat WC and gain access to it.

**Comment by mikepauer** [comment]
Fixed now

**Comment by Palonblade** [comment]
Just did it, no errors or chat messages :)
