### ISSUE TITLE
NxMap.lua:8681: attempt to index field 'ClickIcon' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#274]
4x Carbonite/NxMap.lua:8681: attempt to index field 'ClickIcon' (a nil value)
[string "@Carbonite/NxMap.lua"]:8681: in function <Carbonite/NxMap.lua:8633>

Locals:
self = NxIcon6 {
 NxMap = <table> {
 }
 NxTip = "|cffffd100Bonus Task:
Everyday I'm Snufflin'
- |cff8080800/1 Odd Glob of Wax brought to Gnawbles in Gundargaz"
 NXIconFrm = NxIcon6 {
 }
 texture = Texture {
 }
}
button = "LeftButton"
this = NxIcon6 {
 NxMap = <table> {
 }
 NxTip = "|cffffd100Bonus Task:
Everyday I'm Snufflin'
- |cff8080800/1 Odd Glob of Wax brought to Gnawbles in Gundargaz"
 NXIconFrm = NxIcon6 {
 }
 texture = Texture {
 }
}
map = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 MapPosY = 3053.246404
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 47.413114
 WorldHotspots = <table> {
 }
 Menu = <table> {
 }
 ScrollingX = 164.000002
 EffScale = 0.640000
 Zone = 2214
 WorldAlpha = 1
 StartupShown = false
 ScaleDraw = 0.302739
 ClickFrmY = 135.000141
 BackgndAlphaFade = 0.400000
 MoveLastX = 12980.472360
 PlyrDir = 47.413114
 PlyrSpeedCalcTime = 92969.686000
 MapPosYDraw = 3053.246404
 ArchAlpha = 0.300000
 ScrollingFrm = NxIconS1 {
 }
 MapScale = 0.030213
 CurMapBG = false
 PadX = 0
 BGIncNum = 0
 MenuIMonitorZone = <table> {
 }
 MapW = 350.800110
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 301.000061
 MMScales = <table> {
 }
 MapPosX = 11867.290447
 BackgndAlphaTarget = 1
 MoveDir = 58.177167
 BGGrowBars = true
 ArrowScroll = 0
 H = 141
 Tick = 904
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 1895.080913
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 DotPalScale = 1
 QuestAlpha = 0.300000
 CurWorldUpdateOverlayNum = 0
 Scale = 0.302739
 TextFrm = Frame {
 }
 BackgndAlpha = 1
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 2214
 MMOwn = false
 Size1 = 1.171875
 ShowUnexplored = false
 Arch = ArchaeologyDigSiteFrame {
 }
 PIconMenu = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 GIconMenu = <table> {
 }
 StepTime = -5
 PlyrSpeedX = 12980.472360
 PlyrFrm = Frame {
 }
 ClickFrm = NxIcon6 {
 }
 IconWQFrms = <table> {
 }
 ScaleDrawW = 3.303179
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 44
 IconNavScale = 1
 DebugMapId = 2023
 MiniFrms = <table> {
 }
 InCombat = false
 TrackName = "Connection: Dornogal to The Ringing Deeps"
 TrackDistYd = 434.092479
 Win = <table> {
 }
 InstanceId = false
 ScaleBeforeTarget = 0.028133
 RealScale = 0.046919
 Data = <table> {
 }
 TrackDir = 239.176600
 ScrollingY = 970.000098
 PlyrY = 1895.080913
 CurOverlaysTexFolder = "arathorcanyons"
 MenuIShowTimber = <table> {
 }
 CurOverlays = <table> {
 }
 WorldHotspotTipStr = "Khaz Algar, |cffffff00The Ringing Deeps (70-80)
"
 MouseIsOver = 221.808088
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TrackETA = false
 Targets = <table> {
 }
 TextScFrm = ScrollFrame {
 }
 ClickFrmX = 221.808088
 GIconMenuIFindNote = <table> {
 }
 TargetNextUniqueId = 46
 QuestWin = QuestPOIFrame {
 }
 WorldHotspotsCity = <table> {
 }
 TextFStrs = <table> {
 }
 Scrolling = false
 Cont = 15
 Tracking = <table> {
 }
 Level = 35
 PlyrRZY = 46.646780
 MenuIInstanceMaps = <table> {
 }
 W = 150
 DotRaidScale = 1
 CurWorldUpdateMapId = 2214
 TransMenu = <table> {
 }
 IconFrms = <table> {
 }
 ContFrms = <table> {
 }
 MMOwnedFrms = <table> {
 }
 TileFrms = <table> {
 }
 ScaleW = 2.588387
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 DebugAdjustScale = 0.100000
 PlyrSpeedY = 1895.080913
 PlyrSpeed = 0
 MMChkDelay = 21
 ViewSavedData = <table> {
 }
 BGIconMenu = <table> {
 }
 PlyrRZX = 50.172710
 KillShow = false
 MapPosXDraw = 11867.290447
 NeedWorldUpdate = false
 MapIndex = 1
 DotZoneScale = 1
 Frm = Frame {
 }
 MapsDrawnOrder = <table> {
 }
 MapsDrawnFade = <table> {
 }
 PlyrX = 12980.472360
 BackgndAlphaFull = 1
}
shift = false
cat = 0
(*temporary) = nil
(*temporary) = <table> {
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 MapPosY = 3053.246404
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 47.413114
 Worl

**Comment by Thrumbar** [comment]
Could be just changing 8681.
From
if map.ClickIcon.iconType == "!RSR" and RareScanner then
To
if map.ClickIcon and map.ClickIcon.iconType == "!RSR" and RareScanner then

**Comment by Thrumbar** [comment]
Errors when clicking on bonus quest icons on map..  May be more needed that what I mentioned above,,

**Comment by IrcDirk** [comment]
Im looking into it...

**Comment by IrcDirk** [comment]
Seems your fix @Thrumbar works ;)
