### ISSUE TITLE
Quest watch jumps from quest to quest

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#274]
My quest watch appears to be confused on which quest to track.  Kept jumping from one to another, one being in front of the character and the other over 1k away in the same zone..  Carbonite seems to think I was in Northern part of zone when I was in the Southern.

http://youtu.be/ZI9fqYZ9Tqk

**Comment by samyonair** [comment]
Maplvls are not supported for the moment, you are inside waypoint system still needs to be redone
added new label to have all with same issue together

**Comment by Thrumbar** [comment]
Have not seen this error in a while.  Closing...
