### ISSUE TITLE
Script ran too long...

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#281]
I observed earlier this morning but am running the live version. However, I think this might be an Ace3 issue, but I don't know if you could do anything to safeguard these errors:-

2x Carbonite\NxMapGuide.lua:2012: script ran too long
Carbonite\NxMapGuide.lua:2012: in function `UpdateVisitedVendors'
Carbonite\NxMapGuide.lua:1889: in function `func'
Ace3\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:48>

**Comment by IrcDirk** [comment]
Confirm if this sill occurs. Else ill close this in 3 days.
