### ISSUE TITLE
Carbonite is blocking talent sharing

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#282]
I get this error, aswell as standard blizzard ui popup, everytime i try to copy talent loadout via standard blizzard "share>copy to clipboard" option in talent tree window. I can't send talent loadout without disabling Carbonite because of that.

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Carbonite' tried to call the protected function 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:516: in function <...erSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua:515>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:868: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:74: in function <Blizzard_Menu/MenuTemplates.lua:68>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by IrcDirk** [comment]
Carbonite does not use `CopyToClipboard` function...

**Comment by qlesz** [comment]
Well i get this error only with carbonite loaded somehow. As soon as i disable carb everything work fine....

**Comment by IrcDirk** [comment]
Disable BugGrabber and try again.

**Comment by qlesz** [comment]
> Disable BugGrabber and try again.

I've disabled all addons but Carbonite, did it on 2 chars so to be sure it's not toon related. Still persist. Ofc i don't get error but Blizz "Carbonite has been blocked..." window still pop up

Ed.
I've even disabled Carbonite Notes, Carbonite quests and other addons to carbonite i have and left ONLY Main carbonite addon active. Still got that popup about Carbonite has been blocked - disable.

**Comment by IrcDirk** [comment]
NO clue what part of Carbonite blocks this :/

**Comment by qlesz** [comment]
Working fine now
