### ISSUE TITLE
Carbonite\NxMap.lua:9054: Usage: GetMapNameByID(mapID)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#285]
Using the latest Developer - go big or go home
Most likely a NPC overlay/Carbonite intergration issue

7x Carbonite\NxMap.lua:9054: Usage: GetMapNameByID(mapID)
[C]: in function `GetMapNameByID'
Carbonite\NxMap.lua:9054: in function `GetWorldZoneInfo'
Carbonite\NxMap.lua:7283: in function `ClipZoneFrm'
_NPCScan.Overlay\Modules\Carbonite-6.0.1D.lua:250: in function <_NPCScan.Overlay\Modules\Carbonite.lua:236>
_NPCScan.Overlay\Modules\Carbonite-6.0.1D.lua:289: in function <_NPCScan.Overlay\Modules\Carbonite.lua:280>
[C]: ?
[C]: ?
Carbonite\NxMap.lua:224: in function `SetMapToCurrentZone'
GatherMate2\Display-Display.lua:628: in function `UpdateMaps'
GatherMate2\Display-Display.lua:337: in function `?'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 Scale = 4
 MenuIShowWorld = <table> {
 }
 Targets = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0
 ArrowPulse = 1
 PlyrRZY = 0
 MapId = 0
 MMOwn = true
 TextFStrs = <table> {
 }
 PlyrLastDir = 999
 Scrolling = false
 MMModels = <table> {
 }
 Menu = <table> {
 }
 ShowUnexplored = false
 MenuIShowMine = <table> {
 }
 MMAlphaDelay = 100
 Arch = <unnamed> {
 }
 MMOwnedFrms = <table> {
 }
 MMChkDelay = 5
 PIconMenu = <table> {
 }
 MMScalesC = <table> {
 }
 WorldAlpha = 0
 MMScales = <table> {
 }
 StartupShown = true
 ScaleDraw = 0.025
 Guide = <table> {
 }
 MapIndex = 1
 MapPosY = -3673.3804930813
 StepTime = 1
 PlyrSpeedX = 0
 PlyrFrm = <unnamed> {
 }
 MapPosXDraw = 2200
 DebugAdjustScale = 0.1
 MoveLastX = -1
 PlyrDir = 0
 PlyrSpeedCalcTime = 709.376
 IconNavScale = 1
 MapPosYDraw = -100
 LocTipFrm = NxMapTip {
 }
 PlyrSpeed = 0
 TextFrm = <unnamed> {
 }
 WorldHotspots = <table> {
 }
 MiniFrms = <table> {
 }
 ContFrms = <table> {
 }
 TileFrms = <table> {
 }
 MapScale = 1
 TransMenu = <table> {
 }
 Win = <table> {
 }
 PadX = 0
 GIconMenu = <table> {
 }
 RealScale = 4
 Data = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 150
 TargetNextUniqueId = 1
 MMGathererUpdateDelay = 1
 BGIconMenu = <table> {
 }
 MMAddonFrms = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 ButAutoScaleOn = <table> {
 }
 DotZoneScale = 1
 MapH = 140
 MenuIMonitorZone = <table> {
 }
 GIconMenuIFindNote = <table> {
 }
 DotRaidScale = 1
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 TextScFrm = <unnamed> {
 }
 ArchAlpha = 0.3
 IconStaticFrms = <table> {
 }
 MapPosX = -1543.8933935471
 LOpts = <table> {
 }
 BackgndAlphaTarget = 0.4
 IconFrms = <table> {
 }
 Tracking = <table> {
 }
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 MapsDrawnFade = <table> {
 }
 UpdateTrackingDelay = 0
 ArrowScroll = 0
 UpdateTargetDelay = 0
 H = 141
 PlyrY = 0
 Tick = 0
 CurOpts = <table> {
 }
 IconNIFrms = <table> {
 }
 TitleH = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -1
 MenuIShowHerb = <table> {
 }
 DotPalScale = 1
 DotPartyScale = 1
 PlyrRZX = 0
 PlyrX = 0
 QuestAlpha = 0.3
 NeedWorldUpdate = true
 BackgndAlphaFade = 0.4
 BackgndAlphaFull = 1
 Frm = <unnamed> {
 }
 MoveDir = 0
 PlyrSpeedY = 0
 W = 150
 KillShow = false
}
cont = nil
zone = nil

**Comment by IrcDirk** [comment]
Thats NPCScan bug they should fix this.
