### ISSUE TITLE
Dalaran World Quest Icons

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#29]
My WQ icons in Dalaran went wonky on the Minimap. Just show crossed swords now. 
![wowscrnshot_080217_115939](https://user-images.githubusercontent.com/22230769/28882720-14b908e0-777a-11e7-9f65-78fc8cbab216.jpg)

**Comment by IrcDirk** [comment]
Same here. Even after last commit.

**Comment by milotic** [comment]
hi this bug still up dalaran still show empty when i have 2 wq active minipet wq and alchemy wq
