### ISSUE TITLE
Combat graph logging

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#31]
Dug around the options, can not find anything to disable combat graph logging.  I do not use that feature, and would like to turn it off, if possible.

**Comment by IrcDirk** [comment]
??? I dont know what are u talking about... please explain.

**Comment by SteveEbey73742** [comment]
/carb c to open the log on screen, it may even be something left behind from the original developers. I just was wondering how to disable it.  Even when it is not showing on screen it affect fps in combat.

**Comment by IrcDirk** [comment]
Ok, i will see what i can do with this.

**Comment by SteveEbey73742** [comment]
Thank you

**Comment by mikepauer** [comment]
The entire thing should be removed, or moved to Carb info.

Maps has nothing to do with combat graphs, and there are many other addons that do a better job.

**Comment by IrcDirk** [comment]
I think we should remove it, since there is no need to keep this function in Carbonite, as it isnt as good as in other addons. What do u think @mikepauer and others?

**Comment by SteveEbey73742** [comment]
I agree.

Update:I went through the Carbonite.lua and commented out every single line dealing with Nx.Combat. Tested it in Windows, no fps drop, tested in older Windows xp machine with older video card, NO fps drop, tested on linux with wine64, NO fps drop.

**Comment by SteveEbey73742** [comment]
Made changes on my fork, and created a pull request, to take care of this issue, fully tested and made sure the BG stats are not affected by the changes.  NO fps drops in combat, regardless of hardware or operating system being used.  I can play WoW on Linux, with all of my addons.
