### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Soupereagle** [mikepauer/Carbonite#320]
Carbonite GetPos Err:539: Carbonite\NxMap.lua:9129: in function `GetWorldPos'
Carbonite.Quests\NxQuest.lua:7417: in function `UpdateIcons'
Carbonite\NxMap.lua:4820: in function `Update'
Carbonite\NxMap.lua:3820: in function <Carbonite\NxMap.lua:3735>

**Comment by atk** [comment]
I'm afraid you removed too much information from your description; Please provide 1. the version of Carbonite you used, 2. the full error message including locals and 3. whatever you did before getting that error.

**Comment by samyonair** [comment]
Marked as Invalid because of missing

**Comment by samyonair** [comment]
No further Information provided ..

closeing
