### ISSUE TITLE
Quest in Tanaanjungle not in Database

### ISSUE THREAD

**Issue by samyonair** [mikepauer/Carbonite#321]
Every New Quest says not in Database after reload data is there it is a bit silly to reload after every new  Quest

Think it is a Problem to load Data

greetings Samyonair

No Errormessage to display will test if it is only on first or every char

**Comment by IrcDirk** [comment]
I will think in few days of getting wowhead data for Tanaan Jungle into QuestData.

**Comment by samyonair** [comment]
oki and i will update what i have quested so far^^

**Comment by JWMcQuire** [comment]
I thought I might add that this happens on some of the low level quests as well, so I wonder if there might have been some changes in the latest patch that may need looking into.

Example: My level 40 Horde character has had some quests that would show in the quest watch window but read as "not in database" until after reload.
