### ISSUE TITLE
Carbonite\NxMap.lua:9081: Usage: GetMapNameByID(mapID)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#323]
Have not checked if this is a handynotes astrolabe issue or a npc overlay issue or just carbonite will update later and close if it is an issue with another.

2x Carbonite\NxMap.lua:9081: Usage: GetMapNameByID(mapID)
[C]: in function `GetMapNameByID'
Carbonite\NxMap.lua:9081: in function `GetWorldZoneInfo'
Carbonite\NxMap.lua:7314: in function `ClipZoneFrm'
_NPCScan.Overlay\Modules\Carbonite-6.2.0.lua:250: in function <_NPCScan.Overlay\Modules\Carbonite.lua:236>
_NPCScan.Overlay\Modules\Carbonite-6.2.0.lua:289: in function <_NPCScan.Overlay\Modules\Carbonite.lua:280>
[C]: ?
[C]: ?
Carbonite\NxMap.lua:233: in function `SetMapToCurrentZone'
...rfaceHandyNotes\Libs\Astrolabe\Astrolabe.lua:1135: in function `OnShow'
...rfaceHandyNotes\Libs\Astrolabe\Astrolabe.lua:1297: in function <...rfaceHandyNotes\Libs\Astrolabe\Astrolabe.lua:1296>
[C]: in function `Show'
...rfaceHandyNotes\Libs\Astrolabe\Astrolabe.lua:1167: in function `AllWorldMapsHidden'
...ns\HandyNotes\Libs\Astrolabe\AstrolabeMapMonitor.lua:168: in function <...ns\HandyNotes\Libs\Astrolabe\AstrolabeMapMonitor.lua:160>
(tail call): ?
...ns\HandyNotes\Libs\Astrolabe\AstrolabeMapMonitor.lua:201: in function `OnEvent'
...ns\HandyNotes\Libs\Astrolabe\AstrolabeMapMonitor.lua:230: in function <...ns\HandyNotes\Libs\Astrolabe\AstrolabeMapMonitor.lua:229>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:343: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:389: in function `RaidFrame_LoadUI'
FrameXML\RaidFrame.lua:61: in function <FrameXML\RaidFrame.lua:52>

Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 Scale = 4
 MenuIShowWorld = <table> {
 }
 Targets = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0
 ArrowPulse = 1
 PlyrRZY = 0
 MapId = 0
 MMOwn = true
 TextFStrs = <table> {
 }
 PlyrLastDir = 999
 Scrolling = false
 MMModels = <table> {
 }
 Menu = <table> {
 }
 ShowUnexplored = false
 MenuIShowMine = <table> {
 }
 MMAlphaDelay = 100
 MMOwnedFrms = <table> {
 }
 Arch = <unnamed> {
 }
 MMChkDelay = 5
 MMScalesC = <table> {
 }
 PIconMenu = <table> {
 }
 MMScales = <table> {
 }
 WorldAlpha = 0
 Guide = <table> {
 }
 StartupShown = true
 ScaleDraw = 0.025
 MapPosY = 1906.7869095092
 MapIndex = 1
 MapPosXDraw = 2200
 StepTime = 1
 PlyrSpeedX = 0
 PlyrFrm = <unnamed> {
 }
 LocTipFrm = NxMapTip {
 }
 DebugAdjustScale = 0.1
 MoveLastX = -1
 PlyrDir = 0
 PlyrSpeedCalcTime = 3160.586
 IconNavScale = 1
 MapPosYDraw = -100
 TextFrm = <unnamed> {
 }
 PlyrSpeed = 0
 WorldHotspots = <table> {
 }
 ContFrms = <table> {
 }
 MiniFrms = <table> {
 }
 TileFrms = <table> {
 }
 BGIconMenu = <table> {
 }
 MapScale = 1
 TargetNextUniqueId = 1
 Win = <table> {
 }
 PadX = 0
 MenuIPlyrFollow = <table> {
 }
 RealScale = 4
 Data = <table> {
 }
 GIconMenu = <table> {
 }
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 150
 TransMenu = <table> {
 }
 MMGathererUpdateDelay = 1
 MenuIShowTimber = <table> {
 }
 MMAddonFrms = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 ButAutoScaleOn = <table> {
 }
 DotZoneScale = 1
 MapH = 140
 MenuIMonitorZone = <table> {
 }
 GIconMenuIFindNote = <table> {
 }
 DotRaidScale = 1
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 TextScFrm = <unnamed> {
 }
 ArchAlpha = 0.3
 IconStaticFrms = <table> {
 }
 MapPosX = 6138.1178811797
 LOpts = <table> {
 }
 BackgndAlphaTarget = 0.4
 IconFrms = <table> {
 }
 Tracking = <table> {
 }
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 MapsDrawnFade = <table> {
 }
 UpdateTrackingDelay = 0
 ArrowScroll = 0
 UpdateTargetDelay = 0
 H = 141
 PlyrY = 0
 Tick = 0
 CurOpts = <table> {
 }
 IconNIFrms = <table> {
 }
 TitleH = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -1
 MenuIShowHerb = <table> {
 }
 DotPalScale = 1
 DotPartyScale = 1
 PlyrRZX = 0
 PlyrX = 0
 QuestAlpha = 0.3
 NeedWorldUpdate = true
 BackgndAlphaFade = 0.4
 BackgndAlphaFull = 1
 Frm = <unnamed> {
 }
 MoveDir = 0
 PlyrSpeedY = 0
 W = 150
 KillShow = false
}
cont = nil
zone = nil

**Comment by samyonair** [comment]
for astrolabe rythal has given a file in Forum http://www.wowinterface.com/forums/showpost.php?p=309458&postcount=9

but i think it is npcscan

**Comment by sumfoolz** [comment]
Receiving this same error on login, English

Date: 2015-11-22 13:48:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 9081:
   Usage: GetMapNameByID(mapID)
Debug:
   [C]: GetMapNameByID()
   Carbonite\NxMap.lua:9081: GetWorldZoneInfo()
   Carbonite\NxMap.lua:7314: ClipZoneFrm()
   ...erface\AddOns\_NPCScan.Overlay\Modules\Carbonite.lua:250:
      ...erface\AddOns\_NPCScan.Overlay\Modules\Carbonite.lua:236
   ...erface\AddOns\_NPCScan.Overlay\Modules\Carbonite.lua:289:
      ...erface\AddOns\_NPCScan.Overlay\Modules\Carbonite.lua:280
   [C]: ?
Locals:
(*temporary) = nil

AddOns:
  Swatter, v5.0.0 (<%codename%>)
  NPCScan, v6.2.3.3
  NPCScanOverlay, v6.2.2.1
  AskMrRobot, v30
  Atlas, v1.32.00
  AtlasArena, v1.5.07
  AtlasBattlegrounds, v1.32.00
  AtlasBurningCrusade, v1.32.00
  AtlasCataclysm, v1.32.00
  AtlasClassicWoW, v1.32.00
  AtlasDungeonLocs, v1.32.00
  AtlasMistsofPandaria, v1.32.00
  AtlasOutdoorRaids, v1.32.00
  AtlasScenarios, v1.32.00
  AtlasTransportation, v1.32.00
  AtlasWorldEvents, v3.13
  AtlasWrathoftheLichKing, v1.32.00
  AtlasMajorCitiesEnhanced, vv1.07
  AtlasQuest, v4.9.5
  Babylonian, v5.1.DEV.332(/embedded)
  Carbonite, v6.2.0
  CarboniteInfo, v6.2.0
  CarboniteNotes, v6.2.0
  CarboniteQuests, v6.2.0
  CarboniteSocial, v6.2.0
  CarboniteWarehouse, v6.2.0
  CarboniteWeekly, v6.2.0
  CarboniteTimelessIsleChests, v1.02
  Configator, v5.1.DEV.376(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMGarrisonInvasions, v
  DBMLDB, v
  DBMStatusBarTimers, v
  ElvUI, v8.40
  FBTrackingFrame, v1.5.4
  FishingBuddy, v1.6a
  Gatherer, v5.0.0
  GathererHUD, v5.0.0
  HandyNotes, vv1.4.5
  HandyNotesDraenorTreasures, v1.16
  HandyNotesGuild, v1.8
  HandyNotesHallowsEnd, vv1.2.2
  HandyNotesHigherLearning, v6.2.0.4
  HandyNotesLostAndFound, v1
  HandyNotesTimelessIsleRareElites, v2.32
  HandyNotesTimelessIsleChests, v1.13
  HandynotesTimelessTreasures, v1.0.2
  HandyNotesTreasureHunter, v1
  HandyNotesWellRead, v6.1.0.4
  KCrazyArrowHide, v1.21
  Omen, v3.1.11
  QuestGuru, v2.3.12
  SilverDragon, vv3.2
  Skada, v1.4-32
  SlideBar, v5.0.0 (<%codename%>)
  SorhaQuestLog, vv1.4.8.2
  WeDontWipe, v4.11
  WeDontWipeArcaneMage, v2.12
  WeDontWipeFrostMage, v2.10
  BlizRuntimeLib_enUS v6.2.3.60200 <none>
  (ck=678)

**Comment by IrcDirk** [comment]
Disable all other addons than Carbonite and check again.

**Comment by IrcDirk** [comment]
Thats NPCScan bug they should fix this.
