### ISSUE TITLE
Some minor errors that may need attention

### ISSUE THREAD

**Issue by JWMcQuire** [mikepauer/Carbonite#329]
Carbonite Version 6.2.0 B118 enUS

First Error: As indicated by the text below, this error has happened 3 times. I can't remember what I was doing at the time, so if it is necessary, I'll update this post with that info the next time this error occurs. No locals were listed.

3x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function '<unnamed>:SetPoint()'.
!BugGrabber\BugGrabber.lua:589: in function <!BugGrabber\BugGrabber.lua:589>
[C]: in function `SetPoint'
Carbonite\NxUI.lua:1889: in function `Adjust'
Carbonite\NxUI.lua:3133: in function <Carbonite\NxUI.lua:3085>

Locals:

Second Error:

This is another error that came up once so far. If it comes up again, I'll post what I was doing when it came up. Again, no locals were included in the error report.

1x Carbonite\NxMap.lua:5232: script ran too long
Carbonite\NxMap.lua:5232: in function `?'
Carbonite\NxMap.lua:5006: in function `Update'
Carbonite\NxMap.lua:3843: in function `OnUpdate'
Carbonite\NxMap.lua:1356: in function `MainOnUpdate'
Carbonite\Carbonite-6.2.0.lua:1291: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:

If any other info is needed, let me know.

Also, the map still seems to have some problems. For example, I'll open the map to see what flight points are near my quest area, but the quest will point to a location way out of the zone and can only be fixed by opening Blizzard's quest watch window with it's map and highlighting the quest which then allows Carbonite to point to the correct zone and location.

Another map issue occurs when I open the map and it defaults to Nagrand or Tanaan Jungle  and when I mouse over a zone to zoom in to a flight point or quest location a nearby zone zooms to the foreground covering up the area I am attempting to look at.

Finally, the flight point icons occasionally disappear requiring that I close and open the map a couple of times to get them to show up again. 

I believe these are the most glaring issues I encounter during play besides having to reload to get some quests to "appear" in the database.

Addons: 

Ackis Recipe List (All professions activated only according to each toon's profession)
Carbonite (all modules except Info)
Areko's Grats (activated only for toons in guilds)
Archy
Bitten's SpellFlash and dependencies(SF Core, Library, Utilities) for all classes activated according to each toon's class
Body Guard Away
BugGrabber
BugSack
FlyoutButtonCustom (active on all toons)
Garrison Manager (only active for toons in Dreanor)
GatherMate2Data - Carbonite Edition
GuildTithe (active only for toons in a guild)
LevelFlight
MicroDeclineDuel
OneClickEnchantScroll (active for Enchanters and Inscriptionists)
PetTracker
PetTracker Breeds
PetTracker Carbonite
PetTracker Config
PetTracker Journal
PetTracker Switcher
PetTracker Upgrades
Recount
Scrap
Scrap Merchant
Scrap Options
Scrap Spotlight
Scrap Visualizer
SpellFlash
Deadly Boss Mods Core (This mod and following modules only active on main toon)
DBM Options GUI
DBM Status Bar Timers 
DBM Blackrock Foundry
DBM Dreanor
DBM Garrison Invasions
DBM Hellfire Citadel
DBM Highmaul
DBM Party-WoD
DBM Voicepack VEM

**Comment by IrcDirk** [comment]
Always post your list of addons...

**Comment by JWMcQuire** [comment]
Thanks for the reminder. I added the list to the original post.

**Comment by IrcDirk** [comment]
Its for 6.2 version of Carbonite so for old expansion. Closing. If some of this errors are in Live version open new topics for each problem. Thanks.
