### ISSUE TITLE
Error specific to Scenarios

### ISSUE THREAD

**Issue by JWMcQuire** [mikepauer/Carbonite#330]
Carbonite Version 6.2.0 B118 enUS

The following error occurred during the scenario "Battle for Shattrath" quest # 34099. I don't believe this is unique to just this scenario as I have not been able to tick objectives in any scenario since before the latest update, even before I started using the dev version and submitting edits for the quest database.

When I attempted to tick a quest objective to see where I am supposed to go I got this error.

4x Carbonite.Quests\NxQuest.lua:4555: assertion failed!
[C]: in function `assert'
Carbonite.Quests\NxQuest.lua:4555: in function `FindCur'
Carbonite.Quests\NxQuest.lua:9294: in function `UserFunc'
Carbonite\NxUI.lua:6480: in function `UserFunc'
Carbonite\NxUI.lua:3669: in function <Carbonite\NxUI.lua:3651>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:9935
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:9703
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3027
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3080
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:10571
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:4985
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:10808
 GOpts = <table> {
 }
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:2965
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:4799
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5094
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10215
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3283
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4047
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:3875
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:9973
 ClearCaptured = <function> defined @Carbonite.Quests\NxQuest.lua:4819
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5070
 FindNewQuest = <function> defined @Carbonite.Quests\NxQuest.lua:4146
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:9926
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5592
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:9986
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:10801
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:3787
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:10667
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:7730
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4010
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:3912
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3230
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:7675
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9598
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4644
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4039
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5658
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4195
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4674
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2074
 RealQEntries = 7
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3060
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:3962
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lua:4459
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9522
 Tick = 0
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:4588
 CapFactionAbr = <table

Addons active on this toon: 
Carbonite (all but Info modules activated)
Areko's Grats
FlyoutButtonCustom
GuildTithe
Recount
Bitten's SpellFlash for Rogue
SpellFlash (required for Bitten's)

**Comment by IrcDirk** [comment]
Old expansion. Closing. If this still occours reopen.
