### ISSUE TITLE
Naval Yard 

### ISSUE THREAD

**Issue by mlande5** [mikepauer/Carbonite#334]
When taking a new toon to start there first quest in the Naval Yard Carbonite generates so many errors that you can't close it or stop until you get the message disable addons. I've had this issue with the 4 toons that are level 100.  Anyone else having this issue?

**Comment by Thrumbar** [comment]
Could you post some of the errors...

Thrumbar

**Comment by mlande5** [comment]
Here's one of the errors I get. I'm working on getting the exact one that come up at Naval. 
Message: Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3439: attempt to index local 'ch' (a nil value)
Time: 07/09/15 17:45:11
Count: 3
Stack: Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3439: in function `RecordCharacter'
Interface\AddOns\Carbonite\Carbonite.lua:1300: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = <table> {
 OnButToggleWarehouse = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3403
 AddBag = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2843
 OnLoot_opened = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3103
 CaptureGet = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3182
 OnUnit_spellcast_succeeded = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1027
 OnItem_lock_changed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2708
 UpdateItem = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2109
 CaptureItems = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2772
 ToggleShow = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1346
 OnGuildbankframe_closed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2614
 ImportDo = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1286
 AddLink = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2861
 Menu_OnRemoveChar = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1249
 Menu_OnShowItemCat = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1315
 UpdateBlank = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1789
 Menu_OnSortByRarity = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1320
 OnTime_played_msg = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1004
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2520
 Menu_OnSortBySlot = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1329
 Menu_OnSyncAccount = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1308
 OnChat_msg_skill = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3195
 OnBankframe_closed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2596
 RecordCharacter = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3435
 ReftipProcess = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2478
 ExportDo = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1301
 Menu_OnExport = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1296
 FindCharsWithItem = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2210
 ScanRBank = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2834
 OnLoot_slot_cleared = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3120
 OnItemListEvent = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1457
 OnUnit_inventory_changed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2883
 InitWarehouseCharacter = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3407
 ConvertData = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:814
 UpdateGuild = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1796
 prtdb = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1117
 OnEditBox = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1366
 CaptureUpdate = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2759
 CaptureInvDurabilityTimer = <func

**Comment by mlande5** [comment]
Ok sorry the above is an error from T. Jungle when fighting fel imps. sorry looking for the right one.

**Comment by JWMcQuire** [comment]
Could you please post the version of Carbonite you are using and a list of the addons you have loaded? I have done the killing demons quests several times fighting the fel imps with no errors, so you may need to check for an update or remove and reinstall Carbonite to fix this issue.

**Comment by mlande5** [comment]
Carbonite Version 6.2.0 with no other addons.    


     On Wednesday, July 15, 2015 12:32 AM, JWMcQuire <notifications@github.com> wrote:
   

 Could you please post the version of Carbonite you are using and a list of the addons you have loaded? I have done the killing demons quests several times fighting the fel imps with no errors, so you may need to check for an update or remove and reinstall Carbonite to fix this issue.—

**Comment by mlande5** [comment]
I wasn't able to get the full error message this is all I could get after 15 minutes I just deleted carbonite 6.2.0
Message: Interface\AddOns\Carbonite\Carbonite.lua:3740: bad argument #1 to 'find' (string expected, got nil)
Time: 08/05/15 18:56:02
Count: 2349
Stack: [C]: in function `find'
Interface\AddOns\Carbonite\Carbonite.lua:3740: in function `Split'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:9918: in function `UnpackName'
Interface\AddOns\Carbonite.Quests\NxQuest.lua:7425: in function `UpdateIcons'
Interface\AddOns\Carbonite\NxMap.lua:4856: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3843: in function <Interface\AddOns\Carbonite\NxMap.lua:3758>

Locals: (*temporary) = nil
(*temporary) = "|"
(*temporary) = 0
(*temporary) = true
(*temporary) = "string expected, got nil"

**Comment by mlande5** [comment]
Continuing not running any other addon but carbonite
