### ISSUE TITLE
Weak aura

### ISSUE THREAD

**Issue by Donaging** [mikepauer/Carbonite#34]
After their last update WA and Carbonite are incompatible

**Comment by IrcDirk** [comment]
They need to update they Ace3 lib. U can do it your self by hand: https://www.wowace.com/projects/ace3/files

**Comment by ChaoticWonder** [comment]
Do you mean update the Ace3 sub-directories in the libs folder of WA or Carbonite? I see Ace3 can be pulled from Twitch as an addon in and of itself, is that what you meant?  I tried copying the same folders from the latest Ace3-r1163-alpha into WA and it had no effect.

**Comment by Donaging** [comment]
I just downgrade sa to the .16 Version and all Works properly

**Comment by Donaging** [comment]
I downgrade weak auras...

**Comment by IrcDirk** [comment]
U need to have both latest alpha version of Carbonite and Weak Auras.
