### ISSUE TITLE
Quest track Bonus using bar issues apearance and format

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#341]
When I change the tracking of Bonus Quest to use a bar instead of % number, there is an issue with the alignment.

https://onedrive.live.com/?id=50E237CE0C7C122F%2115451&cid=50E237CE0C7C122F&group=0&parId=50E237CE0C7C122F%21108&authkey=%21AKKvxB10naHmg4c&o=OneUp

 The Bonus is misaligned, there is no endcaps and the bottom border line is not set properly. 
 Just to sorta let yall know. 
 Would be better if it looked like the one below carbonites quest watcher, that is the bar. (QuestKing2)..

 Thrumbar

**Comment by SteveEbey73742** [comment]
Can we show this one closed?
