### ISSUE TITLE
Enhancement - Use of LIB-Herebedragons

### ISSUE THREAD

**Issue by gOOvER** [mikepauer/Carbonite#342]
Looks like an great lib and maybe Corbonite can use it:

http://www.curse.com/addons/wow/herebedragons

**Comment by Thrumbar** [comment]
That addon is the replacement for the the buggy Astrolabe.  Carbonite does not us Astrolabe.

Thrumbar

**Comment by gOOvER** [comment]
Not only... ;)

But Carbonite use it's own "Lib" of Map positions, which use a lot of RAM ;)

**Comment by IrcDirk** [comment]
Rewriting Carb to use this Lib might be a nightmare ;)

**Comment by IrcDirk** [comment]
Closing, becouse we will not use this Lib.
