### ISSUE TITLE
BUG? Minimap Not Flexible. 200px? Please make 2,000+

### ISSUE THREAD

**Issue by xSimone** [mikepauer/Carbonite#348]
I've loved Carbonite for a long time, but this new UI change is too drastic. I loved the old one around err.. version 5.1.0 or something.

Right now this is happening http://i.imgur.com/of5eNlM.jpg

I used to be able to insert any number I liked, usually 1,200+ so I could have my Carbonite Map top right, and my Minimap bottom right of the screen, but now I cannot do this because it's got a hard limit of 200.. 

Why was this done? It's a limit that's crippling to the Minimap placement. 

Is there another setting somewhere that I've missed allowing me to put it where I want it?

If possible, could you release an update allowing people to put at least 2,000plus and negative values for X and Y? 

Edit: This is the old Carbonite I know and love http://i.imgur.com/ZnOBnim.jpg Can we please have it back?

Thanks

**Comment by wownob** [comment]
Remove "Minimap Docks Bottom" and set the Y-Offset to Zero.

**Comment by jeffy162** [comment]
That would, I believe, combine the on-screen minimap and minimized map. That is not what xSimone wants. I believe that what xSimone wants is to move the Blizzard minimap out of the Carbonite minimized map and put it where he wants it. That is what the minimap offset system is for, after all, but with the new restraints the system has it is not currently doable.

**Comment by xSimone** [comment]
jeffy162 thanks for realising through my bad explaination. I've included a screenshot of how I used to have it on Mists of Panderia.

http://i.imgur.com/PViIZdP.jpg

Why has it all been changed though? I overheard Carbonite was abandoned and picked up by someone else?

**Comment by IrcDirk** [comment]
So u want to have 2 maps (carbonite and blizz minimap) in 2 different places?

As to abandoning Carbonite... some people may say that but this is offcial repository and Carb is still developed by Rythal + some other devs. Of course anybody can fork and make own version...

**Comment by jeffy162** [comment]
Yes, that's what he wants to do, apparently, but the options the way they are now won't let it be done. The minimap offset system is too constrictive now. When I tried it (just to check it out - I don't use the minimap offset system) I couldn't even move my minimap out of the minimized map in the X-offset.

![wowscrnshot_112715_125511](https://cloud.githubusercontent.com/assets/8658862/11692397/441ed8b8-9e6d-11e5-99fa-7dfe2be0ca3c.jpg) A screen shot of my UI.


Carbonite was never "officially" abandoned, but the original developers sure made it look that way until they handed the reigns to Rythal.

**Comment by xSimone** [comment]
IrcDirk Yes that's basically what I'm after. I've tried using SexyMap but it's just not the same and it feels terrible. Carbonite has always been my favourite addon. 

What confuses me is the post an admin made saying "People Complained that Carbonite was trying to do too much" I don't understand how when I was using everything it did. Enchantrix, Tracking, double maps, breadcrumbs, even the lovely 'Quest Complete!' chime when I finished a Quest. :'c

**Comment by xSimone** [comment]
WHAT THE! Jeffy162 how did you get the collapsible!?  The box with the colored spots on it under your 'Carbonite' tab at the top. I don't have it! How did you get it back?

**Comment by Rythal** [comment]
That's Carbonite.Quests ... and your 200 has now been adjusted to support -2000 to 2000 so unless someone is on a 4K monitor they should be able to move it anywhere :)

**Comment by jeffy162** [comment]
It never left (that I am aware of, anyway). That is Carbonites Quest Watch, which I have set the key binding for to minimize it. As Rythal has stated it is from the Carbonite.Quests module, and you won't get it unless it is installed. There is a key binding, by default, for it in WoW's "Key Binds" facility to minimize it and I make use of that to minimize and maximize it. You can also minimize it manually by clicking on the arrow next to the "lock" symbol (the graphic changes according to the state of the watch window so in the minimized state it is just a "dash" or line). 

By-the-way, that is not a "Carbonite tab" at the top of my screen. I am currently using the ElvUI interface replacement addon, and that is one of the DataTexts in one of the addons for it that I have installed.

**Comment by xSimone** [comment]
jeffy162 mine isn't there sadly, and I downloaded ALL modules. I'll double check, possibly missed something.

Rythal I want your children I love you.

**Comment by IrcDirk** [comment]
xSimone use this link to download latest stable version: https://github.com/Rythal/Carbonite/archive/master.zip make sure u enable Carbonite Quests. As to fix, it was my job :D

**Comment by xSimone** [comment]
AM I THE FIRST TO GET THE MASTER EDITION OF CARBONITE?! ;U <3 

I'm sooo happy!! <3

**Comment by IrcDirk** [comment]
Nope, every one can download lastest stable and lastest development version from here (github).

**Comment by xSimone** [comment]
Oh, damn it. >xc

**Comment by xSimone** [comment]
Hey IrcDirk, or Mick, or Seven, Slipknot Legend. <3 

Here's a video of what I mean https://www.youtube.com/watch?v=-NchVEJEx9U

Hope this helps. Maybe make it a possible setting if you want zooming to work on both maps at once or separate them.

**Comment by Rythal** [comment]
Sorta :) I did do a change to the push you did to extend it further allowing negatives and a higher big jump so people using arrows or mouse dragging are not going 1 by 1 for 4000 possible numbers.

**Comment by Rythal** [comment]
The client freeze, is normal when you first start.. this is because Carbonite doesn't actually load until your in world so it can make sure your not in combat for some reason. It has a lot of work to do to setup everything and all the tables, and if your in combat some of the calls it needs to do it can't due to blizzard lock down.

The mouse wheel... I had never considered a time the two maps wouldn't be integegrated so it was never coded (yet) to consider the mouse wheel might be happening outside the map, i'll look into that.

**Comment by xSimone** [comment]
Hmm.. okay, let's see how it turns out!
