### ISSUE TITLE
Copy Profile

### ISSUE THREAD

**Issue by xSimone** [mikepauer/Carbonite#354]
Hey there, just a short one. Seems you cannot copy your Carbonite Profile to other characters. Any reason why?

**Comment by IrcDirk** [comment]
Profiles are work in progress... not working right now.

**Comment by jeffy162** [comment]
I don't know about that. I've made several new characters over the last few months and on each one I copy the profile of another character that I already have set up the way I like Carbonite to be. All I can say is "Works for me!".

**Comment by IrcDirk** [comment]
I think she's talking about in game config tab named "Profiles" ;)

**Comment by xSimone** [comment]
Huh.. alright, well, okay! ;d

**Comment by jeffy162** [comment]
Yes, that's what I am talking about. What are you guy's talking about? Copying the profile in the WTF folder?

**Comment by xSimone** [comment]
Damn it jeffy162 you must be lucky then because I have problems all over the joint >xp

http://i.imgur.com/Wa1PFml.jpg  Here's how it looks.

On my main, it seems fine. But on my alt here, it's stuffed. ':f

**Comment by jeffy162** [comment]
You have to set the profile first. In other words, let's say you logged on to an alt named...... ummmm, Rikety. Set the profile to "Rikety" (in the drop down menu, then the "Copy From" will light up), then hit the drop down for "Copy From" and find the profile you want to copy. Select it and [b][i]VIOLA`/i][/b], the profile is copied.

**Comment by xSimone** [comment]
After logging onto my main, I lost all my Carbonite Settings.. ';f

**Comment by jeffy162** [comment]
Wel, _**THAT'S**_ aproblem!!

**Comment by IrcDirk** [comment]
@xSimone on your main account try to "Copy From" and select "Default".

**Comment by xSimone** [comment]
Tried, still blank. I just started fresh.

**Comment by IrcDirk** [comment]
This module just doesnt work good. Temporary i have disabled Profile tab.
