### ISSUE TITLE
Missing map id in carbonite

### ISSUE THREAD

**Issue by milotic** [mikepauer/Carbonite#36]
Hi, when i do RBG and place is Eye of the storm minimap of carbonite go crazy and never load this map

eye of storm in rbg have some diferents changes in textures and bases are capped via flags like arathi basin

**Comment by Thrumbar** [comment]
[482] = "Eye of the Storm",
[813] = "Eye of the Storm",

According to LibTourist

	zones[BZ["Eye of the Storm"]] = {
		low = 35,
		high = MAX_PLAYER_LEVEL,
		continent = Outland,
		groupSize = 15,
		type = "Battleground",
		texture = "NetherstormArena",
	}

**Comment by IrcDirk** [comment]
Should be fixed. Please confirm.

**Comment by milotic** [comment]
i try on tuesday on reset

**Comment by milotic** [comment]
i do 12 rbg yesterday and a bad rng get 0 eots still trying

**Comment by milotic** [comment]
finally i get a eots and dont work and get a error:

Date: 2017-09-05 14:08:28
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4201:
   attempt to perform arithmetic on field 'KBs' (a nil value)
Debug:
   Carbonite\NxMap.lua:4201: Update()
   Carbonite\NxMap.lua:3816:
      Carbonite\NxMap.lua:3700

**Comment by milotic** [comment]
![wowscrnshot_092617_163118](https://user-images.githubusercontent.com/1099848/30887372-699e5660-a2d8-11e7-9368-d2282f188a18.jpg)
![wowscrnshot_092617_163123](https://user-images.githubusercontent.com/1099848/30887373-69a03e76-a2d8-11e7-8282-d93d58ace4f6.jpg)

hi @IrcDirk,  why close if still bug? screens are from today and thanks

**Comment by milotic** [comment]
[17:02:28] Dump: value=GetInstanceInfo()
[17:02:28] [1]="Ojo de la tormenta puntuado",
[17:02:28] [2]="pvp",
[17:02:28] [3]=0,
[17:02:28] [4]="",
[17:02:28] [5]=10,
[17:02:28] [6]=0,
[17:02:28] [7]=false,
[17:02:28] [8]=968,
[17:02:28] [9]=0,

[17:04:43] Dump: value=GetCurrentMapAreaID()
[17:04:43] [1]=813,
[17:04:43] [2]=false

**Comment by IrcDirk** [comment]
This map is allready alised to orginal EOS mapid. Works for me, no error. U need to update to latest alpha release on Curse/Twitch client.

**Comment by milotic** [comment]
![captura](https://user-images.githubusercontent.com/1099848/38955189-1e387546-4311-11e8-9c68-b94cb0f49e64.PNG)
Hi @IrcDirk always i use alpha-beta release to alls addons and EoS in rbg carbonite never load the map

**Comment by IrcDirk** [comment]
Mike made fixes but before it worked for me too. Weird.
