### ISSUE TITLE
Quest Markers

### ISSUE THREAD

**Issue by xSimone** [mikepauer/Carbonite#360]
Carbonite Quest Markers are roughly 50% wrong at the time. Especially when inside your Garrison.

Why is this? 

Also, when I link Quests with Carbonite, the link doesn't show but you see the text in plain.

**Comment by IrcDirk** [comment]
Quest database isnt complete and up to date.

**Comment by xSimone** [comment]
Wow that was quick, Seven! ;d

**Comment by xSimone** [comment]
Is there anything I'm able to supply in helping you update the quest database? Like sniffing or anything?

**Comment by xSimone** [comment]
I think there should be some sort of quest record feature. Like.. a toggle you can turn on that Carbonite puts a pin on the map where you last did a Quest, then you can submit it here. Us users can help that way. Something like "Quest blahblah was completed at X / Y"

**Comment by IrcDirk** [comment]
There is recorder build in:

![carbonite](http://i.imgur.com/3J8WNH0.png)

then u can upload it here http://atk.github.io/Carbonite/ in **Quest DB Upload** section.

**Comment by xSimone** [comment]
You.. are awesome. LUCKILY I have it checked on. I'll upload all the stuff I've done very soon. This'll be great for Missives and Draenor quests. 

Doesn't anyone else upload their logs?

**Comment by xSimone** [comment]
Where's the root of where it's all saved?

C:\Program Files (x86)\World of Warcraft\Interface\AddOns\Carbonite.Quests\Data

This it?

**Comment by jeffy162** [comment]
No. Where its saved at is:  *Path to your WoW folder*\Account\ACCOUNT NAME\SavedVariables\Carbonite.Quests.lua  . All of your quest information is saved there.

**Comment by xSimone** [comment]
Thanks Jeffy!

**Comment by xSimone** [comment]
Curious, then what's all this I've found?

http://i.imgur.com/5i6SXQ9.png

**Comment by IrcDirk** [comment]
Thats normal its quests database, its outdated and not complete...

**Comment by xSimone** [comment]
Oh so that's the database that you've made already. I see.

**Comment by jeffy162** [comment]
Yes, it's the database that they've made up already - but the "new" quests are saved in there and are used by any other characters that go to do them. If I am wrong about that, someone will jump in here and correct me. I hope. 8^)

**Comment by IrcDirk** [comment]
@jeffy162 nope, Carbonite doesnt change or write to this Quests files.

**Comment by jeffy162** [comment]
Then WHY does it have all the quests that have been done,separated by character name, in it? And ONLY by your characters since Carbonite has been installed.

**Comment by IrcDirk** [comment]
Im reffering to these @xSimone files: http://i.imgur.com/5i6SXQ9.png

**Comment by jeffy162** [comment]
Ahh. OK.

**Comment by Rythal** [comment]
The quest data is mostly outdated for 1-90 ... I actually found it had very good tracking for 90-100 after the web crawl they did... just missing the later quests after that. However at the same time Carbonite itself is fairly good at figuring it out on it's own, It may just be my own luck but on the rare cases I have a quest that it says isn't in the database, doing a /reload causes the quest to populate and track properly.

**Comment by Rythal** [comment]
As for garrisons, they can be tricky as if they were crawled and in the database.. the start and end points can vary depending on where you have the buildings and what your layout is.

**Comment by DaveJ61** [comment]
For me, there are still quite a lot of quests that do not populate at all. For me, I have also never managed to get the data to populate by doing a reload.
However, what I have noticed is that if the quest is for another area, such as Nagrand and I am in Talador, it will not populate until I go to that area...Nagrand. I have noticed this, many, many times.

**Comment by IrcDirk** [comment]
@DaveJ61 is right, same issues here. Quest does show up on map even if they are not in Quests Database but always on the map that we are currently on.

**Comment by xSimone** [comment]
IrcDirk just calling back to before. I was just curious about what I found since I went looking before I asked the question. There is no need to be rude. :<

I uploaded my quest file by the way hope it helps. :3
