### ISSUE TITLE
Small Bug ESC + Quest Panel (L)

### ISSUE THREAD

**Issue by xSimone** [mikepauer/Carbonite#362]
If you open the Quest Panel via L or clicking the Quest button it will pop up, clicking it again will close it.

However, if you close your Quest Panel by pressing ESC, you need to press L (or button) TWICE to bring it up again.

An odd little bug. Thought I'd let you know. ;x

It's as if ESC hides the Quest Panel, instead of closing it, and pressing L closes it when it's hidden, then re-opens it to be seen.

**Comment by IrcDirk** [comment]
U should always try only Carbonite and if this works with all other addons disabled there might by compatibility issue. Try to find which is the problematic addon and let us know, couse this function works fine on my WoW (got Caronite + 15 other addons).

**Comment by xSimone** [comment]
I have, and it is doing exactly as I've mentioned.

I'm currently on the latest Carbonite release, uhh.. 21st Jan? 

Press L to open Quest Panel, press ESC, press L, nothing happens, Press L again, quest log pops up.

**Comment by Rythal** [comment]
Confirmed it happens for me, none of the other windows do it so i'll check why.

**Comment by xSimone** [comment]
Thank you Rythal. x'3 <3

**Comment by DaveJ61** [comment]
I also can confirm this happens to me on a regular basis. In fact it has been in existence for quite some time and I believe the bug has been brought up some months ago in another post. I can't remember what happened to it, though.

**Comment by LargeGoose** [comment]
Erm, sorry to hijack your post but latest Carbonite release 21st Jan? The GitHub code section says that nothing has been updated for months. Don't tell me I've been looking in the wrong place for the last year!

**Comment by samyonair** [comment]
I think You haven't looked the right Place here on github You have to look on dev section or Master section, AT the moment i'm Not at my PC, that is why i cannot have a look on github to Tell which Version is latest update 


Greentings Samyonair 






On Sun, Jan 24, 2016 at 4:59 AM -0800, "LargeGoose" <notifications@github.com> wrote:












Erm, sorry to hijack your post but latest Carbonite release 21st Jan? The GitHub code section says that nothing has been updated for months. Don't tell me I've been looking in the wrong place for the last year!

**Comment by LargeGoose** [comment]
<img width="746" alt="carbonite master" src="https://cloud.githubusercontent.com/assets/10414231/12536674/d6087856-c2a3-11e5-8ea2-61b10bd353bf.PNG">

This is what I see...

**Comment by xSimone** [comment]
https://github.com/Rythal/Carbonite/archive/master.zip

Click this ;d

**Comment by xSimone** [comment]
I have a feeling this bug is more severe than it might be. I think it's also the reason my ESC key stops responding after I start spamming it over 10 times. Just now my map didn't open until I spammed it.

**Comment by IrcDirk** [comment]
@LargeGoose 

![ccheck this out](http://i.imgur.com/Kkaql1h.png)

**Comment by xSimone** [comment]
What's the difference between DEV, PTR and Master?

Dev being Alphas, PTR being Beta and Master is release?

**Comment by Rythal** [comment]
Currently, Dev and PTR are out of date, as I have only been doing bug fixes it's all been going to Master.

Normally if i'm preparing for a live release to curse/wowI it's Master that gets used
Dev is for testing of new code and changes that might break everything
PTR is for the rare times someone reports the new build of wow that's on PTR breaks the whole addon so it can be fixed without affecting live or development versions before the PTR goes to live patch.

**Comment by IrcDirk** [comment]
Master is main release version
Development is development version
PTR is development for WoW "Public Test Realm" version

**Comment by IrcDirk** [comment]
> If you open the Quest Panel via L or clicking the Quest button it will pop up, clicking it again will close it.
> 
> However, if you close your Quest Panel by pressing ESC, you need to press L (or button) TWICE to bring it up again.
> 
> An odd little bug. Thought I'd let you know. ;x
> 
> It's as if ESC hides the Quest Panel, instead of closing it, and pressing L closes it when it's hidden, then re-opens it to be seen.

Seems it works good now... Checked on several toons. Closing. Reopen if something is wrong.
