### ISSUE TITLE
Not really an issue but a heads up regarding Tanaan Jungle quests and Dailies

### ISSUE THREAD

**Issue by JWMcQuire** [mikepauer/Carbonite#374]
In my latest pull request, I think I finally added the last of the remaining Tanaan Jungle quests and dailies to the database. If I missed any, I will add them as I find them or are brought to my attention. They are now showing up in my game as intended, so I don't expect any issue on other systems, but that is just me being hopeful.

I know WoD hasn't been very well received and activity in Tanaan has dropped significantly, but I hope if development of Carbonite continues into Legion, these additions will be helpful to future users. And I hope to continue doing what I can to assist when the opportunity presents itself.

Edit: It appears that after the release of the movie, Tanaan activity has spiked a bit. So I see this as a good thing and hopefully incentive to consider a pre-Legion updated release to help Carbonite's, loyal users as they prepare for Legion. :-)

**Comment by vern1701** [comment]
If you want to maintain a constantly updated database if you are (or not) in the beta, you can use Wowhead as a supplement.  Curse has the WowDB addon that is updated every patch.

**Comment by JWMcQuire** [comment]
Thanks Rythal, for the info. I have been using wowhead regularly when updating the data I have been pushing. Their information has been very helpful. I haven't used WowDB, but just installed it as well as installing the beta version for the PTR client. I don't have access to Legion beta but entered a contest on MMO-Champion through curse for one. I am testing the PTR version of the pre-patch which doesn't play nice with Carbonite or any of the other mods except, bug grabber/bugsack, bartender4 alpha, and Bodyguard Away.

So until I get access to Legion either through beta or on release, I am pretty much stuck updating the Tanaan quests in WoW live which is ok.

Will you be pushing an alpha/ptr version here? Since I am not familiar enough with lua to make Carbonite play nice with pre-patch anything from you should help those of us wiling to chip in where we can. :-)

Also, could you please look at the pull requests? I have pushed several commits since my original request. Some of those trim some of my earlier edits of bugged quests that got pulled because I couldn't repeat the success I thought I had with them. An example is one of the Nat Pagle quests that always points to Frostwall  even after I added it twice with 1/2 flags or even just adding two "end" lines pointing to both locations. So I just reverted it back to one quest flagged as neutral and noted it as bugged in the code. Also, there are 2 other pull requests that don't appear to have any conflicts, one of which I believe updates information that has been pushed to master but not to dev.

Again, thank you for your reply and the suggestions. I appreciate that.

**Comment by Rythal** [comment]
I can't push anything as I don't have much of anything yet... However I can say many of the changes that were done during MoP and WoD are working fine, Carbonite will load, and still works fine even going into Legion and not knowing any of the map information.

**Comment by JWMcQuire** [comment]
Thank you for the quick reply. Yes, Carbonite loaded fine in the PTR, but with several bugs reported through bug grabber. I'll try again with bug grabber/bug sack disabled to see how many Carbonite related errors might have been false positives. Do you want me to post any error information I get, or would it be best to wait until you are ready to push what you have?

**Comment by vern1701** [comment]
I'm flattered that you have me confused with Rythal.  Alas, I am not him/her.  However, I just came back two months ago after a 15 month hiatus.

Hello, Rythal.  As you can see, I'm back and ready to help out again.  Legion looks good, so far.  Addon authors are really on a time crunch to get everything ready for it, and the truth of the matter is, we may not get everything ready on time for launch.  But we can sure try.  I've offered some sites and other addons both here and on the main forum that should help with getting most of the info needed.  Maps are a bit tricky, but try to look for map/minimap addon authors who are in beta and ask for info or help.  The landscape is constantly changing in Beta, so be wary of that.

Legion may also have more major content patches than WoD's two.  Sadly, I am not in the Beta, but once it goes live I'll be of more help.  Right now, I'm working through WotLK content (just started), so it will be some time before I can contribute anything.  For now, keep up the work and don't get discouraged.  I'll keep in touch.

**Comment by JWMcQuire** [comment]
Sorry Vern, I barely made it through my first cup of coffee when I read your message, and did think it odd that Rythal would be suggesting places I could go for help with the database after I had already pushed several quest updates. lol

Still, the advice was well received and appreciated just the same. :-)

**Comment by JWMcQuire** [comment]
I just committed a Tanaan table quest I missed which is now included in my most recent pull request. Hopefully this will be that last one. However, since I'm farming Apexis Crystals for armor and to finish as much of the Legendary Ring quests as I can before Legion, I will add others I may have missed.
