### ISSUE TITLE
Message: ..\AddOns\Carbonite\NxMap.lua line 4666

### ISSUE THREAD

**Issue by Clothahump** [mikepauer/Carbonite#381]
Date: 2016-07-10 16:07:09
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4666:
   Usage: C_TaskQuest.GetQuestsForPlayerByMapID(id)
Debug:
   [C]: GetQuestsForPlayerByMapID()
   Carbonite\NxMap.lua:4666: Update()
   Carbonite\NxMap.lua:3843: OnUpdate()
   Carbonite\NxMap.lua:1356: MainOnUpdate()
   Carbonite\Carbonite.lua:1291: NXOnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
(*temporary) = nil

AddOns:
  Swatter, v4.3.1 (<%codename%>)
  Carbonite, v6.2.0
  TomTom, vv60200-2.1.0-917c73d
  BlizRuntimeLib_enUS v6.2.4.60200 <none>
  (ck=7f)

**Comment by jeffy162** [comment]
It _**USED**_ to be that if you ran TomTom with Carbonite, you would get errors. Carbonite contains a TomTom emulator (that works with other addons) and they didn't _**used**_ to work together. Try disabling TomTomand see how it works.

**Comment by Clothahump** [comment]
I’ll give it a shot.  Thanks!
