### ISSUE TITLE
Beta : \Carbonite.Social\NxSocial.lua:1779: attempt to index local 'punk' (a nil value) Time: 07/15/16 10:07:10

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#390]
Message: Interface\AddOns\Carbonite.Social\NxSocial.lua:1779: attempt to index local 'punk' (a nil value)
Time: 07/15/16 10:07:10
Count: 43
Stack: Interface\AddOns\Carbonite.Social\NxSocial.lua:1779: in function `AddLocalPunk'
Interface\AddOns\Carbonite.Social\NxSocial.lua:2716: in function `?'
...ite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[16]"]:4: in function <[string "safecall Dispatcher[16]"]:4>
[C]: ?
[string "safecall Dispatcher[16]"]:13: in function `?'
...ite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...\AddOns\Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\AddOns\Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Cheilynn** [comment]
I am experiencing this as well.
