### ISSUE TITLE
Carbonite.Quests\NxQuest.lua:9025: bad argument #3 to 'format' (string expected, got nil)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#405]
87x Carbonite.Quests\NxQuest.lua:9025: bad argument #3 to 'format' (string expected, got nil)
[C]: in function `format'
Carbonite.Quests\NxQuest.lua:9025: in function `UpdateList'
Carbonite.Quests\NxQuest.lua:8623: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
(*temporary) = "%s%s%s"
(*temporary) = "|cffffd100100 "
(*temporary) = nil
(*temporary) = "A Tale of Romance and Chivalry"
(*temporary) = "string expected, got nil"

**Comment by IrcDirk** [comment]
I think this is fixed.
