### ISSUE TITLE
Heavy Lag With Multiple Quests

### ISSUE THREAD

**Issue by Viusing** [mikepauer/Carbonite#423]
Just begun to notice this. Whenever any of my characters have a lot of quests loaded into Carbonite, it begins to lag heavily.

**Comment by Viusing** [comment]
The amount of lag seems to correlate with certain areas or certain quests. Hovering the cursor over the minimap and/or opening and closing the quest list seems to sometimes provide a temporary relief from said lag.

**Comment by IrcDirk** [comment]
There is setting in Carbonite Quest module that effects performance, set this value to higher then LAG should get lower:

http://i.imgur.com/Uj8Emge.png

**Comment by samyonair** [comment]
Close this because no further Information, reopen if not fixed,
