### ISSUE TITLE
AddOns\Carbonite\Carbonite.lua line 3734:

### ISSUE THREAD

**Issue by Kabulla** [mikepauer/Carbonite#425]
Date: 2016-07-28 23:57:00
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\Carbonite.lua line 3734:
   bad argument #1 to 'find' (string expected, got table)
Debug:
   [C]: ?
   [C]: find()
   Carbonite\Carbonite.lua:3734: Split()
   Carbonite\NxMap.lua:8042:
      Carbonite\NxMap.lua:8025
Locals:

AddOns:
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  WowheadLooter, v60014
  AccountantClassic, v2.07.05
  AckisRecipeList, v7.0.3.2
  AckisRecipeListQuickScan, v7.0.3.1
  ACP, v3.4.28 
  Altoholic, vr168
  Atlas, v1.33.02
  AtlasBattlegrounds, v1.33.00
  AtlasBurningCrusade, v1.33.00
  AtlasCataclysm, v1.33.00
  AtlasClassicWoW, v1.33.00
  AtlasDungeonLocs, v1.33.01
  AtlasMistsofPandaria, v1.33.00
  AtlasOutdoorRaids, v1.33.01
  AtlasScenarios, v1.33.00
  AtlasTransportation, v1.33.01
  AtlasWarlordsofDraenor, v1.33.01
  AtlasWorldEvents, v3.15
  AtlasWrathoftheLichKing, v1.33.00
  AtlasLoot, vv8.01.00
  AutoBar, v6.2.0.04
  Bagnon, v7.0.3
  BagnonConfig, v7.0.3
  BankStack, vv36
  Bartender4, v4.7.1
  BetterAddonList, v1.0.3
  BrokerSmartBuff, v6.0a
  Carbonite, v7.0.0
  CarboniteInfo, v6.2.0
  CarboniteNotes, v7.0.0
  CarboniteQuests, v7.0.0
  CarboniteSocial, v6.2.0
  CarboniteWarehouse, v7.0.0
  CarboniteWeekly, v6.2.0
  CensusPlus, v7.0.0
  DataStore, vr56
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr52
  DataStoreCrafts, vr70
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr45
  DataStoreMails, vr45
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr53
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DugisGuideViewerZ, v4.005
  Ellipsis, v4.0.1
  epgp, vv5.12.0
  FBTrackingFrame, v1.5.4
  FishingBuddy, v1.7
  FriendListColors, v7.0.0.160625
  GarrisonCommanderBroker, v2.13.3 6.2.4
  GearingGuide, v1.3.43
  Grail, v080
  GrailAchievements, v011
  GrailReputations, v007
  GuildCheck, vv 2.4.9
  GuildManager, v6.2.3b
  GuildOx, v6.2.3.78
  IceHUD, v1.10.2
  ImprovedOptionsFrames, v1.5.5
  ItemRack, v
  LibAboutPanel, v1.6.2
  LibExtraTip, v5.12.DEV.390(/embedded)
  LinkWrangler, v1.96
  Oilvl, v6.1.5
  Omen, v3.1.11
  Pawn, v2.0.4
  Postal, vv3.5.8
  QuestCompletist, v105
  Recount, vv7.0.3c release
  SlideBar, v5.21f.5579 (SanctimoniousSwamprat)
  SmartBuff, v6.0c
  Spy, v3.3.0
  Titan, v5.7.1.70000
  TitanBag, v5.7.1.70000
  TitanClock, v5.7.1.70000
  TitanGold, v5.7.1.70000
  TitanGuild, v6.0.3.1
  TitanLocation, v5.7.1.70000
  TitanLootType, v5.7.1.70000
  TitanPerformance, v5.7.1.70000
  TitanRepair, v5.7.1.70000
  TitanSocial, v7.0.3
  TitanVolume, v5.7.1.70000
  TitanXP, v5.7.1.70000
  TradeSkillMaster, vv3.4.24
  TradeSkillMasterAccounting, vv3.0.15
  TradeSkillMasterAppHelper, vv3.0.1
  TradeSkillMasterAuctionDB, vv3.1.12
  TradeSkillMasterAuctioning, vv3.0.12
  TradeSkillMasterCrafting, vv3.1.10
  TradeSkillMasterDestroying, vv3.1.3
  TradeSkillMasterMailing, vv3.0.11
  TradeSkillMasterShopping, vv3.3.7
  TradeSkillMasterVendoring, vv3.0.3
  TradeSkillMasterWarehousing, vv3.0.3
  TrinketMenu, v6.0.1
  Wholly, v057
  WIM, v3.7.8
  WoWDBProfiler, v
  BlizRuntimeLib_deDE v7.0.3.70000 <none>
  (ck=b9d)

**Comment by IrcDirk** [comment]
Confirm if this still occours. Else ill close this issue in 3 days.
