### ISSUE TITLE
Quest window ordering

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#429]
The quest ordering works mostly but there are problems especially with quests for different zones than you are currently in. The list is order by distance.
This first example, I am currently in the Borean Tundra and in the list is shown the quest 'The Masters Grand Design', which is a Nagrand quest but is shown as only 867 yards away. You will also notice the two completed quests in green below this which seem to be out of order, distance-wise. 
This also seems to tie in with the mapping problem issue which I submitted months ago where the quest routing was incorrect and were sometimes off map or sending you to the completely wrong place. I can't seem to find the issue I logged any more, but the problem still exists.

![carbonite1](https://cloud.githubusercontent.com/assets/1816367/17283306/d6a33e34-57a6-11e6-8e05-393bc823b4e4.JPG)

The next screen grab shows that distance ordering doesn't appear to be working. It certainly does not across zones.

![carbonite2](https://cloud.githubusercontent.com/assets/1816367/17283431/1b529538-57a8-11e6-8c4c-58ec1409236e.JPG)

This next image was from before I abandoned a load of quests to make room but as you can see again, the ordering is not correct.

![carbonite3](https://cloud.githubusercontent.com/assets/1816367/17283473/bf5e07fc-57a8-11e6-8939-1a3c42f4b78e.JPG)

This appears to be an issue with quests which are in a zone outside of the one you are currently in.

When clicking the priorities button, the ordering does not make sense to me. What is the number at the end? The picture below gives it as 0.66, but if you click it again, it changes to a different number such as 0.73. I have also seen 0.46 and 0.75. Either way, this does not seem to make a difference.

![carbonite5](https://cloud.githubusercontent.com/assets/1816367/17283685/3c82ad8a-57ab-11e6-8486-a93685a0b8ce.JPG)
 
![carbonite6](https://cloud.githubusercontent.com/assets/1816367/17283687/42862856-57ab-11e6-9f9e-6dc4eb0acb67.JPG)

**Comment by JWMcQuire** [comment]
Yes, quest ordering is tricky and the slider is "invisible". You can still move the slider. Just click the blank part below the one you want to adjust and move your mouse to adjust it.

For quests not in the zone, try ticking the box labeled, "Hide Quests Not In Zone". 

This may not fix the ordering, but hopefully after Rythal and team are finished getting Carbonite ready for Legion, little things like this may get some attention. :-)

**Comment by DaveJ61** [comment]
Hi, I know about moving the quest list about. I use the mouse wheel to scroll it, always have done. I also know about hiding other zones, but I choose not to. I am just highlighting current issues.
I've been using carbonite for more years than I care to remember and playing wow for longer :-)

**Comment by IrcDirk** [comment]
Please try to download recent version and check if this is still an issue.

**Comment by DaveJ61** [comment]
Sorry for the delay. I already have the latest version but will check this out later today.

**Comment by DaveJ61** [comment]
The quest ordering seems to be mostly fixed but I am finding that some quests that were working seem not to be in the database. However, as I know the quest well, as soon as I completed the first part, it all became known to carbonite. The quest was Runes of Compulsion given by Gavrock. However, as recall, it has happened on several quests.
This is actually a different problem so maybe it should be on a separate ticket?

**Comment by IrcDirk** [comment]
Those quests are not in Carb Database since there have incomplete information on wowhead but Carbonite has some workaround functions that if u are in quests zone it tries to scrap quest information from Blizzard function its not perfect but it sometimes works good.
