### ISSUE TITLE
Chat message

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#43]
Getting this in chat.
Edit 1 : this happens when I complete a quest objective..  Was doing a World Quest at the time..

[Carbonite] 1
[Carbonite] 2
[Carbonite] 3
[Carbonite] 4
[Carbonite] 5
[Carbonite] 6
[Carbonite] 7
[Carbonite] 8
[Carbonite] 9
[Carbonite] 10
[Carbonite] 11
[Carbonite] 12
[Carbonite] 13

**Comment by mikepauer** [comment]
Should be fixed now.
