### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by DireGrim** [mikepauer/Carbonite#437]
The minimap doesn't seem to want to stay in "full size" mode. The check I put in the box is removed several times while playing. Thank you for the updates.

**Comment by jeffy162** [comment]
If you mean "all the time", then, no, it doesn't/won't. The minimap goes to various sizes while you are moving in the world. I don't know why either. Want a good representation of this? Just go on a flight using one of the flight masters in the game. Watch the "get off at the next known flight point" icon and you'll see what I mean.
