### ISSUE TITLE
Carbonite\NxMap.lua:7123 - NPCScan problem?

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#458]
4x Carbonite\NxMap.lua:7123: Usage: <unnamed>:SetFrameLevel(level)
[C]: in function `SetFrameLevel'
Carbonite\NxMap.lua:7123: in function `ClipZoneFrm'
_NPCScan.Overlay\Modules\Carbonite-7.0.0.lua:48: in function <_NPCScan.Overlay\Modules\Carbonite.lua:47>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 OnSynchronize = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:578
 Loaded = true
 KeyParent = _NPCScanOverlayKeyParent {
 }
 AchievementNPCNames = <table> {
 }
 RangeRingTargetOnHide = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:201
 OnUpdate = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:523
 KeyParentOnSizeChanged = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:174
 Paint = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:305
 OnShow = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:29
 KeyPaint = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:130
 Alpha = 0.5
 OnUnregister = <function> defined @_NPCScan.Overlay\Modules\WorldMapTemplate.lua:180
 ToggleOnClick = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:218
 RangeRingSetEnabled = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:553
 Registered = true
 KeyToggleOnClick = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:231
 WORLD_MAP_UPDATE = <function> defined @_NPCScan.Overlay\Modules\WorldMapTemplate.lua:119
 RangeRingSetTarget = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:187
 KeyValidateSize = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:154
 RangeRingPaint = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:208
 RangeRingTargetOnShow = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:195
 KeyOnSizeChanged = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:181
 KeyOnLeave = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:544
 DetectionRingSetEnabled = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:571
 Toggle = _NPCScanPathToggle {
 }
 OnDisable = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:329
 Enabled = true
 OnHide = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:15
 OnUnload = <function> defined @_NPCScan.Overlay\Modules\Carbonite.lua:152
 MapNeedsUpdate = true
 KeyOnEnter = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:533
 KeyMinScale = 0.5
 OnEnable = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:322
 Name = "WorldMap"
 RangeRing = <unnamed> {
 }
 OnMapUpdate = <function> defined @_NPCScan.Overlay\Modules\WorldMapTemplate.lua:132
 Config = _NPCScanOverlayModuleWorldMap {
 }
 super = <table> {
 }
 KeyToggle = _NPCScanKeyToggle {
 }
}
(*temporary) = nil

**Comment by DanielFabian** [comment]
I seem to have the same problem with the current master as of right now.

**Comment by mikepauer** [comment]
It will always be a problem, NPCScan tries doing stuff before Carbonite is loaded, once it is loaded it doesn't happen further.

**Comment by DaveJ61** [comment]
This is still occuring. I would have thought there should be a way to fix or suppress this.

`5x Carbonite\NxMap.lua:7165: Usage: <unnamed>:SetFrameLevel(level)
[C]: in function `SetFrameLevel'
Carbonite\NxMap.lua:7165: in function `ClipZoneFrm'
_NPCScan.Overlay\Modules\Carbonite-7.0.3.lua:48: in function <_NPCScan.Overlay\Modules\Carbonite.lua:47>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 OnSynchronize = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:578
 Loaded = true
 KeyParent = _NPCScanOverlayKeyParent {
 }
 AchievementNPCNames = <table> {
 }
 RangeRingTargetOnHide = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:201
 OnUpdate = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:523
 KeyParentOnSizeChanged = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:174
 Paint = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:305
 OnShow = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:29
 KeyPaint = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:130
 Alpha = 0.5
 OnUnregister = <function> defined @_NPCScan.Overlay\Modules\WorldMapTemplate.lua:180
 ToggleOnClick = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:218
 RangeRingSetEnabled = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:553
 Registered = true
 KeyToggleOnClick = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:231
 WORLD_MAP_UPDATE = <function> defined @_NPCScan.Overlay\Modules\WorldMapTemplate.lua:119
 RangeRingSetTarget = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:187
 KeyValidateSize = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:154
 RangeRingPaint = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:208
 RangeRingTargetOnShow = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:195
 KeyOnSizeChanged = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:181
 KeyOnLeave = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:544
 DetectionRingSetEnabled = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:571
 Toggle = _NPCScanPathToggle {
 }
 OnDisable = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:329
 Enabled = true
 OnHide = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:15
 OnUnload = <function> defined @_NPCScan.Overlay\Modules\Carbonite.lua:152
 MapNeedsUpdate = true
 KeyOnEnter = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:533
 KeyMinScale = 0.5
 OnEnable = <function> defined @_NPCScan.Overlay\Modules\WorldMap.lua:322
 Name = "WorldMap"
 RangeRing = <unnamed> {
 }
 OnMapUpdate = <function> defined @_NPCScan.Overlay\Modules\WorldMapTemplate.lua:132
 Config = _NPCScanOverlayModuleWorldMap {
 }
 super = <table> {
 }
 KeyToggle = _NPCScanKeyToggle {
 }
}
(*temporary) = nil
`

**Comment by IrcDirk** [comment]
But this should be done by NPCScan authors, thats not ours bug:

> _NPCScan.Overlay\Modules\Carbonite.lua

as u see this file is not ours ;)

**Comment by IrcDirk** [comment]
Update to latest. I tried to make workaround like Rythal sugested. Infrom if this helped.

**Comment by IrcDirk** [comment]
Any one that usues NPCScan can confrimed if this is fixed?

**Comment by DaveJ61** [comment]
Sorry for the delay. This appears to be ok now.

**Comment by samyonair** [comment]
Ok then I Close it
