### ISSUE TITLE
Keybinding issues

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#466]
Having issues with keybindings showing corrupt characters,  I get " ?_???? " for keybinding on one of my characters for carbonite show hide notes . On another character I get "or the zone you're in will never be summoned" with the keybindings for Carbonite notes and carbonite quest.

On another character there is no carbonite in keybindings but a blank space for "Use Items" is there.

**Comment by IrcDirk** [comment]
Should be fixed.

**Comment by KrysEmlyn** [comment]
Removing the category from the keybinds in the "Binding.xml files fixes the issue, but all the keybindings end up under the Category of "Other".

**Comment by IrcDirk** [comment]
Does not! Reload several times if u have many addons it breaks.

**Comment by Thrumbar** [comment]
Closing pending 7.1

**Comment by IrcDirk** [comment]
We need to move keybinding options from Addons tu Carbonite. This should be fixed by Blizz so there souldnt be problems with that.
