### ISSUE TITLE
Mining Nodes missing

### ISSUE THREAD

**Issue by PhiraNova** [mikepauer/Carbonite#47]
Went to Outland this morning to get some fell iron and all of my mining nodes are missing. Further no new nodes are being saved as I mine. I checked my Argus map cause I mined there yesterday and they are not showing on there as well and I have show mining nodes checked.

**Comment by PhiraNova** [comment]
Just checked Sholazar Basin and the same there. Ran the node count script and it came up as 0.

**Comment by mikepauer** [comment]
Came across this myself when I was trying to debug the node lag problem, it's a bug from the change over to aceevents and fixed on my local copy, it'll be pushed live soon.

**Comment by PhiraNova** [comment]
Awesome, thank you so much. I freaked out this morning and actually screamed "My Nodes!" Looking forward to it being fixed!

**Comment by mikepauer** [comment]
Fix is pushed now, so should work if you update.
