### ISSUE TITLE
Force Max Camera Distance

### ISSUE THREAD

**Issue by vizoere** [mikepauer/Carbonite#471]
The checkbox on the General page no longer seems to change the camera view distance.

Per blue posts:
From Watcher June 25, stating that view distance would be nerfed:
http://us.battle.net/forums/en/wow/topic/20745744692#post-18

From Watcher August 5, stating that they'll compromise:
http://us.battle.net/forums/en/wow/topic/20748204616?page=8#post-147

In-game macro to set max distance to the furthest zoom allowed is:
/console SET CameraDistanceMaxFactor 2.6

Can you change the checkbox in Carbonite to set the max distance to that?

**Comment by IrcDirk** [comment]
> function Nx.Opts:NXCmdCamForceMaxDist()
> 
> --	Nx.prt ("Cam %s", GetCVar ("cameraDistanceMaxFactor"))
> 
> 	if Nx.db.profile.General.CameraForceMaxDist then
> 		SetCVar ("cameraDistanceMaxFactor", 2.6)
> 	end
> end

This is the code in Carbonite, so it should work. Please test and cofirm.
