### ISSUE TITLE
Carbonite.Quests\NxQuest.lua:7448: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#475]
Got this doing the Druid Resto Artifact quest..  Was in Dreamgrove and just talked to the NPC Naralex and aquired the quest In Deep Slumber.  had to disable carbonite to copy the error,,,

1026x Carbonite.Quests\NxQuest.lua:7448: attempt to concatenate a nil value
Carbonite.Quests\NxQuest.lua:7448: in function `UpdateIcons'
Carbonite\NxMap.lua:4668: in function `Update'
Carbonite\NxMap.lua:3638: in function <Carbonite\NxMap.lua:3555>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:9803
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:9571
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3063
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3116
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:10439
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:5001
 Watch = <table> {
 }
 AcceptAId = 1077
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:10676
 GOpts = <table> {
 }
 NullQuest = <function> defined @Carbonite.Quests\NxQuest.lua:10816
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:3001
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:4815
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5110
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10083
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3302
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4064
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:3892
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:9841
 ClearCaptured = <function> defined @Carbonite.Quests\NxQuest.lua:4835
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5086
 FindNewQuest = <function> defined @Carbonite.Quests\NxQuest.lua:4163
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:9794
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5611
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:9854
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:10669
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:3804
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:10535
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:7753
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4027
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:3929
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3249
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:7698
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9466
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4660
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4056
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5677
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4212
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4690
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2106
 RealQEntries = 16
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3096
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:3979
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lua:4475
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9390
 Tick = 0
 Ch

**Comment by IrcDirk** [comment]
This should be fixed.

**Comment by SteveEbey73742** [comment]
I logged in 05:30 local time, ran world quests, and regular, before rolling restarts. on for an hour and a half all over broken isles, and return to dalaran. no issues at all, I consider this fixed.  Please close.
