### ISSUE TITLE
Carbonite' tried to call the protected function '<unnamed>:SetPoint()'.

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#476]
Toing the Resto Druid Artifact quest in Nordrassil fighting big demon and healing allies.  had to shut down carbonite to use artiface to call forrest creatures as icon did not appear in quest frame...

1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function '<unnamed>:SetPoint()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetPoint'
Carbonite\NxUI.lua:1885: in function `Adjust'
Carbonite\NxUI.lua:3129: in function <Carbonite\NxUI.lua:3081>

Locals:

**Comment by IrcDirk** [comment]
I sometimes get this error too. Need to find out in which sytuation this error pops...

**Comment by SteveEbey73742** [comment]
as of the most recent commit, f099030 2 hours ago i do not get this error. I was on for 1-1/2 hours, prior to the rolling restarts for the North American servers.

**Comment by IrcDirk** [comment]
If u set in Carb options "Enable Combat Compatibility Mode" this will never occur. I have this disabled.

First try to fix this is ready.
