### ISSUE TITLE
Minimap fps issues

### ISSUE THREAD

**Issue by GhostiNv** [mikepauer/Carbonite#478]
Hello, for some reason my fps drops to around 10 when minimap is docked. If i close the minimap/open world map/mouseover minimap fps goes back to 50 - 60.

edit: I've narrowed it down to Carbonite Quests (i have 22/25 quests). WIth Quests disabled there's no problem so now i need to fiddle with the settings and hopefully i'm gonna solve it.

**Comment by Wolfane** [comment]
You sir are the hero we deserve.  Ya i've got the same issue, 24/25 quests.  Haven't tried turning off the minimap but maybe I'll try that, I'm down from like 70fps to about 12-16fps.  Is your fps still good using the vanilla minimap?

**Comment by GhostiNv** [comment]
No problems with vanilla minimap. I tried many settings with minimap + quests module but no luck, problem persisted. Now i'm on 15/25 and it's working ok can't test anymore.

**Comment by Wolfane** [comment]
I'm 19/25 turned the quest module back on, full frames.  Turned the docked minimap back on (instead of the vanilla circular minimap) full frames.  Hope it stays this way.  So nice to have my quest module and docked minimap back!

**Comment by Morindra** [comment]
I am still having this issue.  11/25 quests.  Downloaded most recent files this morning.  Mine does the same... works fine with vanilla map, works fine with mouseover or closing carbonite minimap, works fine with disabling quest module.

**Comment by IrcDirk** [comment]
Recently rythal pushed commit to fix issue with quest module, download recent version and check.

**Comment by Morindra** [comment]
OK.  I _had_ downloaded most recent version before posting.  I noted a change made about 2 hours ago.  I downloaded the package again.  It seems to have fixed the issue.
