### ISSUE TITLE
LC 20160902-01 Harvestnodes Language Integration Syntax Error

### ISSUE THREAD

**Issue by tsod76** [mikepauer/Carbonite#479]
For the latest commit by @samyonair, there was an error in the HarvestNodes.lua files.  For each locale, a "=" was forgotten for the entry of "Starlight Rose", before the "true" value.  The line number of the "Starlight Rose" entry varies between locales.

Cheers.
tsod76

**Comment by samyonair** [comment]
Thank you was a mistake by me was fixed by Thrumbar thanks for that
