### ISSUE TITLE
Transporter Pads

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#49]
Any chance of getting the Argus Transporter Pads on the Minimap?

**Comment by mikepauer** [comment]
Yes, just haven't decided yet in which way... I can either add a new transportation type so it shows up as zone connections, or as flight maps since that's the system it uses ingame, or something entirely new

**Comment by samyonair** [comment]
Mikepauer has pushed https://github.com/mikepauer/Carbonite/commit/04439490777310969c80b28e5ed1876cbcee8b20
it's In so far
for Locales in other languages I've created a pull request #52
