### ISSUE TITLE
Double Bonus Quest display has returned .......

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#493]
https://1drv.ms/i/s!Ai8SfAzON-JQgYEOqLVENzNJfqgKDw

have it set to display as a bar instead of a %..  Looks like is is supposed to either, as by the settings, show as a num%  or as a bar.  It seems like it is trying to do both as there may not an else statement to make one or the other...  A use %  if settings not set to bar else do bar...

**Comment by mikepauer** [comment]
There is something really wrong here, because the top bonus task is not coloured, and both instances that can possibly show up saying BONUS TASK are coloured the same (now) that was fixed when I fixed the double display originally.

"|cffff00ff----[ |cffffff00"

**Comment by Thrumbar** [comment]
My bad have to many old copies closing..
