### ISSUE TITLE
[Maps] Stormheim 

### ISSUE THREAD

**Issue by samyonair** [mikepauer/Carbonite#502]
Hi Following Issue 

I Was checking Flightmasters for translation purposes and every time I put my mouse over Shields Rest, Stormheim flight icon all icons on Map disapear same issue for Hafr Fjall, Stormheim.

My Idea is stormheim map area in Carbonite is to small 

greetings Samyonair

**Comment by samyonair** [comment]
Another Map Issue seems to be Dalaran city because only flightpoint not showing on map (Carbonite Icon)

**Comment by IrcDirk** [comment]
Both should be fixed by now.
