### ISSUE TITLE
FPS issue with Quest module

### ISSUE THREAD

**Issue by Raka-loah** [mikepauer/Carbonite#504]
It may sound weird but the moment my character unlocked World Quests, FPS dropped to 15~30 (normally 100+).
Characters haven't unlocked World Quests don't have this issue.
I've tried reset config files and only enable carbonite and carbonite quest module with profiling, lag appears and it shows quest module eating up ~80% CPU resources.
It doesn't produce any Lua error.
Once quest module is disabled, everything is fine.
It's more weird that whenever quest module causes lag, move mouse cursor to carbonite map, lag disappears. And when you move far enough (carbonite map loads another area map), the lag returns.

I don't have another lvl110 character so I can't test further. But when I asked my friend and he said he doesn't have this issue.
Annoying af.

**Comment by Donaging** [comment]
Same problem here

**Comment by GhostiNv** [comment]
Besides the fps issue now i have a different problem with the quest module. On my lvl 110 if quest module is active wow crashes. It works perfect on my other chars. I tried with all other addons disabled, with settings reset, no change. Strange thing is it was working ok last night. Haven't changed anything, didn't update any addon, so no idea why. I'm guessing it doesn't like one of the active world quests.
A solution for the fps issue for me is to keep the carbonite minimap closed. There's a setting to close the map completely when you press m or close and not dock it.

**Comment by mikepauer** [comment]
No addon should ever be able to crash the client, try deleting your cache.

**Comment by GhostiNv** [comment]
I deleted WTF folder, reinstalled the addon and only left Carbonite and quest module, the game loads, the carbonite splash screen appears then the game gets stuck. Game window turns white and says not responding and that's that. Can't explain what is wrong.

**Comment by IrcDirk** [comment]
Newest Carb version from github?

**Comment by Raka-loah** [comment]
After some event tracing, the problem seems to be carbonite map module itself spamming WORLD_MAP_UPDATE and QUEST_LOG_UPDATE events like crazy.
Interestingly, when you put your cursor on the carbonite map, it will stop spamming those events, and map still works.
Use latest github version, clean install, only carbonite map module, /eventtrace to trace events, then move around(e.g. gate of ogrimmar, back and forth), every time when zone name is about to change, tons of WORLD_MAP_UPDATE and QUEST_LOG_UPDATE appears, like every ~0.05 secs.
It affects all characters, but without World Quests (have lots of data I guess), it won't significantly impact game performance, thus I didn't notice before.

**Comment by mikepauer** [comment]
WORLD_MAP_UPDATE is expected, and why I have built in throttles to only process so many

QUEST_LOG_UPDATE should of been removed when I switched to UNIT_QUEST_LOG_CHANGED, looks like it came uncommented, so pushing it again.

**Comment by Raka-loah** [comment]
Commented that RegisterEvent and problem solved!
Many thanks! :+1:

**Comment by SteveEbey73742** [comment]
When I disabled the hud tracking arrow, all zones, and all toons went back up to normal fps.  I was getting lower fps in panda, outland, and older zones, but the worse was broken isles.  Could there be something in hud updates, that caused the other events to fire off, and bog down?

**Comment by IrcDirk** [comment]
@mikepauer u did commented but QUEST_**WATCH**_UPDATE no QUEST_**LOG**_UPDATE ;)
