### ISSUE TITLE
Naval Yard not updating (Old Reload Questlist bug)

### ISSUE THREAD

**Issue by samyonair** [mikepauer/Carbonite#507]
After Rythal's patch for fps Issuses , Quests which are taken from a Questgiver are not shown in QuestList until Reload.

**Comment by samyonair** [comment]
Another Problem with not Updating Questlog after Quest is completed and given to NPC it is shown in Questlog with questinformation from another Quest and questinfo from that other quest is empty.

seems a table problem for disqribtion an example

in a table collum a is head of quest collum b is questinfo

the completed quest is in row 5 

a5 is still head of the finished quest but b5 is cleared and has information from row 6 and b6 is emty

I hope you can understand what i want to tell

my skills are to bad to fix it but my Idea is we need no questlogupdate on load but every time a quest is taken and given to a NPC.

Greetings Samyonair

**Comment by IrcDirk** [comment]
Now everything works fine after @mikepauer fixes.

**Comment by samyonair** [comment]
Sorry, but not at all, have removed quests.lua in wtf to check but rows are mixed up

Questheader and Questinformation are mixed up 

for example 

questhead in a table is a questinfo is b

Have 22 / 25 questes for now 
Head in row 1 show questinfo from b 17
a17 shows b15
a15 shows b7

and so on 
it is bad to quest with this

**Comment by samyonair** [comment]
That is my carbonite.quests.lua 
just new 
`
NXQuest = {
	["Gather"] = {
		["Q"] = {
		},
		["Version"] = 0.8,
		["UserLocale"] = "deDE",
	},
	["profileKeys"] = {
		["Kryptherius - Proudmoore"] = "Default",
	},
	["global"] = {
		["Characters"] = {
			["Proudmoore.Kryptherius"] = {
				["Q"] = {
					[20489] = "C1473834167",
					[39903] = "W0",
					[19452.5] = "C1473834167",
					[39025] = "C1473834167",
					[39027] = "C1473834167",
					[39787] = "W0",
					[38909] = "C1473834167",
					[39793] = "W0",
					[38915] = "C1473834167",
					[39043] = "C1473834167",
					[42451] = "W0",
					[39305] = "W0",
					[43341] = "W0",
					[19472.5] = "C1473834167",
					[39884] = "W0",
					[40012] = "W0",
					[39575] = "C1473834167",
					[39577] = "C1473834167",
					[39579] = "C1473834167",
					[20488.5] = "C1473834167",
					[38957] = "W0",
					[40219] = "C1473834167",
					[38912] = "C1473834167",
					[38286] = "W0",
					[44338] = "W0",
					[39867] = "W0",
					[19997] = "C1473834167",
					[39873] = "W0",
					[42088] = "C1473834167",
					[39373] = "W0",
					[42955] = "W0",
					[40228] = "W0",
					[40072] = "W0",
					[40011] = "W0",
					[38958] = "W0",
					[39889] = "W0",
					[39776] = "C1473834167",
					[39578] = "C1473834167",
					[39580] = "C1473834167",
					[39372] = "W0",
					[40990] = "W0",
				},
			},
			["Alleria.Darkeyê"] = {
			},
			["Alleria.Dârkfly"] = {
			},
		},
	},
	["profiles"] = {
		["Default"] = {
			["QuestOpts"] = {
				["NXWHideDist"] = 20000,
				["NXWPriGroup"] = -100,
				["NXWPriLevel"] = 20,
				["NXWPriComplete"] = 50,
				["NXShowHeaders"] = true,
				["NXWPriDist"] = 1,
				["NXWHideNotInZone"] = false,
				["NXWHideGroup"] = false,
				["NXSortWatchMode"] = 1,
				["NXWWatchParty"] = true,
				["NXWHideUnfinished"] = false,
				["NXWShowOnMap"] = true,
				["NXWHideNotInCont"] = false,
				["Version"] = 0.12,
				["NXWVisMax"] = 8,
			},
		},
	},
}
`

**Comment by IrcDirk** [comment]
Sorry, u are right... it isnt fixed. Questing now is hard with Carb. We need to wait for the fix...

**Comment by samyonair** [comment]
have to check it tonight have no time for now to quest, have cleared cache, wtf and Interface to test but with a fresh copy it works

**Comment by samyonair** [comment]
Have finished a quest only to run and given to an NPC get new ones table gets mixed up

**Comment by IrcDirk** [comment]
That might be a problem with some Carbonite settings in WTF folder... ill try to find which file it is.

**Comment by samyonair** [comment]
you are right only a reload helps, but not logging out and in thats curious

**Comment by IrcDirk** [comment]
Im not so good with Quest module... to many changes recently to try to fix it, @mikepauer should take care of it if he will have time for it... As for know, questing with Carb is very hard. But we can use older version of Carb from repository, when all with quests worked (beside World Quests and some fps fixes).

**Comment by mikepauer** [comment]
I have it fixed, but I can't upload it because my quests module right now is non-existent as I'm half-done testing a theory to move it towards dynamic loading of quest information (I no longer have load0 load1 etc etc) I don't even know if it's going to work or not yet.... I won't be home from work until near midnight EST.

**Comment by mikepauer** [comment]
In the meantime as a work around, You don't need to reload make yourself a macro /script Nx.Quest:RecordQuestsLog() and just hit that macro when you need the log updated.

**Comment by IrcDirk** [comment]
Do what u have to do then in spare time fix Carbonite. Every one have job and other things than Carbonite :) Dynamic loading of quest data would be great. I did think of this also but if u are on it i will wait till u make your changes then maybe propose something to make it better or optimize.

**Comment by IrcDirk** [comment]
@mikepauer u have to remember that there is option to search completed quest and quests in database in quest module, so this option need to be rewriten to work in dynamic quest data loading.

**Comment by IrcDirk** [comment]
New commit from @mikepauer is on repository. Works fo me ;)

**Comment by Palonblade** [comment]
Working much better. One issue which happens and may happen on similar quests are the shipyard quests where you have to complete 15 naval missions then 25 treasure missions (Upgrading the Fleet). The quest will say x/15 and does not update when you complete the missions and exit the shipyard screen. Mine said 11/15 Naval Shipment Victories when I entered the screen, completed a mission, exited the screen and the quest log still said 11/15. After I ran /script Nx.Quest:RecordQuestsLog() the quest log properly updated to 12/15.

**Comment by Palonblade** [comment]
Update. Hope this helps, when the quest completed the quest log updated. So it didn't update when I hit 14/15 but did when I hit 15/15.

**Comment by samyonair** [comment]
Great work found another minor Issue, quest objectives not in database aren't shown with orange dot, 

if you hit an objective in questtracker bug sack tells

7x Carbonite.Quests\NxQuest.lua:9685: attempt to index field 'Objectives' (a nil value)
Carbonite.Quests\NxQuest.lua:9685: in function `TrackOnMap'
Carbonite.Quests\NxQuest.lua:9312: in function `Set'
Carbonite.Quests\NxQuest.lua:9205: in function `UserFunc'
Carbonite\NxUI.lua:6485: in function `UserFunc'
Carbonite\NxUI.lua:3665: in function <Carbonite\NxUI.lua:3647>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:9840
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:9608
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3088
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3141
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:10476
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:5026
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:10713
 SortQuests = <function> defined @Carbonite.Quests\NxQuest.lua:4113
 NullQuest = <function> defined @Carbonite.Quests\NxQuest.lua:10857
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:3026
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:4840
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5135
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10120
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3327
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4089
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:3917
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:9878
 ClearCaptured = <function> defined @Carbonite.Quests\NxQuest.lua:4860
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5111
 FindNewQuest = <function> defined @Carbonite.Quests\NxQuest.lua:4188
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:9831
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5637
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:9891
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:10706
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:3829
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:10572
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:7790
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4052
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:3954
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3274
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:7735
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9503
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4685
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4081
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5703
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4237
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4715
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2106
 RealQEntries = 33
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3121
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:4004
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lua:4500
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Ca

**Comment by IrcDirk** [comment]
Made commit:
- @Palonblade check if quest progress shows ok now
- @samyonair check if error is gone

**Comment by Palonblade** [comment]
Still didn't update until I ran /script Nx.Quest:RecordQuestsLog()

**Comment by IrcDirk** [comment]
There been many chances to files today please update before checking this. U should always provide hash of commit u are using when testing issues.

**Comment by Palonblade** [comment]
Got message @Palonblade check if quest progress shows ok now, downloaded and installed file with latest commits and tested. Not sure what you mean by hash. Maybe the 854-1405? If so there it is. Does this change with every commit?

**Comment by Palonblade** [comment]
You probably mean this "Latest commit 1494c55  6 hours ago" I hadn't seen a lot of peeps even reference this, my bad I guess.

**Comment by Palonblade** [comment]
Got message @Palonblade check if quest progress shows ok now, downloaded and installed file with latest commits and tested. Latest commit 1494c55  6 hours ago  @IrcDirk IrcDirk  Just quick fix missing "function()"

**Comment by IrcDirk** [comment]
Thats weird couse my Carb is showing progress in quest log fine. No errors?

**Comment by IrcDirk** [comment]
@Palonblade latest version should work... try or ill close this issue.

**Comment by samyonair** [comment]
Will Check tonight

**Comment by IrcDirk** [comment]
Great!

**Comment by Palonblade** [comment]
Still not updating. Normal questing seems to be fine. If the normal quest says kill 8 x it updates. This issue may very well be specific to the Shipyard quests. Latest commit 93b8dc9  18 hours ago

**Comment by IrcDirk** [comment]
Link this quest from wowhead :)

**Comment by Palonblade** [comment]
http://www.wowhead.com/quest=39067/upgrading-the-fleet
http://www.wowhead.com/quest=39246/naval-domination

**Comment by samyonair** [comment]
Updated Title to better see what Issue is Open old seems fixed

**Comment by IrcDirk** [comment]
We need confirmation if this is fixed or not, couse we made several changes to Quest Module lately so it might be fixed. Need testing in navyard.

**Comment by Palonblade** [comment]
Latest commit 7b396bb  issue with Naval quests still exists.

**Comment by IrcDirk** [comment]
Please check again with latest.

**Comment by Palonblade** [comment]
Unfortunately I am no longer on these quests so cannot test.

**Comment by IrcDirk** [comment]
Any one else?

**Comment by IrcDirk** [comment]
Ok now it should be really fixed ;) Just need someone to confirm.

**Comment by IrcDirk** [comment]
Ok, on my alt all works well. Closing.
