### ISSUE TITLE
Carbonite hanging up game

### ISSUE THREAD

**Issue by Morindra** [mikepauer/Carbonite#508]
While the lag issue was resolved, yesterday, each time I logged in, the game hung up and I could not do anything.  I had to turn off Carbonite for the game to work.  So, tonight, troubleshooting: 

I turned off all addons except Carbonite.  This still occurred.  So, I went through the modules one by one.  Quest was the culprit.  With just it turned off, all is well and no more hanging on loading screen.

**Comment by samyonair** [comment]
Same Problem here, only for better Understanding 
it freezes and windows tells wow.exe is not answering but after about 15-30 sec game starts.

Seems to be a problem that carbonite quest needs to long to load.

**Comment by IrcDirk** [comment]
Yes and i know whats the problem... Quests0.lua is bigger then before update and takes more time to load, other quests files are sometimes bigger sometimes smaller and Quests110.lua was added so still more quests to load.

**Comment by samyonair** [comment]
An Idea would be loading on request but I think this would need a rewrite of questmodule and a better sorting like as now but with files for seasonal as e.g. to splitt quest0.lua a bit

**Comment by IrcDirk** [comment]
Quest in Quest0.lua dont have lvl or requirements so it might by hard to split this file... Im thinking about rewriting quest loading to load just Quest0 and maybe after this load all others on demand... Or even better to split all Quests to individual files.

**Comment by IrcDirk** [comment]
Ok, after this commit: https://github.com/mikepauer/Carbonite/commit/016cb7cd9bd20c1e48ae133939520776096f3902 my WOW also hangs but not on loading screen but after writing in chat that Carb is loaded...

**Comment by IrcDirk** [comment]
Now everything works fine after @mikepauer fixes.

**Comment by Morindra** [comment]
Ok.  Mine still hangs up.

Interesting, though.  Every time it does it, at the bottom right of the screen it shows an item info box for Enchanted Burial Urn (http://www.wowhead.com/item=140326/enchanted-burial-urn). 
![2016-09-13 2](https://cloud.githubusercontent.com/assets/10010783/18495540/8147e434-79e4-11e6-9197-c674cdbb1bd6.png).  Not sure if that helps or not, but I thought I'd mention it.  I kept seeing the box, but was too busy restarting game.  I paid attention this time...

**Comment by Kabulla** [comment]
mine also hangs up today, just as it has hung up yesterday...

**Comment by IrcDirk** [comment]
I dont have to remind that u have to update to latest version from github? ;)

**Comment by Kabulla** [comment]
hehe... no, you don't... I am on the one, 22h-old... ;-9

**Comment by Morindra** [comment]
I'm good, now.  It was a little squirrelly at start up, and I thought it was going to hang.  It didn't so.. YAY.

**Comment by Morindra** [comment]
I left this open for Kabulla to respond.  I'm still good, so closing.

**Comment by Kabulla** [comment]
I am still on my way back from business;-)
Won't be before late tonight for me to test... sorry...
I wrote that before but somehow my "announcement" got lost...

**Comment by Kabulla** [comment]
downloading just now...

**Comment by Kabulla** [comment]
first glance, problem gone... will report once more but it seems ok...

**Comment by Kabulla** [comment]
encountered no problems, so confirmed...
