### ISSUE TITLE
Disconnect from game

### ISSUE THREAD

**Issue by ihatepms** [mikepauer/Carbonite#509]
game loads, then as soon as i find quest objective (mouse hover) game disconnects. this happens with all alts.
if I disable Carbonite, no disconnect. if i re-enable the d/c is immediate.

might have to go to previous ver (lot's of bugs but no d/c)...

**Comment by IrcDirk** [comment]
What version u have? It has this latest commit: https://github.com/mikepauer/Carbonite/commit/5c5002d75cc3e3bc5b134b68a6a8304a37d25217? If not try this new version.
