### ISSUE TITLE
integer overflow attempting to store 2186115300

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#51]
Saw this in Bugsack when I was going to log off..

365x integer overflow attempting to store 2186115300
[C]: in function `format'
Carbonite\NxMap.lua:5534: in function `?'
Carbonite\NxMap.lua:4885: in function `Update'
Carbonite\NxMap.lua:3816: in function <Carbonite\NxMap.lua:3700>

Locals:
InCombatSkipped

**Comment by IrcDirk** [comment]
Some new shit from Blizz... need to check this **InCombatSkipped**.

**Comment by Thrumbar** [comment]
This appears to come from Buggrabber 342 to 362

		if not errorObject then
			local stack = debugstack(3)

			-- Scan for version numbers in the stack
			for line in stack:gmatch("(.-)\n") do
				tmp[#tmp+1] = findVersions(line)
			end

			-- Store the error
			local inCombat = InCombatLockdown() or UnitAffectingCombat("player")
			errorObject = {
				message = sanitizedMessage,
				stack = table.concat(tmp, "\n"),
				locals = inCombat and "InCombatSkipped" or debuglocals(3),
				session = addon:GetSessionId(),
				time = date("%Y/%m/%d %H:%M:%S"),
				counter = 1,
			}

			wipe(tmp)
		end

**Comment by IrcDirk** [comment]
Nope, after searching this is another Blizz bug: https://us.battle.net/forums/en/wow/topic/18300115893#4 need to wait till they fix this. I dont have time to find workaround to this...
