### ISSUE TITLE
Quest tracker not loading at all

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#510]
1x Carbonite.Quests\NxQuest.lua:3049: ')' expected near 'end'

Locals:

**Comment by Thrumbar** [comment]
Have the latest version post commit ffe29f0c00f44e37b4e63e8943c41ca707da3f6e

**Comment by IrcDirk** [comment]
My bad, cutted to much. Just pushed fix for this, should be fine now.

**Comment by Thrumbar** [comment]
Quest mod loads again with sorting error.   Issue to be addressed with separate ticket..
