### ISSUE TITLE
Carbonite.Quests\NxQuest.lua:2851: attempt to compare number with nil

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#512]
3x Carbonite.Quests\NxQuest.lua:2851: attempt to compare number with nil
Carbonite.Quests\NxQuest.lua:2851: in function `SortQuestDB'
Carbonite.Quests\NxQuest.lua:3049: in function <Carbonite.Quests\NxQuest.lua:3049>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:9882
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:9650
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3130
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3183
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:10518
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:5068
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:10755
 SortQuests = <function> defined @Carbonite.Quests\NxQuest.lua:4155
 NullQuest = <function> defined @Carbonite.Quests\NxQuest.lua:10899
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:3068
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:4882
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5177
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10162
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3369
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4131
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:3959
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:9920
 ClearCaptured = <function> defined @Carbonite.Quests\NxQuest.lua:4902
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5153
 FindNewQuest = <function> defined @Carbonite.Quests\NxQuest.lua:4230
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:9873
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5679
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:9933
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:10748
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:3871
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:10614
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:7832
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4094
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:3996
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3316
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:7777
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9545
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4727
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4123
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5745
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4279
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4757
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2106
 RealQEntries = 34
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3163
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:4046
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lua:4542
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Ca

**Comment by IrcDirk** [comment]
Ok, this error is becouse Sorted table is not properly filled. I will try to redo this "sorting" loop, this sould fix this error.

**Comment by Thrumbar** [comment]
Still getting

1x Carbonite.Quests\NxQuest.lua:2851: attempt to compare number with nil
Carbonite.Quests\NxQuest.lua:2851: in function `SortQuestDB'
Carbonite.Quests\NxQuest.lua:3049: in function <Carbonite.Quests\NxQuest.lua:3049>

Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Carbonite.Quests\NxQuest.lua:9882
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Carbonite.Quests\NxQuest.lua:9650
 Menu_OnTrack = <function> defined @Carbonite.Quests\NxQuest.lua:3130
 GetQuestReward = <function> defined @Carbonite.Quests\NxQuest.lua:3183
 DecodeComRcv = <function> defined @Carbonite.Quests\NxQuest.lua:10518
 MsgNotInDB = <function> defined @Carbonite.Quests\NxQuest.lua:5068
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Carbonite.Quests\NxQuest.lua:10755
 SortQuests = <function> defined @Carbonite.Quests\NxQuest.lua:4155
 NullQuest = <function> defined @Carbonite.Quests\NxQuest.lua:10899
 CheckQuestSE = <function> defined @Carbonite.Quests\NxQuest.lua:3068
 GetFromPlyr = <function> defined @Carbonite.Quests\NxQuest.lua:4882
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Carbonite.Quests\NxQuest.lua:5177
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Carbonite.Quests\NxQuest.lua:10162
 RecordQuestsLog = <function> defined @Carbonite.Quests\NxQuest.lua:3369
 ExtractTitle = <function> defined @Carbonite.Quests\NxQuest.lua:4131
 CalcCNumMax = <function> defined @Carbonite.Quests\NxQuest.lua:3959
 UnpackObjective = <function> defined @Carbonite.Quests\NxQuest.lua:9920
 ClearCaptured = <function> defined @Carbonite.Quests\NxQuest.lua:4902
 TooltipProcess = <function> defined @Carbonite.Quests\NxQuest.lua:5153
 FindNewQuest = <function> defined @Carbonite.Quests\NxQuest.lua:4230
 UnpackNext = <function> defined @Carbonite.Quests\NxQuest.lua:9873
 ShowUIPanel = <function> defined @Carbonite.Quests\NxQuest.lua:5679
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Carbonite.Quests\NxQuest.lua:9933
 PartyUpdateTimer = <function> defined @Carbonite.Quests\NxQuest.lua:10748
 MapChanged = <function> defined @Carbonite.Quests\NxQuest.lua:3871
 OnParty_members_changed = <function> defined @Carbonite.Quests\NxQuest.lua:10614
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Carbonite.Quests\NxQuest.lua:7832
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Carbonite.Quests\NxQuest.lua:4094
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Carbonite.Quests\NxQuest.lua:3996
 AccessAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:3316
 IconOnMouseDown = <function> defined @Carbonite.Quests\NxQuest.lua:7777
 UpdateGiverIconMenu = <function> defined @Carbonite.Quests\NxQuest.lua:9545
 WatchAtLogin = <function> defined @Carbonite.Quests\NxQuest.lua:4727
 CreateLink = <function> defined @Carbonite.Quests\NxQuest.lua:4123
 LightHeadedAttach = <function> defined @Carbonite.Quests\NxQuest.lua:5745
 RecordQuestAcceptOrFinish = <function> defined @Carbonite.Quests\NxQuest.lua:4279
 Goto = <function> defined @Carbonite.Quests\NxQuest.lua:4757
 InitQuestCharacter = <function> defined @Carbonite.Quests\NxQuest.lua:2106
 RealQEntries = 37
 AcceptQuest = <function> defined @Carbonite.Quests\NxQuest.lua:3163
 GetHistoryTimer = <function> defined @Carbonite.Quests\NxQuest.lua:4046
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Carbonite.Quests\NxQuest.lua:4542
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Ca

**Comment by IrcDirk** [comment]
```
2x Carbonite.Quests\NxQuest.lua:2939: attempt to call method 'Load0' (a nil value)
Carbonite.Quests\NxQuest.lua:2939: in function <Carbonite.Quests\NxQuest.lua:2939>

Locals:
(*temporary) = 0
(*temporary) = nil
```

**Comment by IrcDirk** [comment]
Ok, lets debug this:
- download letest version (commit 11256a0f)
- restart wow
- after logging search in chat for "[Carbonite]Debug:" and paste whole line here

**Comment by Morindra** [comment]
DEBUG: false, 2, 100, 999  --- 

I first got line 2851 error, downloaded latest version.  Now I get: 

Date: 2016-09-17 10:43:28
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 2852:
   attempt to compare number with nil
Debug:
   Carbonite.Quests\NxQuest.lua:2852: SortQuestDB()
   Carbonite.Quests\NxQuest.lua:3050:
      Carbonite.Quests\NxQuest.lua:3050
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9883
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9651
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3131
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3184
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10519
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5069
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10756
 GOpts = <table> {
 }
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10900
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3069
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4883
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 1072
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10163
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3370
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4132
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3960
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3894
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4621
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5154
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3237
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9874
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5680
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9934
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10749
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3872
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10615
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:7833
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4095
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3997
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3317
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:7778
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9546
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4728
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4124
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5746
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4280
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3247
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2106
 RealQEntries = 18
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3164
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4047
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4543
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9470
 Tick = 0
 CheckShow = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4672
 Cap
AddOns:
  Swatter, v7.1.5675 (TasmanianThylacine)
  ACP, v3.4.29 
  Altoholic, vr171
  AskMrRobot, v41
  AtlasLoot, vv8.01.02
  AucAdvanced, v7.1.5675 (TasmanianThylacine)
  AucFilterBasic, v7.1.5675 (TasmanianThylacine)
  AucFilterOutlier, v7.1.5675.5459(7.1/embedded)
  AucMatchUndercut, v7.1.5675.5585(7.1/embedded)
  AucStatHistogram, v7.1.5675 (TasmanianThylacine)
  AucStatiLevel, v7.1.5675 (TasmanianThylacine)
  AucStatPurchased, v7.1.5675 (TasmanianThylacine)
  AucStatSales, v7.1.5675.5598(7.1/embedded)
  AucStatSimple, v7.1.5675 (TasmanianThylacine)
  AucStatStdDev, v7.1.5675 (TasmanianThylacine)
  AucStatWOWEcon, v7.1.5675.5613(7.1/embedded)
  AucUtilAHWindowControl, v7.1.5675.5575(7.1/embedded)
  AucUtilAppraiser, v7.1.5675.5666(7.1/embedded)
  AucUtilAskPrice, v7.1.5675.5599(7.1/embedded)
  AucUtilAutoMagic, v7.1.5675.5587(7.1/embedded)
  AucUtilCompactUI, v7.1.5675.5629(7.1/embedded)
  AucUtilEasyBuyout, v7.1.5675.5576(7.1/embedded)
  AucUtilFixAH, v7.1.5675 (TasmanianThylacine)
  AucUtilItemSuggest, v7.1.5675.5651(7.1/embedded)
  AucUtilPriceLevel, v7.1.5675.5633(7.1/embedded)
  AucUtilScanButton, v7.1.5675.5631(7.1/embedded)
  AucUtilScanFinish, v7.1.5675.5588(7.1/embedded)
  AucUtilScanProgress, v7.1.5675.4979(7.1/embedded)
  AucUtilScanStart, v7.1.5675.5347(7.1/embedded)
  AucUtilSearchUI, v7.1.5675.5672(7.1/embedded)
  AucUtilSimpleAuction, v7.1.5675.5654(7.1/embedded)
  AucUtilVendMarkup, v7.1.5675.4828(7.1/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.7.2
  BeanCounter, v7.1.5675 (TasmanianThylacine)
  Carbonite, v7.0.3
  CarboniteInfo, v7.0.3
  CarboniteNotes, v7.0.3a
  CarboniteQuests, v7.0.3b
  CarboniteSocial, v7.0.3
  CarboniteWarehouse, v7.0.3
  CarboniteWeekly, v6.2.0
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.1.5675 (TasmanianThylacine)
  EnchantrixBarker, v7.1.5675 (TasmanianThylacine)
  GarrisonCommander, v2.14.0 6.2.4
  GarrisonCommanderBroker, v2.14.0 6.2.4
  GatherMate2, v1.37.1
  GreenWall, v1.7.3
  GTFO, v4.38.8
  GuildGreet, v7.0.0
  HandyNotes, vv1.4.9
  HandyNotesLegionTreasures, v1
  HealBot, v7.0.3.0
  HealBotTips, v6.2.3.1
  Informant, v7.1.5675 (TasmanianThylacine)
  IskarAssist, v
  LibExtraTip, v5.12.DEV.412(/embedded)
  LibSharedMedia30, v3.0-95
  MacroToolkit, vv7.0.1.1
  MacroToolkitIcons, v7.0.0.0
  MageNuggets, v5.5.4
  MageNuggetsCooldownMonitor, v1.1.2
  MageNuggetsStatMonitor, v1.2.1
  MikScrollingBattleText, v5.7.146
  NPCScan, v7.0.3.17
  OmniCC, v7.0.1
  oRA3, vv7.0.2
  Paste, v1.4.9
  Postal, vv3.5.8
  Prat30, v3.6.14      
  Prat30Libraries, v
  Quartz, v3.3.0-1-gf80a5ba
  ServerHop, v4.0.6
  Skada, v1.5-8
  SlideBar, v7.1.5675 (TasmanianThylacine)
  Stubby, v7.1.5675 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.7.8.70000
  TitanBag, v5.7.8.70000
  TitanClock, v5.7.8.70000
  TitanGold, v5.7.8.70000
  TitanLocation, v5.7.8.70000
  TitanLootType, v5.7.8.70000
  TitanPerformance, v5.7.8.70000
  TitanRepair, v5.7.8.70000
  TitanVolume, v5.7.8.70000
  TitanXP, v5.7.8.70000
  WeakAuras, v2.2.1.5
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=e3e)

**Comment by Thrumbar** [comment]
Getting
[Carbonite] DEBUG: false, 2, 97, 999
have to get to work will not get of for 9 hours if I am lucky...

**Comment by Thrumbar** [comment]
No errors so far so closing

**Comment by IrcDirk** [comment]
Ufff... need more lua experience, but i learned a lot with this issue ;)
