### ISSUE TITLE
\AddOns\Carbonite.Quests\NxQuest.lua line 7771: attempt to index local 'quest' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#515]
Svegan posted this on Wowinterface forums.  Copied and posted it here for him....  Also getting this on my paladin and Priest..

Happens on my Hunter, level 110, when I log in to game. Does not seem to happen again while playing, and even on the hunter, seems to happen only at random. running the most recent, from github.

Date: 2016-09-26 14:24:14
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7771:
attempt to index local 'quest' (a nil value)
Debug:
Carbonite.Quests\NxQuest.lua:7771: UpdateIcons()
Carbonite\NxMap.lua:4654: Update()
Carbonite\NxMap.lua:3638: OnUpdate()
Carbonite\NxMap.lua:1304: MainOnUpdate()
Carbonite\Carbonite.lua:1304: NXOnUpdate()
[string "*:OnUpdate"]:1:
[string "*:OnUpdate"]:1
Locals:
self = <table> {
IconTracking = <table> {
}
UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10144
DailyTypes = <table> {
}
IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9912
Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3134
GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3187
DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10780
MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5072
Watch = <table> {
}
PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11017
SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4159
NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11161
CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3072
GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4886
Custom = <table> {
}
TTChange = <table> {
}
TooltipProcess2 = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5181
IdToCurQ = <table> {
}
PerColors = <table> {
}
GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10424
RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3373
ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4135
CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3963
UnpackObjective = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10182
ClearCaptured = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4906
TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5157
FindNewQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4234
UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10135
ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5683
CapturePlyrData = <table> {
}
GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10195
PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11010
MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3875
OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10876
AlchemistsApprenticeData = <table> {
}
UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8076
DailyIds = <table> {
}
CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4098
QLocColors = <table> {
}
CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4000
AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3320
IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8021
UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9807
WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4731
CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4127
LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5749
RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4283
Goto = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4761
InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2113
RealQEntries = 23
AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3167
GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4050
Requirements = <table> {
}
TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4546
Cols = <table> {
}
CreateGiverIconMenu = <function> defined @Interface\AddOn
AddOns:
Swatter, v7.1.5675 (TasmanianThylacine)
WowheadLooter, v60014
AucAdvanced, v7.1.5675 (TasmanianThylacine)
AucFilterBasic, v7.1.5675 (TasmanianThylacine)
AucFilterOutlier, v7.1.5675.5459(7.1/embedded)
AucMatchUndercut, v7.1.5675.5585(7.1/embedded)
AucStatHistogram, v7.1.5675 (TasmanianThylacine)
AucStatiLevel, v7.1.5675 (TasmanianThylacine)
AucStatPurchased, v7.1.5675 (TasmanianThylacine)
AucStatSales, v7.1.5675.5598(7.1/embedded)
AucStatSimple, v7.1.5675 (TasmanianThylacine)
AucStatStdDev, v7.1.5675 (TasmanianThylacine)
AucStatWOWEcon, v7.1.5675.5613(7.1/embedded)
AucUtilAHWindowControl, v7.1.5675.5575(7.1/embedded)
AucUtilAppraiser, v7.1.5675.5666(7.1/embedded)
AucUtilAskPrice, v7.1.5675.5599(7.1/embedded)
AucUtilAutoMagic, v7.1.5675.5587(7.1/embedded)
AucUtilCompactUI, v7.1.5675.5629(7.1/embedded)
AucUtilEasyBuyout, v7.1.5675.5576(7.1/embedded)
AucUtilFixAH, v7.1.5675 (TasmanianThylacine)
AucUtilItemSuggest, v7.1.5675.5651(7.1/embedded)
AucUtilPriceLevel, v7.1.5675.5633(7.1/embedded)
AucUtilScanButton, v7.1.5675.5631(7.1/embedded)
AucUtilScanFinish, v7.1.5675.5588(7.1/embedded)
AucUtilScanProgress, v7.1.5675.4979(7.1/embedded)
AucUtilScanStart, v7.1.5675.5347(7.1/embedded)
AucUtilSearchUI, v7.1.5675.5672(7.1/embedded)
AucUtilSimpleAuction, v7.1.5675.5654(7.1/embedded)
AucUtilVendMarkup, v7.1.5675.4828(7.1/embedded)
Babylonian, v5.1.DEV.332(/embedded)
BeanCounter, v7.1.5675 (TasmanianThylacine)
BigWigs, vv12.2
BloodShieldTracker, v7.0.11
Boomkinator, vv3.4.7
Carbonite, v7.0.3
CarboniteNotes, v7.0.3a
CarboniteQuests, v7.0.3b
CarboniteWarehouse, v7.0.3
CarboniteWeekly, v6.2.0
Configator, v5.1.DEV.406(/embedded)
DebugLib, v5.1.DEV.337(/embedded)
ElvUI, v10.21
Enchantrix, v7.1.5675 (TasmanianThylacine)
EnchantrixBarker, v7.1.5675 (TasmanianThylacine)
GarrisonCommanderBroker, v2.14.0 6.2.4
GoldBanker, v1.3
Healium, v
Informant, v7.1.5675 (TasmanianThylacine)
LDBPitchSpeed, v
LibExtraTip, v5.12.DEV.412(/embedded)
PetBattleTeams, v3.3.0
Postal, vv3.5.8
ProspectBarLives, v2.3
RepSwitch, v7.0.3.8
SilverDragon, vv3.2.7-3-ge3cae59
Skada, v1.5-11
SlideBar, v7.1.5675 (TasmanianThylacine)
Stubby, v7.1.5675 (TasmanianThylacine)
TipHelper, v5.12.DEV.405(/embedded)
Titan, v5.7.8.70000
TitanBag, v5.7.8.70000
TitanClock, v5.7.8.70000
TitanCurrency, v7.0.3a
TitanGold, v5.7.8.70000
TitanLocation, v5.7.8.70000
TitanLootType, v5.7.8.70000
TitanPerformance, v5.7.8.70000
TitanRepair, v5.7.8.70000
TitanVolume, v5.7.8.70000
TitanXP, v5.7.8.70000
WoWTokenWatch, v1.0.3
BlizRuntimeLib_enUS v7.0.3.70000 <none>
(ck=a6e)

**Comment by IrcDirk** [comment]
Try latest commit, dont know if it helps, cant symulate this on any my chars.

**Comment by IrcDirk** [comment]
Fixed, try latest commit.

**Comment by Thrumbar** [comment]
Will test it after I get off work tonight at midnight...

Thrumbar

**Comment by SteveEbey73742** [comment]
on my hunter, logging between all 15 toons, never had any issues, I would consider it fixed.

**Comment by Thrumbar** [comment]
No errors with the latest release...  Closing...
