### ISSUE TITLE
Extreme fps issues with 1080 gtx

### ISSUE THREAD

**Issue by jcmgamer** [mikepauer/Carbonite#516]
I'm not 100% sure if it's on your guys end or on blizzards end, but having carbonite enabled is dropping my fps to 15 and disabled is shooting me up to 100.  My guildmate was saying that it has something to do with queries to the server.

No errors popping up that would indicate what's going on.

**Comment by IrcDirk** [comment]
Do u use latest version from github? If not download and check again.

**Comment by DaveJ61** [comment]
I had this problem with my Nvidia 760GTX and I thought my card might be playing up, so I went and bought a 1060GTX (I wanted a new one anyway) but it was doing the same on that as well. Frame rates dropping to 16 for several minutes and then would come back to 50 or so. Disabling Carbonite and I would get 90+.The latest Carbonite was always in use. The machine runs flight simulator without a problem and that is far more intensive. 
I'm afraid a gave up on Carbonite a few weeks ago but just happened to see this email come in..

**Comment by IrcDirk** [comment]
Try latest version there was fix for fps, dont know if that help, let me know.

**Comment by jcmgamer** [comment]
I just downloaded the latest and it seems to have fixed the fps problem, but now i'm getting the following error with just carbonite and elvui enabled:

Date: 2016-09-27 10:54:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 7531:
   attempt to index local 'quest' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:7531: UpdateIcons()
   Carbonite\NxMap.lua:4654: Update()
   Carbonite\NxMap.lua:3638:
      Carbonite\NxMap.lua:3555
Locals:
self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10136
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9904
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3134
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3187
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10772
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5072
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11009
 SortQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4159
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11153
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3072
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4886
 Custom = <table> {
 }
 TTChange = <table> {
 }
 TooltipProcess2 = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5181
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10416
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3373
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4135
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3963
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10174
 ClearCaptured = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4906
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5157
 FindNewQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4234
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10127
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5683
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10187
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11002
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3875
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10868
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8076
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4098
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4000
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3320
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8021
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9799
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4731
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4127
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5749
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4283
 Goto = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4761
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2113
 RealQEntries = 23
 AcceptQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3167
 GetHistoryTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4050
 Requirements = <table> {
 }
 TellPartyOfChanges = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4546
 Cols = <table> {
 }
 CreateGiverIconMenu = <function> defined @Interface\AddOn
AddOns:
  Swatter, v7.0.1 (<%codename%>)
  Ace3, v
  ACP, v3.4.29 
  AddOnSkins, v3.39
  Babylonian, v5.1.DEV.332(/embedded)
  BlockChinese, v1.3
  Carbonite, v7.0.3
  CarboniteInfo, v7.0.3
  CarboniteNotes, v7.0.3a
  CarboniteQuests, v7.0.3b
  CarboniteSocial, v7.0.3
  CarboniteWarehouse, v7.0.3
  CarboniteWeekly, v6.2.0
  Configator, v5.1.DEV.406(/embedded)
  ElvUI, v10.21
  Gatherer, v7.0.1
  LibSharedMedia30, v3.0-95
  SlideBar, v7.0.1 (<%codename%>)
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=1ed)

**Comment by IrcDirk** [comment]
Hmm... i have ElvUI and dont get this error, can u disable all other addons and  leave just Carbonite (plus Carb Modules) and check again? Which faction u are?

**Comment by IrcDirk** [comment]
Fixed, try latest commit.

**Comment by jcmgamer** [comment]
It was only once I turned elvui back on.  Works flawlessly with the latest commit.  Many thanks.
