### ISSUE TITLE
Quest Log Details not in sync

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#522]
After doing several world quests, I notice that the quest list details pane does not load the proper quests, and I have to /reload to get it to sync.  I will look into the code, to see if something jumps out at me, as being out of place. Any suggestions from others here, would be appreciated also.

**Comment by IrcDirk** [comment]
U need to be more precised... What quests are not in the list? World Quests or others? Are they not in watcher frame or are they not on quest list (L key)?

**Comment by SteveEbey73742** [comment]
sorry. Current quest list, shows the title and headers on left side, details on right. as set in carb options.  quest title and details are being randomly ordered, after completing world quests.  I have to reload to get details and titles to match. I will log in later today, run some world quests, then post a screen shot, after it happens.

**Comment by IrcDirk** [comment]
Ok, can confirm that. World quests, those emmisary, breaks list, ill try to fix this.

**Comment by IrcDirk** [comment]
Fixed but need confirmation.

**Comment by IrcDirk** [comment]
Have to find other way to fix this ;)

**Comment by SteveEbey73742** [comment]
Ran several toons, at 110 and below, just to make sure, seems to be fixed.

**Comment by IrcDirk** [comment]
Thanks to your fix my fix doesnt make "run to long..." error ;)

**Comment by SteveEbey73742** [comment]
@IrcDirk, thank you.  I am learning more and more about lua. very similar to C and C++ that i coded in years ago, as part of drug and alcohol research team.  Those were fun times, paying college kids to get drunk, testing reaction and performance times, in custom video games.
