### ISSUE TITLE
Script ran too long error

### ISSUE THREAD

**Issue by KrysEmlyn** [mikepauer/Carbonite#537]
With version 3f38a71 of Carbonite, I'm getting constant FPS drops when World Quests are active for characters and the following error occurs during combat at this time while doing World Quests:

Carbonite\NxMap.lua:5004: script ran too long
Carbonite\NxMap.lua:5004: in function `?'
Carbonite\NxMap.lua:4843: in function `Update'
Carbonite\NxMap.lua:3677: in function <Carbonite\NxMap.lua:3594>

Locals

The error repeats each time I engage in combat with an enemy (each kill increments the occurrence of the error). This did not happen until I updated Carbonite today.

**Comment by IrcDirk** [comment]
Fixed.
