### ISSUE TITLE
Quest turn-in NPC's incorrect

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#538]
I have noticed that the quest turn-in NPC's are incorrect. The arrow is directing to a different NPC. So, I re-downloaded carbonite just now but the problem is still apparent. I did notice a few quests the other day when I last played but thought nothing of it. I've just realised I took a snip of the last two but I unfortunately cut off the arrow....
Pictures speak louder than words...
![wrongnpc](https://cloud.githubusercontent.com/assets/1816367/19102376/c3deabb8-8ac7-11e6-9acd-37e1742f580b.JPG)
![wrongnpc2](https://cloud.githubusercontent.com/assets/1816367/19102383/cb743208-8ac7-11e6-9441-abe05ad19505.JPG)
![wrongnpc3](https://cloud.githubusercontent.com/assets/1816367/19102392/d469c292-8ac7-11e6-904a-6c0de4570a06.JPG)
![wrongnpc4](https://cloud.githubusercontent.com/assets/1816367/19102396/dae3bef2-8ac7-11e6-9723-cfd88b9967cf.JPG)

**Comment by IrcDirk** [comment]
Thats weird couse those cordinates of Enders are ok... so arrow should be ok only the name might by broken... Ill have to redo NPCs list, maybe this will fix this.

**Comment by IrcDirk** [comment]
Ok updated. Lets see if this still happens...

**Comment by SteveEbey73742** [comment]
I logged in 05:30 local time, ran world quests, and regular, before rolling restarts. on for an hour and a half all over broken isles, and return to dalaran. no issues at all, I consider this fixed.  Please close.

**Comment by IrcDirk** [comment]
This should be checked on quests before 90lvl like WOTLK quests.

**Comment by IrcDirk** [comment]
Checked Solazar Basin quest maybe not the same as @DaveJ61 but in the same place and all is good. Closing. Reopen if there were some problem
