### ISSUE TITLE
As of this build No World Quest Tooltips

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#540]
Just noticed, and I apologize for not checking this morning, no tooltips on map for world quests.

**Comment by IrcDirk** [comment]
On maximized works no problem, maybe on minimized it doesnt work?

**Comment by SteveEbey73742** [comment]
actuallly, on mini map, it showed up once, then used map maximized, and no tips.  I will post screen shot later.  Need to go fix a computer for a person.

**Comment by IrcDirk** [comment]
Ok u got "Close map instead of minimize"... thats the case i didnt took into consideration... will make fix for this.

**Comment by SteveEbey73742** [comment]
updated my fork, installing. will test and report back.

**Comment by samyonair** [comment]
Just tested it works, minor Issue only Yesterday one Time I used m-Key to maximize but Map do not maximize instead show buttons for the Daily Worldquest (Do 4 Quests for faction) and another strokes on Key only activated / deactivated it, after Closening Map it was gone and function was back, cannot reproduce why.

Greetings

**Comment by IrcDirk** [comment]
Yes @samyonair i got this sometimes too... dont know why, trying to debug with no luck ;)

**Comment by Morindra** [comment]
alt-L map, click back to look at all of broken isles, click specific area to see world quests.  The information is showing up BEHIND the quest window.

**Comment by IrcDirk** [comment]
using M key then Alt-M moves all things were there should be, need to fix those other cases.

**Comment by Morindra** [comment]
My issue of it popping up behind the map is resolved.
