### ISSUE TITLE
Cancelling Abandon Quest Removes Watch

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#541]
Just discovered that if you right click and select abandon quest, and then select 'cancel' the quest is  removed from the log (the on screen list). It never used to be like this. In fact it is removed from the log as soon as you select it to abandon. Before if you selected cancel, it used to put it back..

Something else more serious I just discovered was that I just selected to abandon 'Leave Our Mark' but up popped the the dialog to abandon a different quest 'Deciphering The Journal'.
Re-enabling all quests as watched seems to correct this problem.
 
![abandon1](https://cloud.githubusercontent.com/assets/1816367/19141856/d6726df4-8b90-11e6-963b-a93b162a3b40.JPG)

**Comment by IrcDirk** [comment]
The problem is that clicking abandon removes quest even if u cancel. But if u cancel the list is not updated. Fixing for this should be easy.

**Comment by DaveJ61** [comment]
Yes. Seems to be fixed. Thank you.
