### ISSUE TITLE
Public Release?

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#542]
With all that has been done, and the lack of errors for the last several days, would a public release be considered?  I think the program is stable enough, and it will give us a chance to see if other addons people use have compatibility problems also.

**Comment by mikepauer** [comment]
I'll push carbonite, carbonite quests, and carbonite warehouse ... as far as I know those are the only 3 needing updates, if anything was done on the others let me know.

**Comment by SteveEbey73742** [comment]
Thank you.
