### ISSUE TITLE
Carbonite Quests freezes during "Rites of the Talonpriests"

### ISSUE THREAD

**Issue by kived** [mikepauer/Carbonite#545]
As soon as I accepted the quest [Rites of the Talonpriests](http://wow.gamepedia.com/Quest:Rites_of_the_Talonpriests), WoW froze (not responding). After force quitting and restarting, it froze again. It only started working again once I disabled the Carbonite Quests module (using latest from GitHub). The module continued to freeze WoW until I had completed the quest entirely and turned it in. Now the Quests module is working again, though I've lost all my quest history in Spires of Arak (at least - I haven't gone to another zone yet to see if it affected all history or not).

Wish I could give more info, but I couldn't find any logs or anything related to this.

**Comment by IrcDirk** [comment]
Can any one confirm this?

**Comment by dacandicane** [comment]
I can verify this, my husband and I are both currently having this issue, freezing as soon as i accept the quest Rites of the Talonpriests

**Comment by IrcDirk** [comment]
Ok thanks... ill try to debug this on my alt.

**Comment by IrcDirk** [comment]
Another fix made for this. Now this should not hang wow. Please report back.
