### ISSUE TITLE
Archeology sites do not show in carbonite maps

### ISSUE THREAD

**Issue by Kabulla** [mikepauer/Carbonite#546]
They do, on the standard maps, using alt-m...

**Comment by SteveEbey73742** [comment]
my carb shows the blobs just fine, I would be happy to compare option settings. are you running the most recent release, either from here, or on curse or wowi?

**Comment by IrcDirk** [comment]
Yep blobs shows, but not arch icons like on blizz Map.

**Comment by Kabulla** [comment]
I am always running the latest release, updating every day, yes.
Which settings do you want to compare?
Again... I am talking about the "shovel-signs" on continent level. The actual digging sites, inside the local maps, are showing just fine...

**Comment by IrcDirk** [comment]
Those shovel icons doesnt show on map, @Kabulla is right.

**Comment by Kabulla** [comment]
I won't be back to my private computer until the 24....
So i also won't be able to contribute, until then...

**Comment by Kabulla** [comment]
I played for the last two days with no change (of course there was nothing announced so nothing to expect)...
For the next couple of days I will again be on trains and plains throughout Europe, back to the computer on the 03rd...
Just to let you know as to when I can react...
Thx for all your efforts, it is well appreciated!

**Comment by IrcDirk** [comment]
Ok, now in 7.1 showel icons are back on map... maybe it was blizz bug ;)

**Comment by Kabulla** [comment]
Ok, will be delighted after my return... ;-)
