### ISSUE TITLE
Quest turn-in NPC locations are incorrect

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#549]
I have noticed that quite a few quest NPC's locations are wrong. Thisalee Crow in Mount Hyjal being one of them on a number of quests. This has been occurring for a few days now and I have downloaded the latest version but it is still apparent.
This isn't the only NPC that this happens to but if needed I will post some more examples as I come across them. I know these quests very well but if someone doesn't, then they will have a hard time or most likely refer to the blizzard quest window.

![wrongplace](https://cloud.githubusercontent.com/assets/1816367/19296192/b3490f68-9031-11e6-8ea3-0f580443cd95.JPG)
![wrongplace2](https://cloud.githubusercontent.com/assets/1816367/19296205/cf33f152-9031-11e6-8b96-c6e03f86cffa.JPG)

![nope1](https://cloud.githubusercontent.com/assets/1816367/19296213/e6aaf9a2-9031-11e6-8aed-fb7f3b4dc878.JPG)

**Comment by IrcDirk** [comment]
Post name of Quest and wrong NPC name.

**Comment by DaveJ61** [comment]
They are displayed in the images

**Comment by IrcDirk** [comment]
Next time write them, please, that helps to speed up the process of rechecking.

**Comment by IrcDirk** [comment]
I have checked this first Quest and this is WOWHEADs problem, they have the wrong location and since we scrapped data from them thats why this location is wrong.

http://www.wowhead.com/quest=25740/fact-finding-mission
