### ISSUE TITLE
Quests Not In Database

### ISSUE THREAD

**Issue by DaveJ61** [mikepauer/Carbonite#552]
Here's an interesting bug which I had also noticed before quite a few days ago. I do have the latest version of Carbonite.
Yesterday evening, I picked up some quests in Deepholm, and as you can see in the first screengrab, they were not in the database. The quests were Gunship Down and Flyover (Part 1 of 2).

However, I pressed L to get the quest details dialog, and "Hey Presto!" they suddenly changed to display correctly as in the second screengrab.

![notindatabase](https://cloud.githubusercontent.com/assets/1816367/19415389/dce5dd8c-9366-11e6-990d-c2dd38ac88ef.JPG)

![notindatabase2](https://cloud.githubusercontent.com/assets/1816367/19415391/e4e200d8-9366-11e6-80bf-ece2233a9aba.JPG)

This second example quest (Fight fire and water and air with...), is not quite the same as it does not correct itself by pressing L. I also know that this and other similar multi-part quests have been in existence with this issue for a long time, way before the expansion and before Cataclysm.
These types of quests can be collected in any order, obviously apart from ultimate part which normally involves killing a mob (in this case Haethen Kaul), or combining mats to make something... or even doing something else. They also almost always have one part which is known as in the first picture below. Also In this case, you can clearly see in the last picture below, that I have collected all the wards but it still doesn't know the location of Haethen Kaul.
I think that the locations of all of these parts should be displayed as the default Blizzard quest tracker does.

![notindatabase3](https://cloud.githubusercontent.com/assets/1816367/19415562/ccdace34-936b-11e6-8164-1d43e9a4aca7.JPG)

![notindatabase4](https://cloud.githubusercontent.com/assets/1816367/19415564/d8f45e24-936b-11e6-9ec1-ada415df353f.JPG)

![notindatabase5](https://cloud.githubusercontent.com/assets/1816367/19415566/e2716b54-936b-11e6-8257-9bef1f9cf632.JPG)

![notindatabase6](https://cloud.githubusercontent.com/assets/1816367/19415571/e9d7c6ae-936b-11e6-8cd2-df2f60fe05ab.JPG)

**Comment by IrcDirk** [comment]
Im trying to explain this also in WoWInterface thread: http://www.wowinterface.com/forums/showthread.php?p=319923

See this quest against wowhead data:

http://www.wowhead.com/quest=26245/gunship-down

As u can see there are no objectives marked on the map so there are no coords for them, so Carbonite doesnt have those objctives in database and doesnt know where to point them.

BUT Carbonites tries to find out them by using workaround functions, sometimes it works sometimes it doesnt. It works 99% when u are accepting this quest and u are in the zone of this quest. But if u have it in the list and u reload or relog u may does not have those objectives becouse they are not saved.

**Comment by DaveJ61** [comment]
I understand that, however, in the first example above, the quest became known to Carbonite after I pressed L to get the quest details dialogue. So I think that these objectives were already known by carbonite and my act of pressing L just caused a refresh of the data.

I also understand the explanation on wowinterface, but personally I think the poster is correct. There are quests (not just high level ones, but some old low level ones too) which carbonite had no problems with before, but it does now. I seem to remember a couple of weeks ago reading a post and that one of your devs said that they were going scrap the quest data and reimport all from wowhead. This would tie in with what is being experienced now.

I thought there was a way for people to submit their quest data. If there isn't then maybe it would be a good idea to have a mechanism to do this.

**Comment by IrcDirk** [comment]
Yes all data for quest was rescrapped from wowhead and as we know this database isnt always 100% accurate, so they may be quests that was in old database and now they are without objectives becouse they are not in wowhead.

In spare time ill rewrite my script to detect if there are no objectives in wowhead leave those old from old quest database. BUT THATS ONLY FOR quests < 100 level. There were no quests for 110 in database so this data was not overwritten.

**Comment by DaveJ61** [comment]
I had the same again in Uldum with quest called Traitors!, where it appeared as 'not in the database' but by pressing L, it seemed to refresh the data and then became available.
 
Here is another multi-part quest (Impending Retribution) where all parts were 'objective not in the database', and yet by pressing L, they all became known. This, to me, is a bug.

![uldum1](https://cloud.githubusercontent.com/assets/1816367/19422382/cdb9e434-940b-11e6-887a-43800cfeac76.JPG)

![uldum2](https://cloud.githubusercontent.com/assets/1816367/19422385/d6ab933a-940b-11e6-940a-56b3fedf3a31.JPG)

**Comment by IrcDirk** [comment]
It seems accepting quest doesnt trigger workaround functions, but opening Quest List does... i have to check it my self to debug this behavior.

**Comment by DaveJ61** [comment]
Here's another one which I just got ' The Thrill Of Discovery', which I know did work before. 

![thethrillofdiscovery-unknown](https://cloud.githubusercontent.com/assets/1816367/19426938/5377d83e-9438-11e6-86a1-bdcc8bbca5d0.JPG)

Pressing L...

![thethrillofdiscovery-known](https://cloud.githubusercontent.com/assets/1816367/19426950/6c74a740-9438-11e6-8dd0-6fd7061321cd.JPG)

---------------------------------------------------

This next one appears not to be in the database at all. At the end, the quest cannot be completed by Carbonite but you have to resort to the blizzard Alt-L to complete it. The quest is 'Do the world a favour'.

![dotheworldafavour](https://cloud.githubusercontent.com/assets/1816367/19427027/16da51da-9439-11e6-96cf-eec99c03cabc.JPG)

![dtwaf-cannotcomplete](https://cloud.githubusercontent.com/assets/1816367/19427031/209010ac-9439-11e6-81c0-c94bf649716c.JPG)

![dtwaf-cancomplete](https://cloud.githubusercontent.com/assets/1816367/19427036/28d57ff4-9439-11e6-92b7-8e34c880a4d2.JPG)

I think you have enough to go on now but if not, I'll post some more as I come across them.

**Comment by IrcDirk** [comment]
Thanks for those Screenshot they helped. 

Made fix. Might lag a little bit on first WoW login but it will discover those quests that are not in Carbonite Quests Database.

**Comment by DaveJ61** [comment]
I confirm that this is fixed for me...

**Comment by IrcDirk** [comment]
Works for me too, closing. Reopen when needed.
