### ISSUE TITLE
Icon not showing in quest window for Artifact Resto Druid

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#555]
The icon to use the Artifact in the Druid quest near the end of the event does not appear in the quest window..

With Carbonite as of commit 624058ac12490c88583abc5126d9a4330ad34fe4
https://1drv.ms/i/s!Ai8SfAzON-JQgYE5T58Ws6RuCLLvkQ

With default Warcraft quest
https://1drv.ms/i/s!Ai8SfAzON-JQgYE4KIBEunw3aRUBOQ

Note the icon is not apparent and had to disable Carbonite Quest to do the quest.. The item is G'Hanir, the Mother Tree [http://www.wowhead.com/item=128306/ghanir-the-mother-tree&bonus=0](url).

Thrumbar

**Comment by IrcDirk** [comment]
This issue is new? Or this was working fine before today commits?

**Comment by Thrumbar** [comment]
Have other druids, so will try with carbonite only installed and recheck...

**Comment by Thrumbar** [comment]
Closing this until I can get to my other druid to recheck this.  May be a  non carbonite issue..
