### ISSUE TITLE
Error On Login on PTR

### ISSUE THREAD

**Issue by samyonair** [mikepauer/Carbonite#556]
Message: Interface\AddOns\Carbonite\NxMap.lua:5189: attempt to compare nil with number
Time: 10/20/16 09:32:05
Count: 97
Stack: Interface\AddOns\Carbonite\NxMap.lua:5189: in function `?'
Interface\AddOns\Carbonite\NxMap.lua:4733: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3679: in function <Interface\AddOns\Carbonite\NxMap.lua:3596>

Locals: self = <table> {
 MiniBlks = 6
 IconScale = 3
 Scale = 1.1754777262041
 MenuIShowWorld = <table> {
 }
 TextFrm = <unnamed> {
 }
 TransMenu = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0.4
 PlyrY = -768.61823681501
 ArrowPulse = 1
 Targets = <table> {
 }
 ScaleDrawW = 0.85071794871795
 MenuIShowMine = <table> {
 }
 InstanceId = false
 MMScalesC = <table> {
 }
 CurMapBG = false
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 132.69502004488
 WorldHotspots = <table> {
 }
 Cont = 8
 Zone = 1014
 Size1 = 1.0546874744614
 PlyrRZY = 36.888563632965
 Level = 20
 MapId = 1014
 ShowUnexplored = false
 EffScale = 0.71111112833023
 DotZoneScale = 1
 MMOwn = false
 TextFStrs = <table> {
 }
 Arch = <unnamed> {
 }
 Scrolling = false
 LastDungeonLevel = 10
 PIconMenu = <table> {
 }
 W = 150
 WorldAlpha = 0
 Menu = <table> {
 }
 StartupShown = true
 LocTipFrm = NxMapTip {
 }
 CurWorldUpdateMapId = 1014
 PlyrSpeedY = -768.61823681501
 MMOwnedFrms = <table> {
 }
 StepTime = 0
 BackgndAlphaFade = 0.4
 PlyrFrm = <unnamed> {
 }
 MMChkDelay = 28
 IconWQFrms = <table> {
 }
 MoveLastX = 2066.5520805341
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MapPosYDraw = -768.61823681501
 MMScales = <table> {
 }
 ArchAlpha = 0.3
 MapPosY = -768.61823681501
 ScaleDraw = 1.1754777262041
 MiniFrms = <table> {
 }
 MapPosXDraw = 2066.5520805341
 InCombat = false
 MapScale = 0.11731314632776
 MapIndex = 1
 Win = <table> {
 }
 PadX = 0
 PlyrSpeedX = 2066.5520805341
 RealScale = 1.1754777262041
 Data = <table> {
 }
 TextScFrm = <unnamed> {
 }
 BGIncNum = 0
 MenuIMonitorZone = <table> {
 }
 MapW = 350.79998779297
 DebugAdjustScale = 0.1
 MMGathererUpdateDelay = 1
 MenuIShowTimber = <table> {
 }
 PlyrDir = 132.69502004488
 LClickTime = 0
 MouseEnabled = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 ButAutoScaleOn = <table> {
 }
 PlyrSpeedCalcTime = 512321.738
 MapH = 298.00003051758
 PlyrSpeed = 0
 GIconMenuIFindNote = <table> {
 }
 TileFrms = <table> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 ContFrms = <table> {
 }
 BGIconMenu = <table> {
 }
 DotRaidScale = 1
 Tracking = <table> {
 }
 GIconMenu = <table> {
 }
 BackgndAlphaTarget = 0.4
 TargetNextUniqueId = 1
 ViewSavedData = <table> {
 }
 MoveDir = 180
 BGGrowBars = true
 MapsDrawnFade = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 ArrowScroll = 0
 MapPosX = 2066.5520805341
 H = 141
 ScaleW = 0.85071794871795
 BackgndAlphaFull = 1
 CurOpts = <table> {
 }
 IconNIFrms = <table> {
 }
 TitleH = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -768.61823681501
 MenuIShowHerb = <table> {
 }
 IconFrms = <table> {
 }
 DotPartyScale = 1
 PlyrRZX = 52.153658866882
 KillShow = false
 QuestAlpha = 0.3
 NeedWorldUpdate = true
 MapsDrawnOrder = <table> {
 }
 UpdateTargetDelay = 0
 Frm = <unnamed> {
 }
 Tick = 97
 DotPalScale = 1
 CurWorldUpdateOverlayNum = 1
 PlyrX = 2066.5520805341
}
plX = 2066.5520805341
plY = -768.61823681501
alt = false
redGlow = 0.52399999991059
members = 4
unitName = "party"
raid = nil
pals = <table> {
}
palName = nil
palDist = 99999999
palX = nil
palY = nil
combatName = nil
combatUnit = nil
combatHealth = nil
combatDist = 99999999
combatX = nil
combatY = nil
palsInfo = <table> {
}
(for index) = 1
(for limit) = 4
(for step) = 1
i = 1
unit = "party1"
name = nil
unitRealm = nil
mapId = 1014
pX = nil
pY = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temp

After Loading Error Counter Stopps

**Comment by IrcDirk** [comment]
Which zone?

**Comment by samyonair** [comment]
Login on PTR in Dalaran no Group / Raid Opend

**Comment by IrcDirk** [comment]
Wierd...

**Comment by IrcDirk** [comment]
Ok thats changes in 7.1 API ... shit...

**Comment by samyonair** [comment]
I have read about it because of DBM Information on Range things thats why I wanted to test Carbonite and this happens

**Comment by IrcDirk** [comment]
Yep... many functions will not work in Instances (like cities etc), Dungeons and Raids :(
