### ISSUE TITLE
Error after Login on PTR 

### ISSUE THREAD

**Issue by samyonair** [mikepauer/Carbonite#557]
Message: Interface\AddOns\Carbonite.Quests\NxQuest.lua:7862: attempt to call global 'QuestMapFrame_IsQuestWorldQuest' (a nil value)
Time: 10/20/16 09:35:48
Count: 3453
Stack: Interface\AddOns\Carbonite.Quests\NxQuest.lua:7862: in function `UpdateIcons'
Interface\AddOns\Carbonite\NxMap.lua:4695: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3679: in function <Interface\AddOns\Carbonite\NxMap.lua:3596>

Locals: self = <table> {
 IconTracking = <table> {
 }
 UnpackCategory = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10254
 DailyTypes = <table> {
 }
 IsTargeted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10022
 Menu_OnTrack = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3137
 GetQuestReward = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3190
 DecodeComRcv = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10890
 MsgNotInDB = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5096
 Watch = <table> {
 }
 PartyStartSend = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11127
 GOpts = <table> {
 }
 NullQuest = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11271
 CheckQuestSE = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3075
 GetFromPlyr = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4910
 Custom = <table> {
 }
 TTChange = <table> {
 }
 OldMap = 1014
 IdToCurQ = <table> {
 }
 PerColors = <table> {
 }
 GetClosestObjectivePos = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10534
 RecordQuestsLog = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3376
 ExtractTitle = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4144
 CalcCNumMax = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3972
 ScanBlizzQuestDataZone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3900
 FindCur = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4633
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5181
 SelectBlizz = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3243
 UnpackNext = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10245
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5709
 CapturePlyrData = <table> {
 }
 GetObjectiveType = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10305
 PartyUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:11120
 MapChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3878
 OnParty_members_changed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:10986
 AlchemistsApprenticeData = <table> {
 }
 UpdateQuestDetails = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8178
 DailyIds = <table> {
 }
 CalcDesc = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4107
 QLocColors = <table> {
 }
 CalcPreviousDone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4009
 AccessAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3323
 IconOnMouseDown = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8123
 UpdateGiverIconMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:9917
 WatchAtLogin = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4740
 CreateLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4136
 LightHeadedAttach = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5776
 RecordQuestAcceptOrFinish = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:4292
 ExpandQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:3253
 InitQuestCharacter = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:2113
 RealQ

Counter doesn't Stop

**Comment by IrcDirk** [comment]
Same here... i think u are in new zone that is not in Carbonite?

**Comment by samyonair** [comment]
I'M on Broken Isles Dalaran changed to Aszuna Counter Stops only if ALT-M is Pressed

**Comment by IrcDirk** [comment]
Read what i wrote in the other issue...
