### ISSUE TITLE
Dungeon Icons not showing on Map

### ISSUE THREAD

**Issue by yesCurtis** [mikepauer/Carbonite#559]
When I used to use Carbonite, it used to show me the instance locations on the map, is this not a feature anymore, if it's not could it be added in the future? I miss the green and black dungeon icon, I always forget where the entrances are to some Legion Dungeons and even older raids.

**Comment by IrcDirk** [comment]
Latest commit fixes that. Download newest version from here.

**Comment by yesCurtis** [comment]
Downloaded about 45 minutes ago, there isn't a new one in the past 45 minutes was there? :)

**Comment by yesCurtis** [comment]
http://i.imgur.com/45AtUTV.jpg don't know if you've misunderstood my issue. Or if something has gone wrong in my installation, I reinstalled latest version to see if I mis-installed but issue is still there. entrances for all raids and dungeons not drawing.

**Comment by IrcDirk** [comment]
U need to zoom in more to see them... i dont know your setting of "POI icons at scale.."

http://i.imgur.com/c5bnLcX.png

**Comment by yesCurtis** [comment]
Oh they're there! I made POI lowest now. Is there a way to scale them on the map to make them bigger?

**Comment by IrcDirk** [comment]
Play with this setting:

![img](http://i.imgur.com/NvagtA7.png)
