### ISSUE TITLE
/way points

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite#56]
I use tomtom with lightheaded as well as carbonite, I also like to just put in way points into Carbonite but when tomtom is on it sorta takes all /way commands. is there a way to add a /cway to carbonite that just duplicates the /way function but only adds it to carbonite so the carbonite arrow is the one pointing the way?

**Comment by mikepauer** [comment]
already exists, /carb goto .... yeah it's a lot longer, but it works :) I'll consider adding /cway as an alias for /way, Tomtom made the coding decision to stop / kill anything else receiving a /way command which is why it stopped working with legion's launch.

**Comment by reflexwolf** [comment]
thank you ! I'll set up a macro for now but that will help though /cway
makes a lot of since :)

**Comment by mikepauer** [comment]
So I added it as /cway in my local copy... however it appears Tomtom also has a /cway for telling it's system to point to the closest point.

I can either go /caway or /cbway ... or another letter that works instead of /cway.

**Comment by reflexwolf** [comment]
they do make life hard :) any shortcut works for me :)

**Comment by IrcDirk** [comment]
Closing, as @mikepauer added cway macro. So this is solved.
