### ISSUE TITLE
Turn in Emissary Quest Bug

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#561]
Date: 2016-10-25 16:39:17
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 6693:
   attempt to index local 'cur' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:6693: LogUpdate()
   Carbonite.Quests\NxQuest.lua:6564: Refresh()
   Carbonite.Quests\NxQuest.lua:6648: ?()
   Carbonite\NxUI.lua:2888:
      Carbonite\NxUI.lua:2879
Locals:
self = <table> {
 UpdateMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5657
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6049
 MakeDescLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6515
 TabSelected = 1
 Menu_OnTrackNone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6296
 Menu_OnWatchAll = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6142
 FilterOnEditFocusLost = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5961
 Menu_OnHighPri = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6040
 DetailsFrm = NxQuestD {
 }
 Menu_OnShowAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6063
 Menu_OnShowFinished = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6083
 Menu_OnGoto = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6021
 MenuIShare = <table> {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnShowParty = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6093
 Menu_OnCompleted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6098
 Select = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5881
 Menu = <table> {
 }
 Open = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5344
 OnTabBar = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5996
 AttachFrames = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5633
 List = <table> {
 }
 FilterOnTextChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5971
 Filters = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5946
 FilterDesc = "Search: [click]"
 FilterDescEsc = "Search: %[click%]"
 FilterFrm = NxQuestFilter {
 }
 LogUpdate = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6662
 MenuItems1 = <table> {
 }
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6199
 OnDetailsSetSize = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8142
 Menu_OnAbandon = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6263
 Menu_OnHistoryRemoveAll = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6121
 ToggleWatch = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6460
 Menu_OnShowOnlyDailies = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6088
 DetailsSetWidth = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8164
 Menu_OnShowAllZones = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6078
 Opened = true
 Update = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6715
 CheckShow = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:7430
 SendQuestInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6176
 FilterOnEscapePressed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5985
 Menu_OnShare = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6247
 Menu_OnShowHighLevel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6073
 OnQuestUpdate = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6571
 Menu_OnSortWatched = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6137
 Refresh = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6561
 GetCurSelected = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5907
 FilterOnEnterPressed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5980
 OnListEvent = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6305
 Menu_OnSendQInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6166
 Menu_OnShowObjectives = <function> defined @Interface\AddOns\Carbonite.Quests\NxQues
AddOns:
  Swatter, v7.2.5678 (TasmanianThylacine)
  AucAdvanced, v7.2.5678 (TasmanianThylacine)
  AucFilterBasic, v7.2.5678 (TasmanianThylacine)
  AucFilterOutlier, v7.2.5678.5459(/embedded)
  AucMatchUndercut, v7.2.5678.5585(/embedded)
  AucScanData, v7.2.5678 (TasmanianThylacine)
  AucStatHistogram, v7.2.5678 (TasmanianThylacine)
  AucStatiLevel, v7.2.5678 (TasmanianThylacine)
  AucStatPurchased, v7.2.5678 (TasmanianThylacine)
  AucStatSales, v7.2.5678.5598(/embedded)
  AucStatSimple, v7.2.5678 (TasmanianThylacine)
  AucStatStdDev, v7.2.5678 (TasmanianThylacine)
  AucStatWOWEcon, v7.2.5678.5613(/embedded)
  AucUtilAHWindowControl, v7.2.5678.5575(/embedded)
  AucUtilAppraiser, v7.2.5678.5666(/embedded)
  AucUtilAskPrice, v7.2.5678.5599(/embedded)
  AucUtilAutoMagic, v7.2.5678.5676(/embedded)
  AucUtilCompactUI, v7.2.5678.5629(/embedded)
  AucUtilEasyBuyout, v7.2.5678.5576(/embedded)
  AucUtilFixAH, v7.2.5678 (TasmanianThylacine)
  AucUtilItemSuggest, v7.2.5678.5651(/embedded)
  AucUtilPriceLevel, v7.2.5678.5633(/embedded)
  AucUtilScanButton, v7.2.5678.5631(/embedded)
  AucUtilScanFinish, v7.2.5678.5588(/embedded)
  AucUtilScanProgress, v7.2.5678.4979(/embedded)
  AucUtilScanStart, v7.2.5678.5347(/embedded)
  AucUtilSearchUI, v7.2.5678.5672(/embedded)
  AucUtilSimpleAuction, v7.2.5678.5654(/embedded)
  AucUtilVendMarkup, v7.2.5678.4828(/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.2.5678 (TasmanianThylacine)
  BigWigs, vv20.1-1-g2a08f65
  BonusRollPreview, v70000.32-Release
  Carbonite, v7.1.0
  CarboniteNotes, v7.1.0
  CarboniteQuests, v7.1.0
  CarboniteWarehouse, v7.1.0
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v10.27
  Enchantrix, v7.2.5678 (TasmanianThylacine)
  EnchantrixBarker, v7.2.5678 (TasmanianThylacine)
  GoldBanker, v1.3
  Healium, v
  Informant, v7.2.5678 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.415(/embedded)
  NomiCakes, v7.1.0.1
  PetBattleTeams, v3.3.2
  Postal, vv3.5.8
  ProspectBarLives, v2.6
  RepSwitch, v7.0.3.8
  Skada, v1.5-12
  SlideBar, v7.2.5678 (TasmanianThylacine)
  Stubby, v7.2.5678 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.9.0.70000
  TitanBag, v5.9.0.70000
  TitanClock, v5.9.0.70000
  TitanCurrency, v7.0.3a
  TitanGold, v5.9.0.70000
  TitanLocation, v5.9.0.70000
  TitanLootType, v5.9.0.70000
  TitanPerformance, v5.9.0.70000
  TitanRepair, v5.9.0.70000
  TitanVolume, v5.9.0.70000
  TitanXP, v5.9.0.70000
  WoWTokenWatch, v1.0.3
  BlizRuntimeLib_enUS v7.1.0.70100 <none>
  (ck=9e2)

Happened on turnin of Emissary Quest.  I will see if I can figure it out, after supper this evening.

**Comment by SteveEbey73742** [comment]
Updated my fork, with a possible fix to the random return of nil in the quest.

**Comment by samyonair** [comment]
2x Carbonite.Quests\NxQuest.lua:6693: attempt to index local 'cur' (a nil value)
Carbonite.Quests\NxQuest.lua:6693: in function `LogUpdate'
Carbonite.Quests\NxQuest.lua:6564: in function `Refresh'
Carbonite.Quests\NxQuest.lua:6648: in function `?'
Carbonite\NxUI.lua:2876: in function <Carbonite\NxUI.lua:2867>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5657
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6049
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6515
 TabSelected = 1
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6296
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6142
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:5961
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6040
 DetailsFrm = NxQuestD {
 }
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6063
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6021
 MenuIShare = <table> {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6093
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6098
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5881
 Menu = <table> {
 }
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5344
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:5996
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5633
 List = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:5971
 Filters = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:5946
 FilterDesc = "Suche: [Klick]"
 FilterDescEsc = "Suche: %[Klick%]"
 FilterFrm = NxQuestFilter {
 }
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6662
 MenuItems1 = <table> {
 }
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6199
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8142
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6263
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6121
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6460
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6088
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8164
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6715
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7430
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:5985
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6247
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6073
 OnQuestUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6571
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6137
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6561
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:5907
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:5980
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6305
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6166
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.

Just quested dailies for nat Pagle

**Comment by samyonair** [comment]
For me Error comes up every time give a finished quest to questgiver

**Comment by IrcDirk** [comment]
Im testing solution for this.

**Comment by IrcDirk** [comment]
Fixed. Check if this is ok.

**Comment by SteveEbey73742** [comment]
will give it a try in a little while. I did not know about the quest_removed event being changed.  did not think to look there.

**Comment by IrcDirk** [comment]
That was not the case ;) Just removed that becouse it isnt necessary, they fixed broken events to which i made workarounds ;)

**Comment by SteveEbey73742** [comment]
I need to study the blizzard api more. I appreciate all that you do, and that you explain things to me.

**Comment by IrcDirk** [comment]
Im not a guru... also learning wow lua, but if we can help each other every thing will be simpler. So u can always ask.

**Comment by SteveEbey73742** [comment]
Thank you.  I also want to report this fixed and am closing this issue.
