### ISSUE TITLE
Player locations not showing on map in battlegrounds

### ISSUE THREAD

**Issue by mixilflik** [mikepauer/Carbonite#562]
Prior to 7.1 player locations showed as a blue dot on the map while in battlegrounds (i believe party members showed this way on the world map outside of BG's also), They are not showing up anymore.

**Comment by IrcDirk** [comment]
Thats not a bug, thats RESTRICTION in WoW API. Addons after patch 7.1 doesnt have access to player and other players position in Dungeons/Raids/BGs.

**Comment by mixilflik** [comment]
Well that stinks, such a useful feature in BG's! Thanks for the quick update though.
