### ISSUE TITLE
Tooltips behind map. 

### ISSUE THREAD

**Issue by doctorwizz** [mikepauer/Carbonite#563]
Hiya
Long time Carbonite  user. I have one issue. with this latest for 7.1. I always have the latest github version.
The only modules I am using are Carbonite and Social and Punks. 
When I open the quest loq to do dailies, all the tooltip are behind the window. I can't  see any loot or other tooltips. Sometimes if the quest is near the top of the map, I can partially see the tooltip. But most of it is behind the window. 
If I disable Carbonite,  tooltips are fine and not behind the window at all. 
Can anyone reproduce this? You would only need the Carbonite module enabled. Not Carbonite Quest.

**Comment by IrcDirk** [comment]
Yep it can be that way... i didnt tested it with only Maps enabled and disabled Quest module. In spare time ill try to do a fix for this.

**Comment by doctorwizz** [comment]
TY

**Comment by doctorwizz** [comment]
Don't mean to hijack my own thread but got this error after Eye of the Storm started. It was a constant error. I had to /afk out. Fist BG I tried since 7.1. Punks has always worked perfect. 
Also same in Twin Peaks.
Not a big deal. Just hope this may help. 

`Message: Interface\AddOns\Carbonite.Social\NxSocial.lua:1761: attempt to perform arithmetic on local 'pX' (a nil value)
Time: 10/27/16 21:11:46
Count: 5
Stack: Interface\AddOns\Carbonite.Social\NxSocial.lua:1761: in function `AddLocalPunk'
Interface\AddOns\Carbonite.Social\NxSocial.lua:2701: in function `?'
...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[14]"]:4: in function <[string "safecall Dispatcher[14]"]:4>
[C]: ?
[string "safecall Dispatcher[14]"]:13: in function `?'
...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...rtifactPathFinder\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...rtifactPathFinder\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: self = <table> {
 GetPunkPasteInfo = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2070
 Punks = <table> {
 }
 PCloseWindows = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2668
 RestoreFriendsFrame = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:691
 OnUpdate = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:867
 SetCols = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:518
 Create = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:753
 OnTabBar = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:921
 Show = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:720
 PunksActive = <table> {
 }
 OnChat_msg_addon = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:510
 PanelTemplates_SetTab = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:905
 PHideUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2660
 GotoPunk = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2053
 List = <table> {
 }
 PreCombatHide = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:733
 PunkNewDir = 8.1311741176471
 DecodeComRcvPunks = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1688
 LastLocalPunk = "Jonfknsnow"
 OnFriendListUpdate = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:851
 AddLocalPunk = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1730
 Init = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:558
 Cols = <table> {
 }
 PShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2648
 PunksHUD = <table> {
 }
 UpdateIcons = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1911
 HideUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:672
 CalcPunks = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1885
 OnUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1870
 GetPunk = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1807
 ShowBlizzTabs = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:982
 OnWin = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:844
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:611
 TeamHUD = <table> {
 }
}
name = "Jonfknsnow"
plyrNear = "Hidensneak"
level = nil
class = nil
map = <table> {
 InstMapWX2 = 2173.0807625
 MiniBlks = 6
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 MapPosY = -1977.5874590918
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 0
 WorldHotspots = <table> {
 }
 Menu = <table> {
 }
 EffScale = 0.83999997377396
 Zone = 482
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 0.078146883144867
 BackgndAlphaFade = 0.4
 MoveLastX = 2170.8778684396
 PlyrDir = 0
 PlyrSpeedCalcTime = 13452.861
 MapPosYDraw = -1977.5874590918
 ArchAlpha = 0.3
 MapScale = 0.0077990901342182
 CurMapBG = true
 PadX = 0
 BGIncNum = 0
 MenuIMon`

**Comment by IrcDirk** [comment]
For this please make new issue.

**Comment by jerryjoh** [comment]
I'm having this same issue. It appears the z-index (or whatever the equivalent is in LUA) is too low on the tooltips or too high on the map. I have found a workaround that lasts until the next cut screen: use alt-m to open the standard map without quests. When you close it and use L to open the world map with quests the tooltips will be on top. It's a pain but it helps when doing a bunch of WQs.

**Comment by doctorwizz** [comment]
Good trick. What do you mean by cut screen? It seems to work for my whole session. 
I am using Angry World Quests addon. So pressing alt m won't really bring up just the map without quests But it does fix the tooltip. Thanks!

**Comment by jerryjoh** [comment]
When the game "cuts away" to another scene. Like when a Hearthstone is used or a teleport. Also when cinematics are shown.

**Comment by doctorwizz** [comment]
It still works after I hearth. Not sure about cinematics. 
Stops working if I press M, which brings up the Carbonite map, logout, or reloadui.

**Comment by IrcDirk** [comment]
As i said i will take care of this issue in incomming week.

**Comment by IrcDirk** [comment]
Should be fixed. Please confirm.

**Comment by doctorwizz** [comment]
K Let me check.

**Comment by doctorwizz** [comment]
Confirmed  fixed. TY
