### ISSUE TITLE
Social and Punks error in BGs

### ISSUE THREAD

**Issue by doctorwizz** [mikepauer/Carbonite#564]
got this error after Eye of the Storm started. It was a constant error. I had to /afk out. Fist BG I tried since 7.1. Punks has always worked perfect. 
Also same in Twin Peaks.
Works fine when not in BGs
Not a big deal. Just hope this may help.

Message: Interface\AddOns\Carbonite.Social\NxSocial.lua:1761: attempt to perform arithmetic on local 'pX' (a nil value) Time: 10/27/16 21:11:46 Count: 5 Stack: Interface\AddOns\Carbonite.Social\NxSocial.lua:1761: in functionAddLocalPunk'
Interface\AddOns\Carbonite.Social\NxSocial.lua:2701: in function `?'
...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[14]"]:4: in function <[string "safecall Dispatcher[14]"]:4>

[string "safecall Dispatcher[14]"]:13: in function ?' ...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in functionFire'
...rtifactPathFinder\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...rtifactPathFinder\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: self =

{
GetPunkPasteInfo = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2070
Punks =
{
}
PCloseWindows = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2668
RestoreFriendsFrame = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:691
OnUpdate = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:867
SetCols = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:518
Create = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:753
OnTabBar = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:921
Show = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:720
PunksActive =
{
}
OnChat_msg_addon = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:510
PanelTemplates_SetTab = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:905
PHideUIPanel = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2660
GotoPunk = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2053
List =
{
}
PreCombatHide = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:733
PunkNewDir = 8.1311741176471
DecodeComRcvPunks = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1688
LastLocalPunk = "Jonfknsnow"
OnFriendListUpdate = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:851
AddLocalPunk = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1730
Init = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:558
Cols =
{
}
PShowUIPanel = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2648
PunksHUD =
{
}
UpdateIcons = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1911
HideUIPanel = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:672
CalcPunks = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1885
OnUpdateTimer = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1870
GetPunk = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1807
ShowBlizzTabs = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:982
OnWin = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:844
ShowUIPanel = defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:611
TeamHUD =
{
}
}
name = "Jonfknsnow"
plyrNear = "Hidensneak"
level = nil
class = nil
map =
{
InstMapWX2 = 2173.0807625
MiniBlks = 6
IconScale = 3
MenuIShowWorld =
{
}
GIconMenuITogInst =
{
}
MapPosY = -1977.5874590918
MMScalesC =
{
}
LOpts =
{
}
Guide =
{
}
PlyrLastDir = 0
WorldHotspots =
{
}
Menu =
{
}
EffScale = 0.83999997377396
Zone = 482
WorldAlpha = 0
StartupShown = true
ScaleDraw = 0.078146883144867
BackgndAlphaFade = 0.4
MoveLastX = 2170.8778684396
PlyrDir = 0
PlyrSpeedCalcTime = 13452.861
MapPosYDraw = -1977.5874590918
ArchAlpha = 0.3
MapScale = 0.0077990901342182
CurMapBG = true
PadX = 0
BGIncNum = 0
MenuIMon`

**Comment by IrcDirk** [comment]
Should be fixed.

**Comment by doctorwizz** [comment]
Yes it works perfect now. Thanks so much!
