### ISSUE TITLE
Map issues as of commit 2c74ed272853c33381a682aa5a1eb0b7e94853df First draft restoration of dungeon/instance/pvp maps

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#565]
Having issues with alt - M

The map as appears with the M key
https://1drv.ms/i/s!Ai8SfAzON-JQgYE7drYK4Z_76AZNbw

The map when alt - M
https://1drv.ms/i/s!Ai8SfAzON-JQgYE6qkH3gNDMbz8Kbw

This is with Carbonite only loaded..

**Comment by mikepauer** [comment]
For some reason the second link didn't load anything, however since your mentioning alt-M it is most likely an expected outcome for now

I took over the world map detail frame which means it's blank on the actual world map now, it's the only place you can still see and find player location arrows. 

I will be adding an option to turn this on or off in the same vein as the minimap takeover, if it's on carbonite will function in PVP and dungeons... if it's off, carbonite shuts down and stops working as soon as restricted mode starts.

**Comment by IrcDirk** [comment]
In restricted mode leave option u use Carbonite as it is... dont shut it down... Im using it even in dungs to see quest log etc.

**Comment by mikepauer** [comment]
That is what I meant by shutting it down, making it not try to do any mapping but the rest remains. Hopefully it won't be needed if I can figure out this new PersonalArrow system

**Comment by qlesz** [comment]
not really sure wich commit caused that (i've tried change back code from commit/889582ddb59ce40d7fb40616cbc9b328f4c6d62d but problem still exist) and i don't want to open new ticket so i'll attach screen capture files here. Everytime i mouseover on valsharah area or azsuna i got map glitch. If i'm in any of that zones map is fine but get crazy when i mouse over any other area making it impossible to use. That happening on minimap and full map aswell.
![wowscrnshot_103016_124511](https://cloud.githubusercontent.com/assets/14138274/19836684/0cd04e26-9ea0-11e6-9c53-dc808999522f.jpg)
![wowscrnshot_103016_124525](https://cloud.githubusercontent.com/assets/14138274/19836686/11da11cc-9ea0-11e6-94ad-920a775b80bb.jpg)
![wowscrnshot_103016_124539](https://cloud.githubusercontent.com/assets/14138274/19836687/147ed408-9ea0-11e6-9409-1c8f22e79c18.jpg)

**Comment by IrcDirk** [comment]
Sorry Rythal but something is very wrong with maps... as u hover on zone in which u are not right now, it shows blizz map 100% with and height. It should **use default Carbonite map** not those for restricted areas.

**Comment by IrcDirk** [comment]
To reproduce this behavior go to dalaran, open map by presing M, hover on one zone other than dalaran, then hover on another (not dalaran).

**Comment by mikepauer** [comment]
Fixed.

**Comment by mikepauer** [comment]
Still one more thing I need to add before publishing, hopefully tonight.. the option to turn the worldquest shit off so it's not cluttering the map unless you want to see it.

**Comment by Thrumbar** [comment]
Appears to be fixed,, Closing....
