### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by Keiichi2191** [mikepauer/Carbonite#566]
After the 7.1 update, I have been getting an FPS Drop in instances. This includes battlegrounds, dungeons, etc. With your most recent update, I get the FPS drop in a battleground right after combat begins.

**Comment by mikepauer** [comment]
Which most recent update.. i've pushed 3 tonight

**Comment by Keiichi2191** [comment]
My apologies, I was referring to the 7.1 that you released. I haven't attempted the one you just released. I will try it and let you know shortly.

**Comment by mikepauer** [comment]
It's still a work in progress, and has some display bugs.. but most instance / bg mapping problems should be fixed.

**Comment by Keiichi2191** [comment]
I can see. Everything looked great when in open world. When I opened the Game menu though, this is what appeared
http://i.imgur.com/Q6FTc1v.png
In a battleground everything seemed to work as expected. The map is improved and stretch to the size of the map unlike before (no need to zoom in or out). I also didn't see any FPS drop.
http://i.imgur.com/dousyK2.png

**Comment by IrcDirk** [comment]
This should be fixed by now. Redownload latest.
