### ISSUE TITLE
Display problem in Carbonite Quests

### ISSUE THREAD

**Issue by Baghiel** [mikepauer/Carbonite#567]
![image](https://cloud.githubusercontent.com/assets/23145095/19833958/1ba55200-9e98-11e6-8d78-fa5e988d0c3a.png)

I have the above on my 110 Priest. I have abandoned the quests (not interested in PvP), but they still display in Quests. They are not in the default quest list, only Carbonite Quests. They don't appear to be counted in regards to the number of quests vs the maximum number of quests. I cannot get rid of those 3 quests from the list.

**Comment by IrcDirk** [comment]
Read here this is not Carbonite BUG: http://www.wowinterface.com/forums/showthread.php?t=54730

**Comment by Baghiel** [comment]
Thanks.
