### ISSUE TITLE
Nil bug in quests, agan

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#568]
Different bug, CurQuest returned the nil. as shown here. Picking up a profession quest on my 104 DK.
Date: 2016-10-30 10:13:57
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Quests\NxQuest.lua line 6694:
   attempt to index global 'CurQuest' (a nil value)
Debug:
   Carbonite.Quests\NxQuest.lua:6694: LogUpdate()
   Carbonite.Quests\NxQuest.lua:6563: Refresh()
   Carbonite.Quests\NxQuest.lua:6628: ?()
   Carbonite\NxUI.lua:2876:
      Carbonite\NxUI.lua:2867
Locals:
self = <table> {
 UpdateMenu = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5658
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6050
 MakeDescLink = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6516
 TabSelected = 1
 Menu_OnTrackNone = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6297
 Menu_OnWatchAll = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6143
 FilterOnEditFocusLost = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5962
 Menu_OnHighPri = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6041
 DetailsFrm = NxQuestD {
 }
 Menu_OnShowAllQuests = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6064
 Menu_OnShowFinished = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6084
 Menu_OnGoto = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6022
 MenuIShare = <table> {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnShowParty = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6094
 Menu_OnCompleted = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6099
 Select = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5882
 Menu = <table> {
 }
 Open = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5345
 OnTabBar = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5997
 AttachFrames = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5634
 List = <table> {
 }
 FilterOnTextChanged = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5972
 Filters = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5947
 FilterDesc = "Search: [click]"
 FilterDescEsc = "Search: %[click%]"
 FilterFrm = NxQuestFilter {
 }
 LogUpdate = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6663
 MenuItems1 = <table> {
 }
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6200
 OnDetailsSetSize = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8143
 Menu_OnAbandon = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6264
 Menu_OnHistoryRemoveAll = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6122
 ToggleWatch = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6461
 Menu_OnShowOnlyDailies = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6089
 DetailsSetWidth = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:8165
 Menu_OnShowAllZones = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6079
 Opened = true
 Update = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6716
 CheckShow = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:7431
 SendQuestInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6177
 FilterOnEscapePressed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5986
 Menu_OnShare = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6248
 Menu_OnShowHighLevel = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6074
 OnQuestUpdate = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6572
 Menu_OnSortWatched = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6138
 Refresh = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6562
 GetCurSelected = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5908
 FilterOnEnterPressed = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:5981
 OnListEvent = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6306
 Menu_OnSendQInfo = <function> defined @Interface\AddOns\Carbonite.Quests\NxQuest.lua:6167
 Menu_OnShowObjectives = <function> defined @Interface\AddOns\Carbonite.Quests\NxQues
AddOns:
  Swatter, v7.2.5682 (TasmanianThylacine)
  WowheadLooter, v60014
  AucAdvanced, v7.2.5682 (TasmanianThylacine)
  AucFilterBasic, v7.2.5682 (TasmanianThylacine)
  AucFilterOutlier, v7.2.5682.5459(/embedded)
  AucMatchUndercut, v7.2.5682.5585(/embedded)
  AucScanData, v7.2.5682 (TasmanianThylacine)
  AucStatHistogram, v7.2.5682 (TasmanianThylacine)
  AucStatiLevel, v7.2.5682 (TasmanianThylacine)
  AucStatPurchased, v7.2.5682 (TasmanianThylacine)
  AucStatSales, v7.2.5682.5598(/embedded)
  AucStatSimple, v7.2.5682 (TasmanianThylacine)
  AucStatStdDev, v7.2.5682 (TasmanianThylacine)
  AucStatWOWEcon, v7.2.5682.5613(/embedded)
  AucUtilAHWindowControl, v7.2.5682.5575(/embedded)
  AucUtilAppraiser, v7.2.5682.5666(/embedded)
  AucUtilAskPrice, v7.2.5682.5599(/embedded)
  AucUtilAutoMagic, v7.2.5682.5676(/embedded)
  AucUtilCompactUI, v7.2.5682.5629(/embedded)
  AucUtilEasyBuyout, v7.2.5682.5576(/embedded)
  AucUtilFixAH, v7.2.5682 (TasmanianThylacine)
  AucUtilItemSuggest, v7.2.5682.5651(/embedded)
  AucUtilPriceLevel, v7.2.5682.5633(/embedded)
  AucUtilScanButton, v7.2.5682.5631(/embedded)
  AucUtilScanFinish, v7.2.5682.5588(/embedded)
  AucUtilScanProgress, v7.2.5682.4979(/embedded)
  AucUtilScanStart, v7.2.5682.5347(/embedded)
  AucUtilSearchUI, v7.2.5682.5672(/embedded)
  AucUtilSimpleAuction, v7.2.5682.5654(/embedded)
  AucUtilVendMarkup, v7.2.5682.4828(/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.2.5682 (TasmanianThylacine)
  BigWigs, vv21.2-4-gc6e921e
  BonusRollPreview, v70100.34-Release
  Carbonite, v7.1.0
  CarboniteNotes, v7.1.0
  CarboniteQuests, v7.1.0
  CarboniteWarehouse, v7.1.0
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v10.29
  Enchantrix, v7.2.5682 (TasmanianThylacine)
  EnchantrixBarker, v7.2.5682 (TasmanianThylacine)
  GoldBanker, v1.3
  Healium, v
  Informant, v7.2.5682 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.416(/embedded)
  NomiCakes, v7.1.0.1
  PetBattleTeams, v3.3.2
  Postal, vv3.5.8
  ProspectBarLives, v2.6
  RepSwitch, v7.0.3.8
  SilverDragon, vv3.2.8
  Skada, v1.5-13
  SlideBar, v7.2.5682 (TasmanianThylacine)
  Stubby, v7.2.5682 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.9.2.70100
  TitanBag, v5.9.2.70100
  TitanClock, v5.9.2.70100
  TitanCurrency, v7.0.3a
  TitanGold, v5.9.2.70100
  TitanLocation, v5.9.2.70100
  TitanLootType, v5.9.2.70100
  TitanPerformance, v5.9.2.70100
  TitanRepair, v5.9.2.70100
  TitanVolume, v5.9.2.70100
  TitanXP, v5.9.2.70100
  WoWTokenWatch, v1.0.3
  BlizRuntimeLib_enUS v7.1.0.70100 <none>
  (ck=a12)

**Comment by IrcDirk** [comment]
Link this quest.

**Comment by IrcDirk** [comment]
Another thing is thats in your repository ;) 

Your line 6694:

> CurQuest.QIdsNew[cur.QId] = time()

Carbonite repo:

> Quest.QIdsNew[cur.QId] = time()

So this bug is in your repository and this is your modification.

**Comment by SteveEbey73742** [comment]
Will do. forgot I had tried to fix it when it first occurred, thought I had reset if back, but missed that.
