### ISSUE TITLE
Arrow missing on WQ maps.

### ISSUE THREAD

**Issue by doctorwizz** [mikepauer/Carbonite#569]
With today's update, I can no longer see an arrow on the world quest map. It works on the Carbonite map.  
The arrow that shows your position.

**Comment by IrcDirk** [comment]
Describe that in detail, when, where etc... show screenshot. I dont have this issue.

**Comment by doctorwizz** [comment]
With Carbonite enabled
http://i.imgur.com/UNlSyw9.jpg

With it  disabled
http://i.imgur.com/bhz5shI.jpg

Screenshots might be big. Capped in 4K
No arrow in the first  SS. It's there in the 2nd SS.

**Comment by mikepauer** [comment]
Try it now.

**Comment by doctorwizz** [comment]
Confirmed fixed. U rock thanks!
