### ISSUE TITLE
Strange string in Quest Module

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#577]
NxQuest.lua
Line 3434: 	local desc, _typ, done = GetQuestLogLeaderBoard (n, qi)

If I am correct, the string above the second of the string should be either "Type" or _ not both.. Would have pushed but do not know which goes there in this instance..

text, type, finished = GetQuestLogLeaderBoard(objective [, questIndex])
Arguments:

objective - Index of a quest objective (between 1 and GetNumQuestLeaderBoards()) (number)
questIndex - Index of a quest in the quest log (between 1 and GetNumQuestLogEntries()); if omitted, defaults to the selected quest (number)
Returns:

text - Text of the objective (e.g. "Gingerbread Cookie: 0/5") (string)
type - Type of objective (string)

event - Requires completion of a scripted event
item - Requires collecting a number of items
monster - Requires slaying a number of NPCs
object - Requires interacting with a world object
reputation - Requires attaining a certain level of reputation with a faction
finished - 1 if the objective is complete; otherwise nil (1nil)

**Comment by IrcDirk** [comment]
Wrote answer in your pull request.
