### ISSUE TITLE
Battleground objectvies missing from map

### ISSUE THREAD

**Issue by Storm-Engineer** [mikepauer/Carbonite#586]
Objectives such as mine carts, capture points etc. are not displayed on battleground maps anymore.

I didn't play WoW for a while so don't know when did this break. I updated to latest version when I started playing again. It worked about a year ago when I last played.

**Comment by Thrumbar** [comment]
May have broken with the changes from 7.1...  May be that the icons are not populating as the battlegrounds are using the Blizzard default map....

**Comment by IrcDirk** [comment]
There are restrictions in 7.1 to what can we do in BGs with map... but maybe its possible to move those icons as Rythal did moved Blizz orginal map with cursor to Carbonite map.

**Comment by Storm-Engineer** [comment]
It works in Instances. For BGs I now have to use the Blizz zone map.

And this reminds me: it would be very useful if there was an option to automatically hide Carbonite zone map and/or quest tracker while in a BG.

**Comment by IrcDirk** [comment]
Try know i did enabled POIs to show on BG maps.
