### ISSUE TITLE
Quest Details Shows Wrong Quest

### ISSUE THREAD

**Issue by bcrotty** [mikepauer/Carbonite#587]
After abandoning a quest or sometimes just clicking around the quest log, the wrong details will show for the selected quest. Right clicking on the quest on the left, "My Son..." in the picture, and clicking Abandon will try to abandon the quest shown in the details, not the one shown on the left.
![2016-11-13 11_44_32-world of warcraft](https://cloud.githubusercontent.com/assets/6155964/20247644/ac7f6d2a-a996-11e6-9a24-3c9781857d61.png)

**Comment by IrcDirk** [comment]
Do u use latest version from github? If not try newest and report again ;)

**Comment by bcrotty** [comment]
It seems to be working with the GitHub version.
