### ISSUE TITLE
Minimap missing?

### ISSUE THREAD

**Issue by xSimone** [mikepauer/Carbonite#59]
The Minimap, depending on your Zone, seems to be missing, especially inside Instances.

I need to change to Instance Mode on the main map if I want to see positions of my party mates.

Here's how I use the map. Picture to understand better. https://i.imgur.com/ifn1qOP.jpg

When inside Ironforge, the Minimap for inside disappears unless I mouse the main map outside into Dun'Morogh. It's as if when in Instance Mode, or Inside mode, the Minimap hides? But I made sure that it's checked to show when inside.

Thank you. :<

**Comment by xSimone** [comment]
Also how do I upload my stats again? I'd love to help Carbonite with my logs.

**Comment by Swirrel** [comment]
xSimone: http://atk.github.io/Carbonite/
I believe that's the link you're looking for...

**Comment by xSimone** [comment]
Gah.. I forgot to have Quest Data Gathering on... this should be on by default. ;U

**Comment by xSimone** [comment]
More issues, the Minimap icon or map icon seem to ghost out of the frame..?

https://imgur.com/a/bDaK1

**Comment by IrcDirk** [comment]
U got errors, post screens with only Carbonite enabled, then if this happens again post error logs.
