### ISSUE TITLE
build number not working with autopacker

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#6]
The build number ingame is not present if downloaded from curse (alpha version). Is there a way to fix this?

**Comment by IrcDirk** [comment]
Dont know. Curse makes its own repo clone and from its own repo makes downloads.

**Comment by fdellwing** [comment]
Ok, there is this article: https://www.curseforge.com/knowledge-base/world-of-warcraft/532-repository-keyword-substitutions

I think, this one is the correct thing: @project-revision@

We need to push it to Curse to see it's effect, I will do a PR to test this,

**Comment by fdellwing** [comment]
Works, but seems a bit long? We could format it to 9 chars (short git commit hash) or try another keyword like @project-abbreviated-hash@

Maybe just get them all into the code for your next commit as comment and decide afterwards what to do?

![wowscrnshot_061117_203003](https://user-images.githubusercontent.com/22813377/27013479-d41fb7ec-4ee4-11e7-9477-ef8677278f59.jpg)

**Comment by IrcDirk** [comment]
Thats ok ill just make substring from this.
