### ISSUE TITLE
Zooming issue

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#608]
Middle button zooming is not working on world map when "show instance map" option is ticked (neither on minimap nor full map)

**Comment by IrcDirk** [comment]
Not an issue thats intented. Instance maps now are static, scrolling would break player positioning.

**Comment by qlesz** [comment]
im not saying that instance map is not scrolling, im saying when option is on i can't scroll world map even if im not in an instance

**Comment by IrcDirk** [comment]
Dont set "show instance map" when not in instance PvP... i think this is global option for all exempt PvP instances since Rythal made separate options only for PvP instances.

**Comment by qlesz** [comment]
well if im not in pvp instances when option stays unchecked carb is not displaying instance map

**Comment by IrcDirk** [comment]
ohhh well ... so this is an issue, there shoul be separate option to select this in other instances like Dungs etc...

**Comment by mikepauer** [comment]
It's the conditional I added, I didn't do the full conditional 

RIght now it's 
if map.CurOpts.NXInstanceMaps then
		return
end

It needs to be 

if map.CurOpts.NXInstanceMaps and isinstancecheck (at work so can't write full conditional) then
	return
end

**Comment by IrcDirk** [comment]
OK check now, should be ok. Thanks Rythal.

**Comment by qlesz** [comment]
y seem to be ok now
