### ISSUE TITLE
Weird lag after killing

### ISSUE THREAD

**Issue by samyonair** [mikepauer/Carbonite#61]
Every Time I kill a mob screen stucks about 2-5 sec without carb anything works fine, although another person in friendship has same problem 

First thought with 7.3 was fps drop due to updates but a drop down in graphic settings no change

no error only stucking

greetings 

Samyonair

PS: all Modules installed included gathermate Data Edition 
Modules are listed under Gathermate data edition

**Comment by IrcDirk** [comment]
What do u mean by "mob screen stucks"? Just checked by killing a group mob in Azsuna... no stucking no lag... Describe better your problem. Where does this happen?

**Comment by samyonair** [comment]
Every mob I kill it will hang 4 a moment on Argus it is worst but although on broken isles will test without any modules if I have time , but working 60 hours a week at the moment with 4 hours per day to get to work and back home I have no spare time to log into wow at the moment

**Comment by Korpip** [comment]
I am having this issue as well.

**Comment by IrcDirk** [comment]
Is this in Party or after Party?

**Comment by IrcDirk** [comment]
As i see this happens only in Party... any one can confirm?

**Comment by Korpip** [comment]
Sorry for the late reply.  Yes it seems to happen in a party and from what I can see when updating quest objectives.  More people in group the harder the hit.

**Comment by IrcDirk** [comment]
Ok, im working on fix, but this may take some time.

**Comment by Korpip** [comment]
Ya it's cool.  Time of year and all.
