### ISSUE TITLE
Carbonite freezes the game when Quest Loader starts loading 18k Quests

### ISSUE THREAD

**Issue by xEvilgrin** [mikepauer/Carbonite#611]
![carbonite_freeze_01-27-2017](https://cloud.githubusercontent.com/assets/25394494/22388570/687ba770-e4e1-11e6-8459-bd352357b971.jpg)

the game freezes immediately when the Questloader says 18487 quests loaded.
If i turn off Carbonite Quest 7.1.0 the game stops freezing.
it worked well for weeks now.. the issue came up during playing that morning.
No Bugsack info available. I tried to delete the Questfolder and replace it with the latests one.. i even loaded the whole package down and restored it. No success 

Also came to my attention  entering new Quests doesnt change the Questlog (tracker) unless i click the first Arrowbutton and tell the quest module to show all quests. after that the new quests correctly shown up in the Questtracker

Greetings from germany

xEvilgrin

**Comment by IrcDirk** [comment]
Carbonite and modules are updated to latest version from github? 

If so, clear quest log from all quests, there was Blizz bug that couses someting similar, didnt know if they fixed it.

**Comment by xEvilgrin** [comment]
Hey IrcDirk
thx for your quick reply.. it seems only to happen at the Spires of Arak Zone yet. If i  turn on CQ in Garrison for example it works again.
I have  installed the latest github version what i tried to figure out in my first thread ^^.
Im researching now for more details regarding the freezes

**Comment by IrcDirk** [comment]
Try latest commit and please report back.
