### ISSUE TITLE
minimised map mousover issue

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#616]
I just downloaded newest version of carbonite (solving silverhands work order etc) and my minimised map get into the madness. Basically the big icon for daily faction quests is moving to the middle of the screen every time i mouse over the map, and stays there untill i open full map. I have disabled all addons to make sure it's not other addon causing that but even after that problem still persist (especially when i mouse over dalaran i get it straight away). Here is screenshot 
![wowscrnshot_022617_204539](https://cloud.githubusercontent.com/assets/14138274/23343589/ebcf912c-fc65-11e6-9ad6-ef498153a98e.jpg)

**Comment by IrcDirk** [comment]
Duplicate issue, see here #615.
