### ISSUE TITLE
emissary quest frame issue again

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite#617]
Emissary quest frame issue is still persist. A bit different but also annoying. When i've got minimised map opened when i mouse over screen there is a place across the whole screen (look like it's dummy frame parented to  minimised map) where if my mouse is over it then emisary quest tool tip window pop up next to minimap window. Also if my mouse is over that dummy place i cannot click anything under (ie. mobs) Because it's hard to explain i'll try to share captured video.

**Comment by IrcDirk** [comment]
Need videos and screens. Did u download latest? I made one fix for this, maybe u are one version back?

**Comment by qlesz** [comment]
yes latest one, and i just did video i'll upload it to google drive and put the link in here

**Comment by qlesz** [comment]
ah and i've checked it with all other addons off also, and issue was still there

**Comment by IrcDirk** [comment]
Ok, ill try on my version when im back home.

**Comment by IrcDirk** [comment]
OK i made some changes. Please update, check and report back.

**Comment by kived** [comment]
Commenting to follow this issue. Also I can test the fix this evening after work if it hasn't been tested by that time.

**Comment by qlesz** [comment]
seem to be ok now. Closing
