### ISSUE TITLE
AddOn 'Carbonite' tried to call the protected function 'WorldMapFrame:SetAttribute()'.

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#618]
Got this when I tried to open map in combat (alt - m)..  Have the latest build  2bafd34 

1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite' tried to call the protected function 'WorldMapFrame:SetAttribute()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:82: in function <FrameXML\UIParent.lua:76>
FrameXML\UIParent.lua:2860: in function <FrameXML\UIParent.lua:2856>
[C]: ?
[C]: ?
[C]: in function `ShowUIPanel'
Carbonite\NxMap.lua:3100: in function `BlizzToggleWorldMap'
Carbonite\NxMap.lua:3030: in function <Carbonite\NxMap.lua:3028>
[C]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

**Comment by IrcDirk** [comment]
Yep something changes... will check whats wrong in spare time.

**Comment by IrcDirk** [comment]
Fixed.

**Comment by Thrumbar** [comment]
Have not seen the issue after fix.. Closing..

**Comment by IrcDirk** [comment]
Need to reopen since i had to reverse commit for this issue, since Order Hall orders to complete World Quests are more important.

**Comment by IrcDirk** [comment]
I think ill disable ability to open orginal Blizz World Map in combat, to make this fix. Since blizz doesnt want to fixt those taint errors...

**Comment by Thrumbar** [comment]
Works for me.  Until they fix it or until someone comes up with a better solution that is how it is..

**Comment by IrcDirk** [comment]
Ill make option to allow opening blizz map in combat, so if someone wants to open blizz world map in combat then he can (will trow error but it works).

**Comment by Thrumbar** [comment]
Ok.  Just noticed this in code..
-- Temporary Hack (copy of a "temporary" 6 year hack)
Blizzard sure is funny...

**Comment by IrcDirk** [comment]
Yeah... they are hacking their one code ;)

**Comment by Thrumbar** [comment]
Found this in archives from the original Carbonite authors

Beware that the Blizzard zone map, when visible, will force the current zone you are in to be selected, which is a global game setting. That setting is also used by Carbonite to determine what zone is selected, which means you will have problems mousing over other zones on the Carbonite map to view them.

**Comment by IrcDirk** [comment]
Made workaround for this. Now even in combat opening blizz world map shoudl not trigger taint errors.

**Comment by Thrumbar** [comment]
Have no gotten the reported error in testing I could do with the little time I have for gaming.  Will reopen again if this changes..
