### ISSUE TITLE
Greater Invasions

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#62]
Getting a ton of errors in the Greater Invasions. Noticed last week and now this week. I assume the maps just need to be added (updated). Here is the error from this week:

Date: 2017-10-17 22:55:08
ID: 79
Error occured in: Global
Count: 1
Message: integer overflow attempting to store 2824736898
Debug:
   [C]: format()
   Carbonite\NxMap.lua:5522: ?()
   Carbonite\NxMap.lua:4869: Update()
   Carbonite\NxMap.lua:3816:
      Carbonite\NxMap.lua:3700
Locals:
(*temporary) = "
%s %d %s %d%%"
(*temporary) = "Mistress Alluradel"
(*temporary) = -1
(*temporary) = ""
(*temporary) = 2824736898

**Comment by IrcDirk** [comment]
Hmmm by WowHead Mistress Alluradel got **1.725.880.500** HP but here we see that Wow Api returns **2.824.736.898** HP. Can u tell me how much she got HP on greater invasion? Does she scale to group?

**Comment by Palonblade** [comment]
I think her health scales based on the number of peeps in the instance. The errors only occur once the boss is engaged then repeat over and over.

**Comment by IrcDirk** [comment]
Max 32-bit integer is 2.147.483.647 so 2.824.736.898 is to large... Do u use 32-bit client? If not this is another shitty bilzz bug... Great work Blizz coders...

**Comment by Palonblade** [comment]
I use 64 bit client

**Comment by IrcDirk** [comment]
Ok i think i found workaround for this... Please update, check if this works and report back.

**Comment by Palonblade** [comment]
Thank you so much for trying to fix this. I can't test until the Greater Invasions are up again for me next week.

**Comment by IrcDirk** [comment]
Just test it whenever u can and report back :)

**Comment by Palonblade** [comment]
I've done 3 of 10 toons so far and no issues :). 10 of 10 and no errors.
