### ISSUE TITLE
PTR Issue - NxMap.lua:4571: attempt to call global 'GetMapLandmarkInfo' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#621]
5576x Carbonite\NxMap.lua:4571: attempt to call global 'GetMapLandmarkInfo' (a nil value)
Carbonite\NxMap.lua:4571: in function `Update'
Carbonite\NxMap.lua:3714: in function <Carbonite\NxMap.lua:3620>

Locals:
self = <table> {
 MiniBlks = 6
 IconScale = 3
 Scale = 1.1754776066283
 MenuIShowWorld = <table> {
 }
 TextFrm = <unnamed> {
 }
 TextScFrm = <unnamed> {
 }
 PlyrY = -758.32672057366
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0.05
 ScaleDrawW = 0.85071803525747
 ArrowPulse = 1
 Targets = <table> {
 }
 InstanceId = false
 MenuIShowMine = <table> {
 }
 CurMapBG = false
 MMScalesC = <table> {
 }
 Cont = 8
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 38.870077454253
 WorldHotspots = <table> {
 }
 Zone = 1014
 Level = 6
 Size1 = 1.1718750261934
 PlyrRZY = 48.986011743546
 MenuIMonitorZone = <table> {
 }
 MapId = 1014
 ShowUnexplored = false
 EffScale = 0.63999998569489
 LastDungeonLevel = 10
 MMOwn = false
 TextFStrs = <table> {
 }
 Arch = <unnamed> {
 }
 Scrolling = false
 W = 150
 PIconMenu = <table> {
 }
 CurWorldUpdateMapId = 1014
 WorldAlpha = -0.58333333333333
 Menu = <table> {
 }
 StartupShown = true
 LocTipFrm = NxMapTip {
 }
 MMOwnedFrms = <table> {
 }
 PlyrSpeedY = -758.32672057366
 MMChkDelay = 4
 StepTime = 0
 BackgndAlphaFade = 0.4
 PlyrFrm = <unnamed> {
 }
 MMScales = <table> {
 }
 IconWQFrms = <table> {
 }
 MoveLastX = 2074.2534254487
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MapPosYDraw = -758.32672057366
 MapPosY = -758.32672057366
 ArchAlpha = 0.3
 MapPosXDraw = 2074.2534254487
 ScaleDraw = 1.1754776066283
 MiniFrms = <table> {
 }
 MapIndex = 1
 InCombat = false
 MenuIInstanceMaps = <table> {
 }
 PlyrSpeedX = 2074.2534254487
 Win = <table> {
 }
 PadX = 0
 DebugAdjustScale = 0.1
 RealScale = 1.1754776066283
 Data = <table> {
 }
 PlyrDir = 38.870077454253
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 350.8000793457
 PlyrSpeedCalcTime = 1455.23
 MMGathererUpdateDelay = 1
 MenuIShowTimber = <table> {
 }
 BGIconMenu = <table> {
 }
 LClickTime = 0
 MouseEnabled = true
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 ButAutoScaleOn = <table> {
 }
 PlyrSpeed = 14858.832398497
 MapH = 333.99996948242
 ContFrms = <table> {
 }
 GIconMenuIFindNote = <table> {
 }
 TileFrms = <table> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 DotZoneScale = 1
 DotRaidScale = 1
 MapScale = 0.11731313439405
 Tracking = <table> {
 }
 GIconMenu = <table> {
 }
 BackgndAlphaTarget = 0.4
 TargetNextUniqueId = 1
 TransMenu = <table> {
 }
 MoveDir = 180
 BGGrowBars = true
 MapsDrawnFade = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 ArrowScroll = 0
 MapPosX = 2074.2534254487
 H = 141
 ScaleW = 0.85071803525746
 BackgndAlphaFull = 1
 CurOpts = <table> {
 }
 IconNIFrms = <table> {
 }
 TitleH = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = -758.32672057366
 MenuIShowHerb = <table> {
 }
 IconFrms = <table> {
 }
 DotPartyScale = 1
 PlyrRZX = 58.188831806183
 KillShow = false
 QuestAlpha = 0.3
 NeedWorldUpdate = true
 MapsDrawnOrder = <table> {
 }
 UpdateTargetDelay = 0
 Frm = <unnamed> {
 }
 Tick = 1
 DotPalScale = 1
 CurWorldUpdateOverlayNum = 1
 PlyrX = 2074.2534254487
}
elapsed = 0.68000000715256
Nx = <table> {
 GetDataToolBar = <function> defined @Carbonite\Carbonite.lua:1715
 modules = <table> {
 }
 CancelTimer = <function> defined @Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:145
 Quest = <table> {
 }
 OnUnit_spellcast_sent = <function> defined @Carbonite\Carbonite.lua:1082
 VERSIONFAV = 0.15
 prt = <function> defined @Carbonite\NxUI.lua:95
 BarData = <table> {
 }
 prtVar = <function> defined @Carbonite\NxUI.lua:159
 ScheduleTimer = <function> defined @Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:92
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Carbonite\Carbonite.lua:806
 VERSIONINFO = 0.24
 prtFrame = <function> defined @Carbonite\NxUI.lua:196
 db = <table> {
 }
 UnregisterAllComm = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 SetEnabledState = <function> defined @Carbonite\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Graph = <ta

**Comment by IrcDirk** [comment]
I got it already fixed, see why i dont comit fixes => #620
