### ISSUE TITLE
PTR Issue - NxInfo.lua:280: attempt to call global 'UnitMana' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#622]
2x Carbonite.Info\NxInfo.lua:280: attempt to call global 'UnitMana' (a nil value)
Carbonite.Info\NxInfo.lua:280: in function `OnTimer'
Carbonite.Info\NxInfo.lua:252: in function `Init'
Carbonite.Info\NxInfo.lua:156: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
self = <table> {
 CalcThreatPercent = <function> defined @Carbonite.Info\NxInfo.lua:1032
 CalcIfCombat = <function> defined @Carbonite.Info\NxInfo.lua:1164
 CalcIfLTOrCombat = <function> defined @Carbonite.Info\NxInfo.lua:1188
 EditorOnListEvent = <function> defined @Carbonite.Info\NxInfo.lua:1365
 GetFrame = <function> defined @Carbonite.Info\NxInfo.lua:1275
 New = <function> defined @Carbonite.Info\NxInfo.lua:354
 Infos = <table> {
 }
 CalcFPS = <function> defined @Carbonite.Info\NxInfo.lua:876
 Menu_OnEdit = <function> defined @Carbonite.Info\NxInfo.lua:463
 CalcManaPercent = <function> defined @Carbonite.Info\NxInfo.lua:912
 Vars = <table> {
 }
 DKRunes = <table> {
 }
 CreateFrame = <function> defined @Carbonite.Info\NxInfo.lua:1239
 EditorCreate = <function> defined @Carbonite.Info\NxInfo.lua:1303
 CalcBarHPercent = <function> defined @Carbonite.Info\NxInfo.lua:837
 CalcDur = <function> defined @Carbonite.Info\NxInfo.lua:1043
 Delete = <function> defined @Carbonite.Info\NxInfo.lua:374
 NeedDurability = false
 ToggleShow = <function> defined @Carbonite.Info\NxInfo.lua:670
 CalcCast = <function> defined @Carbonite.Info\NxInfo.lua:856
 ResetFrames = <function> defined @Carbonite.Info\NxInfo.lua:1250
 Create = <function> defined @Carbonite.Info\NxInfo.lua:505
 SetBGStartTime = <function> defined @Carbonite.Info\NxInfo.lua:1231
 CalcStat = <function> defined @Carbonite.Info\NxInfo.lua:1219
 CalcTime = <function> defined @Carbonite.Info\NxInfo.lua:1223
 UpdateItems = <function> defined @Carbonite.Info\NxInfo.lua:758
 CalcBGStats = <function> defined @Carbonite.Info\NxInfo.lua:1212
 CalcTargetMana = <function> defined @Carbonite.Info\NxInfo.lua:999
 OptionsUpdate = <function> defined @Carbonite.Info\NxInfo.lua:327
 CalcHealthPercent = <function> defined @Carbonite.Info\NxInfo.lua:884
 CalcBGHonor = <function> defined @Carbonite.Info\NxInfo.lua:1207
 CalcBGWingWait = <function> defined @Carbonite.Info\NxInfo.lua:1130
 CalcManaChange = <function> defined @Carbonite.Info\NxInfo.lua:916
 ItemFuncs = <table> {
 }
 CalcIfFalse = <function> defined @Carbonite.Info\NxInfo.lua:1176
 CalcComboPoints = <function> defined @Carbonite.Info\NxInfo.lua:953
 CalcCooldown = <function> defined @Carbonite.Info\NxInfo.lua:936
 Update = <function> defined @Carbonite.Info\NxInfo.lua:736
 OpenMenu = <function> defined @Carbonite.Info\NxInfo.lua:441
 CalcIfTrue = <function> defined @Carbonite.Info\NxInfo.lua:1170
 Menu_OnEditItem = <function> defined @Carbonite.Info\NxInfo.lua:472
 CalcTargetCast = <function> defined @Carbonite.Info\NxInfo.lua:1014
 CalcIfMana = <function> defined @Carbonite.Info\NxInfo.lua:1194
 Menu_OnNew = <function> defined @Carbonite.Info\NxInfo.lua:488
 Menu_OnDelete = <function> defined @Carbonite.Info\NxInfo.lua:492
 CalcBGStart = <function> defined @Carbonite.Info\NxInfo.lua:1103
 CalcHealthChange = <function> defined @Carbonite.Info\NxInfo.lua:888
 CalcTargetManaPercent = <function> defined @Carbonite.Info\NxInfo.lua:1006
 CalcMana = <function> defined @Carbonite.Info\NxInfo.lua:908
 Menu_OnClose = <function> defined @Carbonite.Info\NxInfo.lua:459
 Init = <function> defined @Carbonite.Info\NxInfo.lua:178
 CalcBGQueue = <function> defined @Carbonite.Info\NxInfo.lua:1078
 CalcHealth = <function> defined @Carbonite.Info\Nx

**Comment by IrcDirk** [comment]
I got it allready fixed, see why i dont comit fixes => #620
