### ISSUE TITLE
7.2 Question

### ISSUE THREAD

**Issue by yesCurtis** [mikepauer/Carbonite#623]
Just wondering if on patch day next wednesday, all the new broken shore quests are on Carbonite or not. I rely on the addon so much to get around haha!

**Comment by IrcDirk** [comment]
Carbonite uses two diffrent functions to show quests. First it searches internal quest database (wowhead scrapped not 100% update) then if quest is not found it tries to find it using another function that tries to find all data from Blizz functions, its not 100% accurate and sometimes it could be buggy but most of time it does work. So yes u should be able to see those quest in quest tracker and carb map.

**Comment by yesCurtis** [comment]
Awesome, thanks a bunch!
