### ISSUE TITLE
[Carbonite] IdToCont Err 1146

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#625]
Aalwein posted this on Wowinterface but I copied it here..

Same chat spam in the Cathedral of Eternal Light:
The first block repeats over and over while in the dungeon, the second block popped in chat after exiting the dungeon and appearing back in the Trueshot Lodge.

[Carbonite] IdToCont Err 1146
[Carbonite] GetPos Err:1146: Carbonite\NxMap.lua:9120: in function `GetWorldPos'
Carbonite.Quests\NxQuest.lua:7571: in function `UpdateIcons'
Carbonite\NxMap.lua:4736: in function `Update'
Carbonite\NxMap.lua:3714: in function <Carbonite\NxMap.lua:3620>

[1]  Changed Channel: [1. General - Trueshot Lodge]
Loot Specialization set to: Beast Mastery
[Carbonite] GetPos Err:1146: Carbonite\NxMap.lua:9120: in function `GetWorldPos'
Carbonite.Quests\NxQuest.lua:10553: in function `GetClosestObjectivePos'
Carbonite.Quests\NxQuest.lua:10492: in function `CalcDistances'
Carbonite.Quests\NxQuest.lua:8911: in function `func'
...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:48>

**Comment by IrcDirk** [comment]
Thats for rereporting here.

I think thats becouse those maps are not in carbonite table of maps. They need to be added.
