### ISSUE TITLE
Reputation Tab

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#626]
When viewing the reputation tab with Carb loaded you cannot see your progress (xxx/xxx) when hovering over the faction
![IScreenShot](http://i65.tinypic.com/212h3js.png)

**Comment by IrcDirk** [comment]
Fixed. Please check and report back.

**Comment by Palonblade** [comment]
Working for me now. Thanks so much for addressing this!

**Comment by Thrumbar** [comment]
Should close this
