### ISSUE TITLE
Warehouse module exception

### ISSUE THREAD

**Issue by wilki24** [mikepauer/Carbonite#627]
Happens every time I loot something, or change specs.

I am up to date with the submit yesterday "Fix for issue #626."

160x Carbonite\NxUI.lua:5690: attempt to index field '?' (a nil value)
Carbonite\NxUI.lua:5690: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:1884: in function `Update'
Carbonite.Warehouse\NxWarehouse.lua:1444: in function `ToggleShow'
Carbonite.Warehouse\NxWarehouse.lua:1426: in function `NXWarehouseKeyToggleShow'
[string "NxTOGGLEWAREHOUSE"]:1: in function <[string "NxTOGGLEWAREHOUSE"]:1>

Locals:

**Comment by IrcDirk** [comment]
Cant reproduce... U must describe this issue better. Step by step how to reproduce this.

**Comment by wilki24** [comment]
This has not reoccurred since that night.

Closing as CNR.
