### ISSUE TITLE
Carbonite.Quests\NxQuest.lua:6537: attempt to compare nil with number

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#631]
Have the latest git as of eb98ad62cb294e644e67232d9b6ab27433d9501c .
Was using an item that gave artifact power after gaining it in a quest when this error popped.

1x Carbonite.Quests\NxQuest.lua:6537: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6537: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6217: in function `func'
DataStore\libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5661
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:5911
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6067
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6667
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6025
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6102
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5885
 SendQInfoQI = 4
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5343
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6000
 Menu = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:5950
 FilterDescEsc = "Search: %[click%]"
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6267
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6720
 TabSelected = 1
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8149
 QOpts = <table> {
 }
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6082
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:5989
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6251
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6077
 OnQuestUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6575
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6060
 ShowAllZones = false
 Bar = <table> {
 }
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6053
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6519
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6300
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6146
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6203
 MenuIShare = <table> {
 }
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5637
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:5975
 MenuItems3 = <table> {
 }
 MenuItems1 = <table> {
 }
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6125
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6464
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6092
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8171
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:5965
 Opened = true
 SendQInfoMode = -1
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7437
 DetailsFrm = NxQuestD {
 }
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6141
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6170
 MenuItems2 = <table> {
 }
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6087
 MenuItems4 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6097
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6565
 List = <table> {
 }
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:5984
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6309
 Filters = <table> {
 }
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {

**Comment by IrcDirk** [comment]
Fixed.

**Comment by Thrumbar** [comment]
Closing as issue has not resurfaced.
