### ISSUE TITLE
Duplicate Instance/Raid Icons

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#632]
I like what you did with the Sentinax Icons, but with that change also the Orginal Blizzard Raid/Dungeon Circles came to the Carbonite map. That looks quite odd.

![wow1](https://cloud.githubusercontent.com/assets/22813377/24971613/d70cdb0c-1fb8-11e7-9a01-620bf2b5b54e.PNG)

Oh and the boss icons could be a bit smaller.

**Comment by fdellwing** [comment]
It looks really bad in dalaran:

![wow2](https://cloud.githubusercontent.com/assets/22813377/24971840/9b300c20-1fb9-11e7-9f4b-2770b1a30429.PNG)

**Comment by IrcDirk** [comment]
I know. Will fix in spare time. But that icon in dalaran its odd? I dont have this,

**Comment by fdellwing** [comment]
It is for the shaman order hall. There is a portal near the flightmaster.

**Comment by IrcDirk** [comment]
Ohh ok. Ill fix this in 2-3 days.

**Comment by fdellwing** [comment]
Thanks a lot! 👍

**Comment by IrcDirk** [comment]
Fixed.

**Comment by fdellwing** [comment]
Looks good to me.

**Comment by IrcDirk** [comment]
U can close issue ;)
