### ISSUE TITLE
Instance Maps with 7.2

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#635]
Any idea when this will be fixxed? It does not throws an error anymore, but it is not working either.

**Comment by IrcDirk** [comment]
They does work. I wrote about this in here: http://www.wowinterface.com/forums/showthread.php?t=55196

**Comment by fdellwing** [comment]
Will this work automatic like before next time soon?

**Comment by IrcDirk** [comment]
Nope.
