### ISSUE TITLE
Instance Maps

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#640]
It's always showing the starting zone of the raid instance instead of the zone you are in and you can't zoom out and in.

**Comment by IrcDirk** [comment]
Since 7.1.5 instances ware changed and they dont report player positon, so Rythal made workaround to make instance maps work again. Scrolling will not work on instance maps. U can always use alt-m to use orginal blizz map.

Ill check the issue with showing only starting zone.

**Comment by fdellwing** [comment]
Better than before but the level aka inner zone is only updating if you open the map and not while in minimap mode.

**Comment by IrcDirk** [comment]
Ok, dungeon map levels and zones should now work.

**Comment by fdellwing** [comment]
Works like a charme in DH Order Hall, so should work everythere. Good job!
