### ISSUE TITLE
Demonhunter Riftcannon not possible with Carbonite

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#644]
Trying to fire the riftcannon gives the following error on Blizzards Map (Alt+M). The error occurs before you can even fire the cannon.

Would classify that as a gamebreaking bug.

```
Date: 2017-05-03 18:39:18
ID: 1
Error occured in: AddOn: Carbonite.Quests
Count: 1
Message: Error: AddOn Carbonite.Quests attempted to call a forbidden function (SpellStopTargeting()) from a tainted execution path.
Debug:
   [C]: SpellStopTargeting()
   ..\FrameXML\WorldMapActionButton.lua:61: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:428:
      ..\FrameXML\WorldMapFrame.lua:390
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2368: SetUIPanel()
   ..\FrameXML\UIParent.lua:2445: HideUIPanel()
   ..\FrameXML\UIParent.lua:2136:
      ..\FrameXML\UIParent.lua:2128
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2930:
      ..\FrameXML\UIParent.lua:2917
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: HideUIPanel()
   Carbonite\NxMap.lua:3121: BlizzToggleWorldMap()
   Carbonite\NxMap.lua:3042:
      Carbonite\NxMap.lua:3040
   [C]: ToggleWorldMap()
   [string "TOGGLEWORLDMAP"]:1:
      [string "TOGGLEWORLDMAP"]:1
   [C]: RunBinding()
   ..\FrameXML\WorldMapFrame.lua:605:
      ..\FrameXML\WorldMapFrame.lua:602
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  AdvancedInterfaceOptions, v1.1.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.1.1
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  brokerorderhall, vv1.1.3.70100
  Carbonite, v7.2.0
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.0
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.6
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  EasyObliterate, v24
  FishingBuddy, v1.7.13a
  FlightMap, v7.0.0.6
  GarrisonCommander, v2.18.2 70200
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesSuramarLeylines, v1
  HandyNotesTrainers, v1.7.0
  HideOrderHallBar, vv1.2.3
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  MoveAnything, v16.1.7
  NomiCakes, v7.2.0.1
  NPCScan, v7.2.0.2
  Omen, v3.1.12
  OmniCC, v7.1.1
  OrderHallCommander, v1.2.2 70200
  Overachiever, v0.99.7
  OverachieverTabs, v0.99.7
  ParagonReputation, v1.11
  Pawn, v2.2.4
  PersonalLootHelper, v1.29
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Prat30, vr1054      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.9
  Quartz, v3.3.4
  Rarity, v1.0
  RarityOptions, v
  Recount, vv7.2.0b release
  SavedInstances, v7.0.8
  setItemOrder, v
  SimpleILevel, v3.3.10
  SimpleILevelGroup, v3.3.10
  SimpleILevelResilience, v3.3.10
  SimpleILevelSocial, v3.3.10
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20170502
  TipHelper, v5.12.DEV.405(/embedded)
  TradeSkillMaster, vv3.6.28
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterShopping, vv3.4.6
  TradeSkillMasterVendoring, vv3.0.6
  WeakAuras, v2.4.1
  WorldQuestGroupFinder, v0.24.3
  WorldQuestTracker, v
  WowPro, v7.1.5A
  WoWProAchievements, v7.1.5A
  WoWProDailies, v7.1.5A
  WoWProLeveling, v7.1.5A
  WowProProfession, v7.1.5A
  WoWProWorldEvents, v7.1.5A
  ZPerl, v5.2.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v7.2.0.70200 <none>
  (ck=a94)


```

**Comment by IrcDirk** [comment]
This is on latest version from here (github)? If not update and check again.

**Comment by SteveEbey73742** [comment]
Is riftcannon something specific to order hall?  My DK has a frost wyrm that clears one non-elite world quest, and I have to turn off carbonite, since the map has an added icon, but once I use the item, I turn carbonite back on.

**Comment by IrcDirk** [comment]
Blizz broke taints, to many restrictions to WorldMap... Cant manage to make workaround for this.

**Comment by fdellwing** [comment]
Its the version from yesterday. You cannot use the item, you need to click on a special button on the map.

See here: http://de.wowhead.com/spell=221561/risskanone

**Comment by IrcDirk** [comment]
Check with latest test commit from today and please report back.

**Comment by fdellwing** [comment]
Still broken with commit 6b48e660bcfe119b8b66c6674dc1e9c3e0be4a44, but its another tainted function :/

```
Date: 2017-05-04 19:01:17
ID: 1
Error occured in: AddOn: Carbonite.Quests
Count: 1
Message: Error: AddOn Carbonite.Quests attempted to call a forbidden function (UseWorldMapActionButtonSpellOnQuest()) from a tainted execution path.
Debug:
   [C]: UseWorldMapActionButtonSpellOnQuest()
   ..\FrameXML\WorldMapFrame.lua:2020:
      ..\FrameXML\WorldMapFrame.lua:2016
   [C]: ?
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  AdvancedInterfaceOptions, v1.1.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.1.1
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  brokerorderhall, vv1.1.3.70100
  Carbonite, v7.2.0
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.0
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.6
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  EasyObliterate, v24
  FishingBuddy, v1.7.13a
  FlightMap, v7.0.0.6
  GarrisonCommander, v2.18.2 70200
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesSuramarLeylines, v1
  HandyNotesTrainers, v1.7.0
  HideOrderHallBar, vv1.2.3
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  MoveAnything, v16.1.7
  NomiCakes, v7.2.0.1
  NPCScan, v7.2.0.2
  Omen, v3.1.12
  OmniCC, v7.1.1
  OrderHallCommander, v1.2.2 70200
  Overachiever, v0.99.7
  OverachieverTabs, v0.99.7
  ParagonReputation, v1.11
  Pawn, v2.2.4
  PersonalLootHelper, v1.29
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Prat30, vr1054      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.10
  Quartz, v3.3.4
  Rarity, v1.0
  RarityOptions, v
  Recount, vv7.2.0b release
  SavedInstances, v7.0.8
  setItemOrder, v
  SimpleILevel, v3.3.10
  SimpleILevelGroup, v3.3.10
  SimpleILevelResilience, v3.3.10
  SimpleILevelSocial, v3.3.10
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20170502
  TipHelper, v5.12.DEV.405(/embedded)
  TradeSkillMaster, vv3.6.28
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterShopping, vv3.4.6
  TradeSkillMasterVendoring, vv3.0.6
  WeakAuras, v2.4.1
  WorldQuestGroupFinder, v0.24.3
  WorldQuestTracker, v
  WowPro, v7.1.5A
  WoWProAchievements, v7.1.5A
  WoWProDailies, v7.1.5A
  WoWProLeveling, v7.1.5A
  WowProProfession, v7.1.5A
  WoWProWorldEvents, v7.1.5A
  ZPerl, v5.2.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v7.2.0.70200 <none>
  (ck=a95)
```

**Comment by IrcDirk** [comment]
Are u trying to complete this quest using this item on Carbonite world map World Quest circle?

**Comment by fdellwing** [comment]
Orginal Blizz map. On Carbonite Map I dont even have the spellbutton to click on.

**Comment by IrcDirk** [comment]
Works with no problem on my Paladin, should work on DH... weird... Does any one else has this quest item, which completes WQ instantly, on other class than DH or Paladin available?

**Comment by fdellwing** [comment]
Will test tommorow with any other addon disabled that hooks into the map. Just to be sure.

**Comment by SteveEbey73742** [comment]
tried on my dk, got numerous errors about protected function on map, would not show the icon to click on, with carbonite active, so just turn off carbonite, and do the quest, then turn carbonite back on.  I did not think it worth bothering, for something that is on 18 hour cooldown.

**Comment by IrcDirk** [comment]
Tried with newest commit?

**Comment by IrcDirk** [comment]
Ok, my DH is one Order Advancement before this rift core... so i will have in 2 days, then ill test this.

**Comment by mikepauer** [comment]
Possibly not relevant any longer as it's been 3 weeks since I could login to wow, but it wasn't working for warlock either.

**Comment by IrcDirk** [comment]
Always revelant since Paladin is only one that has this working... Waiting till RH get rift core to debug this.

**Comment by Palonblade** [comment]
I do this daily on a Mage, DH, Pally, DK and Warrior. All of which were are working for me. I will test latest commit and post back tomorrow.

**Comment by fdellwing** [comment]
Just to be sure, you do have Carbonite Quest enabled? Because the Bug gets thrown there and not in the Core/Map.

**Comment by IrcDirk** [comment]
Or maybe there is incompatibility with other addon...

**Comment by fdellwing** [comment]
I thougth that to but #646 said:

> After getting this I tried with only Carbonite enabled and got the same error. If I disable Carbonite.Quests the ability works fine. Latest pull from GitHub as of May 3.

Non the less I will try it myself this evening (in about 10 hours).

**Comment by IrcDirk** [comment]
Thats why im researching rift cannon on my DH :) Thanks for testing this with me.

**Comment by fdellwing** [comment]
No luck with current commit. Exact same error as yesterday :(

Also tried it with every addon disabled that possible could hook into map.

Only thing that help is to disable Carbonite Quests, all other Carbonite Modules and the Core can stay enabled.

The good news is, there is another addon (Flight Map and Time) that has the exact same problem:

```
Date: 2017-05-05 18:22:35
ID: 1
Error occured in: AddOn: FlightMap
Count: 1
Message: Error: AddOn FlightMap attempted to call a forbidden function (UseWorldMapActionButtonSpellOnQuest()) from a tainted execution path.
Debug:
   [C]: UseWorldMapActionButtonSpellOnQuest()
   ..\FrameXML\WorldMapFrame.lua:2020:
      ..\FrameXML\WorldMapFrame.lua:2016
   [C]: ?
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  NPCScanOverlay, v7.1.0.1
  AdvancedInterfaceOptions, v1.1.4
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v7.1.1
  Bartender4, v4.7.7
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  brokerorderhall, vv1.1.3.70100
  Carbonite, v7.2.0
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.2.6
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  EasyObliterate, v24
  FishingBuddy, v1.7.13a
  FlightMap, v7.0.0.6
  GarrisonCommander, v2.18.2 70200
  GarrisonCommanderBroker, v2.18.2 1.1.0
  Gatherer, v7.0.5
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesSuramarLeylines, v1
  HandyNotesTrainers, v1.7.0
  HideOrderHallBar, vv1.2.3
  LibExtraTip, v5.12.DEV.423(/embedded)
  MasterPlanA, vA
  MoveAnything, v16.1.7
  NomiCakes, v7.2.0.1
  NPCScan, v7.2.0.2
  Omen, v3.1.12
  OmniCC, v7.1.1
  OrderHallCommander, v1.2.2 70200
  Overachiever, v0.99.7
  OverachieverTabs, v0.99.7
  ParagonReputation, v1.11
  Pawn, v2.2.4
  PersonalLootHelper, v1.29
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  Postal, vv3.5.8
  Prat30, vr1054      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.10
  Quartz, v3.3.4
  Rarity, v1.0
  RarityOptions, v
  Recount, vv7.2.0b release
  SavedInstances, v7.0.8
  setItemOrder, v
  SimpleILevel, v3.3.10
  SimpleILevelGroup, v3.3.10
  SimpleILevelResilience, v3.3.10
  SimpleILevelSocial, v3.3.10
  SlideBar, v7.0.5 (<%codename%>)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20170502
  TipHelper, v5.12.DEV.405(/embedded)
  TradeSkillMaster, vv3.6.28
  TradeSkillMasterAccounting, vv3.0.19
  TradeSkillMasterAppHelper, vv3.0.3
  TradeSkillMasterAuctionDB, vv3.1.17
  TradeSkillMasterAuctioning, vv3.0.15
  TradeSkillMasterShopping, vv3.4.6
  TradeSkillMasterVendoring, vv3.0.6
  WeakAuras, v2.4.1
  WorldQuestGroupFinder, v0.24.3
  WorldQuestTracker, v
  WowPro, v7.1.5A
  WoWProAchievements, v7.1.5A
  WoWProDailies, v7.1.5A
  WoWProLeveling, v7.1.5A
  WowProProfession, v7.1.5A
  WoWProWorldEvents, v7.1.5A
  ZPerl, v5.2.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_deDE v7.2.0.70200 <none>
  (ck=a7b)
```

**Comment by Palonblade** [comment]
My Mage, DH, Pally, DK and Warrior all worked fine today with the latest commit. I run Carbonite and Carbonite Quest. You may want to try deleting your cache.

**Comment by IrcDirk** [comment]
@fdellwing disable all except Carbonite and its modules and then try.

**Comment by fdellwing** [comment]
I will tomorrow, but dont think it will change anything.

But something seems fishy here. We got 3 (4) guys with problems and 2 with no problems.

P.S. Deleting cache wont change shit, because addons dont get cached at all.

**Comment by Palonblade** [comment]
I've solved problems in the past with addons by deleting the cache and it certainly doesn't hurt to try. It may not seem to make sense but it does sometimes help.

**Comment by IrcDirk** [comment]
Other addon may override Blizz global function and can couse this sort of problems. Thats why u have to test this only with Carbonite and its modules enabled.

Tommorow ill have rift cannon available, so ill test it on my side.

**Comment by fdellwing** [comment]
Dont worry, I will try it. Not because I think it will help. But because I want to find the problem ;)

18 hours wait time to debug something is really nasty..

**Comment by IrcDirk** [comment]
Just checked code of FlightMap and it might be the problem becouse they are overriding one of Blizzard native functions. Waiting till tommorow when i get rift cannon ;)

**Comment by fdellwing** [comment]
I'm pretty sure I tried it yesterday with flightmap disabled and carbonite on. But I'm looking forward to your tests tommorow.

**Comment by ChaoticWonder** [comment]
Latest pull.  Disabled all save Carbonite modules. Cleared cache. Still fails.  "Carbonite.Quests has been blocked from an action only available to the Blizzard UI."  Enabled Swatter to get detailed error:

Date: 2017-05-05 20:30:28
ID: 1
Error occured in: AddOn: Carbonite.Quests
Count: 1
Message: Error: AddOn Carbonite.Quests attempted to call a forbidden function (UseWorldMapActionButtonSpellOnQuest()) from a tainted execution path.
Debug:
   [C]: UseWorldMapActionButtonSpellOnQuest()
   ..\FrameXML\WorldMapFrame.lua:2020:
      ..\FrameXML\WorldMapFrame.lua:2016
Locals:
None
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Carbonite, v7.2.0
  CarboniteInfo, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.0
  CarboniteSocial, v7.2.0
  CarboniteWarehouse, v7.2.0
  CarboniteWeekly, v7.2.0
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=104)

Disable Carbonite.Quests, works fine.

**Comment by Palonblade** [comment]
I only use Carb Maps and Quests. Looks like it may be coming from one of the other Carb mods. You could disable then re-enable one by one to find out which one. I don't think the others have been updated as frequently as maps and quests.

**Comment by IrcDirk** [comment]
Latest build  3cab3a1 on Paladin and Demon Hunter only enabled: Bugsack and Buggraber + Carbonite and all modules. No error using Silverhand Orders and Rift Cannon...

**Comment by fdellwing** [comment]
I have bad news...

```
Date: 2017-05-06 12:29:08
ID: 1
Error occured in: AddOn: Carbonite.Quests
Count: 1
Message: Error: AddOn Carbonite.Quests attempted to call a forbidden function (UseWorldMapActionButtonSpellOnQuest()) from a tainted execution path.
Debug:
   [C]: UseWorldMapActionButtonSpellOnQuest()
   ..\FrameXML\WorldMapFrame.lua:2020:
      ..\FrameXML\WorldMapFrame.lua:2016
Locals:
None
AddOns:
  Swatter, v7.0.5 (<%codename%>)
  Carbonite, v7.2.0
  CarboniteQuests, v7.2.0
  BlizRuntimeLib_deDE v7.2.0.70200 <none>
  (ck=79)
```

Any more ideas?

**Comment by IrcDirk** [comment]
Open Carbonite.lua in Carbonite folder and please find string starting with: "-- Commit:" paste me whole line.

Another thing it might be other configuration then mine... shit thats hard to simulate. Can u pack your Wow WTF folder and upload it somewhere? This way my configuration would be the same as yours.

**Comment by fdellwing** [comment]
-- Commit: 2017-05-05 12:51:23 +0200 (3cab3a1)
(Did no yet updated today)

http://files.zerosgaming.de/user/public/WTF.rar

**Comment by IrcDirk** [comment]
Thanks, will try on your settings, but tommorow when rift cannon is available.

**Comment by IrcDirk** [comment]
U are using German client?

**Comment by fdellwing** [comment]
Yes, I'm german and using german client. But that does not seems to be the problem, because @ChaoticWonder is using the english one and having same problems.

**Comment by IrcDirk** [comment]
U can delete it.

He is using enUS im enGB... that so weird.

**Comment by fdellwing** [comment]
Let's check something here: Who is using BlizzMap in fullscreen mode?

@IrcDirk @SteveEbey73742 @Palonblade @ChaoticWonder

**Comment by IrcDirk** [comment]
Not me, but will try that tommorow.

**Comment by ChaoticWonder** [comment]
If that's using alt-M to bring up the blizz map, that's what I have been doing.

**Comment by fdellwing** [comment]
Well my thoughts are indeed corrent @IrcDirk ;)

In non-fullscreen mode it is working fine. Now you might have something to begin finding the problem.

(It's not working in non-fullscreen for FlightMap, but thats not your story)

**Comment by ChaoticWonder** [comment]
The only way I've found to use the Unleash Infernal ability is to bring up the Blizz map.  Whether full screen or smaller window, it doesn't work if Carbonite.Quest is enabled.

**Comment by fdellwing** [comment]
This skills will always and ever only work on BlizzMap, because there isn't even an button on CarbMap.

Does not work:
![wow4](https://cloud.githubusercontent.com/assets/22813377/25778591/eccc2350-3302-11e7-83b2-85c8570e6696.PNG)


Does work;
![wowscrnshot_050717_085440](https://cloud.githubusercontent.com/assets/22813377/25778587/e5081318-3302-11e7-9451-e437cf4a4159.jpg)

**Comment by IrcDirk** [comment]
Just used rift cannon with fullsized map: https://youtu.be/XwpMVXfsnOk

**Comment by fdellwing** [comment]
Ok, that is really really strange...

**Comment by IrcDirk** [comment]
Yep, i doesnt understand that :(

**Comment by ChaoticWonder** [comment]
Latest build works on my Warlock.  Fingers crossed for other classes.

**Comment by IrcDirk** [comment]
@ChaoticWonder please report back with results on other classes :)

**Comment by fdellwing** [comment]
Will check this evening. But it will get late today.

**Comment by fdellwing** [comment]
Works now in Fullscreen as well... I dont understand this world anymore!

**Comment by IrcDirk** [comment]
I think this is resovled but let more people confirm this also before closing.

**Comment by SteveEbey73742** [comment]
using latest commit, mage and dk both still have the issue.  I wonder if the options in carbonite have to be set a specific way.  @Palonblade  can you tell me your map options in carbonite, so I can see if mine are different. I would like to solve this, once and for all.

**Comment by IrcDirk** [comment]
Are u sure this is becouse of Carbonite and not other addon that makes the problem? U did checked it only with Carbonite + modules enabled?

**Comment by SteveEbey73742** [comment]
@ircdirk, of course, latest, only carb running, so forth.  my fork is matched with master, I have been very busy with network penetration testing, to do any coding on my fork, but I have been keeping my fork current.  I thought the options could have some affect and wanted to know what @Palonblade has set for map options, to see if changing something makes it work.  if it is working for you, then share your map options with me, and I will see if matching those options makes it work.

**Comment by Palonblade** [comment]
I'm not sure which map options you mean as there are quite a few. 
![carbmo](https://cloud.githubusercontent.com/assets/22230769/25930656/6698ae36-35d5-11e7-8187-2417edae41bb.png)

**Comment by SteveEbey73742** [comment]
Thank you @Palonblade that does help.  I have a check mark, in that first option, to use the carbonite map. When I use the blizzard map, by pressing Alt-M the function works.  I will remove the check mark, and see if I like using blizzard instead of carbonite map.  I have 5 toons, at 110, that have the appropriate bonus weapon, to do world quests with the map button, will test all of them.  Thanks again for posting that.

**Comment by IrcDirk** [comment]
I have check mark at first option and all works fine. But u need to use this bonus weapon on Blizz Map it will never work with Carbonite.

**Comment by SteveEbey73742** [comment]
Yes, came to that conclusion as well. Thanks.I would consider this fixed, and this topic closed, unless others have problems still.

**Comment by IrcDirk** [comment]
What bonus weapon did u used?

**Comment by SteveEbey73742** [comment]
did both, mage and dk as they were off cooldown. have not researched the rift canon on demon hunter, and have not checked if marksman hunter has the option.  Druid has not been active, been having too much fun with fire mage.
