### ISSUE TITLE
 Carbonite\NxMap.lua:8281: attempt to get length of local 'info' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#645]
Doing Alterac Valley and get this error.  With build commit 841f6e01443c8453e85b54886bd928cf20d514ef

7731x Carbonite\NxMap.lua:8281: attempt to get length of local 'info' (a nil value)
Carbonite\NxMap.lua:8281: in function `UpdateInstanceMap'
Carbonite\NxMap.lua:4561: in function `Update'
Carbonite\NxMap.lua:3775: in function <Carbonite\NxMap.lua:3664>

Locals:
self = <table> {
 MiniBlks = 40
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 TargetNextUniqueId = 1
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 0
 WorldHotspots = <table> {
 }
 Menu = <table> {
 }
 EffScale = 0.63999998569489
 Zone = 401
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 4
 BackgndAlphaFade = 0.4
 MoveLastX = 6132.9543832281
 PlyrDir = 0
 PlyrSpeedCalcTime = 894346.42
 MapPosYDraw = 2482.499991862
 ArchAlpha = 0.3
 MenuIInstanceMaps = <table> {
 }
 CurMapBG = true
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 489.79986572266
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 277.00003051758
 MMScales = <table> {
 }
 MapPosX = 18423.749987793
 BackgndAlphaTarget = 0.4
 MoveDir = 180
 BGGrowBars = true
 ArrowScroll = 0.46
 H = 141
 Tick = 41404
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 1597.3090139592
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 0.99100114219971
 PlyrX = 6132.9543832281
 QuestAlpha = 0.3
 CurWorldUpdateOverlayNum = 1
 Scale = 4
 TextFrm = <unnamed> {
 }
 BackgndAlpha = 0.4
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 401
 MMOwn = false
 Size1 = 1.1718750261934
 ShowUnexplored = false
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 DotRaidScale = 1.0900033876829
 PlyrSpeedY = 1597.3090139592
 StepTime = 0
 PlyrSpeedX = 6132.9543832281
 PlyrFrm = <unnamed> {
 }
 IconWQFrms = <table> {
 }
 ScaleDrawW = 0.25
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1
 MiniFrms = <table> {
 }
 InCombat = false
 Win = <table> {
 }
 InstanceId = false
 RealScale = 4
 Data = <table> {
 }
 TrackDir = false
 MenuIShowTimber = <table> {
 }
 CurOverlays = false
 WorldHotspotTipStr = "Eastern Kingdoms, |cff20ff20Stormwind City (City)
"
 LocTipFStrs = <table> {
 }
 TrackPlyrs = <table> {
 }
 TrackETA = false
 Targets = <table> {
 }
 TextScFrm = <unnamed> {
 }
 PlyrY = 1597.3090139592
 GIconMenuIFindNote = <table> {
 }
 PlyrRZY = 85.529100894928
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 MapPosY = 2482.499991862
 TextFStrs = <table> {
 }
 Scrolling = false
 Tracking = <table> {
 }
 Cont = 90
 Level = 4
 MenuIMonitorZone = <table> {
 }
 LocTipFrm = NxMapTip {
 }
 MapIndex = 1
 GIconMenu = <table> {
 }
 TransMenu = <table> {
 }
 DebugAdjustScale = 0.1
 ContFrms = <table> {
 }
 PlyrSpeed = 0
 TileFrms = <table> {
 }
 ScaleW = 0.25
 UpdateTargetDelay = 0
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 IconFrms = <table> {
 }
 MapScale = 0.39920159680639
 BGIconMenu = <table> {
 }
 MMOwnedFrms = <table> {
 }
 W = 150
 CurWorldUpdateMapId = -1
 PlyrRZX = 55.694305896759
 KillShow = false
 MMChkDelay = 2
 NeedWorldUpdate = true
 MapPosXDraw = 18423.749987793
 MapsDrawnOrder = <table> {
 }
 Frm = <unnamed> {
 }
 MapsDrawnFade = <table> {
 }
 BackgndAlphaFull = 1
 DotZoneScale = 0.99100114219971
 DotPalScale = 1
}
mapId = 401
Map = <table> {
 Menu_OnTrackPlyr = <function> defined @Carbonite\NxMap.lua:2777
 GetInstanceID = <function> defined @Carbonite\NxMap.lua:8716
 ZoneOverlays = <table> {
 }
 HideExtraFrames = <function> defined @Carbonite.Info\NxInfo.lua:1261
 GetZoneAchievement = <function> defined @Carbonite\NxMap.lua:10332
 MinimapOwnInit = <function> defined @Carbonite\NxMap.lua:1813
 RestoreBlizzBountyMap = <function> defined @Carbonite\NxMap.lua:3104
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Carbonite\NxMap.lua:2419
 OnButToggleGuide = <function> defined @Carbonite\NxMap.lua:1587
 GetWinName = <function> defined @Carbonite\NxMap.lua:1172
 SetToCurrentZone = <function> defined @Carbonite\NxMap.lua:8798
 GetIconStatic = <function> defined @Carbonite\NxMap.lua:7891
 UpdateToolBar = <function> defined @Carbonite\NxMap

**Comment by IrcDirk** [comment]
Ok, i think i know whats wrong, ill push fix for this later today :)

**Comment by IrcDirk** [comment]
Ok please test it and report back.

**Comment by Thrumbar** [comment]
Two runs and no errors so calling it fixed...
