### ISSUE TITLE
After closing BlizzMap CarbMap is open

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#648]
So I'm pressing Alt+M to see the BlizzMap and than Esc to close it. I end up with an open CarbMap. This behaviour is new with one of the latest commits and going on my nerves :/

**Comment by IrcDirk** [comment]
Im closing blizz map with Alt-M so doesnt have this behaviour. Ill check this.

**Comment by IrcDirk** [comment]
Working for me fine... do u have mini map combined with carbonite map?

**Comment by fdellwing** [comment]
What do you mean?

**Comment by IrcDirk** [comment]
![scr](http://i.imgur.com/FrwA1Ns.png)

**Comment by fdellwing** [comment]
Yes, I do have.

**Comment by IrcDirk** [comment]
Cant reproduce :(

**Comment by fdellwing** [comment]
You know have my settings, so it should behave identical!?

**Comment by IrcDirk** [comment]
And it works fine... Could be another addon, please try only with Carbonite enabled.

**Comment by fdellwing** [comment]
So, I tried some older commits and I remembered correct ;)

6aa7cf998d4d5b95fe68ddcc5bd5dfab70b972ca works fine with escape

6b48e660bcfe119b8b66c6674dc1e9c3e0be4a44 doesn't anymore

There are only 2 commits between that could cause that 2cd8922b35ed73a950184e492cca4661de39b307 and 6b48e660bcfe119b8b66c6674dc1e9c3e0be4a44 itself. Have fun fixxing it :D

**Comment by IrcDirk** [comment]
I now what i have changed. But on my side all works ok, even with your settings.

**Comment by IrcDirk** [comment]
Can u check this with latest build? I have changed some functions it might fix your problem.

**Comment by IrcDirk** [comment]
OK... got it u have full screen Blizz Map ;) Now i can reproduce this... trying to fix...

**Comment by fdellwing** [comment]
Yeah, full screen. Can't see shit on the small one :D

**Comment by fdellwing** [comment]
Fixed.
