### ISSUE TITLE
AddOn 'Carbonite.Quests' tried to call the protected function '<unnamed>:Hide()'.

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#650]
Got this while standing in combat and pressing alt-M with Carbonite only active and of cource buggrabber/Bugsack also active..   Strangly it only happened the first time,  I wiped the bugs and reentered combat, hit alt-M and the error did no happen again untill I did a reload of the ui...

1x [ADDON_ACTION_BLOCKED] AddOn 'Carbonite.Quests' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function `Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function `SetMapAreaID'
FrameXML\WorldMapFrame.lua:1338: in function `WorldMapFrame_Update'
FrameXML\WorldMapFrame.lua:2883: in function `WorldMapFrame_UpdateMap'
FrameXML\WorldMapFrame.lua:450: in function <FrameXML\WorldMapFrame.lua:434>
[C]: in function `SetMapToCurrentZone'
FrameXML\WorldMapFrame.lua:379: in function <FrameXML\WorldMapFrame.lua:358>
[C]: in function `Show'
FrameXML\UIParent.lua:2373: in function `SetUIPanel'
FrameXML\UIParent.lua:2212: in function `ShowUIPanel'
FrameXML\UIParent.lua:2132: in function <FrameXML\UIParent.lua:2128>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2914: in function <FrameXML\UIParent.lua:2902>
[C]: ?
[C]: ?
[C]: in function `ShowUIPanel'
FrameXML\UIParent.lua:2898: in function `ToggleFrame'
FrameXML\WorldMapFrame.lua:263: in function <FrameXML\WorldMapFrame.lua:235>
[C]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

**Comment by IrcDirk** [comment]
U sure u are using latest? Made some changes lately. Cant reproduce.

**Comment by Thrumbar** [comment]
Updated and issue gone..
