### ISSUE TITLE
Carbonite\NxUI.lua:5595: attempt to perform arithmetic on local 'colW' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#651]
Get this when trying to open warehouse in combat
Warehouse window empty if opened in combat

1x Carbonite\NxUI.lua:5595: attempt to perform arithmetic on local 'colW' (a nil value)
Carbonite\NxUI.lua:5595: in function `CreateStrings'
Carbonite\NxUI.lua:5695: in function `Update'
Carbonite\NxUI.lua:5436: in function `SetSize'
Carbonite\NxUI.lua:1918: in function `Adjust'
Carbonite\NxUI.lua:1820: in function `Attach'
Carbonite.Warehouse\NxWarehouse.lua:1255: in function `Create'
Carbonite.Warehouse\NxWarehouse.lua:1436: in function `ToggleShow'
Carbonite.Warehouse\NxWarehouse.lua:1426: in function `NXWarehouseKeyToggleShow'
[string "NxTOGGLEWAREHOUSE"]:1: in function <[string "NxTOGGLEWAREHOUSE"]:1>

Locals:

**Comment by Thrumbar** [comment]
Still getting this error then clicking on the Weekly tracker and Notes icon in the bottom of the Carbonite map (press m map)..

**Comment by IrcDirk** [comment]
OK, so this the same for those others modulse but warehouse and social are ok now?

**Comment by Thrumbar** [comment]
Yes no error there,

**Comment by Thrumbar** [comment]
See
#657 
for info on exact error as warehouse issue is fixed
