### ISSUE TITLE
Zeppelin Icons in OG are gone

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#654]
Dont know since when, but zeppelin icons in og are gone. They are still there in stv. I cant ever remember there which fucker is, so please dont do that to me.

![wowscrnshot_050617_201044](https://cloud.githubusercontent.com/assets/22813377/25774859/28114e9c-3298-11e7-92d5-cd55e7ca0af4.jpg)

**Comment by IrcDirk** [comment]
They where not updated since i think Mop extension.

**Comment by fdellwing** [comment]
They where definitly there in WoD and I'm pretty sure they are there last time I used a zeppelin. But that was quite a while ago. I would say early november 2016?

**Comment by fdellwing** [comment]
Works, but now the level update does not work anymore in og while getting underground. Need to open and close map.

**Comment by IrcDirk** [comment]
Closing this issue. Open another for new problem.
