### ISSUE TITLE
Warehouse Currency array index

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#667]
Date: 2017-05-13 10:39:59
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Warehouse\NxWarehouse.lua line 1841:
   attempt to index field 'Currency' (a nil value)
Debug:
   Carbonite.Warehouse\NxWarehouse.lua:1841: Update()
   Carbonite.Warehouse\NxWarehouse.lua:1295: Create()
   Carbonite.Warehouse\NxWarehouse.lua:1445: ToggleShow()
   Carbonite.Warehouse\NxWarehouse.lua:847: func()
   ..\FrameXML\UIDropDownMenu.lua:791: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
self = <table> {
 OnButToggleWarehouse = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3506
 AddBag = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2959
 OnLoot_opened = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3219
 NXEqRarityMin = 7
 CaptureGet = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3298
 OnUnit_spellcast_succeeded = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1122
 OnItem_lock_changed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2824
 UpdateItem = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2231
 CaptureItems = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2888
 ToggleShow = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1442
 OnGuildbankframe_closed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2730
 ImportDo = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1382
 AddLink = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2977
 Menu_OnRemoveChar = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1345
 Menu_OnShowItemCat = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1411
 UpdateBlank = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1912
 Menu_OnSortByRarity = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1416
 SelectedChar = 1
 OnTime_played_msg = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1099
 TooltipProcess = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2639
 Menu_OnSortBySlot = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1425
 Menu_OnSyncAccount = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1404
 DurTooltipFrm = NxTooltipD {
 }
 OnChat_msg_skill = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3311
 OnBankframe_closed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2712
 RecordCharacter = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3539
 ReftipProcess = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2600
 ExportDo = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1397
 Win = <table> {
 }
 Menu_OnExport = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1392
 FindCharsWithItem = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2332
 ScanRBank = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2950
 OnLoot_slot_cleared = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3236
 OnItemListEvent = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1553
 OnUnit_inventory_changed = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2999
 InitWarehouseCharacter = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3510
 ConvertData = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:899
 UpdateGuild = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1919
 OnListEvent = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1473
 Menu = <table> {
 }
 EditBox = <table> {
 }
 prtdb = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1213
 ItemList = <table> {
 }
 OnEditBox = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1462
 CaptureUpdate = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:2875
 List = <table> {
 }
 CaptureInvDurabilityTimer = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:3159
 UpdateItems = <function> defined @Interface\AddOns\Carbonite.Warehouse\NxWarehouse.lua:1984
 ShowItemCategory = true
 UpdateProfes
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BigWigs, vv53
  BonusRollPreview, v70200.39-Release
  Carbonite, v7.2.0
  CarboniteNotes, v7.2.0
  CarboniteQuests, v7.2.0
  CarboniteWarehouse, v7.2.0
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v10.52
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  GoldBanker, v1.3
  Healium, v
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  NomiCakes, v7.2.0.2
  PetBattleTeams, v3.3.7
  Postal, vv3.5.8
  ProspectBarLives, v2.7
  RepSwitch, v7.0.3.8
  SilverDragon, vv4.0.2
  SilverDragonBurningCrusade, vv4.0.2
  SilverDragonCataclysm, vv4.0.2
  SilverDragonLegion, vv4.0.2
  SilverDragonMists, vv4.0.2
  SilverDragonVanilla, vv4.0.2
  SilverDragonWarlords, vv4.0.2
  SilverDragonWrath, vv4.0.2
  Skada, v1.6.6
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.11.2.70200
  TitanBag, v5.11.2.70200
  TitanClock, v5.11.2.70200
  TitanCurrency, v7.1
  TitanGold, v5.11.2.70200
  TitanLocation, v5.11.2.70200
  TitanLootType, v5.11.2.70200
  TitanPerformance, v5.11.2.70200
  TitanRepair, v5.11.2.70200
  TitanVolume, v5.11.2.70200
  TitanXP, v5.11.2.70200
  WoWTokenWatch, v1.0.3
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=adc)

Got the same error, all addons off, but Carbonite and warehouse.  Been trying to figure it out, no luck.

**Comment by mikepauer** [comment]
came because chars not logged in yet had no saved currency info for new tables. Should be fixed.
