### ISSUE TITLE
Handynotes and Carbonite Notes

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#671]
Vid: https://youtu.be/0FBEY_mHUkw

Edit:  The mini map poof when I enter the shrine of the Seven Stars will stay gone even with reload untill I exit it and either port (Hearth) or do a reload..

I currently have the minimap not combined with Caronite's.

Noticed that if I have Handynoted installed on my Fury Warrior my minimap disappears.  Tried with only Carbonite and handynotes and the same.  

1. Disabled all but Carb Maps and Handynotes the minimap is there.
2. Activated Info and no change
3. Activated Items no change
4. Activated notes and minimap vanished (the header is still there but no map or buttons)
5 Got the minimap with just all the others leaded but when I activate notes no minimap..

The install is the lateat from Curse for Handynotes and Carbonite as of Build https://github.com/mikepauer/Carbonite/commit/aa2ded7fdd6c33562ff31806a790a31e9a2399f0

Will try deleting SVs for both to double check...

Will not show when Carbonite, Carbonite Notes, Carbonite Quest and Handynotes are active.

Deleted Carbonite and it's SVs and reinstalled but when I have Handynotes and Carb (Maps, Notes and Quest) active minimap poof......

**Comment by IrcDirk** [comment]
Yep, i was testing something and i forgot to comment one line of code. Sorry for that. Now all should be ok.

**Comment by Thrumbar** [comment]
Comfirmed, closing...
