### ISSUE TITLE
Empty quest dialog box 

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#70]
After turning in quest then auto accepting the next one in a chain an empty quest dialog box is still present.

**Comment by samyonair** [comment]
Issue still there if you have the option to accept Quests automatic and you first Open a Questgiver, finishing a Quest first and the Questgiver has a new Quest for You, auto accept it, a frame from quest is still opend after accepting a Quest.

Have seen it in the morning on Legendary Questline

**Comment by atk** [comment]
I have just updated the API change that blizzard had actually introduced in MoP for AutoAcceptQuests.

**Comment by atk** [comment]
Can anybody please test if my fix actually worked?

**Comment by samyonair** [comment]
If I Have time on weekend to take a char do quets I will do

**Comment by Thrumbar** [comment]
As of commit commit bb69962bf31b2a210c7f45b00ab38fa664743008 the issue is still there. Clean install from git..
http://youtu.be/G5GFtZnpuSQ

**Comment by Thrumbar** [comment]
Would the correct API for this be the following
GetNumGossipAvailableQuests - Returns the number of quests (that you are not already on) offered by this NPC
GetGossipActiveQuests - Get the list of active quests from an NPC.
SelectGossipAvailableQuest - Selects an available quest from a gossip list.

As AutoAcceptQuests - Auto Accept refers to quests that are offered to a player automatically via a popup message usually on the upper right of the screen. These quests are triggered by various factors such as entering a subzone, killing a type of mob, or reaching a certain level.

**Comment by samyonair** [comment]
Think has nothing to do with accepting a quest, but from handling a quest to an npc, because failure on my side only if I am Have finished quests to leave at npc and than turning auto in.

Greetings Samyonair
but your Idea atl should look into it

**Comment by IrcDirk** [comment]
Can any one reroduce this in Live version?
