### ISSUE TITLE
Watch window jumps to top 

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#71]
When moving the quest watch window to top area it jumps and locks to top edge.  This places the menu under my brokerbar forcing me to either move the bar or block it's display until I can move the quest watch window.

**Comment by atk** [comment]
Could you please test if the bug still occurs?

**Comment by Thrumbar** [comment]
Yes it is still there ac of patch "Merge pull request #253 from Kaboca/master"

**Comment by IrcDirk** [comment]
Yes same here. Bug stil is anoying.
