### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#73]
I am getting low FPS in LFR with Carb Maps loaded. I did some playing around and was unable to fix the issue but did find something strange which may be related. When in my mage order hall my FPS drops to the 30s. If I simply open the main map it jumps back up to the 70s. I can do this over and over again...open main map FPS goes up, close main map FPS goes down. 
![carb map2](https://user-images.githubusercontent.com/22230769/33923972-e0dd5310-dfa1-11e7-8bf2-43653865bd40.png)
![carb map](https://user-images.githubusercontent.com/22230769/33924030-2803b25c-dfa2-11e7-83f0-fdad420999a3.png)

Same goes for warrior order hall. Will test next LFR I do.

**Comment by IrcDirk** [comment]
Disable all addons and test this only with carbonite + modules enabled... It might be another addon that fucks up events...

**Comment by Palonblade** [comment]
Good call, I should have tried this first before posting. It appears the addon SavedInstances was causing issues. I will test in LFR later without SavedInstances loaded. Why would simply loading the main map improve the FPS so drastically?

**Comment by mikepauer** [comment]
Because maps has a kill switch when the regular map is open to avoid map
jumping if your trying to view other zones. So when the full map is open
carbonite maps stops doing anything at all (or suppose to do).

**Comment by IrcDirk** [comment]
@mikepauer is right... but it shouldnt go from 70 to 30.
