### ISSUE TITLE
PTR 7.3.5

### ISSUE THREAD

**Issue by wownob** [mikepauer/Carbonite#74]
PTR 7.3.5
Only Addons: Carbonite Maps and Quest - Swatter
Without Swatter the same error is repeating in an endless loop. 
Repeating error:
Date: 2017-12-27 17:50:43
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite\NxMap.lua line 4578:
   Division by zero
Debug:
   Carbonite\NxMap.lua:4578: Update()
   Carbonite\NxMap.lua:3816:
      Carbonite\NxMap.lua:3700
Locals:
self = <table> {
 PlyrSpeedX = 6154.0434899756
 MiniBlks = 6
 IconScale = 3
 MapPosX = 6154.0434899756
 Scale = 1.2332131597327
 MenuIShowWorld = <table> {
 }
 TextFrm = <unnamed> {
 }
 ScaleDrawW = 0.81088982233758
 InstanceId = false
 CurMapBG = false
 GIconMenuITogInst = <table> {
 }
 BackgndAlpha = 0.05
 Targets = <table> {
 }
 ArrowPulse = 1
 Cont = 2
 Zone = 301
 PlyrY = 1575.46894379
 Level = 3
 MMScalesC = <table> {
 }
 LastDungeonLevel = 0
 LOpts = <table> {
 }
 Guide = <table> {
 }
 PlyrLastDir = 320.35284873615
 WorldHotspots = <table> {
 }
 W = 150
 MMModels = <table> {
 }
 Menu = <table> {
 }

**Comment by IrcDirk** [comment]
Where did u tested this? Which zone? Do u use alpha version of Carbonite and its Modules?

I have tested Carbonite in PTR Dalaran and Val'sharah **no errors**.

**Comment by IrcDirk** [comment]
Checked other zones no errors... Update to latest Alpha release, disable all other addons and then check if this still occours.

**Comment by wownob** [comment]
Installed alpha for Carbonite Maps and Quest via Curse.
Enabled Addons: Carbonite Maps only.
Language: German.
Location: Stormwind.
Same error as above.

**Comment by IrcDirk** [comment]
Im using English client but this should not be the problem. All works fine. Can anyone confirm this?

In meanwhile can u reset your profile? Then do reload.

![how to reset profile](https://i.imgur.com/kqKtva8.png)

**Comment by wownob** [comment]
I think it was a config error.
I copied my original WTF content to the PTR WTF.
After resetting the error is now gone.
Sorry for your effort.

**Comment by IrcDirk** [comment]
Good to know thats all is good and dont be sorry, this is the right place for such issues ;)
