### ISSUE TITLE
Quest waypoints completely broken in druid orderhall

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#8]
Just look at the pictures...

![wowscrnshot_061117_160630](https://user-images.githubusercontent.com/22813377/27011635-4882b208-4ec0-11e7-9d2d-1f21c80c9664.jpg)
![wowscrnshot_061117_160634](https://user-images.githubusercontent.com/22813377/27011637-48906204-4ec0-11e7-96c9-c3871ab5eacd.jpg)
![wowscrnshot_061117_160725](https://user-images.githubusercontent.com/22813377/27011638-48909bfc-4ec0-11e7-84ff-c0781bc463ae.jpg)
![wowscrnshot_061117_160730](https://user-images.githubusercontent.com/22813377/27011636-488e78f4-4ec0-11e7-805d-2a9a40505d2c.jpg)

The end marker is moving on the map as you move. The big map and minimap are not showing the marker in the same position and the markers are in the wrong position all together,

**Comment by fdellwing** [comment]
Oh, and no red line behind me. So, dont know where I came from..

**Comment by fdellwing** [comment]
https://youtu.be/UkQ2FBJDHuI

Short video, showing the problem better than any image

**Comment by Thrumbar** [comment]
This is related to changes Blizzard made to instances.   Happens in Shaman Maelstorm also...

**Comment by IrcDirk** [comment]
U can disable "instance maps", there is an alternative method that draws maps in instances "the old way". They are some limitation to this but mostly it works.

**Comment by IrcDirk** [comment]
@mikepauer made some changes this could be fixed now. U need to check this with latest alpha version.

**Comment by fdellwing** [comment]
Yeah it is, already checked it yesterday.
