### ISSUE TITLE
Carbonite Quest no longer able to link quests in chat while Elvui is enabled - but the error only mention Carbonite

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite#81]
Yesterday everything was working fine. No errors, no bugs, no nothing.

Information:
Today, I see that there's an update for Elvui via the Tukui Client, so I update Elvui.
I check the Twitch Client too, but there aren't any updates for me today
I also had a driver update for my graphic card today, so I update that too.

Explanation:
I log in to wow, first my bank toon, then my main toon.. At some point I decide that I want to ask my guildies if there's anyone of them, that's not a tank, that want's to do:  [110] [The Seat of the Triumvirate: Armor of the Triumvirate] ?
I never get a reply, because no one inc. my self, can see it linked in chat. I then try to link it in a whisper and nothing shows.. No links, no errors, no bugs
Then I try and link to both the guild chat and after in a whisper: an ability from my spellbook, an item from my bag and a recipe from cooking - that works and gets linked so both my online guildies, bnet whisper (the one I linked in whisper to check if it worked there too) and my self can see them.. hmm.
I turn Elvui off, and I still can't link any of my 3 quests, not even World Quests/Invasion Quests (I tried when I was 1st in Azsuna, and 2nd in Suramar - no such luck)
I then try to link a different quest: 110 Trial of Valor: The Lost Army and I get the below error:

6x Carbonite.Quests\NxQuest.lua:6631: attempt to compare nil with number
Carbonite.Quests\NxQuest.lua:6631: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6460: in function `UserFunc'
Carbonite\NxUI.lua:6455: in function <Carbonite\NxUI.lua:6434>

Locals:
self = <table> {
 UpdateMenu = <function> defined @Carbonite.Quests\NxQuest.lua:5754
 Win = <table> {
 }
 Menu_OnShowHeaders = <function> defined @Carbonite.Quests\NxQuest.lua:6147
 MakeDescLink = <function> defined @Carbonite.Quests\NxQuest.lua:6613
 Menu_OnTrackNone = <function> defined @Carbonite.Quests\NxQuest.lua:6394
 Menu_OnWatchAll = <function> defined @Carbonite.Quests\NxQuest.lua:6240
 TabSelected = 1
 Menu_OnHighPri = <function> defined @Carbonite.Quests\NxQuest.lua:6138
 FilterOnEditFocusLost = <function> defined @Carbonite.Quests\NxQuest.lua:6059
 Menu_OnShowAllQuests = <function> defined @Carbonite.Quests\NxQuest.lua:6161
 Menu_OnShowFinished = <function> defined @Carbonite.Quests\NxQuest.lua:6181
 Menu_OnGoto = <function> defined @Carbonite.Quests\NxQuest.lua:6119
 MenuIShare = <table> {
 }
 DetailsFrm = NxQuestD {
 }
 MenuItems4 = <table> {
 }
 MenuItems3 = <table> {
 }
 MenuItems2 = <table> {
 }
 Menu_OnCompleted = <function> defined @Carbonite.Quests\NxQuest.lua:6196
 Select = <function> defined @Carbonite.Quests\NxQuest.lua:5979
 OnDetailsSetSize = <function> defined @Carbonite.Quests\NxQuest.lua:8099
 Open = <function> defined @Carbonite.Quests\NxQuest.lua:5442
 OnTabBar = <function> defined @Carbonite.Quests\NxQuest.lua:6094
 AttachFrames = <function> defined @Carbonite.Quests\NxQuest.lua:5730
 Menu = <table> {
 }
 FilterOnTextChanged = <function> defined @Carbonite.Quests\NxQuest.lua:6069
 List = <table> {
 }
 FilterOnEditFocusGained = <function> defined @Carbonite.Quests\NxQuest.lua:6044
 Filters = <table> {
 }
 FilterDescEsc = "Search: %[click%]"
 FilterDesc = "Search: [click]"
 FilterFrm = NxQuestFilter {
 }
 MenuItems1 = <table> {
 }
 Menu_OnShowParty = <function> defined @Carbonite.Quests\NxQuest.lua:6191
 QOpts = <table> {
 }
 OnSendQuestInfoTimer = <function> defined @Carbonite.Quests\NxQuest.lua:6297
 Menu_OnAbandon = <function> defined @Carbonite.Quests\NxQuest.lua:6361
 Menu_OnHistoryRemoveAll = <function> defined @Carbonite.Quests\NxQuest.lua:6219
 ToggleWatch = <function> defined @Carbonite.Quests\NxQuest.lua:6558
 Menu_OnShowOnlyDailies = <function> defined @Carbonite.Quests\NxQuest.lua:6186
 DetailsSetWidth = <function> defined @Carbonite.Quests\NxQuest.lua:8121
 Menu_OnShowAllZones = <function> defined @Carbonite.Quests\NxQuest.lua:6176
 Opened = true
 Update = <function> defined @Carbonite.Quests\NxQuest.lua:6823
 CheckShow = <function> defined @Carbonite.Quests\NxQuest.lua:7540
 LogUpdate = <function> defined @Carbonite.Quests\NxQuest.lua:6769
 FilterOnEscapePressed = <function> defined @Carbonite.Quests\NxQuest.lua:6083
 Menu_OnShare = <function> defined @Carbonite.Quests\NxQuest.lua:6345
 Menu_OnShowHighLevel = <function> defined @Carbonite.Quests\NxQuest.lua:6171
 SendQuestInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6274
 Menu_OnSortWatched = <function> defined @Carbonite.Quests\NxQuest.lua:6235
 Refresh = <function> defined @Carbonite.Quests\NxQuest.lua:6659
 GetCurSelected = <function> defined @Carbonite.Quests\NxQuest.lua:6005
 FilterOnEnterPressed = <function> defined @Carbonite.Quests\NxQuest.lua:6078
 OnListEvent = <function> defined @Carbonite.Quests\NxQuest.lua:6403
 Menu_OnSendQInfo = <function> defined @Carbonite.Quests\NxQuest.lua:6264
 Menu_OnShowObjectives = <function> defined @Carbonite.Quests\NxQuest.lua:6154
 ShowAllZones = false
 Menu_OnShowLowLevel = <function> defined @Ad

And "big sigh"... I land, HS to my Garrison for easy log out/log in/reloads
I disable all addons for All toons and do a /reload
I enable Carbonite Maps and Carbonite Quest, /reload and try to link in guild chat. That works.
I disable Carbonite Maps and Carbonite Quest and Enables Elvui + Elvui Config and /reload and link in chat - that works. 
I enable Carbonite Maps + Carbonite Quest along with Elvui, Elvui Config then /reload and try to link in chat - that doesn't work. I then try to link the 110 Trial of Valor Quest and get the above error.
I disable Elvui and Elvui Config leaving Carbonite Maps and Quests on do a /reload and try to link the 110 Trial of Valor and get the above error again.
I've established that Elvui works without Carbonite and Carbonite works without Elvui and both works together IF I don't link any quests in any chat, but that I can link anything else with all addons on so long as it's not a quest that I link.
While having Carbonite Maps + Carbonite Quest on I enabled 2-10 other different addons (atlastloot have sub addons for each expansion we've had) that wasn't Carbonite or Elvui and I still couldn't get the quests to be linked in guild chat, whisper chat or general chat.
I turn Carbonite Maps + Carbonite Quest off and turn Elvui + Elvui Config on while having 2-10 of the same mentioned different addons turned on and I can link quests in guild chat, whisper chat and general chat.
Right now, I have all my addons turned on and so I'm just not linking quests in chat.
1: It's not popping up
2: I get an error with a specific quest

I'll be posting this wall of text on the Elvui Forum/gitlab too. and throw in the info that the post have been posted to both "forums".

I'm sorry for the wall of text, but I'm merely trying to provide as much detail as I can.

Any help would be highly appreciated. Thank you
Swirrel.

**Comment by Swirrel** [comment]
Update: I removed carbonite entirely, absolutely everything and installed it anew. This time only with Carbonite, Carbonite Quest, Carbonite Notes and Carbonites Warehouse.
Logging back in doing nothing to Carbonite on it's default settings and I'm still not able to post quests in chat.

**Comment by Swirrel** [comment]
Having some older'ish folders of the WTF, Cache and Interface folder... copied those over to my current installation of WoW, did nothing. I still can't link quests in chat.

**Comment by Swirrel** [comment]
Update: So I tried to link one of my 3 quests to Party, forgetting temporarily that I wasn't in a party so ofcourse that wouldn't work. I did get a bug though:
5x Carbonite.Quests\NxQuest.lua:4246: bad argument #2 to 'format' (string expected, got nil)
[C]: in function `format'
Carbonite.Quests\NxQuest.lua:4246: in function `CreateLink'
Carbonite.Quests\NxQuest.lua:6641: in function `MakeDescLink'
Carbonite.Quests\NxQuest.lua:6317: in function `func'
Carbonite\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <Carbonite\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
(*temporary) = "|cffffff00|Hquest:%s:%s|h[%s]|h|r"
(*temporary) = nil
(*temporary) = -1
(*temporary) = ""
(*temporary) = "string expected, got nil"

However, when I did get in to a party shortly after, I again right clicked on said quest to link to party, but nothing happend even though I had changed from guild chat to party chat. Anyway, I don't know if the bug report in this post is related to my original post

**Comment by Swirrel** [comment]
Should I use Carbonite Alpha as oppose to Carbonite Release?

**Comment by fdellwing** [comment]
You should, but that will not help in this case.

Can confirm that problem and it is not a ElvUI problem, I'm using only Prat 3.0 for my chat and have the same problem. Did not check further.

**Comment by Swirrel** [comment]
I'll change it from Release to Alpha then even if it doesn't help one bit in this case.

Edit: Changed to Alpha and there was 4 updates from Carb for me.

I went and grabbed Carb gathermate2 yesterday, should that too be set to Alpha?

**Comment by IrcDirk** [comment]
This issue should be reported in Carbonite.Quests repository.

**Comment by IrcDirk** [comment]
This issue was moved to mikepauer/Carbonite.Quests#36

**Comment by Swirrel** [comment]
My apologies for putting it in the wrong section. I know better.
Thank you for moving it.
