### ISSUE TITLE
Carbonite-7.3.0.lua:1251: Attempt to access forbidden object from code tainted by an AddOn

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#83]
Same time as #82 

996x Carbonite\Carbonite-7.3.0.lua:1251: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `IsVisible'
Carbonite\Carbonite-7.3.0.lua:1251: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals:
InCombatSkipped

**Comment by IrcDirk** [comment]
Those tains from Blizz are fucked up...
