### ISSUE TITLE
BFA Alpha, API Documentation

### ISSUE THREAD

**Issue by SteveEbey73742** [mikepauer/Carbonite#84]
Attempted Carbonite on Alpha, ACE Libs errors on load and GetCurrentMapAreaID looks like it has changed to C_Map.GetCurrentMapID()

link to 8.01 Docs for api

https://github.com/tomrus88/BlizzardInterfaceCode/tree/master/Interface/AddOns/Blizzard_APIDocumentation

**Comment by SteveEbey73742** [comment]
digging around found a command line /api that shows me all the functions, for every system in game.  Not sure if it is something specific to alpha or if current live has that feature, but if interested, I can try to capture the api information and build a list in a text file for your use.

**Comment by IrcDirk** [comment]
Dont have access to Alpha so cant check that.

**Comment by mikepauer** [comment]
One of the main functions needed for carbonite to work properly is gone
with no known replacement for now.. getplayermapposition

**Comment by IrcDirk** [comment]
@mikepauer thats really bad, maybe something will change... but if it will stay this way we will have a big problem that might not be able to get around :(

**Comment by mikepauer** [comment]
A solution will hopefully be found.. even if it's finding a way to recreate the function itself, too many addons rely on it.. from basic map coord addons, to quest helping, to crazy arrows/waypointing.

**Comment by IrcDirk** [comment]
This is still alpha it seems that many things might change till beta.

**Comment by SteveEbey73742** [comment]
found an ace lib that appears to work, but MapWorldInfo is throwing errors.  I will keep plugging away, I am pushing changes to my fork, just so I do not lose any good progress I might make.

**Comment by IrcDirk** [comment]
There is table that maps old mapid to new once i think its in Blizzard_depreciated.

**Comment by mikepauer** [comment]
There is thousands of maps that now need declaration as the old way of
dungeon levels is now gone and every level is it's own mapid.. on top of
the removal of map positions.. pretty much everything at the root of how
carbonite built and tracked maps is gone or changed.. but carb isn't the
only add-on facing these difficulties.. a few authors have said they need
to rewrite from scratch almost to support the new map functions.

**Comment by IrcDirk** [comment]
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/AddOns/Blizzard_Deprecated/UIMapIDToWorldMapAreaID.lua

Map levels are here too. 

As for player postition its confirmed that UnitPosition works in BfA so if we know lengths of maps we could rewrite GetPlayerMapPosition.

Maybe there will be a way to rewrite old functions, this way changing most of code will not be necessary. Will see when beta comes out, as for me is still to early to speculate. But as for now this looks bad!!! 

As for Carbonite it needs code rework, but the problem is that no one have time for this and Blizz may force us to do this :(

**Comment by Thrumbar** [comment]
Well here's to the release of 8. on liver either 7 / 17 or 7 / 24  2018.  That is if they follow the release they did in legion.....

**Comment by IrcDirk** [comment]
U mean open beta?

**Comment by mikepauer** [comment]
No.. he means prepatch. They usually update live 2-3 weeks before the
expansion launches with all the new features and start the pre-expansion
storylines

**Comment by Thrumbar** [comment]
BfA is now on PTR server (8.0.1.26838)

**Comment by IrcDirk** [comment]
Great info, updating...

**Comment by IrcDirk** [comment]
Great!

pt., 15 cze 2018, 03:04 użytkownik Thrumbar <notifications@github.com>
napisał:

**Comment by IrcDirk** [comment]
Pushed my changes to BfA branch => e8f6451

**Comment by IrcDirk** [comment]
Damn blizzard no access to Copy Character on PTR :/ I know how to get overlays but got no 110lvl char on PTR :/
