### ISSUE TITLE
BfA on PTR - \MapCanvas_ScrollContainerMixin.lua:425: attempt to index local 'layers' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#86]
This error go off a lot when using carb map and moving mouse over Draenor but happens rarely when mousing over Pandaria...

Message: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:425: attempt to index local 'layers' (a nil value)
Time: Wed Jun 20 16:54:36 2018
Count: 76
Stack: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:425: attempt to index local 'layers' (a nil value)
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:425: in function `CreateZoomLevels'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:412: in function `OnCanvasSizeChanged'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:404: in function `SetMapID'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:31: in function `SetMapID'
Interface\AddOns\Carbonite\NxMap.lua:9112: in function `SetCurrentMap'
Interface\AddOns\Carbonite\NxMap.lua:6014: in function `CheckWorldHotspotsType'
Interface\AddOns\Carbonite\NxMap.lua:5988: in function `CheckWorldHotspots'
Interface\AddOns\Carbonite\NxMap.lua:3898: in function <Interface\AddOns\Carbonite\NxMap.lua:3719>

Locals: self = <unnamed> {
 0 = <userdata>
 MarkCanvasDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:381
 GetMinZoomViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:544
 GetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:700
 SetPanTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:577
 DenormalizeVerticalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:725
 IsAtMaxZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:644
 AccumulateMouseDeltas = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:245
 ScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:290
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:656
 IsZoomingIn = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:636
 ZoomOut = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:598
 ShouldZoomInstantly = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:536
 SetScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:286
 targetScale = 0.441796875
 GetNormalizedCursorPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:750
 TryPanOrZoomOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:86
 shouldPanOnClick = false
 SetZoomTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:582
 normalizedPanXLerpAmount = 0.15
 NormalizeUIPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:745
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:104
 MarkAreaTriggersDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:373
 CalculateViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:548
 ResetZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:610
 NormalizeHorizontalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:713
 SetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:695
 OnLoad = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:7
 Child = <unnamed> {
 }
 zoomLevels = <table> {
 }
 SetShouldPanOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMi

**Comment by IrcDirk** [comment]
After @mikepauer conversion this doesnt accour. Please confirm.

**Comment by Thrumbar** [comment]
Have not gotten this error after upgrading closing..
