### ISSUE TITLE
BfA on Ptr - local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#87]
Message: Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)
Time: Wed Jun 20 16:50:31 2018
Count: 4
Stack: Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)
[C]: in function `GetCorpseMapPosition'
Interface\AddOns\Carbonite\NxMap.lua:4457: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3835: in function `OnUpdate'
Interface\AddOns\Carbonite\NxMap.lua:1348: in function `MainOnUpdate'
Interface\AddOns\Carbonite\Carbonite.lua:1304: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = "Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)"

**Comment by IrcDirk** [comment]
Closing same as #88
