### ISSUE TITLE
BfA on PTR - Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID) (num 2)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#88]
Message: Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)
Time: Wed Jun 20 16:51:48 2018
Count: 87
Stack: Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)
[C]: in function `GetCorpseMapPosition'
Interface\AddOns\Carbonite\NxMap.lua:4457: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3835: in function <Interface\AddOns\Carbonite\NxMap.lua:3719>

Locals: (*temporary) = "Usage: local position = C_DeathInfo.GetCorpseMapPosition(uiMapID)"

**Comment by IrcDirk** [comment]
Fixed.
