### ISSUE TITLE
Instance Map not working in "Death to Chromie"

### ISSUE THREAD

**Issue by fdellwing** [mikepauer/Carbonite#9]
Chat gets spammed with this:

```
[09:46:28] [Carbonite] IdToCont Err 1177
[09:46:28] [Carbonite] GetPos Err:1177: Carbonite\NxMap.lua:9452: in function `GetWorldPos'
Carbonite\NxMap.lua:4374: in function `Update'
Carbonite\NxMap.lua:3821: in function <Carbonite\NxMap.lua:3693>
```

**Comment by IrcDirk** [comment]
Will check this later. 

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fdellwing** [comment]
Its a new instance map, probably needs special handling.

**Comment by mikepauer** [comment]
New 7.2.5 areaids need to be pulled from the db2 file and get added to zones

_Sent from my Samsung SM-G930W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fdellwing** [comment]
Should be tagged as release after the fix :)

**Comment by IrcDirk** [comment]
@mikepauer can u do this? i doesnt have utils to pull this from db2 files.

**Comment by fdellwing** [comment]
9051 = The Deaths of Chromie (overall szenario map)

It does have 6 floors, beeing the Overworld, Obsidian Dragonshrine, Andorhal, Mount Hyjal, The Well of Eternity and Stratholme

**Comment by fdellwing** [comment]
The map id is literally in the bug message: 1177

Line 9452: `Nx.prtStack("GetPos Err:" .. mapId)`

But, I added `[1177] = L["The Deaths of Chromie"] .. "|110|110|3|4|488|59.8|53.6|0"` to the Zones.lua and still getting error:

```
[19:17:23] [Carbonite] GetPos Err:1177: Carbonite\NxMap.lua:9452: in function `GetWorldPos'
Carbonite\NxMap.lua:6813: in function `ClipFrameZ'
Carbonite\NxMap.lua:4827: in function `Update'
Carbonite\NxMap.lua:3821: in function <Carbonite\NxMap.lua:3693>
```

Edit: And please remember, this szenario has 5 more zones, being the 4 portals and the obsidian dragonshrine.

**Comment by mikepauer** [comment]
Added now.

You were close, it is always 3|5 for a dungeon/instance/scenario which is why it failed. With 3|4 it was looking for more information about zone size, map files, scaling, world position etc etc.

There was another zone to be added aswell tho no idea what it's used for yet.
