### ISSUE TITLE
BfA -- NxTravel.lua:79: bad argument #1 to 'tinsert' (table expected, got nil)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#91]
Message: Interface\AddOns\Carbonite\NxTravel.lua:79: bad argument #1 to 'tinsert' (table expected, got nil)
Time: Sat Jun 23 06:41:55 2018
Count: 1
Stack: Interface\AddOns\Carbonite\NxTravel.lua:79: bad argument #1 to 'tinsert' (table expected, got nil)
[C]: in function `tinsert'
Interface\AddOns\Carbonite\NxTravel.lua:79: in function `Add'
Interface\AddOns\Carbonite\NxTravel.lua:41: in function `Init'
Interface\AddOns\Carbonite\Carbonite.lua:817: in function `SetupEverything'
Interface\AddOns\Carbonite\Carbonite.lua:1235: in function `NXOnUpdate'
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: (*temporary) = nil
(*temporary) = <table> {
 Name = "The Argent Vanguard, Icecrown"
 MapId = 492
 WX = 0
 WY = 0
 LocName = "The Argent Vanguard, Icecrown"
}
(*temporary) = "table expected, got nil"

**Comment by mikepauer** [comment]
expected bug for now.. until flights in guide gets converted

**Comment by IrcDirk** [comment]
@Thrumbar maybe u have time to convert filghts to new ids?

**Comment by mikepauer** [comment]
I'll be doing it shortly :) I have lua shell scripts written to do the conversions, just need to eat breakfast then I'll start on it

**Comment by mikepauer** [comment]
all conversions should be done now.. at least for maps
