### ISSUE TITLE
BfA -- NxMap.lua:5070: attempt to call global 'GetMapInfo' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#93]
Got this after zoning into instance in Dalaran Vilot Hold and opening Carb map

Message: Interface\AddOns\Carbonite\NxMap.lua:5070: attempt to call global 'GetMapInfo' (a nil value)
Time: Sat Jun 23 16:20:25 2018
Count: 1
Stack: Interface\AddOns\Carbonite\NxMap.lua:5070: attempt to call global 'GetMapInfo' (a nil value)
Interface\AddOns\Carbonite\NxMap.lua:5070: in function `GetInstanceMapTextures'
Interface\AddOns\Carbonite\NxMap.lua:5028: in function `SetInstanceMap'
Interface\AddOns\Carbonite\NxMap.lua:5109: in function `SwitchRealMap'
Interface\AddOns\Carbonite\NxMap.lua:4305: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3835: in function <Interface\AddOns\Carbonite\NxMap.lua:3719>

Locals: self = <table> {
 Menu_OnTrackPlyr = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2794
 GetInstanceID = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9074
 ZoneOverlays = <table> {
 }
 GetZoneAchievement = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10706
 MinimapOwnInit = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1817
 RestoreBlizzBountyMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3146
 MapLevels = <table> {
 }
 MinimapSetScale = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2436
 OnButToggleGuide = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1594
 GetWinName = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1179
 SetToCurrentZone = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9156
 GetIconStatic = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8189
 UpdateToolBar = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1216
 Menu_OnBackgndAlphaFade = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2699
 BlizzToggleWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:3173
 Menu_OnMapDebugFullCoords = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2745
 ClipFrameByMapType = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6850
 ConvToUMapId = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11237
 ResetIcons = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:7937
 Minimap_OnEvent = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1906
 UnpackObjective = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10954
 GetWorldContinentInfo = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9457
 ReverseTargets = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9769
 GetWorldZoneScale = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9516
 GMenu_OnPasteLink = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2923
 ContCnt = 9
 CreateToolBar = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1186
 PlyrNamesTipStr = ""
 GetPlayerMapPosition = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:11259
 RestoreWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10992
 DetachWorldMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:1429
 ClearTarget = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9731
 BGMenu_OnHelp = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2959
 UnregisterAllEvents = <function> defined @Interface\AddOns\Carbonite\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 VerifySettings = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:270
 HideMiniFrames = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6737
 HideExtraZoneTiles = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6171
 Menu_OnDetailAlpha = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:2695
 IsInstanceMap = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:9401
 EkMapBlks = <table> {
 }
 CheckWorldHotspotsType = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:6010
 BuildPlyrLists = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:8328
 UnpackLocPtOff = <function> defined @Interface\AddOns\Carbonite\NxMap.lua:10947
 Menu_OnScaleRestore = <function> defined @Interface\AddOns\Carbonite\NxMap.

**Comment by mikepauer** [comment]
Instances are completely dead right now... doing testing right now trying to get at least one drawing style back.

**Comment by IrcDirk** [comment]
Please recheck with newest version.
