### ISSUE TITLE
I've got no Carbonite map, quest tracker ect.

### ISSUE THREAD

**Issue by Swirrel** [mikepauer/Carbonite#97]
1x Carbonite\NxMap.lua:9074: attempt to call global 'GetCurrentMapAreaID' (a nil value)
Carbonite\NxMap.lua:9074: in function `GetRealMapId'
Carbonite\Carbonite-7.3.0.lua:2588: in function `GetPlyrPos'
Carbonite\Carbonite-7.3.0.lua:2462: in function `AddInfo'
Carbonite\Carbonite-7.3.0.lua:1132: in function `?'
...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...oot\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
Carbonite\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Carbonite\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil

**Comment by IrcDirk** [comment]
http://www.wowinterface.com/forums/showthread.php?p=328769

**Comment by IrcDirk** [comment]
Use latest Alpha release of Carbonite Maps + Quest module from Curse/Twitch client. Other carb modules are not functional yet.

**Comment by Swirrel** [comment]
Thank you.

Cheers :)
