### ISSUE TITLE
BfA, throwing errors when in Gnomergan 

### ISSUE THREAD

**Issue by reflexwolf** [mikepauer/Carbonite#98]
I'm having this error pop up ever few moments while doing Gnomergan. 

54x Carbonite\NxMap.lua:11255: Usage: local continentID, worldPosition = C_Map.GetWorldPosFromMapPos(uiMapID, mapPosition)
[C]: in function `GetWorldPosFromMapPos'
Carbonite\NxMap.lua:11255: in function `GetCurrentMapContinent'
Carbonite\NxMap.lua:5121: in function `?'
Carbonite\NxMap.lua:5008: in function `Update'
Carbonite\NxMap.lua:3841: in function <Carbonite\NxMap.lua:3725>

Locals:
(*temporary) = 226
(*temporary) = nil

using the Bfa Pull from yesterday  Carbonite Maps 8.0.0

**Comment by Thrumbar** [comment]
Found it ,  disregard question..
What version are you using.??  

Did you get it from the git or Curse..??

**Comment by reflexwolf** [comment]
​its showing as 8.0.0 and I got it from the github, the bfa pull on get
hub.
​
Just reloaded it from the zip file I got last night and am testing it out
again in cause I some how did a pull off curse (I normally have carbonite
on ignore on curse)

464x Carbonite\NxMap.lua:11255: Usage: local continentID, worldPosition =
C_Map.GetWorldPosFromMapPos(uiMapID, mapPosition)
[C]: in function `GetWorldPosFromMapPos'
Carbonite\NxMap.lua:11255: in function `GetCurrentMapContinent'
Carbonite\NxMap.lua:5121: in function `?'
Carbonite\NxMap.lua:5008: in function `Update'
Carbonite\NxMap.lua:3841: in function <Carbonite\NxMap.lua:3725>

Locals:
(*temporary) = 226
(*temporary) = nil

is what I just got, testing now with all but buggrabber and bugstack
loaded.
I got just the same results. the error keeps popping up even if I'm doing
nothing on the game just standing in the room.

and this is happening in Gnomergan

and once again thank you for your great hard work, this bug is anoying but
still lets me use the maps, just move the bugstack window to an unused part
of the screen and let it sit there. :)

**Comment by bmitch1973** [comment]
i can't find it, do you have a link to the 8.0 ?

**Comment by reflexwolf** [comment]
Bmich1073, this is the link I got it off of did the download zip link
https://github.com/mikepauer/Carbonite/tree/BfA

**Comment by IrcDirk** [comment]
This is the right link. I will lookup into this bug.

**Comment by reflexwolf** [comment]
thanks :) it was annoying but was able to work around it with creative
window management :)

**Comment by IrcDirk** [comment]
Ok, should be fixed by.

**Comment by reflexwolf** [comment]
ok went back and tested it out works like a dream thank you!
