### ISSUE TITLE
Carbonite GetPos Err: Carbonite\NxMap.lua:9145: in function `GetWorldPos'

### ISSUE THREAD

**Issue by Thrumbar** [mikepauer/Carbonite#98]
This error in chat box pnly no bugsack/lua box.  Tried searching in wowinterface for this but came up nothing so reporting here.

Carbonite GetPos Err: Carbonite\NxMap.lua:9145: in function `GetWorldPos'
Carbonite\NxMap.lua:9378: in function `SetTargetXY'
Carbonite\NxMap.lua:9545: in function <Carbonite\NxMap.lua:9540>
...
...Ons\WoWPro\Libraries\AceBucket-3.0\AceBucket-3.0.lua:118: in function `func'
...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:48>

[00:59:08] Carbonite GetPos Err: Carbonite\NxMap.lua:9145: in function `GetWorldPos'
Carbonite\NxMap.lua:9378: in function `SetTargetXY'
Carbonite\NxMap.lua:9545: in function <Carbonite\NxMap.lua:9540>
...
...Ons\WoWPro\Libraries\AceBucket-3.0\AceBucket-3.0.lua:118: in function `func'
...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...\AddOns\DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:48>

**Comment by wilki24** [comment]
This is happening to me in the Brawler's Guild in Orgrimmar. It spams continuously, and prevents the chat window from being used normally.
